### ISSUE TITLE
Add videos to Jakarta EE 9 release page

### ISSUE THREAD

**Issue by karenmcnaughton** [jakartaee/jakarta.ee#1001]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by karenmcnaughton** [comment]
Hi @chrisguindon as discussed: we need to add 4 new videos to the Jakarta EE 9 release page.
Ideally positioned below the Projects/Committers/GIT Repositories section.
The videos can be found here:
Reza Rahman: https://youtu.be/H3xkLW-F69E

Kevin Sutter: https://youtu.be/vOVm9P9i8K4

Markus Karg: https://www.youtube.com/watch?v=DxwL02Xgri4&t=2s

Edwin Derks: https://youtu.be/eh_spQ7kHbo

**Comment by flora8984461** [comment]
Hello Karen @karenmcnaughton ,

I added the videos but I'm not sure if there is any preferred design for it? 

Please check the preview here: https://deploy-preview-1007--jakartaee.netlify.app/release/9/

Thanks!

**Comment by karenmcnaughton** [comment]
Hi @flora8984461 are we able to add a "Powered by Participation" with a line under it--same as on this page: https://jakarta.ee/release/ ? That would be perfect, if possible. Thanks!

**Comment by flora8984461** [comment]
Hello Karen,
Sure I can add it, but I would suggest making the style complied with the current design style. So I made some adjustments.

Thanks!
