### ISSUE TITLE
Update the FAQ on the Jakarta EE website

### ISSUE THREAD

**Issue by karenmcnaughton** [jakartaee/jakarta.ee#1002]
We have an update to the FAQ for the Jakarta EE website--the current one is located here:
https://jakarta.ee/about/faq/

The updated text can be found here: https://docs.google.com/document/d/1-ZjjP81SHrgLO_hp2LAQ5JEWKU8tT_drqi6WPphkS6E/edit#

**Comment by flora8984461** [comment]
Hi @karenmcnaughton , Do we also need the translation of Chinese?

**Comment by karenmcnaughton** [comment]
Yes @flora8984461 that would be ideal if possible! Thanks

**Comment by chrisguindon** [comment]
@karenmcnaughton can this go live now or do we need to wait for Jakarta 9 release?

**Comment by TanjaObradovic** [comment]
it can go live now @chrisguindon & @karenmcnaughton

**Comment by flora8984461** [comment]
Please check the preview https://deploy-preview-1004--jakartaee.netlify.app/about/faq/
and Chinese https://deploy-preview-1004--jakartaee.netlify.app/zh/about/faq/

Thanks!

**Comment by flora8984461** [comment]
This is updated and live.
