### ISSUE TITLE
Updates for Payara Server on Compatible Products Page

### ISSUE THREAD

**Issue by MarkWareham** [jakartaee/jakarta.ee#1005]
_Note: this request is an update to version number as well as addition of web profile compatible product listing._

To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://projects.eclipse.org/user/11967

**A product name and version**
Payara Server 5.23.0

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Update version number of [full profile to 5.23.0](https://github.com/eclipse-ee4j/jakartaee-platform/issues/275) and add listing for Payara Server [Web Profile 5.23.0](https://github.com/eclipse-ee4j/jakartaee-platform/issues/276) under web profile compatible products

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
Please use existing logo

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Payara

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Full: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/275](https://github.com/eclipse-ee4j/jakartaee-platform/issues/275)
Web: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/275](https://github.com/eclipse-ee4j/jakartaee-platform/issues/276)

**The URL where Compatible Software Product is available for download**
[https://www.payara.fish/downloads/](https://www.payara.fish/downloads/)

**Comment by flora8984461** [comment]
@MarkWareham Hello,
Just hope to confirm by "Update version number of full profile to 5.23.0", you want to remove 5.21.2? 
Please check the preview: https://deploy-preview-1006--jakartaee.netlify.app/compatibility/#tab-8

Thanks!

**Comment by MarkWareham** [comment]
Hi @flora8984461 
I hadn't appreciated the logic has changed and now the page includes more than just the latest version. In which case, no, please add 5.23.0, and [5.22.0](https://github.com/eclipse-ee4j/jakartaee-platform/issues/252)

**Comment by flora8984461** [comment]
@MarkWareham Thanks for your feedback. 
Please check the preview here: 
https://deploy-preview-1006--jakartaee.netlify.app/compatibility/#tab-8
Thanks!
