### ISSUE TITLE
Add Beijing Huayu Information Technology Co., Ltd to the Jakarta EE website

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#1012]
Hello, 
Please add Beijing Huayu Information Technology Co., Ltd as a Participant Member to the Jakarta EE website
![3E437607D45A41A29FD76AB67EDE38E3 5761651](https://user-images.githubusercontent.com/50374570/100895705-db57e080-348b-11eb-8de1-2a620732a1bc.png)

Thank you,
Zahra

**Comment by flora8984461** [comment]
Hi @ZahraFazli , Can you confirm the company link is  http://www.thunisoft.com/ ?

Thanks!

**Comment by flora8984461** [comment]
@ZahraFazli has confirmed by slack
