### ISSUE TITLE
Update Jakarta EE Compatibility Page

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#1013]
On this page: https://jakarta.ee/compatibility/

We need to do the following:
- remove the orange Download button that is top right on the page
- add a new button the to left of "Compatibility Requests" that says "Download Compatible Products"
- when you click on that new button, it will take you to a new page
- the design file for this new page can be found here: https://drive.google.com/file/d/1IpRSyn_hOVcgxOk1AoQx8Ef7r7vVDOjT/view?ts=5fc8f5e1

**Comment by chrisguindon** [comment]
@karenmcnaughton can you provide a list of download URL for each product?

**Comment by karenmcnaughton** [comment]
Date to be completed by December 18th. 
The .XLS for the versions to be featured on the page are here: https://docs.google.com/spreadsheets/d/1iGDajRprImmkzGBj3QAVbio8TzN6MCSprVskYZwyfx0/edit#gid=0

**Comment by flora8984461** [comment]
Hello, 
Please have a look at the preview:
https://deploy-preview-1019--jakartaee.netlify.app/compatibility/download/

https://deploy-preview-1019--jakartaee.netlify.app/compatibility/

Thanks!

**Comment by chrisguindon** [comment]
@flora8984461 How about we hide sections that are empty? @karenmcnaughton Is that option?

**Comment by flora8984461** [comment]
@karenmcnaughton 
Hi Karen,
Can you please help me confirm the download links for the two Payara Server are:

```
Jakarta EE 8 Platform
Payara Server
        - version: 5.22.0
          version_download: 'https://docs.payara.fish/enterprise/docs/5.22.0/jakartaee-certification/5.22.0/tck-results-full-5.22.0.html'
        - version: 5.23.0
          version_download: 'https://docs.payara.fish/enterprise/docs/5.23.0/jakartaee-certification/5.23.0/tck-results-full-5.23.0.html'
```

And

```
Jakarta EE 8 Web Profile
Payara Server
        - version: 5.23.0
          version_download: 'https://docs.payara.fish/enterprise/docs/5.23.0/jakartaee-certification/5.23.0/tck-results-web-5.23.0.html'
```

Plus, I notice that Eclipse GlassFish 6 for both Full Profile and Web profile are coming for Jakarta EE 9.0, could you please also add these two download links in the google sheet? 

Thanks!

**Comment by karenmcnaughton** [comment]
Hi @flora8984461 the orange button on this page: https://deploy-preview-1019--jakartaee.netlify.app/compatibility/ needs to say "Download Compatible Products" pls.

**Comment by karenmcnaughton** [comment]
@flora8984461 also on this page: https://deploy-preview-1019--jakartaee.netlify.app/compatibility/ need to remove the Orange "Download" button on the top right of the page pls.

**Comment by flora8984461** [comment]
@karenmcnaughton I have made the changes and the pages will refresh soon. I'm wondering do I need to remove the "Download" button on the top right of this page?  https://deploy-preview-1019--jakartaee.netlify.app/compatibility/download/ 

Thanks!

**Comment by karenmcnaughton** [comment]
@flora8984461 thank you I think that's fine the way it is

**Comment by karenmcnaughton** [comment]
@flora8984461 you can push these live pls when ready

**Comment by chrisguindon** [comment]
@karenmcnaughton I am looking at this now. We are quite busy this week!
