### ISSUE TITLE
Upload updated membership prospectus for Jakarta EE

### ISSUE THREAD

**Issue by jph152** [jakartaee/jakarta.ee#1015]
Can you please upload the new Jakarta EE membership prospectus?

"Download Membership Prospectus" button is here: https://jakarta.ee/membership/

[Jakarta_Membership_Prospectus_v06_2020 (1).pdf](https://github.com/jakartaee/jakarta.ee/files/5639191/Jakarta_Membership_Prospectus_v06_2020.1.pdf)

Google Drive link: https://drive.google.com/file/d/1sShegqW_HtlU0NdgPPw8jxLZmEjzrasS/view?usp=sharing

**Comment by flora8984461** [comment]
Hello @jph152 ,

Please check the preview: https://deploy-preview-1020--jakartaee.netlify.app/documents/membership/jakarta-ee-membership-prospectus.pdf

I feel the pdf style is a little bit weird, if this is good for you, we will merge it.

Thanks!

**Comment by jph152** [comment]
[Uploading Jakarta_Membership_Prospectus_v06_2020 (1).pdf…]()

**Comment by jph152** [comment]
[Jakarta_Membership_Prospectus_v06_2020 (3).pdf](https://github.com/jakartaee/jakarta.ee/files/5647433/Jakarta_Membership_Prospectus_v06_2020.3.pdf)
