### ISSUE TITLE
Eclipse GlassFish 6.0 Web Profile as Compatible Product of Jakarta EE 9.0 Web Profile

### ISSUE THREAD

**Issue by edbratt** [jakartaee/jakarta.ee#1017]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
  - [Ed Bratt](https://projects.eclipse.org/content/ed-bratt-committer-eclipse-glassfish)

**A product name and version**
  - Eclipse GlassFish 6.0, Web Profile

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
  - Web Profile

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
 - On File with Eclipse Foundation

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
  - Eclipse Foundation

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
  - [Compatibility certification request for Eclipse GlassFish 6.0 for Jakarta EE 9, Web Profile](https://github.com/eclipse-ee4j/jakartaee-platform/issues/259)

**The URL where Compatible Software Product is available for download**
  - https://glassfish.org/download

**Comment by flora8984461** [comment]
Hi @edbratt , @chrisguindon 
Just hope to confirm is the `Eclipse GlassFish 6.0, Web Profile` TCK result the same as `Eclipse GlassFish 6.0, Full Platform`? 
Since the link `Compatibility certification request for Eclipse GlassFish 6.0 for Jakarta EE 9, Web Profile` is for full platform.

Thanks!

**Comment by edbratt** [comment]
Fixed the link to the Web Profile certification issue. Thanks for catching that.
