### ISSUE TITLE
Jakarta EE 9 - Glassfish 6 - How to get the server?

### ISSUE THREAD

**Issue by rsoika** [jakartaee/jakarta.ee#1028]
I want to try out Jakarta EE 9. We have already started migrating our Java Enterprise Workflow Engine [Imixs-Workflow](https://www.imixs.org) to Jakarta EE 9.

Now I am looking for a server to deploy my code. But it is not clear which one I should use. It seems that Glassfish 6 is the first choice. But of course https://glassfish.org/ does not exist (for what reason ever). Also on the Jakarta pages it is hard to figure out how to get the server. 

What I need is a Docker image. It looks like this does not exits yet. So I try to build my own image. I narrowed down the Download page for Glassfish to this one:

https://projects.eclipse.org/projects/ee4j.glassfish/downloads

But I can not figure out how to get a direct URL for the zip file. Can someone explain me how to get the direct URL? Or more better - has someone already created a Dockerfile for Glassfish 6?

I think in the moment it is important to provide those things to all the open source projects, which are not part of the Jakarta core team. 

In the moment I wonder how I should provide feedback - is this the right place?

===
Ralph

**Comment by edbratt** [comment]
Hi Ralph,

Glassfish.org works for me. Maybe you are trying something more complex? 
The same page is also available by browsing to 
http://eclipse-ee4j.github.io/glassfish. The download page includes 
direct download links.

https://download.eclipse.org/ee4j/glassfish contains the downloads. 
Could you please describe what problems you are encountering with these?

the parameterized download allows the CDN tool to give you the 'closest' 
copy, if it has been distributed. (e.g. 
https://www.eclipse.org/downloads/download.php?file=/glassfish/glassfish-5.1.0.zip 
but the RC links are direct.)

The project download link to RC2 is the latest release. GlassFish 6 
final is still working our a few final kinks. RC3 is available for 
evaluation and that may become 6.0 final, but that's still TBD 
https://github.com/eclipse-ee4j/glassfish/tags

-- Ed

**Comment by rsoika** [comment]
Hi Ed,
thanks - yes I was completely on the wrong way. I can confirm now that glassfish.org works fine - sorry.
Now I can find the information I needed. I will build my own Docker image from 6.0.0-RC2 and hope I can contribute my feedback soon.
Thanks for providing this background info.
