### ISSUE TITLE
Fix broken links on jakarta.ee

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#1029]
As part of our ongoing SEO effort for Jakarta.EE, we need to fix broken links on the site.

Most of the errors are from the /specifications section and I created https://github.com/jakartaee/specifications/issues/318 to fix the broken links for that section.

However, we still have 6 errors that we need to fix on the site. Please see the following report for more information:
https://docs.google.com/spreadsheets/d/16NiMDACYYDb8bRVPaH9dcYj-szXfLPDFbtfs2v0OS1Y/edit?usp=sharing

@flora8984461 We will need to update our Jekyll theme to fix the /members link on start.jakarta.ee:
https://github.com/jakartaee/jekyll-theme-jakarta-ee

That theme is old and outdated. We should make sure that the header and footer match the current website.

**Comment by chrisguindon** [comment]
@ivargrimstad 

We are getting a 404 from https://start.jakarta.ee/starter/samples/simple-hello.zip but https://eclipse-ee4j.github.io/starter/samples/simple-hello.zip is working.

Can we update the link for that page to go to https://eclipse-ee4j.github.io/starter/samples/simple-hello.zip?

**Comment by ivargrimstad** [comment]
@chrisguindon Is it possible to move this issue to https://github.com/eclipse-ee4j/starter/issues

**Comment by chrisguindon** [comment]
@ivargrimstad We should create a new one. We are using this one to tackle other issues on the site.

**Comment by chrisguindon** [comment]
@ivargrimstad It's now created: https://github.com/eclipse-ee4j/starter/issues/62

**Comment by flora8984461** [comment]
Hi @ivargrimstad ,
On this page https://jakarta.ee/committees/specification/operations/ in section "Specification Document Conventions (Currently under discussion)" and in subsection "Initial Migration Tasks", the link for "Project Names and Codes" ( https://jakarta.ee/committees/specification/operations/names.xml ) is missing. I have checked the folder https://github.com/jakartaee/jakarta.ee/tree/src/content/committees/specification/operations, where it does not have anything named `names.xml`. Would you mind helping me provide it? 

Thanks!

**Comment by ivargrimstad** [comment]
@flora8984461 https://github.com/jakartaee/specification-committee/blob/master/names.adoc
