### ISSUE TITLE
Compatibility Request Link Broken

### ISSUE THREAD

**Issue by WalkerWatch** [jakartaee/jakarta.ee#1032]
**Describe the bug**
The "Compatibility Requests" link is malformed (it is missing a .) and results in an inability to resolve the hostname.

**To Reproduce**
1. Go to 'https://jakarta.ee/compatibility/'
2. Click on 'Compatibility Requests'
4. See error.

**Expected behavior**
You would expect to be directed to: https://github.com/eclipse-ee4j/jakartaee-platform/issues?q=is%3Aissue+is%3Aclosed+label%3Acertification

**Comment by chrisguindon** [comment]
Thanks to all that contributed a fix for this! We got 3 different PR!

I committed https://github.com/jakartaee/jakarta.ee/pull/1035 since it had a fix for both file.
