### ISSUE TITLE
Thunisoft Application Servrer V2.8 as a Compatible Software Product for Jakarta EE 8

### ISSUE THREAD

**Issue by zcwslnh** [jakartaee/jakarta.ee#1038]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://www.eclipse.org/membership/showMember.php?member_id=1481

**A product name and version**

Thunisoft Application Servrer V2.8

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**

Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

[tas-logo.zip](https://github.com/jakartaee/jakarta.ee/files/5770050/tas-logo.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Beijing Thunisoft Information Technology Co.,Ltd

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

https://github.com/eclipse-ee4j/jakartaee-platform/issues/290

**The URL where Compatible Software Product is available for download**

http://tas.thunisoft.com/download

**Comment by hantsy** [comment]
There is no download link in the URL: http://www.thunisoft.com/tas/index.jhtml @zcwslnh

**Comment by zcwslnh** [comment]
> There is no download link in the URL: http://www.thunisoft.com/tas/index.jhtml @zcwslnh

Thank you for your reminding @hantsy. We haven't provided the direct download address yet. I will contact our technical department to update it as soon as possible.

**Comment by flora8984461** [comment]
Is it only compatible with Jakarta EE 8 or it is also compatible with Jakarta EE 9? Seems only 8 according to https://github.com/eclipse-ee4j/jakartaee-platform/issues/290 .

**Comment by zcwslnh** [comment]
> Is it only compatible with Jakarta EE 8 or it is also compatible with Jakarta EE 9? Seems only 8 according to [eclipse-ee4j/jakartaee-platform#290](https://github.com/eclipse-ee4j/jakartaee-platform/issues/290) .

You are right. Sorry,I made a mistake.It has been corrected
