### ISSUE TITLE
Please add Oracle WebLogic Server 14c to Jakarta EE Compatible Products page

### ISSUE THREAD

**Issue by edbratt** [jakartaee/jakarta.ee#1042]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Ed Bratt](https://www.eclipse.org/user/ebratt)

**A product name and version**
Oracle WebLogic Server 14c (14.1.1.0)

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[Oracle_WebLogic-Server_for_eclipse.zip](https://github.com/jakartaee/jakarta.ee/files/5777019/Oracle_WebLogic-Server_for_eclipse.zip)
(Other sizes/formats are available. If there are problems with this image we can update)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Oracle Corporation

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
[Compatibility certification request for Oracle Web Logic 14.1.1.0 for Full Platform](https://github.com/eclipse-ee4j/jakartaee-platform/issues/176)

**The URL where Compatible Software Product is available for download**
https://www.oracle.com/middleware/technologies/weblogic-server-downloads.html

**Comment by flora8984461** [comment]
Hi @edbratt 
Please check the preview: https://deploy-preview-1043--jakartaee.netlify.app/compatibility/
https://deploy-preview-1043--jakartaee.netlify.app/compatibility/#tab-8

If got +1 from you, we will merge it. Thanks!

**Comment by edbratt** [comment]
+1. Looks good, thank you!
