### ISSUE TITLE
Updating the Download button on the top right of the homepage

### ISSUE THREAD

**Issue by karenmcnaughton** [jakartaee/jakarta.ee#1045]
We simply want to change the Download button (top right) on https://jakarta.ee/ to go here instead: https://jakarta.ee/compatibility/download/

This is more straightforward and compliant with legal, etc.

**Comment by flora8984461** [comment]
Hi @karenmcnaughton 
Do you want to remove the top right button from all the pages and only include it on https://jakarta.ee/compatibility/download/ ?

And do I put it besides the "compatibility request" button?

Would it be hard to navigate to "release" page?  🤔

I am including @chrisguindon in the loop. 

Thanks!

**Comment by chrisguindon** [comment]
@flora8984461 I don't think that Karen is asking us to remove it.

I think she simply needs us to update the url of the download button!

**Comment by flora8984461** [comment]
> @flora8984461 I don't think that Karen is asking us to remove it.
> 
> I think she simply needs us to update the url of the download button!

Oh IC, sorry for the confusion. Do we want to replace it on every page with download button?
But then I have a question, how to navigate to the release page from https://jakarta.ee/? 🤔

**Comment by chrisguindon** [comment]
@karenmcnaughton did you consider the impact of this change to this page? 
https://jakarta.ee/compatibility/

... I am thinking that we could now remove the "Download Compatible Product" button from the page content  since this download button will go to that page...

**Comment by karenmcnaughton** [comment]
Agree with above^--all good now?

**Comment by flora8984461** [comment]
Hi @karenmcnaughton 
According to your request, I have made a draft preview: 

https://deploy-preview-1046--jakartaee.netlify.app/

And on the download page, https://deploy-preview-1046--jakartaee.netlify.app/compatibility/download/ , the button would be hidden. Let me know if you don't want to hide it, I can change it. 

And please also check the Chinese page https://deploy-preview-1046--jakartaee.netlify.app/zh/compatibility/download/

And on the compatibility page: https://deploy-preview-1046--jakartaee.netlify.app/compatibility/  I removed the "Download Compatible Product" and just keep the download button.

Please let me know if this is good or any more changes are needed.

Thanks!

**Comment by karenmcnaughton** [comment]
+1 looks good to me, thank you!
