### ISSUE TITLE
[SEO Improvements] Jakarta Chinese

### ISSUE THREAD

**Issue by flora8984461** [jakartaee/jakarta.ee#1051]
As we have improved SEO for English pages, we would like to discuss how to improve Chinese SEO.
I am not quite sure about how Chinese Search Engine works, but Google uses meta seo_title and description. 

This is inspired by when I review https://github.com/jakartaee/jakarta.ee/pull/1048

An example using meta description:

On google search:
![image](https://user-images.githubusercontent.com/39588094/104759030-49e7b980-572d-11eb-82d9-da750a8a5750.png)

On baidu: (it's not showing Jakarta EE on the top 😥)
![image](https://user-images.githubusercontent.com/39588094/104759084-5cfa8980-572d-11eb-8b1f-06e376904f0c.png)

**Comment by chrisguindon** [comment]
@laliwa Is there any best practices in regards to SEO in China?

**Comment by chrisguindon** [comment]
WON'T FIX - Please re-open if the community would like to invest time into this effort.
