### ISSUE TITLE
[IE Compatibility] Only IE: Contributor card not showing

### ISSUE THREAD

**Issue by flora8984461** [jakartaee/jakarta.ee#1052]
Updates:

Compatible Products display is fixed on IE.

Only Contributor card not showing for IE remains. (Need to modify the syntax to drop syntax that not supported by IE.)

--------------------

For release page:

with err: `SCRIPT438: Object doesn't support property or method 'forEach'`
![image](https://user-images.githubusercontent.com/39588094/105895953-3289b580-5fe4-11eb-8987-c8090178eaf4.png)

**Comment by chrisguindon** [comment]
This is bad... let's plan at looking at this on Monday!

Great find @flora8984461 !

**Comment by oliviergoulet5** [comment]
I can't reproduce this on IE11 mode for Edge. It looks like it has already been fixed.

![image](https://user-images.githubusercontent.com/17685861/212919412-720a5ace-6ebf-484c-a9dc-b34f95bc1e62.png)
