### ISSUE TITLE
Add Shandong Cvicse Middleware Co.,LTD on Jakarta EE website

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#1055]
Hello, 
Please add Shandong Cvicse Middleware Co.,LTD as Enterprise member on Jakarta EE website https://jakarta.ee/membership/members/
Thank you,
Zahra

**Comment by flora8984461** [comment]
Hi @ZahraFazli , Could you please provide their logo and company website? Thanks!

**Comment by ZahraFazli** [comment]
[Shandong Cvicse Middleware Co.,Ltd.LOGO.zip](https://github.com/jakartaee/jakarta.ee/files/5842754/Shandong.Cvicse.Middleware.Co.Ltd.LOGO.zip)

**Comment by flora8984461** [comment]
Hi @ZahraFazli , thanks for the logo, can you help me confirm their website is http://www.inforbus.com/ ? Since normally we add the company link to the member' logo.
