### ISSUE TITLE
Open Liberty 21.0.0.2-beta as a Compatible Software Product for Jakarta EE 9, Web Profile

### ISSUE THREAD

**Issue by brideck** [jakartaee/jakarta.ee#1059]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Brian Decker - IBM - Eclipse Profile](https://accounts.eclipse.org/users/bdeckerhdt)

**A product name and version**
[Open Liberty 21.0.0.2-beta](https://openliberty.io/)

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Web Profile

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[https://openliberty.io/certifications/assets/OL_logo_navy.zip](https://openliberty.io/certifications/assets/OL_logo_navy.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[IBM Corporation](https://www.ibm.com/)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Web Profile: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/295](https://github.com/eclipse-ee4j/jakartaee-platform/issues/295)

**The URL where Compatible Software Product is available for download**
[https://openliberty.io/downloads/#runtime_betas](https://openliberty.io/downloads/#runtime_betas)

**Comment by flora8984461** [comment]
Hi @brideck , please check the preview: 
https://deploy-preview-1061--jakartaee.netlify.app/compatibility/#tab-one
https://deploy-preview-1061--jakartaee.netlify.app/compatibility/#tab-9

And we had the logo from the past, do you like to use the new logo for the open liberty on Jakarta EE 8 as well? (I think the logo is the same, just the file format changed)

We will push to live once got +1 from you.

Thanks!

**Comment by brideck** [comment]
It looks like our download link is pointing to Glassfish instead of Open Liberty.

The template here indicated that the logo should be sent as an SVG, so that's what we've done.  That must not have been the case before?  I'm indifferent to changing the format of the one used for EE 8, unless there's some compelling reason to use the new one.

**Comment by chrisguindon** [comment]
@brideck @flora8984461 If the logos are the same, I say that we should use the .svg since this is what we are asking! 

As far as I know, we currently don't support different logos per Jakarta EE releases. We can change that but we should create an issue to discuss.

**Comment by kwsutter** [comment]
> As far as I know, we currently don't support different logos per Jakarta EE releases. We can change that but we should create an issue to discuss.

No reason to allow for multiple logos.  Use the latest .svg for Open Liberty that @brideck provided for this update.  Thanks.

**Comment by brideck** [comment]
The new set of changes look good to me.
