### ISSUE TITLE
Add new weblinks to release pages on https://jakarta.ee/compatibility/download/

### ISSUE THREAD

**Issue by karenmcnaughton** [jakartaee/jakarta.ee#1063]
We need to add links on the Compatibility Page to the Jakarta EE 9 Release page and the Jakarta EE 8 Release page.

On the left side, on top of the Jakarta EE 9 Platform block, please add a text link in orange font (or a button) that says "Jakarta EE 9 Release Page" (link to: https://jakarta.ee/release/9/)

Same thing further down the page, on the left side, on top of the Jakarta EE 8 Platform, please add a text link in orange font (or a button) that says "Jakarta EE8 Release Page" (link to: https://jakarta.ee/release/8/)

**Comment by flora8984461** [comment]
Hi @karenmcnaughton , please take a look at the preview: https://deploy-preview-1064--jakartaee.netlify.app/compatibility/download/ 

Is this what you expect? 

Thanks!

**Comment by chrisguindon** [comment]
I will ping @karenmcnaughton on slack about this. Your message might have gotten lost in her inbox!

**Comment by karenmcnaughton** [comment]
Hi--apologies--I think in the text we should say "Visit Jakarta Release..." because it's not too visible that it's a hotlink. Thoughts? Thanks!

**Comment by flora8984461** [comment]
@karenmcnaughton  Do you mean like this?

![image](https://user-images.githubusercontent.com/39588094/107529326-c1700380-6b88-11eb-9d91-746167787542.png)

Thanks!

**Comment by karenmcnaughton** [comment]
No--like this: 
View Jakarta EE 9 Release Page 

View Jakarta EE 8 Release Page

**Comment by flora8984461** [comment]
@karenmcnaughton Thanks for the feedback. I just updated the preview, https://deploy-preview-1064--jakartaee.netlify.app/compatibility/download/ will be updated soon.

**Comment by karenmcnaughton** [comment]
Thanks yes, that's good.
