### ISSUE TITLE
the Jakarta EE Steering and Jakarta EE Specification pages update

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1066]
Can you please make the following update on both: the Jakarta EE Steering (https://jakarta.ee/committees/steering/) and Jakarta EE Specification pages (https://jakarta.ee/committees/specification/)

Instead  
Scott (Congquan) Wang - Primeton - Elected Enterprise Representative

please list 
Dr. Jun Qian  - Primeton - Elected Enterprise Representative

Thanks!
Tanja

**Comment by karenmcnaughton** [comment]
Can we please update this page:  https://jakarta.ee/committees/marketing/

VACANT - Elected Committer Member Representative
VACANT - Elected Participant Member Representative

With:
- Otavio Santana: Elected Committer Member Representative
- Tetiana Fydorenchyk: Elected Participant Member Representative

**Comment by chrisguindon** [comment]
> Can we please update this page: https://jakarta.ee/committees/marketing/
> 
> VACANT - Elected Committer Member Representative
> VACANT - Elected Participant Member Representative
> 
> With:
> 
> * Otavio Santana: Elected Committer Member Representative
> * Tetiana Fydorenchyk: Elected Participant Member Representative


@flora8984461 can you add this to your list for today?

**Comment by flora8984461** [comment]
@chrisguindon @karenmcnaughton  The changes are updated and the preview is https://deploy-preview-1080--jakartaee.netlify.app/committees/marketing/

Thanks!
