### ISSUE TITLE
Add jadeva GmbH on Jakarta EE website

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#1069]
Hello 
Please add jadeva GmbH as Participant Member on the Jakarta EE website https://jakarta.ee/membership/members/

![Logo_JadevaGmbH+Slogan_CMYK_72dpi](https://user-images.githubusercontent.com/50374570/108374858-67e28700-71cf-11eb-9927-c10c6c1d80f4.png)

**Comment by flora8984461** [comment]
Hi @ZahraFazli 

Can you please help me confirm with the member's website? I found one https://jadeva.eu/

**Comment by ZahraFazli** [comment]
Yes, confirmed. Thanks
