### ISSUE TITLE
Create a projects tab pulling from https://projects.eclipse.org/projects/ee4j (similar to http://microprofile.io/projects)

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakarta.ee#107]
**This is a placeholder, more details to come**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jgallimore** [comment]
For reference, the microprofile.io site runs on TomEE, and the code for it is here: https://github.com/microprofile/microprofile-site.

The list of projects is populated dynamically by using the GitHub API to search for projects under the microprofile organization. This has the advantage that adding new project repositories doesn't require a manual update to the page, but does require a backend server, which this site currently does not have or need.

I don't know off the top of my head if there is public access to the relevant GitHub APIs without credentials, but I suspect there isn't. GitHub API tokens should be correctly secured, so we can't really expose them in Javascript executed in the browser.

I'm happy to investigate further, but initial suggestions are to make either a static page with links to the repository, or generate the static page daily using an external process that can query GitHub and commit updates to this project.

**Comment by chrisguindon** [comment]
The new project page is now available on the website:
https://jakarta.ee/projects/

The projects link on the homepage was updated to point to this new page. 

EMO is currently responsible for managing the list of projects on this page from projects.eclipse.org. 

Please open an issue if we are missing a project of if you think we should remove a project from this page.
