### ISSUE TITLE
[redesign-2021] - Jakarta New Website Design Feedback

### ISSUE THREAD

**Issue by karenmcnaughton** [jakartaee/jakarta.ee#1070]
https://projects.invisionapp.com/share/MV1064CX7GC6#/screens/444513792

Initial Input from Meeting: Feb 18, 2021
* Consider a carousel at the top which would scroll and highlight
* Reduce the overall jumbotron header size (top to bottom)
* Consider increasing content on the page to ensure we have enough for SEO value
* Potentially move away from stock images if possible
* Ensure still in format that easily supports translation
* Specs page - search and sort is great
    * Add search on active, evolving
    * Change “Jakarta Specifications” to “Component Specifications” to avoid confusion about the top specs not being Jakarta specs.
    * Add click of the Spec header to take you to the spec summary page - eg. https://jakarta.ee/specifications/authorization/
    * Make searchable on higher level versions (eg. Jakarta EE 8)
    * Compatible Products
    * Need to clarify the role and meaning of the dropdown
    * Could we show the latest version information as the default int the dropdown?
    * Rather than certification results, could the button take people to the download?
    * Do we need a similar page to Compatible Products for Tools Vendors?
    * Meet on the March 4th to review GitHub issue and David’s presentation

**Comment by laliwa** [comment]
#about homepage
I'd like to suggest that we put the most important information on Top of the home page which could change frequently. So each visitor will always check something new. It will also do good for the SEO and enrich the content.
It can be implemented as a slider with different banners scrolling horizontally and automatically. Just like this. http://primeton.com/

#about subpage banners
Karen said that should be should be shrunk into a better appearance, but I think it doesn't have to do this. We can also add some key information about this page on the banner. So visitors will grasp the main idea of the page at first sight. Just like this. 
![微信图片_20210220110755](https://user-images.githubusercontent.com/1784830/108582154-51256700-736c-11eb-90ef-20e9b573b54f.png)

**Comment by dominikatasarz** [comment]
A few comments from my team:

- The resources page - are we going to categorize resources by type of resource first (Presentation, Documentation, Datasheets) rather than by project or by topic (maybe there aren't resources for every project)? People don't really say "I need a new datasheet", they look for the answer to a problem or info to see how to do something - so categorising may need re-thinking
- Navigation font at the top looks a bit too small

**Comment by aeiras** [comment]
+1 @dominislawa!

A good example is the MicroProfile Branding Resources [space](https://microprofile.io/resources/branding/) & the MPWG [page](https://microprofile.io/workinggroup/)

Both pages contain call to action buttons that make the reader interact.

**Comment by cesarhernandezgt** [comment]
Comment from my team:

- We should have an inventory of current open Issues from https://github.com/jakartaee/jakarta.ee/issues and https://github.com/jakartaee/collateral/labels/website
- The testimonials can include Contributors, Committers, companies etc.
- The white papers can have categories for users, tools, and implementers.
- Highlighting community members.JUG's logos, etc.

**Comment by chrisguindon** [comment]
The design files have been delivered to the webdev team:
https://github.com/jakartaee/jakarta.ee/issues/1106

I assume the feedback period is over.

Closing this bug.
