### ISSUE TITLE
Open Liberty 21.0.0.3-beta as a Compatible Software Product for Jakarta EE 9, Platform

### ISSUE THREAD

**Issue by brideck** [jakartaee/jakarta.ee#1078]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Brian Decker - IBM - Eclipse Profile](https://accounts.eclipse.org/users/bdeckerhdt)

**A product name and version**
[Open Liberty 21.0.0.3-beta](https://openliberty.io/)

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[https://openliberty.io/certifications/assets/OL_logo_navy.zip](https://openliberty.io/certifications/assets/OL_logo_navy.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[IBM Corporation](https://www.ibm.com/)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Full Platform: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/307](https://github.com/eclipse-ee4j/jakartaee-platform/issues/307)

**The URL where Compatible Software Product is available for download**
[https://openliberty.io/downloads/#runtime_betas](https://openliberty.io/downloads/#runtime_betas)

**Comment by flora8984461** [comment]
Hi Tanja @TanjaObradovic , can you help us check the preview link to verify the compatibility product is expected?

https://deploy-preview-1081--jakartaee.netlify.app/compatibility/#tab-9

Thanks!

**Comment by TanjaObradovic** [comment]
Looks good! thanks @flora8984461
