### ISSUE TITLE
Add case studies section to jakarta.ee/resources/

### ISSUE THREAD

**Issue by jph152** [jakartaee/jakarta.ee#1087]
Please create a heading for Case Studies on the Jakarta EE Resources page. Attached is the Payara member case study to go under this section

Content:
### Case Studies
[Payara Services Gains an Equal Footing With Industry Leaders at the Eclipse Foundation
](https://outreach.eclipse.foundation/payara-services-open-source-case-study)

**Comment by flora8984461** [comment]
@jph152 Hi, just hope to confirm, this should also appear on the Chinese page, right? I am going to include Eric to help with the translation. Thx! (I speak Chinese but translation is too literature for me 😅)

**Comment by flora8984461** [comment]
The preview is https://deploy-preview-1088--jakartaee.netlify.app/
And I included it in the menu as well.

**Comment by jph152** [comment]
Thanks Yi! It looks ready to go live. 
And yes, this will be going on the Chinese page as well
