### ISSUE TITLE
Compatibility certification request for TongWeb Application Server for Full Profile

### ISSUE THREAD

**Issue by tongtech-web** [jakartaee/jakarta.ee#1092]
- [x] Organization Name ("Organization") and, if applicable, URL:  
    [Beijing TongTech Co., Ltd.](https://www.tongtech.com/)
    
- [x] Product Name, Version and download URL (if applicable):  
    [TongWeb Application Server](http://www.tongtech.com/Services/Services-104.html)
    
- [x] Specification Name, Version and download URL:  
    [Jakarta EE Platform, Full Profile 8.0](https://jakarta.ee/specifications/platform/8)
    
- [x] TCK Version, digital SHA-256 fingerprint and download URL:  
    [Jakarta EE Platform TCK 8.0.2](https://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip)  
    `SHA-256: 14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965`
    
- [x] Public URL of TCK Results Summary:  
    [TongWeb TCK results](http://www.tongtech.com/tw7.jakarta-full-platform-8.html)
    
- [x] Any Additional Specification Certification Requirements:  
	[Jakarta Dependency Injection 1.0 TCK](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip)  
    `SHA-256: b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`  
  
	[Jakarta Contexts and Dependency Injection 2.0 TCK](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip)  
    `SHA-256: 75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`  
  
	[Jakarta Bean Validation 2.0 TCK](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip)  
    `SHA-256: b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974`  
- [x] Java runtime used to run the implementation:  
  Oracle JDK 1.8.0_202
  
- [x] Summary of the information for the certification environment, operating system, cloud, ...:  
  
  ```
  OS version: CentOS Linux Server 7.5 x86_64
  Database version:   Apache Derby Network Server 10.14.2.0
  Database JDBC Driver and version:  Apache Derby 10.14.2.0
  ```
  
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by TanjaObradovic** [comment]
Please close this issue, as the Jakarta EE Platform team cannot see it here. Please open it under
https://github.com/eclipse-ee4j/jakartaee-platform

**Comment by chrisguindon** [comment]
Closing as invalid.
