### ISSUE TITLE
Add iJUG as Participant Member

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#1094]
Please add iJUG as a Participant Member on the Jakarta EE website
![iJUGdownload](https://user-images.githubusercontent.com/50374570/111213458-24e5ba80-85a7-11eb-8b15-ca93ae118c4a.png)

https://jakarta.ee/membership/

**Comment by autumnfound** [comment]
Preview available on https://deploy-preview-1101--jakartaee.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
+1
