### ISSUE TITLE
Please add WildFly Preview as Jakarta EE 9 Web Profile compatible

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#1096]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://www.eclipse.org/membership/showMember.php?member_id=731

**A product name and version**

[WildFly Preview 23.0.0.Final](https://wildfly.org/downloads)

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**

Web Profile

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

https://github.com/wildfly/certifications/blob/EE8/images/wildfly-logo-stacked-100px-2132977.zip?raw=true

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Red Hat

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

https://github.com/eclipse-ee4j/jakartaee-platform/issues/315

**The URL where Compatible Software Product is available for download**

https://wildfly.org/downloads

**Comment by TanjaObradovic** [comment]
LGTM! +1

**Comment by chrisguindon** [comment]
Preview is available here:
https://deploy-preview-1102--jakartaee.netlify.app/compatibility/

**Comment by scottmarlow** [comment]
@chrisguindon the preview looks awesome, thank you for making the change!
