### ISSUE TITLE
[Jelastic] Submission of Jakarta EE Working Group Participant Quote

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1098]
In the collateral repository, we received https://github.com/jakartaee/collateral/issues/41 created by @TetianaFTV a couple of months ago. 

Technically speaking, the update is fairly simple so I took the change to understand the existing `Member Testimonials
 section` from the page https://jakarta.ee/membership/ and created the following PR: https://github.com/jakartaee/jakarta.ee/pull/1097 that can be previsualized here: https://deploy-preview-1097--jakartaee.netlify.app/membership/

For reviewing the PR, please notice that the member testimonials section Is a carousel, every time you refresh the page you get a new random set of quotes.

**Comment by chrisguindon** [comment]
#1097 has been merged!
