### ISSUE TITLE
Add "Community Cards" to Jakarta EE Resources

### ISSUE THREAD

**Issue by jph152** [jakartaee/jakarta.ee#1099]
We’d like to add the attached images to a new page on the Jakarta website similar to this:

https://maven.apache.org/resource/branding/actioncards.html

The individual image files should be hosted on https://jakarta.ee as well

Potential URL: https://jakarta.ee/resources/action-cards

Content for new page: https://docs.google.com/document/d/1wiIkibakpgqSGR-2wLBxnsObeFuewhFWNEofzdzkaXk/edit?usp=sharing

<img width="1200" alt="1" src="https://user-images.githubusercontent.com/69642121/111823677-9b422f80-88bb-11eb-951e-b703a31f56f1.png">
<img width="1200" alt="2" src="https://user-images.githubusercontent.com/69642121/111823684-9d0bf300-88bb-11eb-8c5b-2f5acc6b164b.png">
<img width="1200" alt="3" src="https://user-images.githubusercontent.com/69642121/111823688-9f6e4d00-88bb-11eb-8f16-b99dcc93c885.png">
<img width="1200" alt="4" src="https://user-images.githubusercontent.com/69642121/111823694-a1381080-88bb-11eb-815b-3313a3eefdc0.png">
<img width="1200" alt="5" src="https://user-images.githubusercontent.com/69642121/111823701-a301d400-88bb-11eb-8382-5cdbc77ac0b6.png">

**Comment by aeiras** [comment]
Clean, simple, and a beautiful start of the many cards @jph152! 

Thank you for working on request ticket 57 from the Collateral repo.  +1 from me! 

https://github.com/jakartaee/collateral/issues/57

**Comment by aeiras** [comment]
Additional cards could be: 

> I am a contributor to X Spec (33 API + Platform + TCK). 

> I am a Committer to X Spec 33 API + Platform + TCK) 

I recommend making cards for all Specs, including Marketing as well matters. 
currently Jakarta doesn’t recognize business contributors, that will have to change as collateral Repo allows fixing it that oversight. 

🙏

**Comment by mkarg** [comment]
Until the spec-specific cards exist, would it be appropriate to use the Jakarta EE cards instead, or are the Jakarta EE cards just for the  platform committers?

**Comment by ivargrimstad** [comment]
@mkarg Go ahead! They're not specific to any specification.

**Comment by jph152** [comment]
Hi @autumnfound , is there a timeline for this one? Let me know if we can provide any more information/clarification

**Comment by autumnfound** [comment]
How would you like these to be displayed on the page? As links to the image, as the image themselves, or something else?

**Comment by jph152** [comment]
We'd like it to be the image themselves, linked to the corresponding file.

Do you need smaller versions of the images to display on the page?

**Comment by autumnfound** [comment]
Nope! I can just have them display smaller easily enough!

**Comment by autumnfound** [comment]
@jph152 looking at the apache site, they use the full res images on their page, but the largest image is around 600kb, which is around a third of the size of our images. If we want to use the images in full res on the page, I would recommend compressing them for web (making them a little smaller in size). 

Alternatively, converting them to jpg and offering it as the standard resolution, and having a full resolution image through a link that a user can open for bigger images might be better. This way, we can allow for people to use larger, less compressed images, or use the compressed for web images that load quickly. WDYT?

**Comment by aeiras** [comment]
Team, 

the size matters as it can be used by any media channel without issues.

**Comment by rstjames** [comment]
I recommend 1200x629. This format will work well with Twitter, FB, and Linkedin. Try to leave a "safe zone" around the edges (80px on all sides.). This will make sure that no important content is cut off if some resizing occurs. 
<img width="1069" alt="Screen Shot 2021-04-16 at 8 28 04 PM" src="https://user-images.githubusercontent.com/12132146/115069387-c8522400-9ef3-11eb-8cf5-9953ddcc6c05.png">

**Comment by autumnfound** [comment]
@jph152 any decisions upstream on what we should do?

**Comment by jph152** [comment]
![1](https://user-images.githubusercontent.com/69642121/115891189-cde3c880-a423-11eb-9541-450fdfc86b30.jpg)
![2](https://user-images.githubusercontent.com/69642121/115891194-cfad8c00-a423-11eb-9c7d-9554b03b60a4.jpg)
![3](https://user-images.githubusercontent.com/69642121/115891197-d0deb900-a423-11eb-8b94-936bacb3db9f.jpg)
![4](https://user-images.githubusercontent.com/69642121/115891202-d0deb900-a423-11eb-86c0-908724c6eba8.jpg)
![5](https://user-images.githubusercontent.com/69642121/115891203-d1774f80-a423-11eb-9386-36e271630050.jpg)

**Comment by jph152** [comment]
@autumnfound Above are the smaller jpg images that we can use to display on the page (1200x629 as recommended)

**Comment by jph152** [comment]
Here are the larger images that we can link to:
<img width="900" alt="2" src="https://user-images.githubusercontent.com/69642121/115891945-accfa780-a424-11eb-960b-c2ffa95cc8ae.png">
<img width="900" alt="3" src="https://user-images.githubusercontent.com/69642121/115892059-ccff6680-a424-11eb-9eed-0b2bc2f2c1cb.png">
<img width="900" alt="4" src="https://user-images.githubusercontent.com/69642121/115892066-cec92a00-a424-11eb-81d3-bc8fa90d75cd.png">
<img width="900" alt="5" src="https://user-images.githubusercontent.com/69642121/115892077-d12b8400-a424-11eb-9ab5-c5abfbecd263.png">

<img width="900" alt="1" src="https://user-images.githubusercontent.com/69642121/115891732-68440c00-a424-11eb-9b48-1610ef077f55.png">

**Comment by autumnfound** [comment]
@jph152 I've got a preview for this available https://deploy-preview-1122--jakartaee.netlify.app/ I've added space between the cards as just an initial way of stacking them. Did you want something different?

**Comment by jph152** [comment]
Thanks! I added some content for the page in this doc:
[Jakarta EE Community Cards.docx](https://github.com/jakartaee/jakarta.ee/files/6367373/Jakarta.EE.Community.Cards.docx)

Could we change the heading to "Community Cards" ?
 
We should also add a link to this page on https://jakarta.ee/resources/

**Comment by autumnfound** [comment]
I've updated the page with the content https://deploy-preview-1122--jakartaee.netlify.app/resources/community-cards/ where would you want this link?

**Comment by jph152** [comment]
I think adding it on a list item on https://jakarta.ee/resources/ is fine. (pic attached for reference)

<img width="648" alt="Screen Shot 2021-04-23 at 3 21 28 PM" src="https://user-images.githubusercontent.com/69642121/115920103-b9192c00-a447-11eb-8987-c85f1e99aadd.png">
Content:

[H2] Social Cards
[Body] Jakarta EE Community Cards

**Comment by autumnfound** [comment]
I've added it to the page in the preview: https://deploy-preview-1122--jakartaee.netlify.app/resources/ is everything good with this change?

**Comment by jph152** [comment]
Yes +1 
Thank you!

**Comment by autumnfound** [comment]
This is now live, thanks everyone!
