### ISSUE TITLE
Expand https://jakarta.ee/connect/ to provide more information to members on which mailing lists are recommended, how to communicate with the community, etc. 

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakarta.ee#110]
**This is a placeholder, more details to come**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jgallimore** [comment]
It would be useful to try and draft up some text for this one. How about:

* Recommending new users start by joining the Jakarta EE Community Mailing List
* For each list, provide a rough idea of the message volume and a "Join this list if you are a <newcomer / developer / CTO / looking to become a strategic member / etc>"
* Point to the code of conduct (there is one for this website project, which might work if we don't already have one)

**Comment by TanjaObradovic** [comment]
I think we can close this one.
