### ISSUE TITLE
Add 2020 Survey Infographic to jakarta.ee/resources/

### ISSUE THREAD

**Issue by jph152** [jakartaee/jakarta.ee#1103]
Can we add the link below to the resources page under **Infographics**?

TEXT: Jakarta EE Developer Survey Findings 2020

LINK: https://f.hubspotusercontent30.net/hubfs/4753786/JakartaEE-Infographic.pdf?utm_campaign=2021%20Jakarta%20EE%20Developer%20Survey&utm_source=resources

**Comment by autumnfound** [comment]
Initial preview of this change is now available: https://deploy-preview-1111--jakartaee.netlify.app/resources/#infographics

This is one of the pages with a Chinese language copy, do we want the initial launch to have the right label?

**Comment by jph152** [comment]
Yes, if possible
