### ISSUE TITLE
Remove K-teq from the Jakarta EE Website

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#1104]
K-Teq Srls is no longer an Eclipse and Jakarta EE Member. 
Please remove their logo from the website
https://jakarta.ee/membership/members/

**Comment by aeiras** [comment]
When a jkta member departs, do we ask them the why? 

It has been + 3 years & I have never seen a summary of retrospective feedback brought in to the WG to help adjust what currently is & improve the dynamics of the WG. 

Who can answer this & how can we improve it?

**Comment by chrisguindon** [comment]
@aeiras I am not sure who is the best person to answer your question but I will @TanjaObradovic!

**Comment by aeiras** [comment]
Gracias, Chris!
