### ISSUE TITLE
[redesign-2021] - Final Jakarta.ee Redesign Files

### ISSUE THREAD

**Issue by karenmcnaughton** [jakartaee/jakarta.ee#1106]
For WebDev:

Here are the Final Design Files: https://www.dropbox.com/sh/uuwc2uapbk0bxdi/AACXXn80GxVSu6OZkYFyRScAa?dl=0

Invision link: https://invis.io/AX10M9QL74RN

Notes:

- Size of home page banner is only reduced on one of the artboards so that you can choose from the bigger or smaller size
- Compatible Products page - added back the download button from earlier versions just on the first box in case the downloads are incorporated here

- Next steps: WebDev to review and regroup for timeline of implementation.

- A phased approach may be planned

**Comment by chrisguindon** [comment]
Let's use this bug to discuss any issues related to the files that were delivered for this project.

@ericpoirier @meKokabi,
Can you both also review the xd files for jakarta.ee and confirm that we can extract everything we need to implement this re-design.

I assume that the files here are very similar to the one from ecdtools:
https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/91

...but let's make sure all is well before we get started!

//cc @autumnfound & @shanda-eclipse  for visibility.

**Comment by meKokabi** [comment]
> Let's use this bug to discuss any issues related to the files that were delivered for this project.
> 
> @ericpoirier @meKokabi,
> Can you both also review the xd files for jakarta.ee and confirm that we can extract everything we need to implement this re-design.
> 
> I assume that the files here are very similar to the one from ecdtools:
> [EclipseFdn/ecdtools.eclipse.org#91](https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/91)
> 
> ...but let's make sure all is well before we get started!
> 
> //cc @autumnfound & @shanda-eclipse for visibility.

This files has all the required assets. All stored here: https://www.dropbox.com/sh/uuwc2uapbk0bxdi/AACXXn80GxVSu6OZkYFyRScAa?dl=0 and under links folder.
 It also includes the Native Adobe Illustrator files.

**Comment by chrisguindon** [comment]
@meKokabi,

So we will need you to extract images that we need from these adobe illustrators files? Can you give us a rough estimate of how much work this is for you?

@ericpoirier is this something you can do?

@karenmcnaughton, @shanda-eclipse,

Why is Excentric delivering designs in two different formats for two websites? We got .xd file for ecdtools.eclipse.org and an .ai file jakarta.ee.

We can be flexible but we need them to deliver files in a consistent format.

**Comment by chrisguindon** [comment]
Webdev and Marketing recently had a discussion about this. 

There is still some work that needs to be done on these files before we can start the implementing stage. 

@shanda-eclipse have we decided to deal with this internally or will we ask Excentric to make the changes for us?

**Comment by shanda-eclipse** [comment]
I think we can do this internally. I'll ask Mehrnaz to work on prepping the files and we will have them to you by May 1 so you can start development.

**Comment by karenmcnaughton** [comment]
This work is complete, the design is final and development has begun.
