### ISSUE TITLE
Add Jakarta EE White Paper to https://jakarta.ee/release/9/ and https://jakarta.ee/resources/

### ISSUE THREAD

**Issue by jph152** [jakartaee/jakarta.ee#1107]
Please add this link to the button on the Jakarta EE 9 page and Jakarta EE Resources.
Link: https://outreach.jakartaee.org/white-paper-java-applications

On the Jakarta EE 9 page, we'd like to change the heading to "NEW WHITE PAPER" and the button text to "DOWNLOAD"
<img width="508" alt="Screen Shot 2021-03-31 at 11 17 36 AM" src="https://user-images.githubusercontent.com/69642121/113168485-b47ba200-9212-11eb-97ac-4e9909da8130.png">

For the Resources page, we'd like a section titled "White Papers" 
[Why Jakarta EE Is the Right Choice for Today’s Java Applications
](https://outreach.jakartaee.org/white-paper-java-applications)

**Comment by jph152** [comment]
Hi guys, do we have a timeline for this issue?

**Comment by autumnfound** [comment]
Preview is now available: https://deploy-preview-1115--jakartaee.netlify.app/ let me know if you need additional changes!

**Comment by jph152** [comment]
Everything on the resources page looks good thanks!

Has the button and text on https://jakarta.ee/release/9/ been updated too?

**Comment by autumnfound** [comment]
Yep! https://deploy-preview-1115--jakartaee.netlify.app/release/9/

**Comment by jph152** [comment]
Great! +1

**Comment by jph152** [comment]
Hi Martin, can we push this live?
