### ISSUE TITLE
Add Istanbul JUG as Member of the Jakarta EE WG site

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#1108]
Istanbul JUG has joined as a Guest Member of the WG
Please add Istanbul JUG on the Jakarta EE Website https://jakarta.ee/membership/members/
![Istanbul JUG](https://user-images.githubusercontent.com/50374570/113183288-d6305580-9221-11eb-9aad-532039606e37.png)

**Comment by ZahraFazli** [comment]
Requires Steering Committee approval

**Comment by ZahraFazli** [comment]
Reopening the issue as they are now approved by the Steering Committee

**Comment by TanjaObradovic** [comment]
Please create a section for Guest Members and list the JUG there.

**Comment by aeiras** [comment]
Istanbul JUG rocks, happy to see this ticket move! 

@TanjaObradovic, 

Does the Jakarta WG has a public document where ORGs and JUGs can refer as to how they could become and request to be a Guest member for the project?
I look & cannot see it. 
Also, it is important to note that only Committers and Guests pay $0 WG memberships, within the document. 

The WG Charter for EF projects rules on how Guests are welcomed and stuff. As this is relevant & goes with the EF bylaws and the Project's bylaws, I look forward to that document coming to the light! 

Thanks for the follow up,

**Comment by TanjaObradovic** [comment]
@aeiras it is all documented and published at https://jakarta.ee/membership/ pages, in particular https://jakarta.ee/documents/membership/jakarta-ee-membership-prospectus.pdf. Please see slide 9, and subtitle "Jakarta EE Committer and Jakarta EE Guest Member Annual Participation Fees". 
For other classes of membership fees please refer to the table on the same page. There are various options.
Note, your statement "Also, it is important to note that only Committers and Guests pay $0 WG memberships, within the document." is not correct.

**Comment by aeiras** [comment]
wonderful, Tanja! 
thank you.

**Comment by linkfang** [comment]
Istanbul JUG was added into Guest Member list.
Check here: https://jakarta.ee/membership/members/

**Comment by ZahraFazli** [comment]
Hello
Istanbul JUG just brought to our attention that the link to the logo should redirect to website: https://www.jugistanbul.org/
Thanks,
Zahra

**Comment by linkfang** [comment]
Hi @ZahraFazli , sorry for the incorrect URL. Just fixed it and here is the preview:
https://deploy-preview-1131--jakartaee.netlify.app/membership/members/
