### ISSUE TITLE
add 2020 Survey Infographic to jakarta.ee (Chinese translation)

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#1112]
We need a translation for: https://github.com/jakartaee/jakarta.ee/pull/1111

**Comment by chrisguindon** [comment]
@laliwa,

Please meet our new Front-End Developer @linkfang.

Zhou can also speak Chinese. Feel free to reach out to him if you have any questions!

**Comment by linkfang** [comment]
Hi @laliwa , nice to meet you!

For the translation, I think we can do it like
Jakarta EE Developer Survey Findings 2020 => Jakarta EE 开发者调研结果2020
Or it might be better this way:  Jakarta EE 开发者2020调研结果

What do you think?
Thanks!

**Comment by laliwa** [comment]
Nice to meet you, too. It's great to have some more speaking Chinese, you can contact my Wechat if you would like to.
What you suggested sounds OK to me. It can also be "2020年Jakarta EE 开发者调研发现" as well

**Comment by laliwa** [comment]
> @laliwa,
> 
> Please meet our new Front-End Developer @linkfang.
> 
> Zhou can also speak Chinese. Feel free to reach out to him if you have any questions!

Thanks a lot to Chris and sorry that I missed this issue.
