### ISSUE TITLE
Please change the link of the Jakarta EE Community Folder under Resources 

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1113]
Please change the current link of the Jakarta EE Community Folder to 

https://drive.google.com/drive/folders/11nvqdVqFlCxm5AfPh2NdnanTBrCPW8Xv

See here

![image](https://user-images.githubusercontent.com/40073121/114041531-a05b2480-9852-11eb-9823-0432bc9d1ecc.png)

Thanks!

**Comment by autumnfound** [comment]
Please see the following link for a preview: https://deploy-preview-1116--jakartaee.netlify.app/
