### ISSUE TITLE
Please add Jakarta EE Specifications Meetings Calendar to the connect page

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1114]
Can you please add a section on https://jakarta.ee/connect/ for Jakarta EE Specifications Meetings Calendar?

The section name can be *Jakarta EE Specifications Meetings Calendar*

Here is the link

https://calendar.google.com/calendar/embed?src=eclipse-foundation.org_e9ki8t2gc75sh07qdh95c8ofvc%40group.calendar.google.com&ctz=America%2FToronto

@karenmcnaughton please have a look and give your +1 as well.

This Calendar is open to the public if they are interested to attend any of the any of the specification project meetings.

**Comment by autumnfound** [comment]
See https://deploy-preview-1117--jakartaee.netlify.app for the preview of the fix! Currently, we are missing body text for the section, and the heading is quite long and nearly doesn't fit properly. We also require a Chinese translation for the labels
