### ISSUE TITLE
Please add Apusic Application Server as Jakarta EE 9 Web Profile compatible

### ISSUE THREAD

**Issue by PatrickHuang888** [jakartaee/jakarta.ee#1120]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=1397

**A product name and version**
AAS V10-EE9

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Web Profile

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/apusic/aas-tck/blob/master/aas.jpg

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Kingdee Apusic cloud computing Co., Ltd.

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/328

**The URL where Compatible Software Product is available for download**
Currently we will not likely provide public downloading this version, and we will provide it to customer or specific user if they apply for.

**Comment by linkfang** [comment]
Hi @chrisguindon 

For the Jakarta EE 9 Platform Compatible Products part, we normally need a download URL for each product. Like here:
https://jakarta.ee/compatibility/#tab-9 

But for Apusic, it's a little special, as they currently will not provide public download, only offer it to specific customers and users.

What should we do for this case? I am not sure if we can leave the download URL empty?

**Comment by chrisguindon** [comment]
Hi @linkfang,

I will redirect your question to @TanjaObradovic. She is responsible for this section. These changes must be approved with a +1 from @TanjaObradovic before we can make them live!

@TanjaObradovic Can we publish a compatible product without a download link?

**Comment by TanjaObradovic** [comment]
@linkfang @chrisguindon, we will deal with these on case to case bases. Please go ahead and publish the Apusic Application Server as Jakarta EE 9 compatible if everything else is in order.

**Comment by linkfang** [comment]
@TanjaObradovic OK, sounds good. Thanks Tanja!

**Comment by chrisguindon** [comment]
@linkfang We need to provide a preview URl on this issue to let @TanjaObradovic review and approve.

Netlify will generate one for you once you submit your PR!

**Comment by linkfang** [comment]
@chrisguindon OK, got it!
Hi @TanjaObradovic , you can review the page here:
https://deploy-preview-1121--jakartaee.netlify.app/compatibility/#tab-9
