### ISSUE TITLE
Add Survey Social Cards to jakarta.ee/resources

### ISSUE THREAD

**Issue by jph152** [jakartaee/jakarta.ee#1124]
Please add this link under the **Social Cards** heading of the Jakarta EE Resources page:

[I Completed the Jakarta EE 2021 Developer Survey](https://f.hubspotusercontent30.net/hubfs/4753786/Completed-Jakarta-Developer-Survey.gif)

**Comment by linkfang** [comment]
Hi @jph152 
The link was added. Check here:
https://jakarta.ee/resources/#cases-studies

**Comment by jph152** [comment]
Looks good, thanks
