### ISSUE TITLE
Jumbotron redesign

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1133]
In the new Jakarta EE redesign, all pages will have at least a standard height jumbotron (see the second link). On the homepage, there will be a jumbotron with an alternate image and larger font size for the headline. Additionally, the image used in the jumbotron on every page should be configurable at the page level, as there are cases where this can change page to page (an alternative to this if the only case of this is on the home page is that the alternate layout has the secondary image configured).

@karenmcnaughton question for the larger text size. Do we want to use the larger headline text on any page with an additional tagline in the jumbotron, or just on the homepage? 

Design elements:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585117

**Comment by autumnfound** [comment]
RE text size, just a homepage style treatment rather than a styling for interior pages.

**Comment by linkfang** [comment]
In the design elements, the height of the jumbotron in [1st](https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585111) and [2nd](https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585112) screen is different. 

So, should we show a different jumbotron height on home page based on whether the navigation menu shows up or not?

**Comment by autumnfound** [comment]
> In the design elements, the height of the jumbotron in [1st](https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585111) and [2nd](https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585112) screen is different.
> 
> So, should we show a different jumbotron height on the home page based on whether the navigation menu shows up or not?

I believe that is just a holdover from changes made between revisions. Changing the page as you open the menu wouldn't be a good experience, so we would either use the taller or shorter version. Based on how we've been going with the Jumbotrons lately, I would say we're likely going to use the shorter version.

**Comment by ericpoirier** [comment]
The jumbotron section was merged with the site's redesign.

Thanks!
