### ISSUE TITLE
Navigation and tool bar updates

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1134]
The navbar will be given more room to breathe in the new look, with a larger top and bottom margin, along with a larger logo. Active sections will be given an orange underline to denote the section (which can be accomplished with a border-bottom and some padding).

The toolbar which hoses the language toggle, user account, and cookie management links will also be updated. In the new design, the language toggle is given more padding, and the other links are replaced with a search toggle. In addition, the background will change from a solid color to use a background image (which seems to be a centered version of the image used for the homepage jumbotron section). The last change to this section is a bottom border will be added with the same color as the dropdown menu state pre-hover (#1F1F65), with a thickness of about 5px.

@karenmcnaughton a question about the design here. Are we expecting a similar flyout to the menu described on the [second screen in the design](https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585112) for the language toggle and search menu, or is there an alternative planned for it?

Design elements:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585119
![image](https://user-images.githubusercontent.com/23018241/117822652-be91b700-b23a-11eb-9379-d105b6d82b7f.png)
![image](https://user-images.githubusercontent.com/23018241/117822772-d23d1d80-b23a-11eb-9da6-948ac0ed4ad4.png)

**Comment by autumnfound** [comment]
RE flyout, they will be the same style as the navigation menu flyouts!

**Comment by linkfang** [comment]
I am not sure if all the navigation items/options will have a flyout? 

If yes, then I think I am good.
But if not, I think it might be a little clearer for users if we have a drop-down icon besides the item/option? Just like what we currently have for "Resources"
![image](https://user-images.githubusercontent.com/43075439/118036650-d2bcdd80-b33a-11eb-9084-47fc1bc98710.png)

**Comment by autumnfound** [comment]
I agree with the dropdown indicator, good catch on the details! For accessibility purposes we should indicate that there are more options associated with the option.

**Comment by ericpoirier** [comment]
The navigation was updated with the site's redesign.

Thanks!
