### ISSUE TITLE
Homepage split headline section

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1135]
For the homepage, a special section will be created with 2 sections. The first will contain text for the page, with icon highlight cards starting in this section and overlaying into the second section. The second section should be large enough to contain the cards with an additional 50px bottom margin (estimate). 

Relative positioning should be used with some static heights and maxes used to contain the cards properly. This will mean that this section will have a maximum content height or risk breaking out of the container and impacting other sections of the page. The content maximum should be maintained manually rather than through concatenation of the content, as this could create issues in the future.

Design elements: 
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585111
![image](https://user-images.githubusercontent.com/23018241/117822521-9f932500-b23a-11eb-8a5b-ae62b05376bc.png)

**Comment by ericpoirier** [comment]
The split headline section was merged with the site's redesign.

Thanks!
