### ISSUE TITLE
Homepage members carousel

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1136]
The homepage members carousel can be created using an Owl carousel with simple text sections underneath the section. Ordering and data for this component will be driven by a `members.yaml` file created in the data folder. An example of how this carousel is built can be seen in the [user_display component](https://github.com/EclipseFdn/hugo-solstice-theme/blob/master/layouts/shortcodes/events/user_display.html) in the Hugo solstice theme.

The member levels should each have an i18n key that matches a string representing the level (e.g. "strategic" would map to an i18n label with a key like "members-strategic-text" and value of "Strategic Members" in English). This would allow us to have a single data file rather than forcing multiple translations for a straightforward file.

Design Elements: 
![image](https://user-images.githubusercontent.com/23018241/117330291-86b5f880-ae63-11eb-9a43-0c85827f62b6.png)

**Comment by ericpoirier** [comment]
The members section was merged with the site's redesign.

Thanks!
