### ISSUE TITLE
What's new homepage section

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1137]
The What's New section will be a section driven by a tabbed section from bootstrap. The first 2 sections are populated by newsroom News (with different content types), and the third through Newsroom Events, retrieving upcoming events only. The current homepage makes use of this, but will need some markup and templates created+configured to better accomodate the new look and feel. IoT makes use of custom templates, and may be a good place to start for those!

@karenmcnaughton question regarding the other sections. Is the intention that we use similar horizontal card layouts for each of the following news and events sections? For the news section, images are an optional field and may not exist for all news items. How should we display those?

Additionally, there is no field to capture images for events submitted to newsroom, so we would either need to use static images for these events (which could be confusing), or use a rext only version of the horizontal card in its place. The text only version is the easiest solution here I think, but WDYT?

Design:
![image](https://user-images.githubusercontent.com/23018241/117330667-ed3b1680-ae63-11eb-863f-d747d0f3503e.png)

**Comment by autumnfound** [comment]
RE images, we need a generic image for the news image embed when there is none available. If we want something snazzy, we might need to do this post-launch if things get tight. 

RE events not having images, we will need more discussions to decide what look and feel we want. There are a lot of tile alternatives in the process of being created (rough draft here [card styleguide](https://deploy-preview-248--eclipsefdn-solstice-assets.netlify.app/cards)).

**Comment by ericpoirier** [comment]
The what's new section was merged with the site's redesign.

Thanks!
