### ISSUE TITLE
Redesigned footer section

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1139]
The majority of the work for this section has been done within the JakartaOne site code, with just the orange bar over the copyright footer missing from that implementation. We can wholesale copy most of that code with some minor work to clean up and make the CSS customizable (I can see this type of footer becoming more common, so customization variables would be the cherry on top, not critical path)

Design:
![image](https://user-images.githubusercontent.com/23018241/117338622-c7fed600-ae6c-11eb-9578-993075b9c626.png)

**Comment by ericpoirier** [comment]
The footer has been redesigned with the last layout update.

Thanks!
