### ISSUE TITLE
Simple homepage content

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1140]
This issue covers the more simple sections defined in the redesign of the home page not covered by the other issues. These should be straightforward sections, populated by files in the data folder, under the translated data section (e.g. `/data/en` and `/data/zh`). We have many examples of translated components across our code base. Feel free to reach out if you need some help with this!

Design:
![image](https://user-images.githubusercontent.com/23018241/117339576-e31e1580-ae6d-11eb-9cb5-ad0bf23754ea.png)

**Comment by autumnfound** [comment]
It was requested that the Video section pull the newest video under resources/videos and display it as seen above. This shouldn't be too hard as we have similar logic in other places. I believe IoT resources page gets resources by date and type, so you should be able to make use of that logic https://github.com/EclipseFdn/iot.eclipse.org/blob/master/layouts/community/resources.html

**Comment by ericpoirier** [comment]
The simple content ended up being the featured story secton and videos but this is all on production now.

Thanks.
