### ISSUE TITLE
FAQ page refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1141]
The FAQ section should be updated to use a [Bootstrap accordion collapse](https://getbootstrap.com/docs/3.3/javascript/#collapse) section. Some minor JS may be needed to transition between the open and close arrows on the right side of the collapse block. This would bind to the `show.bs.collapse` and `hide.bs.collapse` events on the page, and would use some animation to transition between the 2 glyphs.

The simpler alternative would be to use 2 glyphs in the section that are hidden by CSS depending on the collapse state of the container. This would be simpler and more robust than the JS solution. In regards to choosing an implemention, let's use some timeboxed dev time (say 2-3 hours) to see if you can get the JS solution working with some degree of  stability, otherwise lets add the simpler solution. We can always upgrade this in the future!

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585117
![image](https://user-images.githubusercontent.com/23018241/117340280-b74f5f80-ae6e-11eb-9a3f-90b5caba5274.png)

**Comment by shabnammayel** [comment]
We are working on refreshing the content on this page, we are planning to finalize the content by early to mid November.

**Comment by ericpoirier** [comment]
> We are working on refreshing the content on this page, we are planning to finalize the content by early to mid November.

Ok for now I'll implement the design and when the content is ready, we'll update it.

**Comment by ericpoirier** [comment]
Hi @shabnammayel,

Please review the FAQ page here:
https://deploy-preview-1282--jakartaee.netlify.app/about/faq/

Note that we are currently missing the text above the collapsing sections.

Let me know if there's any changes to be made.

Thanks.

**Comment by shabnammayel** [comment]
Thanks @ericpoirier , looks good! we are working on updating the content so we can add the missing the text above the collapsing sections later once we have the updated content

**Comment by ericpoirier** [comment]
@shabnammayel can we merge the PR that I create and make the content changes when it's ready?

Thanks.

**Comment by shabnammayel** [comment]
Sounds good @ericpoirier! thanks

**Comment by excentrickristy** [comment]
I'm a bit late to review so I apologize for commenting on a closed issue. I did want to make two suggestions though:

- There are two h1 tags on this page, I would recommend removing it from the "FAQ" h1 above the questions. and just converting it to a p tag with header styling. It would probably be helpful to change that heading to "Frequently Asked Questions" since FAQ is just above.
- The questions should be in h2 tags instead of h4

Picky thing:
- in the title tag, "the Future" isn't capitalized

**Comment by ericpoirier** [comment]
Hi @excentrickristy, I updated the FAQ page as per your recommendation and the changes are now live.

**Comment by excentrickristy** [comment]
Hi Eric,
Just one thing - I see that you are using an h2 tag now for "Frequently Asked Questions" which means the questions themselves should be h3s.

Thanks!
