### ISSUE TITLE
About Working Groups page refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1142]
The creation of this section should be a pretty straightforward process. The first 2 sections are segmented text sections, with the third being a more complex use case of the new cards component we are in the process of creating. This means that we will need to be able to configure additional classes per card in the data file so that we can mix colours, and also define type by entry rather than for all cards of a section (which is the more straightforward way).

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585113
![image](https://user-images.githubusercontent.com/23018241/117341339-faf69900-ae6f-11eb-9e43-bd979a7a54b1.png)

**Comment by shabnammayel** [comment]
We are working on refreshing the content on this page, we are planning to finalize the content by early to mid November.

**Comment by ericpoirier** [comment]
> We are working on refreshing the content on this page, we are planning to finalize the content by early to mid November.

I will also need the assets (icons, images) at the bottom of the page.

**Comment by meKokabi** [comment]
Please find attached images:
![2](https://user-images.githubusercontent.com/75500459/138743195-009504e5-a2d8-495f-befa-d32d7e2b16ce.jpg)
![11](https://user-images.githubusercontent.com/75500459/138743197-528b865b-4c0c-4776-9a5d-7b1469e320ee.jpg)
[svg icon.zip](https://github.com/jakartaee/jakarta.ee/files/7412433/svg.icon.zip)

**Comment by ericpoirier** [comment]
@shabnammayel can you provide the updated content in a Google doc for this page?

Thanks.

**Comment by shabnammayel** [comment]
It is still in works, I will add it here once the content is finalized. thanks

**Comment by ericpoirier** [comment]
Ok for now I'll create a PR and wait until the content is ready to merge to production.

**Comment by ericpoirier** [comment]
@shanda-eclipse @excentrickristy I created the following staging page to update the layout of the WG page.

https://deploy-preview-1309--jakartaee.netlify.app/about/working-group/

You'll notive that we are still missing text in the blocks at the bottom of the page which will be provided by @shabnammayel when its finalized. Should I just remove the lorem and we can merge it as is and add the content when available or should we just wait?

Thanks.

**Comment by excentrickristy** [comment]
A few notes:

- Under our vision there is a bold sentence that introduces the list in the right column. For user experience it makes more sense to move this above the list in the right side column.

- Can you add a bit more space under the guiding principals section and before the 3 boxes to match the design?

-  Change the title tag to read: "About the Jakarta EE Working Group | Eclipse Enterprise for Java (EE4J)  | The Eclipse Foundation"

- Change the meta description tag to: "The Jakarta EE Working Group drives the evolution and adoption of Eclipse Enterprise for Java (EE4J) technologies. Learn about our vision and guiding principles."

- In the first paragraph under Our Vision, the second sentence has (EE4) instead of (EE4J). The last sentence in this same paragraph starts with "EE4)" instead of "EE4J"

- In the middle box you will need to change the colour for an active or visited link to white or to stay orange because when it changes colour, it no longer meets accessibility standards

- Change Guiding Principles to an h2 tag

- Change the titles in the 3 boxes to h2 tags 

- For the dummy text in the 3 boxes, I think it's fine to delete that out for now so we can merge.

**Comment by ericpoirier** [comment]
@excentrickristy I made updates as per your comments.

https://deploy-preview-1309--jakartaee.netlify.app/about/working-group/

Please review and let me know if I missed anything.

Thanks.

**Comment by excentrickristy** [comment]
@ericpoirier we are close!

The 3 boxes at the bottom are missing links:
https://www.eclipse.org/org/workinggroups/jakarta_ee_charter.php
https://jakarta.ee/about/faq/
https://jakarta.ee/membership/

Without the additional text, we can remove the "learn more" links and just have the headings in the boxes, and reduce the height of the boxes. 

In the third box, it would be nice to vertically center the icon and header at the new box height.

The first paragraph under Our Vision, the last sentence starts with  EE4J) - delete the closing bracket

**Comment by ericpoirier** [comment]
> @ericpoirier we are close!
> 
> The 3 boxes at the bottom are missing links: https://www.eclipse.org/org/workinggroups/jakarta_ee_charter.php https://jakarta.ee/about/faq/ https://jakarta.ee/membership/
> 
> Without the additional text, we can remove the "learn more" links and just have the headings in the boxes, and reduce the height of the boxes.
> 
> In the third box, it would be nice to vertically center the icon and header at the new box height.
> 
> The first paragraph under Our Vision, the last sentence starts with EE4J) - delete the closing bracket

I made the updates you requested on the following staging page:
https://deploy-preview-1309--jakartaee.netlify.app/about/working-group/

Let me know if there's anything else.

Thanks.

**Comment by excentrickristy** [comment]
Looks good to me!

**Comment by shabnammayel** [comment]
Hi @ericpoirier here is the updated content for this page https://docs.google.com/document/d/1iAd8-SHzr0r5OyPyumFZEkBeSgkV9tik/edit thanks

**Comment by shabnammayel** [comment]
Please note that we are separating the content for "About Jakarta EE WG" page from "About Jakarta EE" page. So can you please help and create a new page "About Jakarta EE" page with a similar look and feel to this page? As discussed previously, it should fall under the About dropdown, under the Jakarta EE dropdown and just above the Frequently Asked Questions button. Here is the content for the "About Jakarta EE" Page: https://docs.google.com/document/d/10-0RE4fGQZ55Z2iRZzXLmdO3PKwCjyXR/edit 
@excentrickristy FYI

**Comment by ericpoirier** [comment]
@shabnammayel I updated the About Working Group page with the content you provided.
https://deploy-preview-1309--jakartaee.netlify.app/about/working-group/

I also created the About Jakarta EE page
https://deploy-preview-1309--jakartaee.netlify.app/about/jakarta-ee/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
They both look good to me! @excentrickristy FYI

**Comment by excentrickristy** [comment]
@ericpoirier @shabnammayel 
I think this page is missing from the main menu: https://jakarta.ee/about/jakarta-ee/
