### ISSUE TITLE
Adopt-a-spec page refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1144]
The adopt-a-spec page is about 90% simple markdown content, with a small list of adopter logo images that will be created and shown through a shortcode. [The adopt a spec page already exists](https://jakarta.ee/community/adopt-a-spec/) with the same content and should be an exercise of reviewing the output once the site CSS has been updated.

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585123
![image](https://user-images.githubusercontent.com/23018241/117342783-9a685b80-ae71-11eb-9d4f-cd31f75339fa.png)

**Comment by ericpoirier** [comment]
Hi @shabnammayel,

Please review the Adopt A Spec page here:
https://deploy-preview-1283--jakartaee.netlify.app/community/adopt-a-spec/

Let me know if there's any changes to be made.

Thanks.

**Comment by ericpoirier** [comment]
@shabnammayel are we good to merge the layout changes for this page?

Thanks.

**Comment by shabnammayel** [comment]
LGTM, thanks Eric for making the change.
