### ISSUE TITLE
Jakarta EE Committees page refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1145]
The committees' page is made up of 2 distinct sections with pretty standard content to author content for. The bordered boxes should use flex-grow to accomplish the bottom-aligned links. The events section of the current site makes use of this and could be useful when creating this section. These values should be i18n labels so that they would work across languages.

The second section is 2 sections stuck side by side with i18n labels for the different languages in the shortcode file.

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585124
![image](https://user-images.githubusercontent.com/23018241/117342889-bc61de00-ae71-11eb-927a-a155fac50651.png)

**Comment by aeiras** [comment]
Hola Martin, 

Who provided you with the write-up for the Committees's mission? 
Ideally, we need to a re-write so that when the 3 committees are listed side by side they look as 1 WG and not 3 different wg.
 
I recommend we pull Tanja for her to get each committee to review 2021 goals of the committees, that write-up ought to be fixed within a fixed number of words on a draft that can be edited to match the side of the message by side.

**Comment by autumnfound** [comment]
> Hola Martin,
> 
> Who provided you with the write-up for the Committees's mission?
> Ideally, we need to a re-write so that when the 3 committees are listed side by side they look as 1 WG and not 3 different wg.
> 
> I recommend we pull Tanja for her to get each committee to review 2021 goals of the committees, that write-up ought to be fixed within a fixed number of words on a draft that can be edited to match the side of the message by side.

This content was pulled from https://jakarta.ee/committees/ as far as I can tell. This content was likely authored when the site was last redesigned/launched (though I'd have to dig for the exact time frame) and hasn't been refreshed since. For a refresh of the actual content, I defer to the owners of the page, which is either the committees or marketing themselves (I'm not totally sure, to be honest). We could reach out to @TanjaObradovic to see who owns this and see if we should update this content copy!

**Comment by aeiras** [comment]
thanks for prompt update, Martin. Thanks for confirming that there has been no update since we push the website live back in 2018/2019. time to improve the content as well. :)

**Comment by ericpoirier** [comment]
@shabnammayel can you review the following redesign:
https://deploy-preview-1292--jakartaee.netlify.app/committees/

Thanks.

**Comment by shabnammayel** [comment]
LGTM, @ericpoirier ! We should probably add a link to the  Meeting Mins on this page as well since once we update the Committees page and Meeting Mins page, they are going to be in 2 separate pages. but we can do it later once other pages are also updated.

**Comment by ericpoirier** [comment]
Closing this issue since my changes were merged to production.
