### ISSUE TITLE
Meeting minutes refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1146]
The meeting minutes page is very similar to what is currently up on production, with a few small changes in looks but not functionality. The tab headings used on the homepage for the news and events sections will be used here as well, replacing the standard simple boxed design. Instead of surrounding the section in a border, each year will be surrounded with a box with a left-side highlight mark with the year contained.

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585127
![image](https://user-images.githubusercontent.com/23018241/117348491-3d23d880-ae78-11eb-8707-253d408c864d.png)

**Comment by ericpoirier** [comment]
@shabnammayel I created a PR that updates the meeting minutes page.

You can see the preview here:
https://deploy-preview-1300--jakartaee.netlify.app/about/meeting_minutes/

Let me know if you'd like to change anything.

Otherwise, i'll wait for your +1 to merge to production.

Thanks.

**Comment by shabnammayel** [comment]
+1 LGTM! Thanks

**Comment by TanjaObradovic** [comment]
Looks great!

**Comment by ericpoirier** [comment]
My changes have been merged to production.
