### ISSUE TITLE
Specification detailed single page refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1147]
This page has 2 distinct sections, the main content from the spec repo, and the right side sidebar with some navigation content and additional information. The main content looks to be standard content that is already printed on the [same page in current production](https://jakarta.ee/specifications/platform/9/).

The sidebar content contains already existing components (a brand colored card, and adopter logos), and one new component. As the new component is fully new functionality, it will be considered a post-launch enhancement and will be tracked in a separate issue.

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585126
![image](https://user-images.githubusercontent.com/23018241/117355106-22edf880-ae80-11eb-9294-7cce8976b066.png)

**Comment by ericpoirier** [comment]
@shanda-eclipse @shabnammayel I'm looking at this redesign and I have an issue.

To move the title from the body to the jumbotron, we will have to update all the specifications page manually which can be found on the following repo:
https://github.com/jakartaee/specifications

There's probably some search and replace that we can do but since the body of those pages are all in markdown its going to be hard to nail to down at a 100%.

I propose that we make the styling changes first and then if we feel like we realy need to, we can look at moving the title to the jumbotron.

Let me know what you think.

Thanks.

**Comment by shanda-eclipse** [comment]
I agree that we should make the styling changes first, rather than editing the other repo.

**Comment by ericpoirier** [comment]
I updated the layout of specification single pages.

Here is an example but you can have a look at them all.
https://deploy-preview-1336--jakartaee.netlify.app/specifications/webprofile/8/

Let me know if you'd like to make any changes.

Note that to make changes to the SEO, we will need to make changes to every single speficiation pages from the specifications repo:
https://github.com/jakartaee/specifications

**Comment by shabnammayel** [comment]
LGTM! But I would like @TanjaObradovic to review this page as well before going live!

**Comment by TanjaObradovic** [comment]
In the section "Compatible Implementations" it should say 
_Jakarta EE 8 Compatible Web Profile Implementations_ and point to section of the page that says _Jakarta EE 8 Web Profile Compatible Products_

Other than that it looks great!

**Comment by ericpoirier** [comment]
> In the section "Compatible Implementations" it should say _Jakarta EE 8 Compatible Web Profile Implementations_ and point to section of the page that says _Jakarta EE 8 Web Profile Compatible Products_
> 
> Other than that it looks great!

@TanjaObradovic The content of the Specification pages are coming from another repo which we do not have control over here in the jakarta.ee repository.

Specification repo: https://github.com/jakartaee/specifications

As I was saying in my [first comment](https://github.com/jakartaee/jakarta.ee/issues/1147#issuecomment-964273041), I think for this issue we should concentrate in doing styles changes and open issues in the Specification repo to make the appropriate content changes there.

Let me know if that makes sense.

**Comment by TanjaObradovic** [comment]
Makes sense, thanks!
