### ISSUE TITLE
Compatibility Get Listed page refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1148]
The compatibility page has 3 noticeable sections to create. The first section is a list of vertical icon highlight cards with simple text elements and a small orange linebreak between the heading and the text. These cards are shadowless with a white background, which should be simple to author.

The second section to create is plain markdown content between the 2 more complicated components and will be a simple content section.

The third section is a single horizontal card with text and a link. This card, like the first set of cards, is shadowless with no background color. This card should be straightforward to author content for overall.

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585125
![image](https://user-images.githubusercontent.com/23018241/117360542-ed98d900-ae86-11eb-9ecb-0e28fa4f85ea.png)

**Comment by ericpoirier** [comment]
@shabnammayel @meKokabi do you know where I can get the icons and image from this page?

Thanks.

**Comment by meKokabi** [comment]
Unfortunately, I do not have access. Perhaps Shabnam can help!

**Comment by meKokabi** [comment]
Attached includes assets zip folder. 
Please note there were no Illustrator file for this page so I made screenshots and make the pngs from it.

[Assets.zip](https://github.com/jakartaee/jakarta.ee/files/7412205/Assets.zip)

**Comment by ericpoirier** [comment]
@shabnammayel The content here didn't seem to have changed from what is currently on production at the exception of the block at the bottom of the page for now that section still contains lorem. For now I will create that block without body text in it until you provide some text to add there.

Thanks.

**Comment by shabnammayel** [comment]
@ericpoirier we can add this text from the compatible products page here: The success of Jakarta EE technology relies on compatibility to ensure application portability, security, stability, and resiliency. Compatibility will allow more technology providers to leverage and strengthen the Jakarta EE brand in the enterprise Java community.

**Comment by ericpoirier** [comment]
> @ericpoirier we can add this text from the compatible products page here: The success of Jakarta EE technology relies on compatibility to ensure application portability, security, stability, and resiliency. Compatibility will allow more technology providers to leverage and strengthen the Jakarta EE brand in the enterprise Java community.

Ok no problem.

**Comment by shabnammayel** [comment]
@ericpoirier some of the content on the mockup for the "How to get listed" steps is different from the actual one from the website. Can you please use the content on the live page for the "How" Section?

**Comment by ericpoirier** [comment]
@meKokabi can you provide the icons and image from this mock-up?

Thanks.

**Comment by meKokabi** [comment]
@ericpoirier Sure, I just need to double check with Shanda. Will get back after!

**Comment by ericpoirier** [comment]
@shabnammayel @meKokabi do you think you can provide the image and icons for this page?

Thanks.

**Comment by meKokabi** [comment]
@ericpoirier I will do my best to prepare all by the end of the day today or tomorrow early morning.

**Comment by meKokabi** [comment]
![iStock-1225535210](https://user-images.githubusercontent.com/75500459/142458172-55db0b6c-81e2-4564-9774-899c8db14e1b.jpg)

**Comment by meKokabi** [comment]
![image](https://user-images.githubusercontent.com/75500459/142458791-646c09b4-6707-4416-ab93-929490399c2f.jpg)

**Comment by ericpoirier** [comment]
> Attached includes assets zip folder. Please note there were no Illustrator file for this page so I made screenshots and make the pngs from it.
> 
> [Assets.zip](https://github.com/jakartaee/jakarta.ee/files/7412205/Assets.zip)

Can you provide the icons without the blue background? Just the white icons.

Thanks

**Comment by meKokabi** [comment]
sure, will do shortly!

**Comment by meKokabi** [comment]
Here You Are (White Icons)
[PNG-Icons.zip](https://github.com/jakartaee/jakarta.ee/files/7566506/PNG-Icons.zip)

**Comment by ericpoirier** [comment]
@shabnammayel @meKokabi please review the updated "Get Listed" page and let me know if there's anything to be changed.

https://deploy-preview-1327--jakartaee.netlify.app/compatibility/get-listed/

Thanks!

**Comment by meKokabi** [comment]
@ericpoirier looks good to me!

**Comment by shabnammayel** [comment]
the text on the block at the bottom of the page is still missing. We can use: The success of Jakarta EE technology relies on compatibility to ensure application portability, security, stability, and resiliency. Compatibility will allow more technology providers to leverage and strengthen the Jakarta EE brand in the enterprise Java community.

**Comment by shabnammayel** [comment]
other than that LGTM! thanks

**Comment by ericpoirier** [comment]
> the text on the block at the bottom of the page is still missing. We can use: The success of Jakarta EE technology relies on compatibility to ensure application portability, security, stability, and resiliency. Compatibility will allow more technology providers to leverage and strengthen the Jakarta EE brand in the enterprise Java community.

I updated the text in my PR.
