### ISSUE TITLE
Community Stay Connected page refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1149]
The stay connected page is a simple page made with a list of horizontal, half-width cards. These cards have a logo on the left and text and buttons on the right. This can be one or multiple links, with mixed types. I'm not totally sold on mixed link types, but we can also support custom links for weird edge cases like this. Otherwise, this seems to be pretty straightforward.

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585121
![image](https://user-images.githubusercontent.com/23018241/117453792-59288800-af13-11eb-9579-26882e112d13.png)

**Comment by ericpoirier** [comment]
@shabnammayel @meKokabi do you know where we can get the icons from this page?

Thanks.

**Comment by ericpoirier** [comment]
@thatsmekristy Can you provide the icons from this page?

Thanks.

**Comment by meKokabi** [comment]
![image](https://user-images.githubusercontent.com/75500459/138744350-fffd11fe-57e7-4304-9982-a662a6b3d5ec.png)

**Comment by ericpoirier** [comment]
@meKokabi we are missing the "Updates" icon from the zip file.

**Comment by meKokabi** [comment]
Sorry @ericpoirier not clear which one you mean, There were 8 icons on this page that I converted to svgs, Is there any other one that I missed.

**Comment by ericpoirier** [comment]
We are missing the following icon:
![image](https://user-images.githubusercontent.com/623165/139084801-f4f32457-44cb-49d2-ae2d-555d24aaae04.png)

It's also missing from the latest zip file you sent.

**Comment by meKokabi** [comment]
Here You Are! Added it to the folder!
[icons-svg 2 2.zip](https://github.com/jakartaee/jakarta.ee/files/7426964/icons-svg.2.2.zip)

**Comment by ericpoirier** [comment]
> Here You Are! Added it to the folder! [icons-svg 2 2.zip](https://github.com/jakartaee/jakarta.ee/files/7426964/icons-svg.2.2.zip)

thanks!

**Comment by meKokabi** [comment]
☺️

**Comment by ericpoirier** [comment]
@shabnammayel I created a PR to update the Stay Connected page.

https://deploy-preview-1297--jakartaee.netlify.app/connect/

Note that we are missing some text for the following blocks:

Slack
- Body

Newsletter
- Body

Community Folder
- Body
- Link

Tech Talks Meet-Ups
- Body
- Both links

Friends of Jakarta EE
- Body
- Link

I'll update the content of the PR once you provide the Google Doc.

Thanks.

**Comment by shabnammayel** [comment]
@excentrickristy Can you please review as well?

**Comment by shabnammayel** [comment]
@ericpoirier I have added the requested content in this document: https://docs.google.com/document/d/1ETKnqm_TbP3zz-1M0CtAcY1WszAuaHwrTrux9d0nyXY/edit
Thanks

**Comment by excentrickristy** [comment]
Hi guys, 

Just a few notes:

Probably a global issue, but I saw that there is an h3 tag being used for screen readers only to tag the breadcrumbs. For SEO as well as accessibility I would recommend following this code pattern instead:  https://www.w3.org/TR/wai-aria-practices-1.1/examples/breadcrumb/index.html

Also, the titles for each contact card are being contained in h3 tags, these should be promoted to h2 to maintain header order.

Not important for SEO but from an editorial standpoint.. there is inconsistent use of periods in each contact block. I recommend adding periods to the end of each of the last sentences in each block that doesn't have it as most blocks have multiple sentences.

I reviewed the meta tags and those look fine, no changes there!

**Comment by ericpoirier** [comment]
> Hi guys,
> 
> Just a few notes:
> 
> Probably a global issue, but I saw that there is an h3 tag being used for screen readers only to tag the breadcrumbs. For SEO as well as accessibility I would recommend following this code pattern instead: https://www.w3.org/TR/wai-aria-practices-1.1/examples/breadcrumb/index.html
> 
> Also, the titles for each contact card are being contained in h3 tags, these should be promoted to h2 to maintain header order.
> 
> Not important for SEO but from an editorial standpoint.. there is inconsistent use of periods in each contact block. I recommend adding periods to the end of each of the last sentences in each block that doesn't have it as most blocks have multiple sentences.
> 
> I reviewed the meta tags and those look fine, no changes there!

Thanks for the feedback, I'll make all the changes related to this page only and I'll create another PR to deal with the breadcrumb since it will affect all the sub pages.

**Comment by ericpoirier** [comment]
@shabnammayel @shanda-eclipse @excentrickristy you can review the updated Stay Connected page here:

https://deploy-preview-1297--jakartaee.netlify.app/connect/

Let me know if there's anything else.

Thanks.

**Comment by excentrickristy** [comment]
Just missing one period in the last sentence of the last box and you should be good to go!

**Comment by thatsmekristy** [comment]
One thing I just noticed. On the Newsletter page the subscribe button goes here: https://eclipsecon.us6.list-manage.com/subscribe/post

On the Stay Connected page it links to here: https://newsroom.eclipse.org/eclipse-newsletter/2021/october

 

I believe the link on the Stay Connected page should be: https://eclipsecon.us6.list-manage.com/subscribe/post

**Comment by ericpoirier** [comment]
My PR for this page was merged last week.
