### ISSUE TITLE
Community Events refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1150]
The events page is broken into 2 sections, the main dynamic events section, and the sidebar. The main dynamic section uses rows of events with images, times, and links. These events will likely require the same sort of treatment as the home page event as there are no associated images. 

On the right side, we have a simple sidebar menu that implies that we have the ability to target different sub-menus based on what page we are on. This functionality should already exist in the base theme under the sidebar partial file, so much of the work is already done and may just be styling work.

@karenmcnaughton in regards to the images not existing for external events, do we want to just switch to simple text here in the meantime?

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585116
![image](https://user-images.githubusercontent.com/23018241/117455398-267f8f00-af15-11eb-9448-d11e0fc97c10.png)

**Comment by ericpoirier** [comment]
@shabnammayel @shanda-eclipse I'm seeing an issue with this redesign. We currently do not support adding images to Events in newsroom.eclipse.org. Since this is where we are fetching the Jakarta EE events, we would need to add this field when create an event on newsroom.

Also, I'm looking at the sidebar, is this a sub menu that we need to add only on the Events page? Or is this something that will appear somewhere else on the site?

And the "Interested In Hosting an Event" block, where is this linking to?

Thanks.

**Comment by chrisguindon** [comment]
We can't assume that we will always have an image for an event. 

+1 for adding images to events in the newsroom but this layout must be able to support events items without an image.

**Comment by ericpoirier** [comment]
I created the following MR to add an image field to Event nodes on newsroom.eclipse.org

https://gitlab.eclipse.org/eclipsefdn/it/webdev/drupal/eclipse_api/-/merge_requests/6

**Comment by ericpoirier** [comment]
@shabnammayel here is the preview of the Events page:

https://deploy-preview-1330--jakartaee.netlify.app/community/events/

You'll notice that some of the Events doesn't have an image. This is on purpose because I wanted you to see what it would look like without videos. Images are being added in the Events on newsroom.eclipse.org

Let me know if you'd like to make any changes.

Thanks.

**Comment by shabnammayel** [comment]
Thanks @ericpoirier LGTM!

**Comment by shanda-eclipse** [comment]
The event order seems off to me. You have 2 upcoming events, but the January event is listed before the Dec event. Then move right into past events, I think you need some separation and a header before past events.

**Comment by ericpoirier** [comment]
> The event order seems off to me. You have 2 upcoming events, but the January event is listed before the Dec event. Then move right into past events, I think you need some separation and a header before past events.

I think we made a change to how we pull events from newsroom.eclipse.org so that we have events in this order.

That being said, should we separate upcoming and past events on different pages?

**Comment by shabnammayel** [comment]
As this page is called events, we can keep both past and upcoming ones in one page but just separate the sections and add the heading "Past Events" from where we start listing the old ones.

**Comment by ericpoirier** [comment]
This is more of a note for myself.

I created a PR for the solstice-assets repo so that I can easiy retrieve past events.

**Comment by ericpoirier** [comment]
I updated the staging for the Events page:

https://deploy-preview-1330--jakartaee.netlify.app/community/events/

I separated the Upcoming and Past events in 2 sections.

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
Can we add the links to the past tech talks?link to their YouTube video is ideal, but even link to the Crowdcast session where they can watch the replay now would be good. @ericpoirier

**Comment by shanda-eclipse** [comment]
> I updated the staging for the Events page:
> 
> https://deploy-preview-1330--jakartaee.netlify.app/community/events/
> 
> I separated the Upcoming and Past events in 2 sections.
> 
> Let me know if there's anything else.
> 
> Thanks.

Event order looks good to me. I will leave it to Shabnam to approve after her other request.

**Comment by ericpoirier** [comment]
@shanda-eclipse maybe you can help, @shabnammayel's request is related to missing links to some of the old events. Specialy for the TechTalk items. I can see that in newsroom the website links are missing for those event items.

Example: https://newsroom.eclipse.org/node/38436/edit

Is there a reason why the links are missing in newsroom?

**Comment by shanda-eclipse** [comment]
> 

It's because registration and "more info" are the same link for these webinar. For the event listing before the event, we only have the registration link. If you can write some logic, the event should link to the "registration" link when the "more info" link is empty.

**Comment by ericpoirier** [comment]
> > 
> 
> It's because registration and "more info" are the same link for these webinar. For the event listing before the event, we only have the registration link. If you can write some logic, the event should link to the "registration" link when the "more info" link is empty.

Ah ok got it.

Yeah I can write some logic for that.

**Comment by ericpoirier** [comment]
@shanda-eclipse I'm looking at the generic code that was written to get events from newsroom and we remove the registration link if the event is in the past. I think the reason for that is so that people are not trying to register for past events.

I think it would be better to just copy the url from registration to website field in newsroom. What do you think?

**Comment by shanda-eclipse** [comment]
I'm not sure workflow-wise, it's realistic to go back into every event in the newsroom to add links after the event ends. @shabnammayel is there a simpler solution? Maybe a CTA on the right column below "Interested in Hosting an Event?" that says "Watch recordings from the past events on our YouTube channel" or something like that?

**Comment by shabnammayel** [comment]
+1 I think that's a good idea. Let's leave it as it is for the tech talks and add a CTA below "Interested in Hosting an Event?"  as Shanda suggested.

**Comment by shabnammayel** [comment]
also looking at the mock up, the box on the right does not reflect the current items on the Community dropdown. Please update those as well @ericpoirier thanks

**Comment by shanda-eclipse** [comment]
@ericpoirier you can style the CTA the same as the hosting an event one. 

Here is the image:
![Untitled design (3)](https://user-images.githubusercontent.com/61751191/144644885-7dc14098-ad09-4dda-9dde-1530d48fd0a0.png)

First line: Watch recordings from the past events 

Second line: on our YouTube channel

Link: https://www.youtube.com/jakartaee

**Comment by ericpoirier** [comment]
@shanda-eclipse @shabnammayel I updated the staging page for the Events.

https://deploy-preview-1330--jakartaee.netlify.app/community/events/

Let me know if I missed anything.

Thanks.

**Comment by shabnammayel** [comment]
Looks good @ericpoirier we should still update the Community navigation box on the right to reflect the items in the current dropdown.

**Comment by shabnammayel** [comment]
Also events page link is missing from the navigation, we should add it to the community dropdown as well

**Comment by ericpoirier** [comment]
@shabnammayel I updated the sidebar and the dropdown menu on the following staging page:

https://deploy-preview-1330--jakartaee.netlify.app/community/events/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
Looks good Eric! but since we are arranging the overview page on an alphabetic order, I think we should arrange the dropdown and the sidebar on an alphabetic order as well.

**Comment by shabnammayel** [comment]
I just noticed that we actually merged the box for events to cover livestream as well! So we might as well update the dropdown and sidebar and drop the JakartaOne Livestream from the navigation. It's already included  in the Events box. So the Navigation bar and side bar should be: Overview, Adopt a Spec, Events, Stay Connected, Tech Talk Meet-ups, Videos.

**Comment by ericpoirier** [comment]
> I just noticed that we actually merged the box for events to cover livestream as well! So we might as well update the dropdown and sidebar and drop the JakartaOne Livestream from the navigation. It's already included in the Events box. So the Navigation bar and side bar should be: Overview, Adopt a Spec, Events, Stay Connected, Tech Talk Meet-ups, Videos.

I updated the menu and sidebar on the following staging site:

https://deploy-preview-1330--jakartaee.netlify.app/community/events/

Note that I just pushed the changes which might take a few minutes to show on staging.

**Comment by shabnammayel** [comment]
LGTM! thanks @ericpoirier
