### ISSUE TITLE
Join Jakarta EE working group refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1152]
The first half of the join page is simple markdown content, while the second half is comprised of 2 complex components. The first component is a set of cards with headings and no body text, an image, and a full card link. It should be pretty straightforward to author the content through a card component.

The second component on the page is an expanded view of the testimonials cards with an Owl carousel to display a more expanded view of the testimonials than found on the home page (#1138). These should be a simpler version of the homepage testimonials, with a larger area to display content and no content truncation.

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585118
![image](https://user-images.githubusercontent.com/23018241/117468508-c0016d80-af22-11eb-81fa-1551a13009d3.png)

**Comment by ericpoirier** [comment]
@meKokabi can you provide the 3 images that are in this redesign?
Thanks.

**Comment by meKokabi** [comment]
@ericpoirier Would you please share the illustrator file with me again, I need the original package to find access to images.

**Comment by meKokabi** [comment]
@ericpoirierHere you are:

![1](https://user-images.githubusercontent.com/75500459/141380220-d8893837-66b3-4172-8006-2ddcc4e5df7d.jpg)
![3](https://user-images.githubusercontent.com/75500459/141380221-8172ee99-f25a-4a6f-a22e-bdcc9533e7ec.jpg)
![2](https://user-images.githubusercontent.com/75500459/141380222-a839fca1-9035-42c8-a20a-96ee21f937f6.jpg)

**Comment by ericpoirier** [comment]
Hi @shabnammayel can you review the following page:
https://deploy-preview-1335--jakartaee.netlify.app/membership/

Thanks.

**Comment by shabnammayel** [comment]
LGTM @ericpoirier! Thanks 
excentrickristy FYI
