### ISSUE TITLE
Specifications list page refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1153]
The list page has 3 new aspects to it compared to the current specification list page. The first is that the platform spec projects have been separated from the rest of the specifications. We can likely accomplish this by creating a string list of projects we want to be in the top section and just loop through the list of specs twice. The first time we will only print the projects that match the allowlist, and the second loop through we will print the rest of the specifications, using the before mentioned list as an exclude list.

The specification list page makes use of a lot of content that is already available on the page that is current, just not used, so a lot of the current logic can be preserved in terms of looping through specs which should save some time. Additionally, the buttons used to link to the project page and website exist on the specification summary page, as well as logic to fetch the implementations of the specification. Example spec page with buttons and implementation links: https://jakarta.ee/specifications/platform/

The second and more complex part of this page is a new filtration system. As this is the second time we've had to make use of filtration and flags, we should consider looking into a JS library to help us accomplish this such as [Fuze.js](https://fusejs.io/demo.html) (which falls under the APL 2 license). Fuse seems to support adding additional flags by value match, so we should be able to easily add search filters as well as text search with this product.

@chrisguindon WDYT of adding Fuse? We could add it just on pages where we need special text search, and it would greatly simplify our life now and in the future when we need to do stuff like this.

Design: 
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585120
![image](https://user-images.githubusercontent.com/23018241/117469683-03101080-af24-11eb-8fda-989df21140d5.png)

**Comment by shabnammayel** [comment]
We are working on adding content on this page, we are planning to finalize the content by early to mid November.

**Comment by ericpoirier** [comment]
@shabnammayel any update on the content of this page?

**Comment by shabnammayel** [comment]
@ericpoirier here is the content for this page: https://docs.google.com/document/d/1Zuv9dqBF3sImTywUKfJWtUTKryhDBVnh/edit thanks

**Comment by ivargrimstad** [comment]
For the filtering, keep in mind that we already have some metadata available for each specification's detail page. And we are considering adding more metadata to generate more of the content. So adding metadata for filtering should be done in the same place to avoid spreading this data around. This also allows for the flexibility that one **version** of a specification may be in a different _profile_ than the previous version. So the granularity needs to be on version and not on specification level.

**Comment by ericpoirier** [comment]
@shabnammayel I updated the layout of the Specifications page on the following staging site:

https://deploy-preview-1350--jakartaee.netlify.app/specifications/

Note that I didn't add a search yet since i'm not sure yet what we are going to use for it but i'd like to get the ball rolling on the reviwing side of things. Let me know if you'd like to make any changes to the Specifications page that I shared.

**Comment by shabnammayel** [comment]
LGTM! I would like @TanjaObradovic to review this page as well when she gets a chance! :) thanks!

**Comment by ivargrimstad** [comment]
Core Profile also needs to be displayed at the top together with the Platform and Web  Profile

**Comment by ericpoirier** [comment]
> Core Profile also needs to be displayed at the top together with the Platform and Web Profile

Just to make sure, we will add a 3rd box in the first section?

**Comment by ivargrimstad** [comment]
> > Core Profile also needs to be displayed at the top together with the Platform and Web Profile
> 
> Just to make sure, we will add a 3rd box in the first section?

Yes, later we need to add some sort of metadata for the profile specs, so they're identified automatically. 
But for now, there are only these three.

**Comment by ericpoirier** [comment]
@ivargrimstad @shabnammayel I added the 3rd block to the specifications page.

https://deploy-preview-1350--jakartaee.netlify.app/specifications/

Let me know if there's anything else.

Thanks.

**Comment by ivargrimstad** [comment]
LGTM

**Comment by ericpoirier** [comment]
@TanjaObradovic can you review this page?

Thanks.

**Comment by TanjaObradovic** [comment]
It looks great!
Should we correct the text in the tiles for Web and Core profiles, but we can do that later.
Thanks!

**Comment by shabnammayel** [comment]
@ericpoirier please change the text in the Web Profile and Core Profile boxes to: 
Web: Defines a profile of the Jakarta EE Platform specifically targeted at web applications
Core: Defines a profile of the Jakarta EE Platform specifically targeted at smaller runtimes

**Comment by ericpoirier** [comment]
> @ericpoirier please change the text in the Web Profile and Core Profile boxes to: Web: Defines a profile of the Jakarta EE Platform specifically targeted at web applications Core: Defines a profile of the Jakarta EE Platform specifically targeted at smaller runtimes

The text in those boxes is being pulled from the Specifications repo:
https://github.com/jakartaee/specifications

In order to update the text from those items, we would have to update it here:
https://github.com/jakartaee/specifications/tree/master/webprofile
https://github.com/jakartaee/specifications/tree/master/coreprofile

@TanjaObradovic @ivargrimstad I'm not entirely sure of the process of making text changes to the specifications repo?

To move the redesign process forward, I would suggest we merge the changes that we've made so far and depending on the process of updating text in the Specifications repo, we can make those changes after.

What do you think?
