### ISSUE TITLE
Resource videos refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1154]
The videos section refresh has 3 pieces of work to consider, 2 of which are on the critical path for the refresh, and the third being a new feature that allows for live filtering of the videos by video category. The top banner is a custom section using an image background and 3 visible sections of content in a 15-65-20 split. The first section containing a PNG logo in a container with a white bg and border radius. The second section is text with a couple of glyphs. The third section is a simple button.

The second component is more image + text sections displaying the list of videos defined in the site. A similar concept is done on the IoT site under the [Video Resources section](https://iot.eclipse.org/community/resources/videos/). We could use that implementation as a base with an updated look and feel. Currently, there are no images associated with videos, and it would be a task to have images be given on the addition of new videos. 

The new feature, which will be defined in a further issue scoped to post-launch changes would allow for the videos to be filtered by updating a dropdown that contains all of the different categories of videos present on the page.

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585122
![image](https://user-images.githubusercontent.com/23018241/117476713-27232000-af2b-11eb-8151-60d15cf09bcf.png)

**Comment by ericpoirier** [comment]
@shabnammayel @excentrickristy I created a PR to add the Videos page to the Jakarta EE website. I added a link under Community but let me know if this is not the right place.

https://deploy-preview-1318--jakartaee.netlify.app/community/videos/

Note that all the videos listed on this page are placeholders as I don't have a list of the videos to be listed on this page.

It would be good if you can have a look at the metatags as this is a new page and I didn't add any specific content there.

Also, as noted by Martin, the filters will be added on a later date just so we can move forward with the layout updates.

Thanks.

**Comment by excentrickristy** [comment]
@ericpoirier The initial idea for this page was that it be updated in tandem with the Jakarta EE Youtube channel.
However, without the category filtering capability this might be overwhelming. Until that feature is ready, perhaps @shabnammayel or @TanjaObradovic could help us pick a few cornerstone videos to feature on this page.

While putting together the initial concept, I was hoping the the video thumbnails on the page currently would actually be the embedded Youtube video so that you could watch the video without leaving the page, but you would also have the opportunity to click to watch the video on Youtube if you wanted to comment. Is this possible?

Originally this was supposed to go under Community in the nav, but I think once it's ready it would probably be better to go under Resources -> Videos replacing Resources -> Youtube Channel.

I will provide meta tags shortly!

**Comment by ericpoirier** [comment]
> @ericpoirier The initial idea for this page was that it be updated in tandem with the Jakarta EE Youtube channel. However, without the category filtering capability this might be overwhelming. Until that feature is ready, perhaps @shabnammayel or @TanjaObradovic could help us pick a few cornerstone videos to feature on this page.
> 

Ok let me know which videos to add to this page.

> While putting together the initial concept, I was hoping the the video thumbnails on the page currently would actually be the embedded Youtube video so that you could watch the video without leaving the page, but you would also have the opportunity to click to watch the video on Youtube if you wanted to comment. Is this possible?
> 

If you accept the cookies in the cookie banner, the video will load on the page like you want it.

Not sure what you mean by going to youtube to comment, you can already do that with the "Watch on Youtube" button.

> Originally this was supposed to go under Community in the nav, but I think once it's ready it would probably be better to go under Resources -> Videos replacing Resources -> Youtube Channel.
> 
> I will provide meta tags shortly!

Sounds good, thanks!

**Comment by shabnammayel** [comment]
@ericpoirier It will be great to see the feature to sync with the Jakarta EE YouTube channel on this page soon. But here is the list of videos to list in no particular order for now: 1. https://www.youtube.com/watch?v=slEqCW9Rf5c
Why Jakarta EE Matters | Jakarta Tech Talks | May 18, 2021
2. https://www.youtube.com/watch?v=F7IW-cdjnMU&t=2s Jakarta Concurrency: What's Next | Jakarta Tech Talks | August 11, 2021
3. https://www.youtube.com/watch?v=kESOZXqS1H8&t=665s Jakarta EE Update Call | April 2021
4. https://www.youtube.com/watch?v=rV_91fzJBTQ&t=65s Studio Jakarta EE: How to Contribute to Jakarta EE | JakartaOne Livestream 2020
Please let me know if we need more. thanks 
@excentrickristy FYI

**Comment by ericpoirier** [comment]
Thanks for providing a list of videos.

Just to clarify, Shabnam and I had a chat last week about this and for now we will be manually adding videos to that page. 

Once the redesign is live, we can open a separate issue to investigate the possibility of creating a mechanism that would automatically add videos to that page.

**Comment by ericpoirier** [comment]
Just to give an update, the new video links have been added to staging

https://deploy-preview-1318--jakartaee.netlify.app/community/videos/

But I'm having issues with some of the videos not being embeded properly to the page. I'll have to investigate what's going on here.

**Comment by ericpoirier** [comment]
@shabnammayel I fixed the issue with the videos not being displaying properly.

https://deploy-preview-1318--jakartaee.netlify.app/community/videos/

Please review and let me know if there are more changes to be made.

Thanks.

**Comment by excentrickristy** [comment]
New title tag: "Video Resources | Jakarta EE | The Eclipse Foundation"
New meta description tag: "View featured videos resources about Jakarta EE. Subscribe to our YouTube Channel to learn more about Jakarta EE and the latest developments."

**Comment by shabnammayel** [comment]
Thanks @excentrickristy 
@ericpoirier please change the order of the first and second video and that way all videos will be displayed based on the date uploaded. thanks

**Comment by ericpoirier** [comment]
@shabnammayel I updated the order of the videos and I updated the SEO tags.

https://deploy-preview-1318--jakartaee.netlify.app/community/videos/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
LGTM @ericpoirier! thanks

**Comment by excentrickristy** [comment]
@ericpoirier just noticed on the live site that that meta title tag has "The Eclipse Foundation" twice in a row. Can you take a look?

Thanks!
