### ISSUE TITLE
Random weighted testimonial cards on the homepage

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1157]
As part of the redesign, there was an ask to allow for testimonials to be randomly displayed and weighted to allow for some testimonials to show up more often than others. As of right now we don't have this system in place and there would be overhead involved with the testing and development of this feature, it has been added to the post-launch queue from #1138.

This system would involve printing all of the tiles to the page in a no display state and be displayed and ordered based on some javascript that would run post page load. This should allow for a `data-weight` attribute to be set on the card to allow for some elements to show up more often depending on a designated weight.

![Testimonial display](https://user-images.githubusercontent.com/23018241/117336877-aef52580-ae6a-11eb-8b02-62bc783e4de3.png)

**Comment by ericpoirier** [comment]
This is now on production.
