### ISSUE TITLE
[Jakarta EE 9.1 Contributors Cards Update] Update 9.1 Release landing page

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#1159]
Using the 9.0 feature created via  [Contributors' Rotation Cards](https://github.com/jakartaee/jakarta.ee/pull/923) PR, we need to bring the same form for 9.1. 

**Pull in Contributors' Repo activity from:**

- https://github.com/jakartaee/specifications/pulls - **merged pulls** this includes all activity since last release 1 day after freezing the Cards Novemeber 20th, 2020. 

https://github.com/jakartaee/specifications/pull/372

1. https://deploy-preview-372--jakartaee-specifications.netlify.app/specifications/platform/9.1/ **and**
2. https://deploy-preview-372--jakartaee-specifications.netlify.app/specifications/webprofile/9.1/ 

**Dates frozen:**

- November 21st, 2020 to May 18th, 2021.

**Comment by aeiras** [comment]
@kwsutter, @jeanouii, @dblevins & @cesarhernandezgt, 

Before we pull @chrisguindon and team to update the Contributors' cards for 9.1 Release, can you take a look at the information placed on the repo gathering the meat of what goes into highlight activity please? 

Thank you,

**Comment by cesarhernandezgt** [comment]
Thank you @aeiras for the github issue. I reviewed the content and references provided and the following is my understanding of the task from the technical point of view:

Main goal: Have an updated contributors list for website cards for Jakarta EE 9.1 release.

Description: 
Creation of https://github.com/jakartaee/jakarta.ee/blob/src/data/contributors/jakarta-ee-9-1.json via https://github.com/jakartaee/jakarta.ee/blob/src/js/contributor-cards/generate-contributor-lists.sh filtering by the date between November 21st, 2020 to May  18th, 2021

The newly generated jakarta-ee-9-1.json will be used under the hood by the Jakarta 9.1 release page to randomly display the contributor's cards.

**Comment by aeiras** [comment]
Correct, Cesar! 
Thank you for converting the git issue into the PR beef. You are amazing in preparation for tmw submission and to enable community review. :)

**Comment by jeanouii** [comment]
ManageFish does not show up as a compatible implementation in this page
https://jakarta.ee/compatibility/#tab-9.1 which is listed here https://deploy-preview-372--jakartaee-specifications.netlify.app/specifications/platform/9.1/

Same for Apache TomEE because in the page https://jakarta.ee/compatibility/#tab-9.1 there is no difference between full and web profile which is a good thing.

Other than that it looks good

**Comment by aeiras** [comment]
Good catch @jeanouii. Can you please submit a new issue pointing the issue. 

that fix is outside the PR code & focus.

**Comment by cesarhernandezgt** [comment]
@aeiras 
For the compatible implementations I think @karenmcnaughton already open this issue: https://github.com/jakartaee/jakarta.ee/issues/1165

**Comment by Dexmaster** [comment]
Created [contributor list for 9.1](https://github.com/jakartaee/jakarta.ee/pull/1168), it generates list into data/contributors/jakarta-ee-9.1.json by default.

Also provided 2 commands you can test how generation works/re-run it on 18th of May which is expected to_date, or tweak dates if needed.

**Comment by aeiras** [comment]
Thank you reviewers @cesarhernandezgt & @jeanouii and Andrii for converting the review into a PR using past work. 
The 3 of you are wonderful!

**Comment by ericpoirier** [comment]
Closing this issue since there seems like the work got merged to production.

However, please reopen if you think work is not done here.

Thanks.
