### ISSUE TITLE
Select dropdown in-site navigation component

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1160]
A new navigation component will be created that contains a dropdown that on click will navigate you to the designated specification. In the below example, this dropdown will be used to display specification landing pages. While this concept is reused a few times, this component will just have a look and feel associated with it, and will have multiple implementations. This is due to the fact that the selection parameters are irregular, and would be hard to create data files for.

![design](https://user-images.githubusercontent.com/23018241/117355106-22edf880-ae80-11eb-9294-7cce8976b066.png)

**Comment by autumnfound** [comment]
This feature is used in #1147 and #1153

**Comment by ericpoirier** [comment]
@shabnammayel what information do you expect to be shown in the "View a Specification" dropdown?

Thanks.

**Comment by shabnammayel** [comment]
@TanjaObradovic and @excentrickristy can you help with this please? I was on leave when the goals for this mock up and dropdown were discussed last year. and since this is for Spec pages, I want to make sure we are all aligned! thanks

**Comment by TanjaObradovic** [comment]
It is better for @excentrickristy to respond as there could be few different ways to answer it, but let me try.
I believe the drop-down should show list of the individual specifications that are part of the Jakarta EE Platform 9 release (in this case).  @excentrickristy, please confirm. Thanks!

**Comment by ericpoirier** [comment]
@TanjaObradovic wouldn't it make more sense to have a list of the items located on this page in the dropdown:
https://jakarta.ee/specifications/platform/

For example, all the Jakarta EE Platforms would have the same list.

And then if you're looking at a Jakarta EE Web Profile item the dropdown would be populated with the list from the following page:
https://jakarta.ee/specifications/webprofile/

Does that make sense?

**Comment by TanjaObradovic** [comment]
That is correct if we are not showing the versions of individual specifications. 

For example Jakarta EE Platform 10 will have different versions of the individual specifications then Jakarta EE 9.

**Comment by excentrickristy** [comment]
The menu was supposed to be a quick navigation to get to the other specifications, e.g. a list of the platform/profile and individual specs, just leading to the main pages for each.

I see what @ericpoirier is saying though and if you wanted to add a side bar to display the different versions of the current spec, we could maybe use the sidebar from this design: https://invis.io/AX10M9QL74RN#/462294355_Compatibility_Tab_2 in addition to the dropdown box.

**Comment by ericpoirier** [comment]
For this issue I would like to try and avoid adding features. If we are to add a new feature to a page, I would create a new issue.

**Comment by TanjaObradovic** [comment]
all makes sense to me as well. thanks!

**Comment by ericpoirier** [comment]
I created a PR to add the sidebar widget.

https://deploy-preview-1385--jakartaee.netlify.app/specifications/platform/

Let me know if you'd like to change anything.

Thanks.

**Comment by excentrickristy** [comment]
Looks great, I really like this added functionality!
