### ISSUE TITLE
Video resource filter dropdown

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1161]
On the video resources page there is a new feature that filters visible videos by a small JS widget that allows videos to be actively filtered by categories. This will be a new JS functionality that allows us to display and hide videos based on category. While we have similar search function filters in other sites, they have additional features that aren't currently needed, and it would likely be easier to write a short jq function to target and filter a set of containers.

An option for implementation is to add a `data-target` to the dropdown that indicates the container to be filtered, and a `data-filter-attr` with the values that can be filtered. Right now we can simply just hide and show the videos, but we may want to consider using short slide-in animations after hiding all videos. This will create a nicer effect of videos not just popping in and hide any processing time we may have.
 
Design: 
![design](https://user-images.githubusercontent.com/23018241/117476713-27232000-af2b-11eb-8151-60d15cf09bcf.png)

**Comment by ericpoirier** [comment]
We are currently listing videos in a data file so we could easily add a param in there for the category and use those values in the dropdown widget.

**Comment by ericpoirier** [comment]
@shabnammayel do we have a list of categories that we can use for each of the videos listed on that page?

Thanks.

**Comment by shabnammayel** [comment]
We can use the "playlist" titles https://www.youtube.com/c/JakartaEE/playlists  from our YouTube channel for the categories. @excentrickristy can you please confirm that was the idea when creating this mockup? thanks

**Comment by ericpoirier** [comment]
@shabnammayel can you make me a list of those categories and to which videos it should be tied to?

Thanks.

**Comment by excentrickristy** [comment]
@shabnammayel the original idea here was just that we would choose some broad categories such as "Tech Talks", "Update Calls", "JakartaOne" and "Interviews". The team did not spend any time defining these categories. In the interest of keeping the list small and user friendly though, I would recommend keeping these categories very high-level.

**Comment by shabnammayel** [comment]
okay then yes, these are what we have in playlists as well. 
@ericpoirier 
"JakartaOne Livestream 2021": https://www.youtube.com/playlist?list=PLutlXcN4EAwCxiFhy8X7vi4gxqVUNbqkI
"Jakarta Tech Talks": https://www.youtube.com/playlist?list=PLutlXcN4EAwC64sgFLJSWAgQJvVo6T4Dh
Jakarta EE Update Calls: https://www.youtube.com/playlist?list=PLutlXcN4EAwDCVHTlhymKrKBwSyddZoc8
"JakartaOne Livestream en Español 2021": https://www.youtube.com/playlist?list=PLutlXcN4EAwCRzLMA8SE5On-QS39klYUn
"JakartaOne Livestream Portuguese 2021: https://www.youtube.com/playlist?list=PLutlXcN4EAwCEsKLYLFPoE-EjnaBWj7oQ
JakartaOne Livestream Turkish 2021: https://www.youtube.com/playlist?list=PLutlXcN4EAwDLjU8vlAFnFm6ATE3YigwY
JakartaOne Livestream - Russian 2021: https://www.youtube.com/playlist?list=PLutlXcN4EAwD4L_vwgYXtoHoNembpw_t0

**Comment by ericpoirier** [comment]
@shabnammayel Ok so my understanding is that we would use the playlist titles as "categories" and associate videos to those categories. Correct?

**Comment by ericpoirier** [comment]
@shabnammayel Do you know when I should expect the list of categories and new videos to add to the site?

Thanks.

**Comment by shabnammayel** [comment]
@ericpoirier we can use the ones I added previously:
"JakartaOne Livestream 2021": https://www.youtube.com/playlist?list=PLutlXcN4EAwCxiFhy8X7vi4gxqVUNbqkI
"Jakarta Tech Talks": https://www.youtube.com/playlist?list=PLutlXcN4EAwC64sgFLJSWAgQJvVo6T4Dh
Jakarta EE Update Calls: https://www.youtube.com/playlist?list=PLutlXcN4EAwDCVHTlhymKrKBwSyddZoc8
"JakartaOne Livestream en Español 2021": https://www.youtube.com/playlist?list=PLutlXcN4EAwCRzLMA8SE5On-QS39klYUn
"JakartaOne Livestream Portuguese 2021: https://www.youtube.com/playlist?list=PLutlXcN4EAwCEsKLYLFPoE-EjnaBWj7oQ
JakartaOne Livestream Turkish 2021: https://www.youtube.com/playlist?list=PLutlXcN4EAwDLjU8vlAFnFm6ATE3YigwY
JakartaOne Livestream - Russian 2021: https://www.youtube.com/playlist?list=PLutlXcN4EAwD4L_vwgYXtoHoNembpw_t0

**Comment by ericpoirier** [comment]
> @ericpoirier we can use the ones I added previously: "JakartaOne Livestream 2021": https://www.youtube.com/playlist?list=PLutlXcN4EAwCxiFhy8X7vi4gxqVUNbqkI "Jakarta Tech Talks": https://www.youtube.com/playlist?list=PLutlXcN4EAwC64sgFLJSWAgQJvVo6T4Dh Jakarta EE Update Calls: https://www.youtube.com/playlist?list=PLutlXcN4EAwDCVHTlhymKrKBwSyddZoc8 "JakartaOne Livestream en Español 2021": https://www.youtube.com/playlist?list=PLutlXcN4EAwCRzLMA8SE5On-QS39klYUn "JakartaOne Livestream Portuguese 2021: https://www.youtube.com/playlist?list=PLutlXcN4EAwCEsKLYLFPoE-EjnaBWj7oQ JakartaOne Livestream Turkish 2021: https://www.youtube.com/playlist?list=PLutlXcN4EAwDLjU8vlAFnFm6ATE3YigwY JakartaOne Livestream - Russian 2021: https://www.youtube.com/playlist?list=PLutlXcN4EAwD4L_vwgYXtoHoNembpw_t0

Based on our last meeting, I thought you were going to provide me a list of new videos to add to the Videos page as well as a list of categories to group all the videos.

I don't mind using the categories you are providing just now but can you tell me which videos should go with which categories?

Thanks.

**Comment by ericpoirier** [comment]
After discussion with @shabnammayel, i'm going to get the Top 5 videos of each lists and add them to the video's data file.

We should also look at adding a view more link when selecting a category that would go to that category's youtube playlist.

**Comment by ericpoirier** [comment]
@shabnammayel please review the following staging page where I added additional videos as well as the filter.

https://deploy-preview-1421--jakartaee.netlify.app/community/videos/

**Comment by excentrickristy** [comment]
@ericpoirier the page looks great! I was testing and I noticed something strange though. If you don't allow cookies and then use the dropdown filter, the filtered videos don't show a thumbnail, they are just black with the youtube button overlaid.

Similarly, if you do accept cookies, then you filter the videos or use the pagination at the bottom of the screen, the new videos that show up are not embedded and have no thumbnail.

**Comment by ericpoirier** [comment]
> @ericpoirier the page looks great! I was testing and I noticed something strange though. If you don't allow cookies and then use the dropdown filter, the filtered videos don't show a thumbnail, they are just black with the youtube button overlaid.
> 
> Similarly, if you do accept cookies, then you filter the videos or use the pagination at the bottom of the screen, the new videos that show up are not embedded and have no thumbnail.

Thanks for reporting this.

There seems to have something blocking the thumbnails to load. I'll have a look at that.

**Comment by ericpoirier** [comment]
After looking into it, I found out that videos that are 1080p will have the maxresdefault.jpg thumbnail which we are hardcoding in our eclipsefdn.videos.js plugin to create the thumbnails.

The videos that are not printing the thumbnail are videos that have a resolution of 720p or lower. I'll have to look into updating the eclipsefdn.videos.js plugin so that it fetches at least a thumbnail.

**Comment by ericpoirier** [comment]
@excentrickristy I created a separate issue to deal with updating our videos plugin which is outside the scope of the Jakarta EE website.

https://gitlab.eclipse.org/eclipsefdn/it/webdev/solstice-assets/-/issues/291

**Comment by ericpoirier** [comment]
I was able to fix the thumbnail issue:

https://deploy-preview-1421--jakartaee.netlify.app/community/videos/

I also encountered an issue with videos not being loaded on the page when intereracting with the pagination and also the filter. Note that this issue is now fixed on staging as well.

**Comment by shabnammayel** [comment]
LGTM! FYI @excentrickristy

**Comment by excentrickristy** [comment]
beautiful!
