### ISSUE TITLE
Allow deeper nesting of main navigation elements

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1162]
As part of the design, there is a request to allow an additional level of nesting within the menu. Currently, this feature does not exist and would need to be implemented in the post-launch phase (with a higher priority). The most reliable and accessible way to implement this would be to use clickable sections in the menu that trigger the submenus to open (rather than using hover events that aren't present on some devices that use touch screens). Before hand, the space the menu occupies would be present but empty, allowing us to easily fill with the desired content (or lay it overtop).

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585112
![image](https://user-images.githubusercontent.com/23018241/117822862-e4b75700-b23a-11eb-8908-cbd8591a73db.png)

**Comment by ericpoirier** [comment]
The deep nesting is all done and on production.

Thanks!
