### ISSUE TITLE
Add The Apache Software Foundation as Guest Member of the WG

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#1164]
Hello 
Please add The Apache Software Foundation as Guest Member of the working group.

[asf_logo_url.pdf](https://github.com/jakartaee/jakarta.ee/files/6461649/asf_logo_url.pdf)

**Comment by linkfang** [comment]
Hi @ZahraFazli , The Apache Software Foundation is added, please review here:
https://deploy-preview-1171--jakartaee.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
Looks good, thanks
