### ISSUE TITLE
Compatible Products - View all tab

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1167]
The view all tab is a new content section in the compatible products page that lists a compressed view of all of the products with all links to the TCK's available side by side for ease of access. Each category of compatibility for each release will have its own heading and table to view all of this content.

@karenmcnaughton regarding the odd pagination stuff at the bottom of this section, what would this be used for? When there are multiple tables side by side it's kind of ambiguous what the idea is here. I think it might be easier to just show all of the tables in a list for the user to peruse at their leisure. The design has done well to compress it, and if we ever get to the point of having more than 5 tables sort of thing, we could always look at enhancing this to split it up by release or something similar. 

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585114
![image](https://user-images.githubusercontent.com/23018241/117981798-64105d80-b303-11eb-8fc5-0c1a7fb2553f.png)

**Comment by ericpoirier** [comment]
Hi @shabnammayel,

I implemented this redesign on the following staging page:
https://deploy-preview-1340--jakartaee.netlify.app/compatibility/download/

Note that the "Sort by" filter was note implemented but will be implemented when we are in a better position with the redesign.

Let me know if you have more questions.

Thanks.

**Comment by excentrickristy** [comment]
Hi @ericpoirier,
Does this page have pagination built in after a certain number of releases/tables?
If not, is their ability to add the  functionality?

Thanks.

**Comment by ericpoirier** [comment]
> ertain number of releases/tables?
> If not, is their ability to add the functionality?

Hi @excentrickristy, the functionality is not implemented yet but i'm going to try and implement it today. I'll keep you posted.

**Comment by shabnammayel** [comment]
For the View all tab which is the current download tab, we are making a slight change: 

https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/462294356_Compatibility_Tab_3

Please remove the certification results column from the table in the tab.

**Comment by excentrickristy** [comment]
@ericpoirier for this page and the certification results tab I discussed with Shabnam the possibility of having actual URLs for each version of Jakarta and that page would only contain the links for those releases. I wasn't sure if the current setup would rely on a dynamic loading of the content without urls, but if we could have urls for each release it would be great for indexability and search visibility.

**Comment by excentrickristy** [comment]
Link to design files: https://www.dropbox.com/s/2hzszsowkimzhu6/Jakarta-Design-4Drev2.ai?dl=0

**Comment by ericpoirier** [comment]
Shabnam and I had a quick call to discuss the changes requested and here are some clarifications to what needs to be done:

Tab 3:

- [x] Create a new page to list the Download links
- [x] Each links should be on their own line
- [x] Links should be blue
- [x] Ignore the Certification column from the design, this should not be implemented

**Comment by ericpoirier** [comment]
@shabnammayel you can find the updated "View All" section on the following staging page:

https://deploy-preview-1372--jakartaee.netlify.app/compatibility/

Let me know if you'd like to change anything.

Thanks.

**Comment by shabnammayel** [comment]
Thanks Eric, looks good. Couple of things:

-Please add an underline for all the links in both Certification results and download compatible products tables to make it clear the links are to download the product.
-Please change the title of the table on the second tab from "Certification" to "Certification Results"
-similar to the mockup, please make the sidebar highlighted for the release version that the user clicks on:
<img width="344" alt="Screen Shot 2022-01-07 at 8 19 15 AM" src="https://user-images.githubusercontent.com/51449073/148549686-97836756-11b4-4f7c-860f-79a796f37632.png">
 -the download compatible products table is very long, can we add pagination similar to the mockup? 

Thanks.

@excentrickristy FYI

**Comment by ericpoirier** [comment]
After a quick chat on Slack we agreed to keep the links as is and only update the sidebar and Certification title.

Here is the updated staging page:
https://deploy-preview-1372--jakartaee.netlify.app/compatibility/certification/9.1/

Let me know if there's anything else.

**Comment by shabnammayel** [comment]
LGTM! Thanks Eric!
