### ISSUE TITLE
Create filters for different Jakarta Releases in compatible products

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1173]
This pertains solely to the feature to allow for checkbox filters that can hide and show elements on the page based on the available released products. This may be able to make use of #1161 code if made general enough, and it could accelerate the development of this feature.

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585115
![image](https://user-images.githubusercontent.com/23018241/118166852-fd1ea180-b3f3-11eb-8621-43d8ae360443.png)

**Comment by ericpoirier** [comment]
Closing this issue since we are moving away from this new design and using the old design instead.

Here is the updated layout going forward:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/462294357
