### ISSUE TITLE
Create solution for opening TCK or download links per released product

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1174]
TBD

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585115
![image](https://user-images.githubusercontent.com/23018241/118166852-fd1ea180-b3f3-11eb-8621-43d8ae360443.png)

**Comment by ericpoirier** [comment]
@autumnfound was this issue meant to track the development of the dropdown items in each boxes or something else on the page?

Thanks.

**Comment by ericpoirier** [comment]
I'm going to close this issue since we are moving away for this design.

Here is the design going forward:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/462294357
