### ISSUE TITLE
[data for 9.1 release page] Number of repositories and projects related to Jakarta EE 9.1 release

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1177]
@ivargrimstad @aeiras

Currently, a lot of numbers, (and requests to update work in progress pull request) has been mentioned in https://github.com/jakartaee/jakarta.ee/issues/1165 , so I opened this GitHub issue to come up with a consensus and final Number of **Repositories** and **Projects** related to the Jakarta EE 9.1 release and also the **equation** we can later document for making this a smooth process for future releases.

**Comment by ivargrimstad** [comment]
Number of Specification projects: **31**
Source: https://projects.eclipse.org/list-of-projects?combine=Jakarta&field_project_techology_types_tid=1102&field_state_value_2=All&page=1

Number of Specifications (including Platform and Web Profile): **41**
Number of Specifications (excluding Platform and Web Profile): **39**
Source: https://jakarta.ee/specifications/

**Comment by cesarhernandezgt** [comment]
Thank you for the pointers @ivargrimstad

I have a third set of results:  Projects 30 and Specifications 35.

**Analysis for number of Projects**

-Total number of `projects` the current [search](https://projects.eclipse.org/list-of-projects?combine=Jakarta&field_project_techology_types_tid=1102&field_state_value_2=All&page=1) providers: 33 

Then the number can be reduced to `29` projects if you apply the following criteria:

- If you collect stats only related to specs that were included in the [9.1 release plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9.1ReleasePlan), this to my eyes means Eclipse JNoSQL, Jakarta NoSQL, and Jakarta MVC can be subtracted from the final number.
- The same applies for Jakarta Stable APIs project because this project generate four [1] specifications that were pruned since  [Jakarta EE 9 release plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan)

Don't get me wrong, I have nothing against NoSQL and MVC :), I'm just parsing the information and trying to understand the data.

Also, I notice https://projects.eclipse.org/projects/ee4j.jakartaee-tck is not listed in the list of projects from the  [search](https://projects.eclipse.org/list-of-projects?combine=Jakarta&field_project_techology_types_tid=1102&field_state_value_2=All&page=1), and that is because the Jakarta EE TCK project is missing the tag `Specification` and `Cloud Native Java`  cc: @scottmarlow

If we include Jakarta EE TCK project as related to Jakarta 9.1 release, then we are back at the `30` project number :).


**Analysis for number of Specifications**

https://jakarta.ee/specifications/ page list a total of `41` specification. Then the number can be reduced to `35` specifications if you apply the following criteria:

- As peer [Jakarta EE 9 release plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), four specifications were pruned [1] 
- Not including MVC and NoSQL 
- Jakarta EE TCK is not listed on the [specifications](https://jakarta.ee/specifications/ ) page. So it's not part of the `41`nor the `35` number.
- Notice I didn't subtract Platform and Web Profile


As you can see in my above analysis, all will depend on the criteria you are using to obtain the data.  The complexity of gettering these numbers, as Ivar already mentioned it, the relationship between `project` and `specification` is not 1 to 1. 

My personal recommendation would be to show on the website **both**  Project and Specification data. cc @karenmcnaughton @TanjaObradovic 

But if there is only space for one, I prefer to show `projects` over `specifications` because the term `project` seems to be easier to read for non-technical website visitors and understand the amount of top level work the 9.1 (or any other future release) requires. 

[1]
Jakarta XML Registries
Jakarta XML RPC
Jakarta Deployment
Jakarta Management

I haven't done the math for repositories since I think we first need to iron the `Project` versus `specifications` number.

**Comment by ivargrimstad** [comment]
You are right, @cesarhernandezgt. 
It depends whether the list should display only those that were part of 9.1, those related to 9 and 9.1, or all.

If we should be _really_ picky then, the 9.1 list should only contain 1 project and 2 specifications since only the Platform and Web Profile had updates (other than service releases to the TCKs) :)

I would recommend choosing the simple approach and list all, always. Makes it easier for everyone.

**Comment by aeiras** [comment]
@cesarhernandezgt, thank YOU for the fantastic inventory on Specs and projects. Just wow. 

@ivargrimstad, I sort of agree with you on the overall overview of inclusion. 

3 things:

1. the Jakarta TCK ought to be added to the count, which brings the number to 30. 
2. the removal of NoSQL and MVC ought to happen.  We have also removed them from the CN4J communications slides and added projects to the presentation showing information. 
3. let us add both numbers, projects, and specs to the new page and set it as future template information.

**Comment by ivargrimstad** [comment]
> @cesarhernandezgt, thank YOU for the fantastic inventory on Specs and projects. Just wow.
> 
> @ivargrimstad, I sort of agree with you on the overall overview of inclusion.
> 
> 3 things:
> 
> 1. the Jakarta TCK ought to be added to the count, which brings the number to 30.
Still think we should stick with the total number. Keep it simple. Not confuse anyone by filtering out based on something the community at large doesn't see as relevant

> 2. the removal of NoSQL and MVC ought to happen.  We have also removed them from the CN4J communications slides and added projects to the presentation showing information.

That is wrong @aeiras.
NoSQL was removed since it hasn't had a release yet. 
MVC is still on the slide, as it should be. Same reasoning as with e.g. GraphQL and Reactive Messaging. Listed as independent specification.

> 3. let us add both numbers, projects, and specs to the new page and set it as future template information.
+1

**Comment by cesarhernandezgt** [comment]
@aeiras @ivargrimstad 

> I would recommend choosing the simple approach and list all, always. Makes it easier for everyone.

>let us add both numbers, projects, and specs to the new page 

By merging your last comments, this is how the page will look like.

![image](https://user-images.githubusercontent.com/1454523/118699407-bbfd0780-b7ce-11eb-824c-bea7e8627dcc.png)

**Comment by aeiras** [comment]
gotcha Ivar. good stuff. 

Cesar, it looks fantastic and more complete. thank you for prioritizing the PR changes.

**Comment by ivargrimstad** [comment]
Sorry to be a troublemaker, but the number of Git repositories should include all the spec- and tck-repositories under the EE4J organization. We just have to figure out an easy way to filter out the samples and implementations there to get the correct number.

**Comment by aeiras** [comment]
> Sorry to be a troublemaker, but the number of Git repositories should include all the spec- and tck-repositories under the EE4J organization. We just have to figure out an easy way to filter out the samples and implementations there to get the correct number.

Ivar, while you figure out the actual number with details, can you make a plan to mirror those findings to start the export to the Jkta repo via bugzilla tickets? That was voted early that year. the work needs to start sometime. :) If not during current work, when.

**Comment by ivargrimstad** [comment]
I'll do my best to find the number. Regarding the other part, I will leave it to the responsible committee to decide when to start the work :)

**Comment by aeiras** [comment]
> @aeiras @ivargrimstad
> 
> > I would recommend choosing the simple approach and list all, always. It makes it easier for everyone.
> 
> > let us add both numbers, projects, and specs to the new page
> 
> By merging your last comments, this is how the page will look like.
> 
> ![image](https://user-images.githubusercontent.com/1454523/118699407-bbfd0780-b7ce-11eb-824c-bea7e8627dcc.png)

@cesarhernandezgt, can you please add a feature to the page where the formal blog announcement gets added to the release page? 
Like that, all release pages will always have the formal WG announcement within the page. 

Ideally, we fix many issues with such an integration:

1. The announcement is not lost as time passes under the Formal announcement page. Having the write-up in 2 sections, 1 with a focus on release, is a huge improvement to communication betterment. 
2. I think quotes from the community behind the release are being added to the page, correct? this is just a follow-up from that feature. 

Let us know the drawbacks of this request, and thanks for bringing any issues directly to the ticket.

**Comment by aeiras** [comment]
> I'll do my best to find the number. Regarding the other part, I will leave it to the responsible committee to decide when to start the work :)

thank you for being extra snuggly efficient with current work Ivar. It is fun to get to do this via open conversations. I appreciate it more than words show. Let's do this!

**Comment by ivargrimstad** [comment]
The number of repositories associated with spec and TCKs in the EE4J GitHub organization is currently: **51**

I have filtered out everything related to tutorials, examples, implementations, and release scripts.

**Comment by cesarhernandezgt** [comment]
@aerias

> @cesarhernandezgt, can you please add a feature to the page where the formal blog announcement gets added to the release page?

I think this is out of the scope of the present GitHub issue. Can you please open a new Github issue describing in details the new feature you are proposing?

@ivargrimstad
> The number of repositories associated with spec and TCKs in the EE4J GitHub organization is currently: 51

Thank you, I updated also my local branch with the number of repositories and this is the current view:
![image](https://user-images.githubusercontent.com/1454523/118719020-2caf1e80-b7e5-11eb-8451-5633f49949a1.png)

I'm going to push the latest changes and provide the update in the main ticket #1165 from where this conversation was originated.

**Comment by aeiras** [comment]
> @Aerias
> 
> > @cesarhernandezgt, can you please add a feature to the page where the formal blog announcement gets added to the release page?
> 
> I think this is out of the scope of the present GitHub issue. Can you please open a new Github issue describing in details the new feature you are proposing?
> 
> @ivargrimstad
> 
> > The number of repositories associated with spec and TCKs in the EE4J GitHub organization is currently: 51
> 
> Thank you, I updated also my local branch with the number of repositories and this is the current view:
> ![image](https://user-images.githubusercontent.com/1454523/118719020-2caf1e80-b7e5-11eb-8451-5633f49949a1.png)
> 
> I'm going to push the latest changes and provide the update in the main ticket #1165 from where this conversation was originated.

great suggestion @cesarhernandezgt. Here it goes https://github.com/jakartaee/jakarta.ee/issues/1186

**Comment by cesarhernandezgt** [comment]
@aeiras @ivargrimstad I'm closing now this issue to bring back the 9.1  work to the main GitHub issue: #1165
