### ISSUE TITLE
Highlighted Text for JakartaEE 9.1 release page

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1179]
The following three boxes need text related to 9.1 release. 
This will be part of: https://github.com/jakartaee/jakarta.ee/issues/1165

![image](https://user-images.githubusercontent.com/1454523/118516263-643d9e00-b6f3-11eb-87d0-a64853a2f844.png)

cc: @karenmcnaughton

**Comment by karenmcnaughton** [comment]
Recommend that we keep the text in the 3 boxes the same, except change 9 to 9.1

Also recommend to add a line underneath the 3 boxes in the orange  bold text that says: "NOW SUPPORTING JAVA SE 11"

**Comment by cesarhernandezgt** [comment]
@karenmcnaughton 
Done in the PR https://github.com/jakartaee/jakarta.ee/pull/1170
Feel free to close this ticket if the boxes and orange text looks as expected.

![image](https://user-images.githubusercontent.com/1454523/118556312-f4dea300-b720-11eb-97d4-1ccba34244b8.png)

Live Preview:  https://deploy-preview-1170--jakartaee.netlify.app/release/9.1/

**Comment by karenmcnaughton** [comment]
Thank you @cesarhernandezgt just one last request pls. For this text up above the two call to action boxes: Previous Release: Jakarta EE 9 -- can you pls make that text in ALL CAPS, as the rest is..? Thank you!

**Comment by cesarhernandezgt** [comment]
@karenmcnaughton 

> just one last request pls. For this text up above the two call to action boxes: Previous Release: Jakarta EE 9 -- can you pls make that text in ALL CAPS, as the rest is..? Thank you!

Done in the PR #1170:
![image](https://user-images.githubusercontent.com/1454523/118686470-43437e80-b7c1-11eb-985f-b4a277882f0a.png)


Live Preview: https://deploy-preview-1170--jakartaee.netlify.app/release/9.1/

**Comment by cesarhernandezgt** [comment]
@karenmcnaughton 

After the review and help we got from https://github.com/jakartaee/jakarta.ee/issues/1177 ,I just updated the Project, Specifications and Repositories data with the latest numbers:

Live Preview: https://deploy-preview-1170--jakartaee.netlify.app/release/9.1/

![image](https://user-images.githubusercontent.com/1454523/118720067-66ccf000-b7e6-11eb-8492-5f57a98d329a.png)

**Comment by cesarhernandezgt** [comment]
@karenmcnaughton 
Now that the 3 boxes have the desired text, can we close this GitHub issue and continue the review in the main ticket https://github.com/jakartaee/jakarta.ee/issues/1165 ?
