### ISSUE TITLE
Redesign Preview site

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1180]
We should set up netlify to build the redesign branch to better enable demos, user feedback, and integration testing. I tried looking into the actual Netlify configs but it seems I don't have access to the Netlify site config for this site. Christopher, could you either give access or create a rule to watch the `redesign` branch?

Also, as an aside, we should probably streamline the build for the redesign to reduce build minutes used. We could do this by checking in a copy of the specs and disabling the checkout process which is one of the heaviest parts of the build. I can take care of this part on my own.

**Comment by chrisguindon** [comment]
I added `redesign` as an additional `Branch deploys` branch. This should allow you to do what you need.

I have an idea for streamlining the build.  We can create proxy rules with netlify.

How about we create a proxy rule for jakarta.ee/specifications => https://jakartaee-specifications.netlify.app/specifications/

This would allow us to remove this custom build process from jakarta.ee.

**Comment by autumnfound** [comment]
That sounds perfect!! I was looking into compressing a copy of the specs, but man is that section big.

**Comment by chrisguindon** [comment]
I will submit a PR to see if that can work. 

Let use https://github.com/jakartaee/jakarta.ee/issues/1026 for that!

**Comment by chrisguindon** [comment]
I think we are done here!
