### ISSUE TITLE
Post Jakarta EE 9.1 Press Release to https://jakarta.ee/news/

### ISSUE THREAD

**Issue by jph152** [jakartaee/jakarta.ee#1190]
The marketing committee would like the press release to be published to this page: https://jakarta.ee/news/

Please let me know if this request should be directed elsewhere, since I haven't submitted a content request for this page before.

Here is the content for the press release:

----

[Jakarta EE 9.1 PR.docx](https://github.com/jakartaee/jakarta.ee/files/6524846/Jakarta.EE.9.1.PR.docx)

**Comment by aeiras** [comment]
Hola @jph152 

It should be re-directed in the EE 9.1 landing page as well. Look at this ticket. Thanks! https://github.com/jakartaee/jakarta.ee/issues/1186

**Comment by cesarhernandezgt** [comment]
@jph152 
A PR is now available for adding the entry in the https://jakarta.ee/news/  news section.
https://github.com/jakartaee/jakarta.ee/pull/1193

cc:
@chrisguindon @autumnfound

**Comment by gerdogdu** [comment]
@aeiras  @cesarhernandezgt Can you please also add our company ManageCat quote to this document (Jakarta EE 9.1 PR.docx)  and #1193 as follows: (Sorry for the delay)

cc:
@chrisguindon @autumnfound

**ManageCat**

"ManageCat would like to thank all Jakarta EE working group members who contributed to this amazing work," said Gurkan Erdogdu, Director of ManageCat."  "We are delighted and proud to provide a Jakarta EE 9.1 Full Platform compliant and certified application server, ManageFish. I believe that with the version of Jakarta EE 10, the innovations that the platform will offer will increase exponentially."

**Comment by cesarhernandezgt** [comment]
> @aeiras @cesarhernandezgt Can you please also add our company ManageCat quote to this document (Jakarta EE 9.1 PR.docx) and #1193 as follows: (Sorry for the delay)

Hi @gerdogdu

I can't edit the article content since the pull request (#1193) was base on the official Press Release for Jakarta EE 9.1 provided in this Github Issue. Please contact Senior Marketing Manager, @karenmcnaughton, for any press release inquiry.

**Comment by cesarhernandezgt** [comment]
@TanjaObradovic 
The URL for the social media link to the press release will be:
https://jakarta.ee/news/jakarta-ee-9-1-released/

Please make sure the Dev team merges first PR #1193 , then the social media team will be able to perform the card's distribution.

**Comment by chrisguindon** [comment]
@cesarhernandezgt @TanjaObradovic I just merged the PR!

**Comment by cesarhernandezgt** [comment]
Thanks much @chrisguindon

**Comment by autumnfound** [comment]
As this has been merged, I'll close this issue, thanks guys!
