### ISSUE TITLE
Jakarta EE 9 release videos can't be played full screen

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1191]
**Describe the bug**
Videos from the Jakarta EE 9 release page can't be played in full screen.

**To Reproduce**
1. Go to https://jakarta.ee/release/9/
2. Click Play on any video
3. Click on Full screen
4. Ther is an error on the screen.

**Expected behavior**
The video should be able to be watched on full screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/1454523/119202417-f6c0a300-ba4d-11eb-88d0-7aa508d969cd.png)

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: chrome

**Comment by aeiras** [comment]
do you mean, that as a viewer I cannot stay on the page while watching the video @cesarhernandezgt ?
if correct, that's a major feature flaw.

**Comment by cesarhernandezgt** [comment]
@aeiras 
It means you can't read anything if for future release pages a video has slides or text because the video size is fixed and can't be maximized.

**Comment by aeiras** [comment]
Gotcha, Cesar. I understand the problem. Thank you

**Comment by autumnfound** [comment]
@cesarhernandezgt if you follow the Learn More, does it give any context for the error? I tested on my machine and I don't have the playable videos in my browser, just links to the videos essentially. I think this is due to how YT does embeds, and it working differently on different OSs. I'll see if the other iOS user on our team can replicate this issue!

**Comment by autumnfound** [comment]
Update: Dug in the code and found out why it wasn't working for me. I dismiss the cookie banners/ignore them, and we need it as YT embeds trackers when we import the video, d'oh! Google's help page isn't very helpful sadly. It just says fullscreen might be disabled on sites outside of YT without explaining why or how to fix this.

Looking around online, I might have found a solution, but this is at the level of all of our embedded YT videos not allowing fullscreen and would need a small patch

**Comment by autumnfound** [comment]
@aeiras @cesarhernandezgt We've made a patch in the framework so we can apply this fix to all of our sites. The usual expected behaviour was to follow through to YT and engage in comments and such. I'm guessing that the fullscreen button hasn't been tested in a while as its older functionality and there have been some external changes (in browser security + Youtube embeds) since it's been added that may have broken it. You can follow along or view the fix here! https://github.com/EclipseFdn/solstice-assets/pull/252

**Comment by aeiras** [comment]
Hey Martin, 
I have comment directly on[252 AEB comment](https://github.com/EclipseFdn/solstice-assets/pull/252#issuecomment-852401834) my only concern is the long term scalability as the release template and its connection with Youtube. I think it is great to play the videos in large screen directly in the page without clicks taken the viewer to youtube. After all, we want the viewer to stay in EE longer. 

Thanks for the nice follow up and fixes, @autumnfound :)

**Comment by cesarhernandezgt** [comment]
Thank you for the update and the work done for this patch @autumnfound . I saw the fix on EclipseFdn/solstice-assets#252 and it worked fine :)!

**Comment by autumnfound** [comment]
> Hey Martin,
> I have comment directly on[252 AEB comment](https://github.com/EclipseFdn/solstice-assets/pull/252#issuecomment-852401834) my only concern is the long term scalability as the release template and its connection with Youtube. I think it is great to play the videos in large screen directly in the page without clicks taken the viewer to youtube. After all, we want the viewer to stay in EE longer.
> 
> Thanks for the nice follow up and fixes, @autumnfound :)

Pretty sure we've addressed the concern, but I want to circle back here as well for transparency! The next SA release will fix fullscreen toggle on the in page embed, and doesn't require you to go to youtube. This will have a delay of a day or two while we try and bundle other changes with the release, but should make it here soon enough! We'll keep this issue open to ensure we don't lose track of this.

**Comment by aeiras** [comment]
Martin, 
Cesar did some wiki documentation on the release page, is it ok for you to add a bit on the Youbute side on that document?  I think transparency is only protected is written down in places that live beyond this ticket :) 

You rock!

**Comment by autumnfound** [comment]
This has been fixed! We've updated the theme to the version including this fix, and the mentioned YT videos can now be maximized insite.

**Comment by autumnfound** [comment]
> Martin,
> Cesar did some wiki documentation on the release page, is it ok for you to add a bit on the Youbute side on that document? I think transparency is only protected is written down in places that live beyond this ticket :)
> 
> You rock!

As long as the youtube component that we've been making use of is used, there should be no real concern. The pattern we typically follow is to copy paste the previous release page and change it to match the current releases content, this way we inherit the work done in the past!
