### ISSUE TITLE
Please add BES Application Server v10.0.0 to Jakarta EE 9 Compatible Products page

### ISSUE THREAD

**Issue by guojjanjun** [jakartaee/jakarta.ee#1218]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=1506
**A product name and version**
BES Application Server v10.0.0
**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Full Platform
**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/guojjanjun/bes-tck/blob/main/BES_Application_Server_for_eclipse.zip
**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Beijing Baolande Software Corporation
**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/372
**The URL where Compatible Software Product is available for download**
https://www.bessystem.com/product/0ad9b8c4d6af462b8d15723a5f25a87d/info?p=101#page-2

**Comment by linkfang** [comment]
Now it is live!
https://jakarta.ee/compatibility/#tab-9
