### ISSUE TITLE
connect/mailing-lists/ shows outdated Jakarta Messaging link

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1227]
The new Jakarta Messaging mailing list is: https://accounts.eclipse.org/mailing-list/messaging-dev
In this github issue https://github.com/jakartaee/jakarta.ee/issues/1216#issuecomment-867075283, the spreadsheet @chrisguindon uses for update the https://jakarta.ee/connect/mailing-lists/ was provided containing the updated address for Jakarta Messaging.

Thanks @scottmarlow  for finding this issue.

**Comment by chrisguindon** [comment]
The content of that connect page is here:
https://github.com/jakartaee/jakarta.ee/blob/src/layouts/shortcodes/pages/mailing-lists.html

**Comment by chrisguindon** [comment]
However, I can help to update content on https://accounts.eclipse.org/mailing-list/messaging-dev if that is needed. That content for that page is stored in a database.

**Comment by aeiras** [comment]
Hola Chris, 
Thanks for the follow up to Cesar's update on the messaging mailing list. 

The PR created back in Q4 2020 is no longer valid nor good.  
We moved away from it and instead used the spreadsheet to update the jakarta mailing lists within the Connect button and the EF Infra mailing list. 

I think it is enough for you or someone in your team to push the update spreadsheet and done.  

I hope this clarifies the current work and request. Do ask away. I am sure Cesar could fill in the blanks as well.

**Comment by scottmarlow** [comment]
I'm not fully understanding the above conversation but did just check and see that https://jakarta.ee/connect/mailing-lists/ contains:
```
[Jakarta Messaging](https://accounts.eclipse.org/mailing-list/jms-dev) | The list is used for technical discussions related to Jakarta Messaging. Messaging via loosely coupled reliable async services-- | --
```

But I think that should be:
```
[Jakarta Messaging](https://accounts.eclipse.org/mailing-list/messaging-dev) | The list is used for technical discussions related to Jakarta Messaging. Messaging via loosely coupled reliable async services-- | --
```

The key being changing `https://accounts.eclipse.org/mailing-list/jms-dev` to `https://accounts.eclipse.org/mailing-list/messaging-dev`.

Hope that helps. :-)

**Comment by chrisguindon** [comment]
I created a PR to fix the change that @scottmarlow has highlighted: 
https://github.com/jakartaee/jakarta.ee/pull/1230/files

**Comment by aeiras** [comment]
Hola Scott and Chris, 

here https://github.com/jakartaee/jakarta.ee/issues/1216#issuecomment-867973942

**Comment by ivargrimstad** [comment]
I believe this is fixed by @chrisguindon's PR
