### ISSUE TITLE
Please add Apusic Application Server as Jakarta EE 9 Full Platform compatible

### ISSUE THREAD

**Issue by PatrickHuang888** [jakartaee/jakarta.ee#1228]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=1397

**A product name and version**
AAS V10-EE9

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Both 

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/apusic/aas-tck/blob/master/aas.jpg

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Kingdee Apusic cloud computing Co., Ltd.

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/376

**The URL where Compatible Software Product is available for download**
http://www.apusic.com/info_safety/server

**Comment by ivargrimstad** [comment]
+1 The certification request is approved, so this is good to go.

**Comment by linkfang** [comment]
Hi @ivargrimstad @TanjaObradovic 
Please preview the changes here:
https://deploy-preview-1231--jakartaee.netlify.app/compatibility/#tab-9

**Comment by ivargrimstad** [comment]
Pr #1231 approved. Thanks!

**Comment by linkfang** [comment]
NP!
Now the changes are live!
