### ISSUE TITLE
Payara Server Community 6.2021.1.Alpha1 Jakarta EE 9.1 compatibility 

### ISSUE THREAD

**Issue by dominikatasarz** [jakartaee/jakarta.ee#1232]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting** https://accounts.eclipse.org/users/dtasarzsochacka

**A product name and version** Payara Server Community 6.2021.1 Alpha 1

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)** (same logo as already used for Payara Server Jakarta EE 9 compatibility)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product** Payara Services Ltd

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process** https://github.com/eclipse-ee4j/jakartaee-platform/issues/375

**The URL where Compatible Software Product is available for download** https://www.payara.fish/downloads/payara-platform-community-edition/  ( https://search.maven.org/remotecontent?filepath=fish/payara/distributions/payara/6.2021.1.Alpha1/payara-6.2021.1.Alpha1.zip  direct)

**Comment by ivargrimstad** [comment]
+1

**Comment by linkfang** [comment]
Hi @ivargrimstad 
Please preview the changes here:

https://deploy-preview-1235--jakartaee.netlify.app/compatibility/#tab-9_1

**Comment by ivargrimstad** [comment]
> Hi @ivargrimstad
> Please preview the changes here:
> 
> https://deploy-preview-1235--jakartaee.netlify.app/compatibility/#tab-9_1

Done!
