### ISSUE TITLE
Add and Change Fujitsu products and  logos on Compatible Page

### ISSUE THREAD

**Issue by kazumura** [jakartaee/jakarta.ee#1252]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://accounts.eclipse.org/users/kkazumura

**A product name and version**

 * FUJITSU Software Enterprise Application Platform V1.0
 * FUJITSU Software Interstage Application Server V13.0

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**

Jakarta EE 8 Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

[fujitsu-product-logo.zip](https://github.com/jakartaee/jakarta.ee/files/7112787/fujitsu-product-logo.zip)

 * banner_EAP.svg for FUJITSU Software Enterprise Application Platform V1.0
 * banner_IAPS.svg for FUJITSU Software Interstage Application Server V13.0

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

 * eclipse-ee4j/jakartaee-platform#244  
   for FUJITSU Software Enterprise Application Platform V1.0
 * eclipse-ee4j/jakartaee-platform#359  
   for FUJITSU Software Interstage Application Server V13.0

**The URL where Compatible Software Product is available for download**

 * https://www.fujitsu.com/jp/software/applatform/
   for FUJITSU Software Enterprise Application Platform V1.0
 * https://www.fujitsu.com/jp/software/interstage/apserver
   for FUJITSU Software Interstage Application Server V13.0

**Comment by linkfang** [comment]
Hi @TanjaObradovic , @ivargrimstad ,
Please preview the changes here:
https://deploy-preview-1254--jakartaee.netlify.app/compatibility/#tab-8
