### ISSUE TITLE
No App Servers...?

### ISSUE THREAD

**Issue by rsoika** [jakartaee/jakarta.ee#1253]
The pace, the jakarta.ee project shows in pushing the new platform is impressive. Jakarta EE9 and EE9.1 are already released, version 9.2 is in the starting blocks and Jakarta EE 10 release plan is approved. 

But still there are no official Application Servers available. Wildfly provides a preview version but no official Docker images. Payara is making announcements but also has no official way to test it. And OpenLiberty says nothing on its web page.

We form [Imixs-Workflow](https://github.com/imixs/imixs-workflow), which is a BPMN Workflow engine based on Java Enterprise since more than 10 years, have already released a new version 6.0 now build with Jakarta EE9. But we can not proceed to migrate our projects like [Imixs-Office-Workflow](https://github.com/imixs/imixs-office-workflow) because there is still no Application Server available.

Why is that?  And how long do you think it will take until we finally get servers? The servers are crucial in order to be able to present new solutions.

**Comment by ericpoirier** [comment]
Hi @rsoika, sorry for the late response but I don't think this is the right channel to ask questions about servers.

I would suggest asking your question on the Eclipse Forum:
https://www.eclipse.org/forums/

Thanks.
