### ISSUE TITLE
Add Jakarta EE Developer Survey report to Resources page

### ISSUE THREAD

**Issue by jph152** [jakartaee/jakarta.ee#1258]
Please add the new survey report to https://jakarta.ee/resources under the "Surveys" heading.

TEXT: 2021 Jakarta EE Developer Survey
LINK: https://outreach.jakartaee.org/2021-developer-survey-report?utm_campaign=2021%20Jakarta%20EE%20Developer%20Survey&utm_source=resources%20page

**Comment by linkfang** [comment]
Hi @jph152 ,
Please preview the changes here:
https://deploy-preview-1259--jakartaee.netlify.app/resources/#surveys

Please note, as the link you offered has some parameters which do not make any difference on what will be shown on the page, so I removed them to make the URL clean and short. Please let me know if those parameters are included on purpose so I can add them back.

https://outreach.jakartaee.org/2021-developer-survey-report?utm_campaign=2021%20Jakarta%20EE%20Developer%20Survey&utm_source=resources%20page
V.S.
https://outreach.jakartaee.org/2021-developer-survey-report

Thanks!

**Comment by jph152** [comment]
Hi @linkfang, 
Looks good. Can we keep the parameters? We just include them to see how many form fills we get from each source. Thanks

**Comment by linkfang** [comment]
> Hi @linkfang,
> Looks good. Can we keep the parameters? We just include them to see how many form fills we get from each source. Thanks

Sure! That's what I was thinking. Now it's back!
https://deploy-preview-1259--jakartaee.netlify.app/resources/#surveys
