### ISSUE TITLE
Jakarta.ee New Homepage SEO Optimization

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1264]
CC: @shabnammayel 

In reviewing the new homepage ready for deployment I am making the following recommendations to support greater search visibility for term enterprise java:

New title tag:
Jakarta® EE | Cloud Native Enterprise Java | Java EE | The Eclipse Foundation

New meta description tag:
Jakarta Enterprise Edition (EE) is the open source future of cloud native enterprise Java. Protect your investments in Java EE and modernize your enterprise applications.

On the main banner, right now Jakarta EE and the subtitle underneath are being shown in an H1 and h2 tag separately. Combine these into one h1 tag, and we are going to add the word enterprise:
`<h1><img class=""jumbotron-title"" src=""/images/jakarta/jakarta-ee-text.svg"" alt=""Jakarta EE""><br>
BUILDING AN OPEN SOURCE ECOSYSTEM FOR CLOUD NATIVE ENTERPRISE JAVA
</h1>`

Under the Youtube section header, let's change the text slightly :
The Jakarta EE Youtube channel is a platform that features Jakarta EE related videos aiming to educate the new and existing enterprise java community members about open source, cloud native and microservices technologies.

Under the "Members" header and above the carousel, we can add this line from the membership page. I've added the word enterprise:
Working together, the world’s enterprise Java ecosystem leaders, including Fujitsu, IBM, Oracle, Red Hat, and Tomitribe, are advancing Java EE and Jakarta EE to support moving mission-critical applications and workloads to the cloud.

**Comment by ericpoirier** [comment]
These changes have been implemented on the following staging site:
https://deploy-preview-1267--jakartaee.netlify.app/

Let me know if there's anything else.

**Comment by ericpoirier** [comment]
My PR was merged to the redesign branch.

**Comment by excentrickristy** [comment]
Hi Eric,
I was looking back at this and realized that the change to the h1 in the main banner was missed. We just need to add in the word Enterprise please :)
