### ISSUE TITLE
Order on this page is wrong

### ISSUE THREAD

**Issue by ericpoirier** [jakartaee/jakarta.ee#1272]
While looking at the site after merging the redesign, we noticed that the order on the following page is wrong.

https://jakarta.ee/specifications/platform/

We will need to get that fixed.

**Comment by ivargrimstad** [comment]
It's a common "feature" of sorting by title text, meaning that: 

-  "1" comes before "2" 
- "10" comes before "2" 
- "100" comes before "11"
- ...and so on

We can easily solve it by adding a version parameter to the metadata and sort by it.

**Comment by ericpoirier** [comment]
@ivargrimstad I can fix the order of this page by ordering by date.

https://deploy-preview-1347--jakartaee.netlify.app/specifications/platform/

Do you think we can safely rely on the date or should we concider a different option? Ordering by name is not working since this is what we are actually using on production.

**Comment by ericpoirier** [comment]
@ivargrimstad This is now fixed since we merged the redesign work for the Specifications section.

Let me know if there's anything else.

Thanks.
