### ISSUE TITLE
Please add WildFly Preview WildFly 25.0.0.Final as Jakarta EE 9.1 Full Platform/Web Profile compatible on Java 17

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#1277]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://www.eclipse.org/membership/showMember.php?member_id=731

**A product name and version**

[WildFly Preview 25.0.0.Final](https://wildfly.org/downloads)

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**

Both `Full Platform` + `Web Profile`

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

https://github.com/wildfly/certifications/blob/EE8/images/wildfly-logo-stacked-100px-2132977.zip?raw=true

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Red Hat

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/418 
+ https://github.com/eclipse-ee4j/jakartaee-platform/issues/419 (both are pending approval as were just created today)

**The URL where Compatible Software Product is available for download**

https://wildfly.org/downloads

**Comment by linkfang** [comment]
Hi @ivargrimstad @TanjaObradovic ,
Please preview the changes here:
https://deploy-preview-1279--jakartaee.netlify.app/compatibility/#tab-9_1

**Comment by scottmarlow** [comment]
@linkfang 
Would it make sense to change `Java SE 17` to `Java 17` to be more consistent with other references to the Java version?

I'll update this request to refer to `Java 17` instead of `Java SE 17` to be more consistent with other results shown on https://deploy-preview-1279--jakartaee.netlify.app/compatibility/#tab-9_1

**Comment by linkfang** [comment]
Sure, sounds good!

Please preview the updated version here:
https://deploy-preview-1279--jakartaee.netlify.app/compatibility/#tab-9_1
