### ISSUE TITLE
Please add Thunisoft Application Server V3.0 as Compatible product of Jakarta EE 9.1 Full Platform

### ISSUE THREAD

**Issue by zcwslnh** [jakartaee/jakarta.ee#1280]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://www.eclipse.org/membership/showMember.php?member_id=1481

**A product name and version**

Thunisoft Application Server V3.0

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**

Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

[tas-logo.zip](https://github.com/jakartaee/jakarta.ee/files/5770050/tas-logo.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Beijing Thunisoft Information Technology Co.,Ltd

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

https://github.com/eclipse-ee4j/jakartaee-platform/issues/415

**The URL where Compatible Software Product is available for download**

http://tas.thunisoft.com/download

**Comment by linkfang** [comment]
Hi @ivargrimstad  @TanjaObradovic @zcwslnh ,
Please preview the changes here:
https://deploy-preview-1281--jakartaee.netlify.app/compatibility/#tab-9_1

**Comment by ericpoirier** [comment]
Hi @zcwslnh,

Can we get a +1 on the changes @linkfang has submitted in the previous comment?

Thanks.

**Comment by zcwslnh** [comment]
@ericpoirier Yes, of course.
