### ISSUE TITLE
Add SouJava as a Guest Member 

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#1287]
Please SouJava as a Guest member on the Jakarta EE website: https://jakarta.ee/membership/members/
Thanks,
Zahra
![download](https://user-images.githubusercontent.com/50374570/137503140-6ae18253-f1c2-47bf-bbd5-4a1afa9f0361.png)

**Comment by linkfang** [comment]
Hi @ZahraFazli , 

Please preview here:
https://deploy-preview-1291--jakartaee.netlify.app/membership/members/

I am using https://soujava.org.br/ as their website, correct me if I am wrong. 
Thanks!

**Comment by ZahraFazli** [comment]
Looks good, thanks!
