### ISSUE TITLE
Create Community page

### ISSUE THREAD

**Issue by ericpoirier** [jakartaee/jakarta.ee#1289]
@ericpoirier we would like to create a similar page to the resource page here https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585119 for the "Community" and "Specification" dropdown in the navigation bar so that all the link would land and be anchored to this page first instead of going to the third party website. The objective is to keep the traffic within the Jakarta EE website before driving it to an external page. The boxes content should be the list that we hav on the "Community" and "Specification" dropdown for each of the pages. Please let me know if you need further information to get this going. thanks

_Originally posted by @shabnammayel in https://github.com/jakartaee/jakarta.ee/issues/1236#issuecomment-944391661_

**Comment by ericpoirier** [comment]
In this issue we will be doing the Community page only.

**Comment by shabnammayel** [comment]
@meKokabi Can you please help with the 4 icons required for this page? thanks

**Comment by ericpoirier** [comment]
@shabnammayel I created the Community page based on the requirements but let me know if you'd like to change anything.

Also, not that I used icons that are not related to the titles, @shabnammayel I would suggest you review the sections and let me know if you'd like to add more or remove some and then we can ask @meKokabi to create the icons we need.

https://deploy-preview-1332--jakartaee.netlify.app/community/

Thanks.

**Comment by shabnammayel** [comment]
Please remove the space between Jakarta One. It should be "JakartaOne Livestream" with small s. We should add a text similar to the resource page. 
"Stay Connected": Find the Communication Channels
"JakartaOne Livestream": Find the latest events 
"Adopt a Spec" : Learn about the Adopt a Spec Program
"Techtalk Meet-ups": Find the latest Jakarta Techtalks" link https://www.meetup.com/jakartatechtalks_/
Sign up to host a talk link https://docs.google.com/forms/d/e/1FAIpQLSdbG1FTITUCtzk36N0mc_981rMnuThqFLQMHJg2IFxOTkPoRQ/viewform

**Comment by ericpoirier** [comment]
I updated the community page on staging:

https://deploy-preview-1332--jakartaee.netlify.app/community/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
Looks good! But I think Kristy's comment regarding the icons makes sense. @excentrickristy can you help us with the icons for this page and also the resource page and specification page as well? thanks

**Comment by ericpoirier** [comment]
@shabnammayel Should we also put the blocks in alphabetical order just like we did for the Resources page?

**Comment by shabnammayel** [comment]
Yes @ericpoirier let's have them in alphabetic order both in the dropdown and the blocks

**Comment by excentrickristy** [comment]
> Looks good! But I think Kristy's comment regarding the icons makes sense. @excentrickristy can you help us with the icons for this page and also the resource page and specification page as well? thanks

@shabnammayel is it just the arrows you need from the specifications page? https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585120

**Comment by ericpoirier** [comment]
@shabnammayel I reordered the Community page and the menu items.

https://deploy-preview-1332--jakartaee.netlify.app/community/

Let me know if there's anything else.

**Comment by excentrickristy** [comment]
@shabnammayel should there be a space between Tech Talk Meet-Ups in the box on the page? It has a space in the nav and on the meetup page. I also noticed that we have this box on the Stay Connected page already.

The titles in the boxes need to be promoted to h2 tags but with h3 style which should make the titles a bit bigger (like on the stay connected page).

Title tag: Jakarta EE Community Links | The Eclipse Foundation
Meta description: "Connect with the Jakarta EE community and find opportunities to contribute and participate." 

@ericpoirier I noticed on the live site if you click on Community -> Tech Talk Meetups the link is broken because the new page isn't published yet. You could anchor it to the box on /connect/ instead.

**Comment by shabnammayel** [comment]
+1 to fixing the Tech talk link for now. and other suggestions that Kristy has made. But Kristy and I will have more discussions around this page and the dropdown tomorrow and may suggest further changes. thanks

**Comment by ericpoirier** [comment]
Kristy just shared new icons by email.

Posting them here just to keep track of the assets that were sent for the Community page.
[Jakarta-Icons.zip](https://github.com/jakartaee/jakarta.ee/files/7635357/Jakarta-Icons.zip)

**Comment by ericpoirier** [comment]
@shabnammayel I updated the icons that was provided on the Community page.
https://deploy-preview-1332--jakartaee.netlify.app/community/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
please remove the space between Tech Talk. Also please a box for "Events" that is currently missing from the website https://deploy-preview-1330--jakartaee.netlify.app/community/events/  and add the description "Find the latest Cloud Native Java Events" that should be added in the dropdown. @excentrickristy can you please help us with an icon for that as well? thanks

**Comment by ericpoirier** [comment]
> please remove the space between Tech Talk. Also please a box for "Events" that is currently missing from the website https://deploy-preview-1330--jakartaee.netlify.app/community/events/ and add the description "Find the latest Cloud Native Java Events" that should be added in the dropdown. @excentrickristy can you please help us with an icon for that as well? thanks

We currently have a JakartaOne Livestream section. Can we refactor this section and do something like this:

Event
- Find the latest JakartaOne Livestream (link)
- Find the latest Cloud Native Java Events (link)

This way we won't have to create another icon which we will be missing if we create a new box.

**Comment by shabnammayel** [comment]
Sounds good! Please change the name to Events. @excentrickristy FYI

**Comment by excentrickristy** [comment]
@shabnammayel do you still need an events icon then? or no?

**Comment by shabnammayel** [comment]
Not anymore! :) thanks @excentrickristy

**Comment by ericpoirier** [comment]
@shabnammayel I updated the Community page on staging:

https://deploy-preview-1332--jakartaee.netlify.app/community/

Let me know if there's anything else.

**Comment by shabnammayel** [comment]
LGTM @ericpoirier thanks!

**Comment by excentrickristy** [comment]
@ericpoirier can you remove the space between tech talk in the menu as well to match?

@shabnammayel since videos has been added to the community menu, it should probably be represented on the overview page?

**Comment by ericpoirier** [comment]
> @ericpoirier can you remove the space between tech talk in the menu as well to match?
> 
> @shabnammayel since videos has been added to the community menu, it should probably be represented on the overview page?

I updated the menu item on the following staging page:

https://deploy-preview-1352--jakartaee.netlify.app/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
Apologies @ericpoirier but after taking a look at the meetup page, I noticed that it's actually Tech Talk with a space. Please see https://www.meetup.com/jakartatechtalks_/ 
So can you please make the change for both the dropdown and the box in the overview page? thanks

**Comment by ericpoirier** [comment]
> Apologies @ericpoirier but after taking a look at the meetup page, I noticed that it's actually Tech Talk with a space. Please see https://www.meetup.com/jakartatechtalks_/ So can you please make the change for both the dropdown and the box in the overview page? thanks

Ok will do.

**Comment by ericpoirier** [comment]
@shabnammayel I updated the Tech Talk text

https://deploy-preview-1352--jakartaee.netlify.app/

Let me know if there's anything else.

**Comment by shabnammayel** [comment]
Looks good! but +1 to @excentrickristy we need to add the "videos" to the overview page. do we have an icon for it?

**Comment by ericpoirier** [comment]
> Looks good! but +1 to @excentrickristy we need to add the "videos" to the overview page. do we have an icon for it?

I don't think we do have an icon for that one.

**Comment by ericpoirier** [comment]
@shabnammayel that being said, I did update the staging page using an icon we already have on another Overview page.

https://deploy-preview-1352--jakartaee.netlify.app/community/

Let me know if that works.

Thanks.

**Comment by shabnammayel** [comment]
LGTM, the space between Tech Talk is missing again :) other than that +1 thanks
