### ISSUE TITLE
Create Specification page

### ISSUE THREAD

**Issue by ericpoirier** [jakartaee/jakarta.ee#1290]
@ericpoirier we would like to create a similar page to the resource page here https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585119 for the "Community" and "Specification" dropdown in the navigation bar so that all the link would land and be anchored to this page first instead of going to the third party website. The objective is to keep the traffic within the Jakarta EE website before driving it to an external page. The boxes content should be the list that we hav on the "Community" and "Specification" dropdown for each of the pages. Please let me know if you need further information to get this going. thanks

_Originally posted by @shabnammayel in https://github.com/jakartaee/jakarta.ee/issues/1236#issuecomment-944391661_

**Comment by ericpoirier** [comment]
In this issue we will be creating the Specification page only.

**Comment by shabnammayel** [comment]
@meKokabi Can you please help with the 4 icons required for this page? thanks

**Comment by meKokabi** [comment]
[LineIcons.zip](https://github.com/jakartaee/jakarta.ee/files/7572248/LineIcons.zip)

**Comment by ericpoirier** [comment]
@shabnammayel Looking at this issue and there's already a Specifications page which represents the list of Specifications:
https://jakarta.ee/specifications/

I would suggest we move the Specifications List page to
https://jakarta.ee/specifications/list

And then create a new page for 
https://jakarta.ee/specifications/

Which would display the boxes.

What do you think?

One thing to consider is that whenever we move a page to a different location, we create a redirect so that the old link would still bring people to the same content. In this case here, the Specifications page would still exist but will display different content from what is currently on production.

Let me know if you have a different idea for the structure of  that section.

Thanks.

**Comment by shabnammayel** [comment]
Can we name the page "Browse Specifications" instead of Specifications List? Specifications List might be a bit misleading. and then create a new page called specifications to anchor all the links from the dropdown. Thanks @ericpoirier

**Comment by ericpoirier** [comment]
> Can we name the page "Browse Specifications" instead of Specifications List? Specifications List might be a bit misleading. and then create a new page called specifications to anchor all the links from the dropdown. Thanks @ericpoirier

Ok will do, thanks.

**Comment by ericpoirier** [comment]
@shabnammayel I updated the Specifications section in the following staging page:
https://deploy-preview-1337--jakartaee.netlify.app/specifications/

Note that the Layout of the Browse Specifications page didn't change. In the PR i'm focusing only on reorganising the pages.

Let me know if you'd to make more changes to the structure.

Thanks.

**Comment by shabnammayel** [comment]
For consistency, can we have the boxes in an alphabetic order here as well? Also what is the Overview button that is showing up in the Specifications dropdown? We don't have for other dropdowns such as Community or resources.

**Comment by ericpoirier** [comment]
> For consistency, can we have the boxes in an alphabetic order here as well? Also what is the Overview button that is showing up in the Specifications dropdown? We don't have for other dropdowns such as Community or resources.

Ok no problem for the order.

I you look at the staging pages that I created for both Resources and Community, I'm adding those menu items in there. It was suggested by Kristy for one of the pages so I'm adding it here as well for consistency.

**Comment by shabnammayel** [comment]
+1 sounds good. FYI excentrickristy
