### ISSUE TITLE
HuiNan Asiainfo AnHui new Participant Member

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#1294]
Please add HuiNan Asiainfo AnHui as a Participant member on the Jakarta EE website. 

![HuNan Asiainfo AnHui logo](https://user-images.githubusercontent.com/50374570/138934019-b827e187-c613-42ea-b4e0-69628b10f985.png)

URL: https://www.asiainfo.com/zh_cn/index.html

Thanks,
Zahra

**Comment by linkfang** [comment]
Hi @ZahraFazli ,

Please preview the changes here:
https://deploy-preview-1296--jakartaee.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
+1 Thanks!

**Comment by linkfang** [comment]
NP!
The code is merged and the change will be live shortly
