### ISSUE TITLE
[Add a Triage Contributor to the Repo] Request 

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#1305]
Can you please add me to this repo via Triage feature add?
Please see https://github.com/microprofile/microprofile-wg/wiki/Contributors-GitHub-“Triage”-access to learn how.

Thank you,

**Comment by TanjaObradovic** [comment]
Amelia, as you know we are in the middle of new design implementation for the Jakarta EE website and in general we not like to add new people to the jakartaee/jakarta.ee; however if there are any comments to be made, please feel free to use the jakartaee/collateral to raise issues and tag anyone in MKT team to address it.
