### ISSUE TITLE
Updating the Steering Committee page with alternate for LJC

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1313]
On the Steering Committee page  https://jakarta.ee/committees/steering/ can you please update this line

Martijn Verburg - London Java Community - Elected Participant Member Representative

to this one

Martijn Verburg - London Java Community - Elected Participant Member Representative, Marcelo Ancelmo - alternate

**Comment by linkfang** [comment]
Hi @TanjaObradovic ,

Please preview the change here:
https://deploy-preview-1316--jakartaee.netlify.app/committees/steering/

**Comment by TanjaObradovic** [comment]
Looks great! thanks!
