### ISSUE TITLE
Updating https://jakarta.ee/membership/members/ (Pivotal -> VMWare) 

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1317]
Can we update logo of Pivotal to VMWare? This acquisition happened awhile ago, so we need to correct it? I am hoping you have the VMWare logo already, but let me know if need help with it.

**Comment by linkfang** [comment]
Hi @TanjaObradovic ,

Please preview the change here:
https://deploy-preview-1319--jakartaee.netlify.app/membership/members/

**Comment by TanjaObradovic** [comment]
Looks great! Thanks.
