### ISSUE TITLE
Publishing Steering Committee meeting minutes September & October 2021

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1322]
Can you please publish September and October meeting minutes for the Steering Committee?

[Minutes of the September 14, 2021 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/7572238/Minutes.of.the.September.14.2021.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the September 28, 2021 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/7572239/Minutes.of.the.September.28.2021.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the October 12, 2021 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/7572240/Minutes.of.the.October.12.2021.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the October 26, 2021 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/7572241/Minutes.of.the.October.26.2021.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by linkfang** [comment]
Hi @TanjaObradovic ,

Please preview the changes here:
https://deploy-preview-1323--jakartaee.netlify.app/about/meeting_minutes/#steering_committee

**Comment by TanjaObradovic** [comment]
Looks great! thanks!!

**Comment by linkfang** [comment]
No problem! The changes should be live soon.
