### ISSUE TITLE
Embed membership form on jakarta.ee

### ISSUE THREAD

**Issue by shanda-eclipse** [jakartaee/jakarta.ee#1328]
Similar to https://github.com/EclipseFdn/iot.eclipse.org/issues/666, we would like to embed the contact us form on jakarta.ee.

Here is the code to embed the form:
```
<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	region: "na1",
	portalId: "5413615",
	formId: "92df565f-cf45-49dc-8f2d-f59ebe148d13"
});
</script>
```

CC @shabnammayel

**Comment by linkfang** [comment]
Hi @shanda-eclipse ,

Please preview the embedded form here:
https://deploy-preview-1333--jakartaee.netlify.app/membership/join-us/

The Join Jakarta EE button on membership page and the "Contact us about membership in the Jakarta EE Working Group" link on /about/working-group page will both take the user to this form.

https://deploy-preview-1333--jakartaee.netlify.app/membership/
https://deploy-preview-1333--jakartaee.netlify.app/about/working-group/

**Comment by shanda-eclipse** [comment]
+1 from me. @shabnammayel can you review/approve as well?

**Comment by linkfang** [comment]
Hi @shabnammayel , 

Are we good to go ahead with this change?
https://github.com/jakartaee/jakarta.ee/issues/1328#issuecomment-980079684

**Comment by shabnammayel** [comment]
+1 thanks
