### ISSUE TITLE
Create a dropdown for the Membership button in the navigation bar

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1339]
Members page is missing from the navigation bar. Please add a dropdown on the "Membership" button in the navigation bar and include "Join" that goes to the existing page "Join Jakarta EE Working Group" page https://jakarta.ee/membership/ and also include "Members" that goes to https://jakarta.ee/membership/members/

**Comment by ericpoirier** [comment]
@shabnammayel I updated the menu to create the dropdown to the Membership item.

https://deploy-preview-1341--jakartaee.netlify.app/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
LGTM @ericpoirier ! Thanks
