### ISSUE TITLE
Browse Specifications listed

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/jakarta.ee#1342]
**Describe the bug**

**To Reproduce**
1. Go to https://jakarta.ee/specifications/browse/
2. See error: Browse Specifications is not a specification and should not be listed here

**Expected behavior**
Only specs to be shown

**Screenshots**
![BrowseSpecs](https://user-images.githubusercontent.com/149188/144564232-3d2e3411-fd39-4ff2-865f-b4486125c0a8.png)
.

**Comment by ericpoirier** [comment]
Good catch, i'll make sure to remove this item from the list.

**Comment by ericpoirier** [comment]
A PR was merged to reorganise the hierachy of the Specifications section which removed the Browse Specifications item from the list.
