### ISSUE TITLE
Root URL of the Specifciations List

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/jakarta.ee#1343]
**Describe the bug**
The root URL of the Specification List should be https://jakarta.ee/specifications, not https://jakarta.ee/specifications/browse

- Since the beginning,  /specifications/ has been the location we communicate as the location of the specifications. 
- An extra click to get to the list is unnecessary
- It complicates the navigation back and forth between the specifications (e.g. clicking on the "Specifications" breadcrumb brings you to the root and you have to click browse again to get to the list.
- Browse is treated as a spec (#1342) in the list

**Comment by ericpoirier** [comment]
@ivargrimstad we decided to put the "Overview" page on /specifications top keep things consistent with the other sections of the site.

If we were to put the Specifications List page back to /specifications it would break consitency with other sections.

I don't mind doing the change but I'll leave the decision between you and @shabnammayel.

Also if we are to make the change, what would be the url of the "Overview" page?

Thanks.

**Comment by ivargrimstad** [comment]
> Also if we are to make the change, what would be the url of the "Overview" page?

Anywhere, something else than /specifications/
Then you won't need the special treatment of the browse page to get it out of the list (#1342)

**Comment by shabnammayel** [comment]
@ericpoirier the reason we are creating an overview page is to anchor all external links in Jakarta EE's domain first and drive the traffic to our own page before going to external pages. So to solve this issue, we should move the Specification Projects to the "Resource dropdown" (we can use the same box that we created on the Specification Overview" page currently for the box but in the Resource page instead). Once we do that, all the other links on the Specification dropdown are internal and we won't need an overview page anymore. The Browse Specification URL can be https://jakarta.ee/specifications then. thanks

**Comment by shabnammayel** [comment]
@excentrickristy looks like we don't have an icon for Specification Projects to move it to the "resource page". I was looking at the icons we have to see if we can reuse one of them but it looks like we have used them all in the resource page already! :) Can you please help with that?

**Comment by ericpoirier** [comment]
@shabnammayel @ivargrimstad please review the following staging page and let me know if you'd like to make more changes.

https://deploy-preview-1345--jakartaee.netlify.app/specifications/

Thanks.

**Comment by shabnammayel** [comment]
@ivargrimstad We will keep the name of the button "Browse Specification" instead of "Specification List" in the dropdown. But the URL will be the same as Eric has shared. WDYT?

**Comment by ivargrimstad** [comment]
Yes, great! Thanks!

**Comment by ericpoirier** [comment]
@ivargrimstad @shabnammayel can you review the following staging page and let me know if you'd like to make more changes.

https://deploy-preview-1345--jakartaee.netlify.app/specifications/

**Comment by ericpoirier** [comment]
My PR was merged today. Let me know if there's anything else.

Thanks.

**Comment by excentrickristy** [comment]
@shabnammayel what do you think of this icon?

![image](https://user-images.githubusercontent.com/73264129/144885362-69250465-9cee-4352-95eb-94661f0f0c45.png)

[specification-project.svg.zip](https://github.com/jakartaee/jakarta.ee/files/7662157/specification-project.svg.zip)

**Comment by shabnammayel** [comment]
Thanks @excentrickristy looks good!
