### ISSUE TITLE
Hover State Issue on Nav for Release Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1348]
**Describe the bug**
There is a double underline for the hover state on the release page template.

**To Reproduce**
1. Go to https://jakarta.ee/release/9.1/ 
2. Hover over "About" (or any item) in the main navigation
3. You see two underlines under the navigation 

This issue is for all of the releases pages, so must be part of the CSS for that template.

**Expected behavior**
When you hover over a nav item, you should see one orange line.

**Screenshots**
![image](https://user-images.githubusercontent.com/73264129/144655534-430005cd-6ba4-443e-a81a-fc92938c15d7.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by ericpoirier** [comment]
@shabnammayel @excentrickristy I updated the styles for the Jakarta EE 9.1 menu on staging:

https://deploy-preview-1355--jakartaee.netlify.app/release/9.1/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
LGTM! thanks @ericpoirier
