### ISSUE TITLE
Add the Jakarta EE 9 Specifications image to the Jakarta EE 9 release page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1358]
Hi @ericpoirier 

Can you please add a section in the Jakarta EE 9 release page https://jakarta.ee/release/9/ below the banner and above the features and benefits section and add the shared image below there? 

https://xd.adobe.com/view/5e4a0b3e-7114-4b86-8d19-8f228ddb2c78-0b19/

The image should be added in the middle. thanks

**Comment by ericpoirier** [comment]
Hi @shabnammayel, can you attach the image in a format that we can use on the website such as a jpg, png?

Thanks.

**Comment by shabnammayel** [comment]
@meKokabi can you please help with that? I don't have the latest one in png. thanks

**Comment by meKokabi** [comment]
@ericpoirier Hi Eric, attached includes the png format of the table/chart. For your information, I have made this in  Xd file for accessibility purposes. it has lots of texts and boxes/rows/columns. which could not be readable as image. right?
<img width="884" alt="Jakarta ee 9" src="https://user-images.githubusercontent.com/75500459/146005842-3138dfb4-3d8f-4198-a865-8b7f26aaa596.png">

**Comment by linkfang** [comment]
Hi @shabnammayel ,

I added the image and it is also linked to the XD URL for people who need to view it in a bigger size.
Please preview here:
https://deploy-preview-1360--jakartaee.netlify.app/release/9/

**Comment by shabnammayel** [comment]
LGTM! Can we add the exact image in the 9.1 release page. The only difference will be in the title: Jakarta EE 9.1 Platform and Jakarta EE 9.1 Web Profile. thanks

**Comment by linkfang** [comment]
> LGTM! Can we add the exact image in the 9.1 release page. The only difference will be in the title: Jakarta EE 9.1 Platform and Jakarta EE 9.1 Web Profile. thanks

Cool! 
Hi @meKokabi , can you create a new XD link and give me a .jpg/.png file so that I can add them to 9.1 release page? Thanks!

**Comment by meKokabi** [comment]
Sure! Will do shortly.

**Comment by meKokabi** [comment]
https://eclipse.zoom.us/j/87880876765?pwd=YUc5OG5wc3hYR29iYmZRVUxCdzdaZz09 
<img width="371" alt="Jakarta EE9 1" src="https://user-images.githubusercontent.com/75500459/146574876-5a7b5ace-a40c-48f1-bb97-3ae31c3e0dbe.png">

**Comment by linkfang** [comment]
> https://eclipse.zoom.us/j/87880876765?pwd=YUc5OG5wc3hYR29iYmZRVUxCdzdaZz09 <img alt="Jakarta EE9 1" width="371" src="https://user-images.githubusercontent.com/75500459/146574876-5a7b5ace-a40c-48f1-bb97-3ae31c3e0dbe.png">

Hi Mehrnaz, the link you posted is a zoom link instead of the XD one, can you correct this please, thanks!

**Comment by meKokabi** [comment]
Sorry Here You are:
https://xd.adobe.com/view/cda36cbb-814f-4a38-b78f-0a117307f340-98f0/

**Comment by linkfang** [comment]
> Sorry Here You are: https://xd.adobe.com/view/cda36cbb-814f-4a38-b78f-0a117307f340-98f0/

No problem, thanks for the quick response!

**Comment by linkfang** [comment]
Hi @shabnammayel , please preview the 9.1 here:

https://deploy-preview-1360--jakartaee.netlify.app/release/9.1/

**Comment by shabnammayel** [comment]
LGTM! thanks

**Comment by linkfang** [comment]
Hi @meKokabi , can you give me a .jpg/.png image for Jakarta 9.1 chart with 1768 x 1656 or higher resolution?
As we decided to show a higher resolution image for the chart after click. (which was implemented as an XD link)

Thanks!

**Comment by meKokabi** [comment]
Hi @linkfang Here You Are: 
 
![1768-1656 ](https://user-images.githubusercontent.com/75500459/148087622-def8f7d9-6c8c-4668-9823-f7510175e67b.jpg)

The optimized image:

![Optimized](https://user-images.githubusercontent.com/75500459/148087711-013c1040-d2c6-4691-bf55-40086b8e9f75.jpg)

The XD link:
XD link: https://xd.adobe.com/view/e11fef13-da1c-445e-badf-fb25da5e5fcd-b44c

**Comment by linkfang** [comment]
Thanks @meKokabi !
And can you give me a Jakarta 9 chart in this format?

The previous image has a white padding-right, and I think the format of 9.1 version looks better!
Thanks a lot!

**Comment by meKokabi** [comment]
Hi @linkfang 
Here You Are, the EE 9 jpg and optimized jpg
![Jakarta EE9](https://user-images.githubusercontent.com/75500459/148228539-ab8affaa-1302-44e5-95ef-b5839daaefc8.jpg)
![JakartaEE9Optimized](https://user-images.githubusercontent.com/75500459/148228555-d079048d-2330-4195-9967-5cc45e78c363.jpg)

**Comment by linkfang** [comment]
Awesome! Thanks @meKokabi
