### ISSUE TITLE
Chinese subpages sometimes loading sidebar on pages it shouldn't

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1363]
The sidebar changes column layouts for the page, which results in some broken functionality when it isn't accounted for. This is happening on https://jakarta.ee/zh/membership/, where the Chinese copy has a sidebar that isn't on the English copy. 

Discovered this while reviewing #1362.

**Comment by laliwa** [comment]
Is there anything I should do with this?

**Comment by autumnfound** [comment]
No, we can look into this, though it may take some time as I'm the only one in for the next 2 days and then we're all off until the new year. I'll see if I can get it done today

**Comment by ericpoirier** [comment]
@autumnfound other then the membership page, did you notice any other pages where this issue occurs?

Thanks.
