### ISSUE TITLE
Remove the old sidebars from pages

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1364]
please remove the old sidebars from the following pages:

https://jakarta.ee/membership/members/
https://jakarta.ee/community/events/
https://jakarta.ee/committees/specification/guide/
https://jakarta.ee/about/jesp/
https://jakarta.ee/legal/trademark_guidelines/
https://jakarta.ee/committees/

**Comment by ericpoirier** [comment]
@shabnammayel I updated the sidebars on the following staging page:
https://deploy-preview-1369--jakartaee.netlify.app/

Please review and let me know if you'd like me to change anything else.

Thanks.

**Comment by shabnammayel** [comment]
The only page that still has the sidebar is the events page https://jakarta.ee/community/events/ other than that LGTM! thanks

**Comment by ericpoirier** [comment]
> The only page that still has the sidebar is the events page https://jakarta.ee/community/events/ other than that LGTM! thanks

The sidebar on the events page is new and was provided in the redesign I didn't think you'd want to remove it. Which part of the sidebar you'd like to remove?

**Comment by shabnammayel** [comment]
I reached out to Kristy as well and we think the side bar "Overview" table should go. That will be more consistent with our current design on all other pages as well.

**Comment by ericpoirier** [comment]
@shabnammayel The overview sidebar was removed from the Events page on the following staging page.

https://deploy-preview-1369--jakartaee.netlify.app/community/events/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
LGTM! thanks
