### ISSUE TITLE
Please update and remove RedHat from the Jakarta EE Committees list

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1367]
Please remove RedHat representatives from the Jakarta EE Committees here https://jakarta.ee/committees/

Marketing Committee: John Clingan - Red Hat https://jakarta.ee/committees/marketing/
Specification Committee: Scott Stark - Red Hat, Mark Little - alternate https://jakarta.ee/committees/specification/
Steering Committee: Mark Little - Red Hat, Scott Stark - alternatehttps://jakarta.ee/committees/steering/

Thanks

**Comment by linkfang** [comment]
Hi @shabnammayel , please preview the changes here:

https://deploy-preview-1368--jakartaee.netlify.app/committees/marketing/
https://deploy-preview-1368--jakartaee.netlify.app/committees/specification/
https://deploy-preview-1368--jakartaee.netlify.app/committees/steering/

**Comment by shabnammayel** [comment]
LGTM! thanks
