### ISSUE TITLE
Remove Jelastic from the Jakarta EE Website

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#1374]
Jelastic is no longer a foundation member. Kindly remove their logo from the members page on Jakarta EE website: https://jakarta.ee/membership/members/

**Comment by linkfang** [comment]
Hi @ZahraFazli , do we also need to remove Jelastic from the testimonials section?
![image](https://user-images.githubusercontent.com/43075439/149025283-45ca09a6-2654-4eb6-89d1-c1dda4bc42d9.png)

**Comment by linkfang** [comment]
Please preview the change here:

https://deploy-preview-1377--jakartaee.netlify.app/membership/members/

I haven't removed it from testimonials section. Let me know if we need to do so.

**Comment by chrisguindon** [comment]
//cc @shabnammayel @ZahraFazli,

Please see @linkfang question ^^. We would like to know if we now need to remove their testimonial!

**Comment by shabnammayel** [comment]
+1 Please remove their testimonial as well.

**Comment by linkfang** [comment]
Cool, here is the updated version (removed their testimonial)
https://deploy-preview-1377--jakartaee.netlify.app/

Membership page:
https://deploy-preview-1377--jakartaee.netlify.app/membership/members/

**Comment by shabnammayel** [comment]
LGTM! thanks
