### ISSUE TITLE
Remove Jelastic's representative from the Jakarta EE Marketing Committee list on the Website

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1375]
Please remove Jelastic's representative from the Jakarta EE Marketing Committee's list on the Website:
Marketing Committee: Tetiana Fydorenchyk https://jakarta.ee/committees/marketing/

Thanks

**Comment by linkfang** [comment]
Hi @shabnammayel , please preview the change here:

https://deploy-preview-1377--jakartaee.netlify.app/membership/members/

**Comment by linkfang** [comment]
Hi @shabnammayel , please preview the change here:

https://deploy-preview-1377--jakartaee.netlify.app/committees/marketing/
