### ISSUE TITLE
Red Hat is now Enterprise member

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1378]
Can we update and move Red Hat into Enterprise member category? 
https://jakarta.ee/membership/members/

Also please remove Red Hat the carousel on the home page as well
https://jakarta.ee/

**Comment by linkfang** [comment]
Hi @TanjaObradovic ,

Please preview the changes here:

carousel: https://deploy-preview-1379--jakartaee.netlify.app/
members page: https://deploy-preview-1379--jakartaee.netlify.app/membership/members/

**Comment by TanjaObradovic** [comment]
looks great, thanks!
