### ISSUE TITLE
Open Liberty 21.0.0.12 as a Compatible Software Product for Jakarta EE 9.1

### ISSUE THREAD

**Issue by brideck** [jakartaee/jakarta.ee#1380]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Brian Decker - IBM - Eclipse Profile](https://accounts.eclipse.org/users/bdeckerhdt)

**A product name and version**
[Open Liberty 21.0.0.12](https://openliberty.io/)

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Both Web Profile and Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[https://openliberty.io/certifications/assets/OL_logomark.zip](https://openliberty.io/certifications/assets/OL_logomark.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[IBM Corporation](https://www.ibm.com/)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Web Profile, Java 8: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/442](https://github.com/eclipse-ee4j/jakartaee-platform/issues/442)
Web Profile, Java 11: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/443](https://github.com/eclipse-ee4j/jakartaee-platform/issues/443)
Web Profile, Java 17: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/444](https://github.com/eclipse-ee4j/jakartaee-platform/issues/444)
Full Platform, Java 8: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/445](https://github.com/eclipse-ee4j/jakartaee-platform/issues/445)
Full Platform, Java 11: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/446](https://github.com/eclipse-ee4j/jakartaee-platform/issues/446)
Full Platform, Java 17: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/447](https://github.com/eclipse-ee4j/jakartaee-platform/issues/447)

**The URL where Compatible Software Product is available for download**
[https://openliberty.io/start/#runtime_releases](https://openliberty.io/start/#runtime_releases)

**Comment by brideck** [comment]
Note that this listing should supersede the previous one for the Open Liberty Beta release.

Also, note that this request contains a different logo file than the previous request.  We would like to use this new one instead.

**Comment by linkfang** [comment]
Hi @brideck , @ivargrimstad , @TanjaObradovic ,

Please preview the changes here:
https://deploy-preview-1381--jakartaee.netlify.app/compatibility/#tab-9_1

**Comment by brideck** [comment]
> Hi @brideck , @ivargrimstad , @TanjaObradovic ,
> 
> Please preview the changes here: https://deploy-preview-1381--jakartaee.netlify.app/compatibility/#tab-9_1

Is there a way to have the three links for the different Java versions be on three separate lines for each section?  That list is pretty hard to read as-is, unless you luck into the right browser width.

**Comment by linkfang** [comment]
Sure, please preview the change here:
https://deploy-preview-1381--jakartaee.netlify.app/compatibility/#tab-9_1

**Comment by brideck** [comment]
Looks great to me.  Thanks!

**Comment by ivargrimstad** [comment]
LGTM +1
