### ISSUE TITLE
Adding Emily Jiang as alternate on the Spec Committee

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1382]
Can you please update 
https://jakarta.ee/committees/specification/
Under Committee Members for IBM line 

Please have
Tom Watson - IBM, Emily Jiang - alternate

Instead 
Kevin Sutter - IBM, Tom Watson - alternate

**Comment by linkfang** [comment]
Hi @TanjaObradovic ,
Please preview the change here:
https://deploy-preview-1384--jakartaee.netlify.app/committees/specification/

**Comment by TanjaObradovic** [comment]
Looks great! Thanks!
