### ISSUE TITLE
Add the new Cloud Native Java eBook to the website

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1390]
Please add the new Cloud Native Java eBook to the resource page here: https://jakarta.ee/resources/#ebooks

The name should be added to the ebook section above the current one as: How Jakarta EE Delivers on the Vision for Open Source, Cloud Native Java

the URL: https://outreach.jakartaee.org/open-source-cloud-native-java-ebook?hs_preview=vUXuuJeF-64105276785

Thanks

**Comment by linkfang** [comment]
Hi @shabnammayel , please preview the change here:
https://deploy-preview-1396--jakartaee.netlify.app/resources/#ebooks

**Comment by shabnammayel** [comment]
LGTM! thanks @linkfang
