### ISSUE TITLE
Please update Payara alternate for Jakarta EE Steering Committee 

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1391]
On the page https://jakarta.ee/committees/steering/
under 
_Committee Members_

Please replace Eliot Martin with  Hadar Vorenshtein 

It should look like this
Steve Millidge - Payara, Hadar Vorenshtein - alternate

**Comment by ericpoirier** [comment]
Hi @TanjaObradovic, please review the following changes:

https://deploy-preview-1394--jakartaee.netlify.app/committees/steering/

Thanks.

**Comment by TanjaObradovic** [comment]
Looks great!

**Comment by ericpoirier** [comment]
This was merged.

Thanks.
