### ISSUE TITLE
Increase the font size on the navigation bar

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1392]
Can you please increate the font size on the navigation bar of the website? it is too small. thanks

**Comment by shabnammayel** [comment]
Also can you please move the blog button under the community drop down and replace it with the resources button to the main navigation bar since there are many items and useful resources under the resources dropdown which are currently very difficult to find.

**Comment by ericpoirier** [comment]
@shabnammayel please review the following staging page:

https://deploy-preview-1395--jakartaee.netlify.app/

I updated the font size in the menu and moved the menu items.

Let me know if there's anything else.

**Comment by shabnammayel** [comment]
Thanks @ericpoirier the font size of the navigation bar definitely looks better and is more visible now!

minor edit: please move the blog in the "Community" dropdown to the top below "Adopt a spec" as I believe that dropdown is on an alphabetic order. 

Thanks

**Comment by ericpoirier** [comment]
> Thanks @ericpoirier the font size of the navigation bar definitely looks better and is more visible now!
> 
> minor edit: please move the blog in the "Community" dropdown to the top below "Adopt a spec" as I believe that dropdown is on an alphabetic order.
> 
> Thanks

@shabnammayel I updated the order of the Community dropdown

https://deploy-preview-1395--jakartaee.netlify.app/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
LGTM! Thanks @ericpoirier
