### ISSUE TITLE
Publishing Steering Committee Meeting minutes

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1398]
Can you please publish Steering Committee Meeting minutes?

https://jakarta.ee/committees/steering/

[Minutes of the Jan 11, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8024115/Minutes.of.the.Jan.11.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the November 30, 2021 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8024116/Minutes.of.the.November.30.2021.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the December 14, 2021 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8024117/Minutes.of.the.December.14.2021.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by linkfang** [comment]
Hi @TanjaObradovic ,

Please preview the updates here:
https://deploy-preview-1400--jakartaee.netlify.app/committees/steering/

**Comment by TanjaObradovic** [comment]
looks great! thanks!!

**Comment by linkfang** [comment]
NP! The changes should be live soon! (around 15 mins)
