### ISSUE TITLE
Publish the previous Marketing Committee Meeting Mins

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1399]
Please publish the following Marketing Committee Meeting Mins:
[Jakarta EE Marketing Committee Meeting - January 20, 2022 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/8024523/Jakarta.EE.Marketing.Committee.Meeting.-.January.20.2022.11_00.ET.pdf)
[Jakarta EE Marketing Committee Meeting -January 6, 2022 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/8024524/Jakarta.EE.Marketing.Committee.Meeting.-January.6.2022.11_00.ET.pdf)
[Jakarta EE Marketing Committee Meeting - December 9, 2021 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/8024525/Jakarta.EE.Marketing.Committee.Meeting.-.December.9.2021.11_00.ET.pdf)

And I just noticed that the last meeting mins in November 18, 2021 is wrongly published as November 30 here: https://jakarta.ee/about/meeting_minutes/ 

Please change that to November 18, 2021 as mentioned in the mins doc as well: 
https://jakarta.ee/about/meeting_minutes/marketing_committee/minutes-marketing-1118-2021.pdf

Thank you

**Comment by linkfang** [comment]
Hi @shabnammayel ,

Please preview the updates here:
https://deploy-preview-1400--jakartaee.netlify.app/committees/marketing/

**Comment by shabnammayel** [comment]
LGTM! thanks

**Comment by linkfang** [comment]
NP! The changes should be live soon! (around 15 mins)
