### ISSUE TITLE
Page "https://jugpe.com.br/" doesn't exist: Request to send us the right URL of "JUG PE".

### ISSUE THREAD

**Issue by DmitriGit** [jakartaee/jakarta.ee#1401]
Hello,

1) on the page "[https://jakarta.ee/specifications/jsonp/](https://urldefense.com/v3/__https:/jakarta.ee/specifications/jsonp/__;!!ACWV5N9M2RV99hQ!bx4hE0SK8SQPNEwhO4GxkGNXJul6mXaq8R2Vok-vgsN5sxFN52a6XcPc75glYi-UT7SX$)" ("Jakarta EE JSON Processing" project's page) a link to "JUG PE" (see the image "JUG PE") point to a site that doesn't exists - I have "Page doesn't exists" when click on it,

2) the same problem is also on the "https://jakarta.ee/community/adopt-a-spec/" page: if you click on "JUG PE" image, then will be displayed "Page doesn't exists".

Can "JUG PE" site send us the right URL ?

Thank you,
Dmitri.

**Comment by ericpoirier** [comment]
@shabnammayel would you know how we can get the proper url for JUG PE?

Thanks.

**Comment by ivargrimstad** [comment]
Maybe @vinyfalcao can help?

**Comment by TanjaObradovic** [comment]
Until we hear from  @vinyfalcao  or maybe @otaviojava, we can use this link https://www.linkedin.com/in/jug-pe-713ab1191/?originalSubdomain=br

**Comment by linkfang** [comment]
The link has been set to the LinkedIn page for now, please preview the change here:

https://deploy-preview-1405--jakartaee.netlify.app/specifications/jsonp/
https://deploy-preview-1405--jakartaee.netlify.app/community/adopt-a-spec/

**Comment by vinyfalcao** [comment]
Hello everyone, it was a domain expired problem, we already renew and update the DNS in the host provides, in the next hours should work again...
Sorry about it :(

**Comment by ivargrimstad** [comment]
Works fine now. Thanks!
