### ISSUE TITLE
Create a html page for the old Cloud native Java eBook on Jakarta EE's domain

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1408]
Can you please create an html page for the old CNJ eBook and add that to the resource dropdown of the website under the eBooks section here: https://jakarta.ee/resources/#ebooks 
It should go under the : Charting a Course for Cloud Native Java
Please provide both the link to the landing page to download the ebook as it is: (https://outreach.jakartaee.org/cloud-native-java-ebook) and then add the link to the html page once created.

Here is the link to the pdf version of the ebook to use and create the page: 
https://drive.google.com/drive/u/0/folders/10zS1TiMr33AGH_6tu6WmgKsGutE8ngtC
thanks

**Comment by ericpoirier** [comment]
@shabnammayel can you provide a text version of the ebook?

Thanks.

**Comment by ericpoirier** [comment]
@shabnammayel is there a reason why we need to create an html version of that PDF?

**Comment by shabnammayel** [comment]
@ericpoirier here is the text version of the ebook: https://docs.google.com/document/d/1mP3jK-zka5NngqOt4KIwBhEV7dYVWGPtp6Fh6jJJ3nw/edit

and yes we want to improve our rankings for our main keywords such as Cloud native Java, Java EE and Enterprise Java. Publishing the ebook on Jakarta's domain is going to help us with that.

**Comment by ericpoirier** [comment]
@shabnammayel I added the CNJ page to the following staging page:

https://deploy-preview-1411--jakartaee.netlify.app/resources/ebook/cnj/

I also added a link to the Resources page.

Let me know if there's anything else.

**Comment by shabnammayel** [comment]
LGTM @ericpoirier thanks
