### ISSUE TITLE
Highlighting JakartaOne Livestream 

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1412]
On the https://jakarta.ee/ we need to introduce a couple of changes
![image](https://user-images.githubusercontent.com/40073121/154494589-4a74f17d-bce7-4e6c-874e-f43813ec2e96.png)

we need to add JakartaOne Livestream menu item.

To do so we need to add under Overview menu choice / section / page another box that will be dedicated to JakartaOne Livestream, like so

![image](https://user-images.githubusercontent.com/40073121/154496255-110774d3-e66e-469b-924c-474fb40d0907.png)
 
 and correct the current event box
 
![image](https://user-images.githubusercontent.com/40073121/154496447-706c9d2e-9e45-43eb-95d8-ab38399a77a7.png)

**Comment by ericpoirier** [comment]
Hi @meKokabi, would it be possible for you to provide a new icon for this new section?

Thanks.

**Comment by meKokabi** [comment]
@ericpoirier Absolutely! will do and come back to you shortly.

**Comment by meKokabi** [comment]
Sorry @ericpoirier  can you please clarify where/which section we want to have the icon, for sake of creating a consistent sizing/look.

**Comment by ericpoirier** [comment]
Tanja would like to add a new section on the Community page:

https://jakarta.ee/community/

This new section would list the JakartaOne Livestreams.

**Comment by meKokabi** [comment]
@ericpoirier Please find attached folder. I have prepared 3 options for Tanja to choose from. Let me know if I missed anything.
[Jakarta LiveStreamIcon.zip](https://github.com/jakartaee/jakarta.ee/files/8120095/Jakarta.LiveStreamIcon.zip)

**Comment by ericpoirier** [comment]
@TanjaObradovic can you have a look at the icons that @meKokabi provided and let us know which one you would like us to use on the website?

Thanks.

**Comment by TanjaObradovic** [comment]
Wow! Thanks @meKokabi! Hard to to decide! I like the sailing boat the best. @shabnammayel do you have any input?

**Comment by shabnammayel** [comment]
Agreed! I think b.svg matches the style of that page best. thanks @meKokabi

**Comment by meKokabi** [comment]
> Wow! Thanks @meKokabi! Hard to to decide! I like the sailing boat the best. @shabnammayel do you have any input?

My pleasure!

**Comment by ericpoirier** [comment]
Please review the following staging page:

https://deploy-preview-1414--jakartaee.netlify.app/community/

Let me know if you'd like to change anything.

Thanks.

**Comment by TanjaObradovic** [comment]
Looks great to me, however maybe another little thing to add :)

Can we add another bulletin point in the JakartaOne Livestream box?

![image](https://user-images.githubusercontent.com/40073121/155383171-630bb4a4-cb3b-4150-82bf-880f895a7c7c.png)


* Find out how to host a JakartaOne Livestream in your own language 

and link it to this link
https://jakartaone.org/documents/jakartaone-language-host-process.pdf

**Comment by ericpoirier** [comment]
@TanjaObradovic I updated the Community page on staging:

https://deploy-preview-1414--jakartaee.netlify.app/community/

Let me know if there's anything else.

Thanks.

**Comment by TanjaObradovic** [comment]
Thanks - looks good!

**Comment by TanjaObradovic** [comment]
@ericpoirier 
can we please add JakartaOne Livestream menu item in the main drop down from the begging of the thread?
https://user-images.githubusercontent.com/40073121/154494589-4a74f17d-bce7-4e6c-874e-f43813ec2e96.png

The menu item should point to jakartaone.org

**Comment by ericpoirier** [comment]
> @ericpoirier can we please add JakartaOne Livestream menu item in the main drop down from the begging of the thread? https://user-images.githubusercontent.com/40073121/154494589-4a74f17d-bce7-4e6c-874e-f43813ec2e96.png
> 
> The menu item should point to jakartaone.org

@TanjaObradovic please review the following staging page:

https://deploy-preview-1425--jakartaee.netlify.app/

I added the menu item.

**Comment by TanjaObradovic** [comment]
This looks good to me! Thanks Eric.

@shabnam please see, we probably need to do similar for Tech Talks meet-ups.

**Comment by TanjaObradovic** [comment]
I am sorry Eric, but I found another bit.

Once you go into Overview menu item, the JakartaOne Livestream title in orange should also be a link to jakartaone.org

![image](https://user-images.githubusercontent.com/40073121/156776295-2de9d690-b855-45b4-b458-bec5745464a9.png)

**Comment by ericpoirier** [comment]
> I am sorry Eric, but I found another bit.
> 
> Once you go into Overview menu item, the JakartaOne Livestream title in orange should also be a link to jakartaone.org
> 
> ![image](https://user-images.githubusercontent.com/40073121/156776295-2de9d690-b855-45b4-b458-bec5745464a9.png)

Ok I added that to my PR.

**Comment by TanjaObradovic** [comment]
thx! looks great!
