### ISSUE TITLE
Create a Releases page on Jakarta EE website

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1413]
Please create a "Releases" page that lists all of Jakarta EE releases and replace it with the existing link on the "About" dropdown on navigation bar that goes to Jakarta EE 9.1 release page.

Here is the mockup for the page: https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/463539587/comments

Please see the comments on the mockup page for the content.

Thanks

**Comment by ericpoirier** [comment]
Hi @shabnammayel,

Please review the following staging page:

https://deploy-preview-1416--jakartaee.netlify.app/release/

Let me know if there's anything else.

Thanks.

**Comment by ericpoirier** [comment]
After talking to @shabnammayel on a call, I will be making changes to the title and description parameters so they align with the content in the mockup and i will create a new parameter to add the subtitle.

The content can be found in the press release pages of each releases.

**Comment by ericpoirier** [comment]
@shabnammayel I updated the Release page:

https://deploy-preview-1416--jakartaee.netlify.app/release/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment]
LGTM! thanks @ericpoirier
