### ISSUE TITLE
Update on Compatible Products page is needed - GlassFish link

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1415]
Can you please update on https://jakarta.ee/compatibility/download/ page Eclipse GlassFish entry?

![image](https://user-images.githubusercontent.com/40073121/155396580-5e626aa1-01de-4d3e-8573-b6c7540ce329.png)

Instead 
[6.1 RC1](https://download.eclipse.org/ee4j/glassfish/glassfish-6.1.0-RC1.zip)

It should be 
[6.1](https://download.eclipse.org/ee4j/glassfish/glassfish-6.1.0.zip)

**Comment by ericpoirier** [comment]
@TanjaObradovic by looking at the following file: 

https://github.com/jakartaee/jakarta.ee/blob/850991d0cde911a05b8f3ff67b3414e3604ec997/data/compatible_products.yml#L34

I see that there is 2 separate links for the 6.1 RC1 version (compatibility and download_url). Can you provide both links so that we can replace them both?

Thanks.

**Comment by TanjaObradovic** [comment]
yes the link for the TCK 6.1 results is 

https://glassfish.org/certifications/jakarta-web-profile/9.1/TCK-Results-6.1

**Comment by linkfang** [comment]
Hi @TanjaObradovic, are we going to update the entry for both web and platform?

If so, can you confirm if the download URL would be the same for both, and the TCK 6.1 for platform is:
https://glassfish.org/certifications/jakarta-platform/9.1/TCK-Results-6.1 ?

**Comment by TanjaObradovic** [comment]
yes, please update  the entry for both web and platform and use the same links. Thanks!

**Comment by linkfang** [comment]
Cool, please preview the changes here:
https://deploy-preview-1426--jakartaee.netlify.app/compatibility/download/

**Comment by TanjaObradovic** [comment]
looks great! thanks!

**Comment by linkfang** [comment]
NP! The change is live now!
