### ISSUE TITLE
Add the Jakarta EE presentations on the website

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1417]
Please add the Jakarta EE Community Update presentation deck on the homepage in the "Get Informed" box below the "Get Specification" bulletin. Add it as "Jakarta EE Presentation" 
link:
https://docs.google.com/presentation/d/1LBjjJg64j0HjmFu6m3EApN--mkavemyPFMUobIbGZds/edit#slide=id.g10a8950dfd6_0_139
Also please add it to the resource overview page under presentations, please change the current item "Jakarta EE Presentations" to "Jakarta EE Presentation" and replace the link with the one I provided above.

Also please add the following presentation template on the resource overview page under presentations below the Jakarta EE Presentation:

Jakarta EE Presentation Template: 
https://docs.google.com/presentation/d/1fqsJOvWmwbtPeTu3pcEJAfsOb1pLdnN-YPsBpD7fouo/edit#slide=id.g10a8950dfd6_0_139

Also I just noticed when you click on "presentations" on the resource dropdown, it takes you to the footer of the overview page instead of the proper section on that page.

**Comment by linkfang** [comment]
Hi @shabnammayel , please preview the updates here:

https://deploy-preview-1419--jakartaee.netlify.app/
https://deploy-preview-1419--jakartaee.netlify.app/resources/#presentations

And for the "presentations" will navigate to footer issue, it only happens on production site with Chrome browser (both Edge and Firefox work on my end). 
I did make a fix to it, but we will only know if it works after we make the change live.

If it is not working, we can make a separate issue for it and try some other solutions.

**Comment by shabnammayel** [comment]
Thanks @linkfang LGTM! and the issue seems to be fixed as well! Thank you!

**Comment by ericpoirier** [comment]
@shabnammayel is there a reason why we are using google docs instead of a PDF for example?

**Comment by shabnammayel** [comment]
yes, We make regular updates to these presentations and want to be directly reflected on the site

**Comment by linkfang** [comment]
NP! The changes are now live!
