### ISSUE TITLE
Fix the alignment of the lines in the boxes on the Get listed page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1418]
Please fix the alignment of lines in the boxes of the Get listed page here: https://jakarta.ee/compatibility/get-listed/ thanks

**Comment by ericpoirier** [comment]
@shabnammayel please review the following page where i'm fixing the spacing in the cards.

https://deploy-preview-1422--jakartaee.netlify.app/compatibility/get-listed/

Thanks.

**Comment by shabnammayel** [comment]
Looks good! Thanks @ericpoirier
