### ISSUE TITLE
Adding alternate for Payara on the Specification Committee

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1424]
Can you please add Petr Aubrecht on https://jakarta.ee/committees/specification/ page for Payara?

The line 

Andrew Pielage - Payara

should be 

Andrew Pielage - Payara, Petr Aubrecht - alternate

**Comment by linkfang** [comment]
Hi @TanjaObradovic , please preview the change here:
https://deploy-preview-1427--jakartaee.netlify.app/committees/specification/

**Comment by TanjaObradovic** [comment]
looks great! thx!

**Comment by linkfang** [comment]
NP! The change is live now!
