### ISSUE TITLE
Please add xigemaAS 9.1 as Compatible product of Jakarta EE 8 Full Platform

### ISSUE THREAD

**Issue by vsettanTCK** [jakartaee/jakarta.ee#1430]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=1557

**A product name and version**
xigemaAS 9.1

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/vsettanTCK/vsettan-tck/blob/main/xigemaAS.zip

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Beijing Vsettan Data Technology Co. Ltd.

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/472

**The URL where Compatible Software Product is available for download**
http://www.vsettan.com.cn/7752.html

**Comment by linkfang** [comment]
Hi @TanjaObradovic , @ivargrimstad , please preview the changes here:

https://deploy-preview-1431--jakartaee.netlify.app/compatibility/
https://deploy-preview-1431--jakartaee.netlify.app/compatibility/certification/8/
https://deploy-preview-1431--jakartaee.netlify.app/compatibility/download/

**Comment by vsettanTCK** [comment]
thanks a lot @ericpoirier , @linkfang , @TanjaObradovic , @ivargrimstad

**Comment by TanjaObradovic** [comment]
looks great! thanks!!

**Comment by linkfang** [comment]
NP! The change is now live!
