### ISSUE TITLE
Add Beijing Vsettan Data Technology Co. Ltd. as a Participant Member

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#1433]
Beijing Vsettan Data Technology Co. Ltd. is a new Participant Member of the Jakarta EE Working Group. 
Please add the attached logo to the website: https://jakarta.ee/membership/members/
![华胜信泰logo-透明底](https://user-images.githubusercontent.com/50374570/158400371-978e8443-6c9d-498c-b962-1fa6db5a6d13.png)
Thanks!

**Comment by vsettanTCK** [comment]
Thanks a lot! @ZahraFazli

**Comment by linkfang** [comment]
Hi @ZahraFazli , please preview the change here:
https://deploy-preview-1434--jakartaee.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
Looks good! Thanks!

**Comment by linkfang** [comment]
NP! The change is now live!
