### ISSUE TITLE
Add my Survey blog to the Jakarta EE blog section

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1435]
Please add my blog re the 2022 Jakarta EE developer survey in the blog section of the website here: 

https://jakarta.ee/blogs/

Blog Content to use: https://docs.google.com/document/d/1YJmFZGx7PJpNbJKknLQTHLByG7O6FsHtuyjXB0j11z4/edit

thanks

**Comment by linkfang** [comment]
Hi @shabnammayel , please preview the change here:
https://deploy-preview-1437--jakartaee.netlify.app/blogs/
https://deploy-preview-1437--jakartaee.netlify.app/blogs/the-2022-jakarta-ee-developer-survey-is-now-open/
