### ISSUE TITLE
Please publish my blog to https://jakarta.ee/news

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1436]
Please publish my blog at 
https://jakarta.ee/news

Please replace the placeholder text by the proper content.

https://docs.google.com/document/d/1qvaS03uelTYW8Jf7xuIQZ6f4r3nONZpeBHq-0v9ipbA/edit

or from unpublished blog

https://blogs.eclipse.org/post/tanja-obradovic/welcome-beijing-vsettan-data-technology-co-ltd-jakarta-ee-working-group

**Blog post information**
title: Welcome Beijing Vsettan Data Technology Co. Ltd. to the Jakarta EE Working Group!
date: Monday, March 21, 2022 
summary: Let me share good news and welcome Beijing Vsettan Data Technology Co. Ltd. as  a participant member of the Jakarta EE working group!
content: Let me share good news and welcome Beijing Vsettan Data Technology Co. Ltd. as  a participant member of the Jakarta EE working group. It is great to see continuous growth of the working group and I am looking forward to Beijing Vsettan Data Technology Co. Ltd contributions and collaboration with other members.

Beijing Vsettan Data Technology Co. Ltd.(a.k.a Vsettan) is a high-end basic software service provider that can provide database and middleware products and services at the same time. Vsettan focuses on providing industry users with xigema series basic software with high performance, high stability, high availability and high security, and meets the requirements of core business systems in finance, telecommunications, government, energy, transportation, retail and other industries. Vsettan has established good cooperative relations with more than 100 partners in related industries such as CPU, server, operating system and industrial applications.

**Comment by linkfang** [comment]
Hi @TanjaObradovic , please preview the update here:

https://deploy-preview-1446--jakartaee.netlify.app/news/
https://deploy-preview-1446--jakartaee.netlify.app/news/welcome-beijing-vsettan-data-technology-co-ltd-jakarta-ee-working-group/

**Comment by TanjaObradovic** [comment]
Yes!!! many thanks!

**Comment by linkfang** [comment]
NP! The changes are now live!
