### ISSUE TITLE
Change the showing product name and logo of xigemaAS in in jakarta EE compatible list on website https://jakarta.ee

### ISSUE THREAD

**Issue by vsettanTCK** [jakartaee/jakarta.ee#1439]
**Is your feature request related to a problem? Please describe.**
I have submitted the issue: https://github.com/jakartaee/jakarta.ee/issues/1430, now I can see our product xigemaAS is being showed in jakarta EE compatible list on website https://jakarta.ee/, but the product name and logo do not contain our company information, which is not conducive to the marketing of our company and our product, so we want to change them.

**Describe the solution you'd like**
Please help us change the product name and logo of xigemaAS being showed in jakarta EE compatible list, where I can see at least in the following pages:
https://jakarta.ee/compatibility/
https://jakarta.ee/compatibility/certification/8/
https://jakarta.ee/compatibility/download/

1. product name change: 
from: xigemaAS
to: xigema Application Server

2. product logo change:
from: https://github.com/vsettanTCK/vsettan-tck/blob/main/xigemaAS.zip
to: https://github.com/vsettanTCK/vsettan-tck/blob/main/xigemaAS-updated.zip

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by linkfang** [comment]
Hi @vsettanTCK , please preview the change here:

https://deploy-preview-1447--jakartaee.netlify.app/compatibility/

**Comment by vsettanTCK** [comment]
looks great! thanks!  @linkfang

**Comment by linkfang** [comment]
No problem! The change is now live!
