### ISSUE TITLE
Please publish my "Even closer to Jakarta EE 10!" blog to https://jakarta.ee/news

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1440]
Please publish my blog at
https://jakarta.ee/news

Please use text from here
https://blogs.eclipse.org/post/tanja-obradovic/welcome-beijing-vsettan-data-technology-co-ltd-jakarta-ee-working-group

**Blog post information**
title: 
Even closer to Jakarta EE 10!
date: 
Monday, March 21, 2022
summary: 
The Release Review for Jakarta EE 10 is now completed for the additional specifications!
content:
The Jakarta EE community is completely focused on execution of the [Jakarta EE 10 release plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee10/JakartaEE10ReleasePlan). Following the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/) we are seeing the progress of the individual specifications. In addition to the previous blog, we now have the Release Review completed for the following specifications

[Jakarta SOAP with Attachments 3.0](https://jakarta.ee/specifications/soap-attachments/3.0/) - https://github.com/jakartaee/specifications/pull/444
[Jakarta JSON Binding 3.0](http://jakarta.ee/specifications/jsonb/3.0/) - https://github.com/jakartaee/specifications/pull/456
[Jakarta Batch 2.1](https://jakarta.ee/specifications/batch/2.1/) - https://github.com/jakartaee/specifications/pull/438
We are expecting more progress in the upcoming weeks! Stay tuned, or monitor[ progress on individual specifications release reviews](https://github.com/jakartaee/specifications/pulls?q=is%3Apr+is%3Aopen)!

Please see [the other specifications with completed Release Review](https://blogs.eclipse.org/post/tanja-obradovic/getting-closer-jakarta-ee-10-release).

**Comment by TanjaObradovic** [comment]
Can you please publish this one by March 24th? Many thanks!!!

**Comment by linkfang** [comment]
Hi @TanjaObradovic , no problem! Working on it now.

And for the blog, I assume you shared a wrong link? Could it be this one instead? 
https://blogs.eclipse.org/post/tanja-obradovic/even-closer-jakarta-ee-10

**Comment by linkfang** [comment]
And please preview the change here:
https://deploy-preview-1444--jakartaee.netlify.app/news/
https://deploy-preview-1444--jakartaee.netlify.app/news/even-closer-to-jakarta-ee-10/

**Comment by TanjaObradovic** [comment]
hmmm, the text does not look right :(

it should be like on the picture here

![image](https://user-images.githubusercontent.com/40073121/159783860-7112bf0d-bfa9-4812-82ee-e70cb1a367c4.png)

The text / bulletin points has links as below.

[Jakarta SOAP with Attachments 3.0](https://jakarta.ee/specifications/soap-attachments/3.0/) - https://github.com/jakartaee/specifications/pull/444
[Jakarta JSON Binding 3.0](http://jakarta.ee/specifications/jsonb/3.0/) - https://github.com/jakartaee/specifications/pull/456
[Jakarta Batch 2.1](https://jakarta.ee/specifications/batch/2.1/) - https://github.com/jakartaee/specifications/pull/438

**Comment by linkfang** [comment]
Fixed it, please check it here:
https://deploy-preview-1444--jakartaee.netlify.app/news/even-closer-to-jakarta-ee-10/

**Comment by TanjaObradovic** [comment]
Looks great!! thanks!!!!

**Comment by linkfang** [comment]
NP! The change is now live!
