### ISSUE TITLE
Please publish my "Take the 2022 Jakarta EE Developer Survey Today!" blog to https://jakarta.ee/news

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1441]
Please publish my blog at
https://jakarta.ee/news

Please use text from here
https://blogs.eclipse.org/post/tanja-obradovic/take-2022-jakarta-ee-developer-survey-today

**Blog post information**
title: 
Take the 2022 Jakarta EE Developer Survey Today!
date: 
Monday, March 21, 2022
summary:
Help us shape up Jakarta EE, take [the 2022 Jakarta EE Developer Survey Today](2022 Jakarta EE Developer Survey Today)!
content: 
A great way to get involved, provide input and insights of Java enterprise industry is taking part in our fifth annual [2022 Jakarta EE Developer Survey](https://www.surveymonkey.com/r/9NLY63D). It takes less than 6 minutes of your time, but the impact is extremely important: it gives, the Jakarta EEworking group and community opportunity to better understand the top priorities for future Jakarta EE releases.

![image](https://user-images.githubusercontent.com/40073121/159484146-f9490002-4bf5-493d-beba-3f20dbabdcc0.png)

This year’s survey asks developers to share their future plans for building modern enterprise applications and their choices for architectures, technologies, and tools in the new cloud era. [Take the survey today](https://www.surveymonkey.com/r/9NLY63D) and let us know about the Java industry landscape, needs of Java enterprise developers in order to help shape up the future and direction of [Jakarta EE specifications](https://jakarta.ee/specifications/).

**Comment by linkfang** [comment]
Hi @TanjaObradovic , please preview the update here:

https://deploy-preview-1446--jakartaee.netlify.app/news/
https://deploy-preview-1446--jakartaee.netlify.app/news/take-2022-jakarta-ee-developer-survey-today/

**Comment by TanjaObradovic** [comment]
looks great! thanks!

**Comment by linkfang** [comment]
Hi @TanjaObradovic , are we also good on the other blog? (Welcome Beijing Vsettan Data Technology Co. Ltd. to the Jakarta EE Working Group!)
https://github.com/jakartaee/jakarta.ee/issues/1436#issuecomment-1077763376

**Comment by linkfang** [comment]
NP! The changes are now live!
