### ISSUE TITLE
Issues on Release 9 Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1442]
**Describe the bug**
On the Release 9 page: https://jakarta.ee/release/9/

- The previous release link in the main banner links to https://jakarta.ee/release/9/ - Instead it should link to https://jakarta.ee/release/8/
- there is a line break tag "showing" in the feature box that says LOWER ENTRY BARRIERS - this should be removed
- the banner says "VERSION 9.1 NEW RELEASE" - instead it should say VERSION 9 (unless I've misunderstood, but it says the same on the 9.1 page)

![banner](https://user-images.githubusercontent.com/73264129/159606144-f974ab5d-8cf0-4dd2-955e-aae4d61afcc1.png)
![features](https://user-images.githubusercontent.com/73264129/159606146-fb1af9e3-4577-463b-9e4b-f7aa5e83c883.png)

**Comment by excentrickristy** [comment]
After discussion with @shabnammayel, we decided that the PREVIOUS RELEASE: JAKARTA EE 9 link for all of the individual pages should be changed to point to the main release page and say VIEW ALL RELEASES

**Comment by linkfang** [comment]
Hi @excentrickristy , for the "VERSION 9.1 NEW RELEASE", I think it might be a promotion for the latest version? Like when 9.2 comes out, all 3 pages will say "VERSION 9.2 NEW RELEASE" to indicate the user that we have a new lease and feel free to check it out. I could be wrong though. WDYT?

And I can change it to "VERSION 9.0" for release 9 page of course if we would like to.

**Comment by excentrickristy** [comment]
Hi @linkfang, I'm not sure that that was the intention, and I think it does make for some confusion.
I will have to let @shabnammayel be the decision maker here though!

**Comment by linkfang** [comment]
Sounds good! I checked the code and I think you are right. It should have been 9.0 on release 9 page and 9.1 for 9.1 etc.
So, I changed the version text to "version 9.0" while we wait for Shabnam to confirm.

Please preview here:
https://deploy-preview-1450--jakartaee.netlify.app/release/9/
https://deploy-preview-1450--jakartaee.netlify.app/release/9.1/

Please note, I haven't updated the "view all release" button on Chinese version, as there is no "all releases" page yet. So, I think it could be better that we keep using previous release for now and update it later when we have that page up.

**Comment by shabnammayel** [comment]
+1, Thanks for the changes @linkfang for consistency can you please change "Version 9" to "Version 9 New Release" similar to the 9.1 page?

The rest looks good to me. Thank you both!

**Comment by linkfang** [comment]
OK, I can add it back. I removed it as I thought we only need the New Release tag for the latest version. Like we only have the yellow "New" budge for 9.1 on the all releases page. 
![image](https://user-images.githubusercontent.com/43075439/160406966-216ddb0a-22a9-4499-b0de-794541aea14b.png)

**Comment by shabnammayel** [comment]
that's a good point! let's keep it for the new version only then

**Comment by linkfang** [comment]
Now the change is live!
