### ISSUE TITLE
Aesthetic Issue: Link boxes missing padding around text

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1443]
I noticed recently that the feature boxes that are used to link to internal pages no longer have padding around the text.

Example: the boxes at the bottom of this page: https://jakarta.ee/about/working-group/

And in the sidebar of any of the specification pages: https://jakarta.ee/specifications/platform/

It should look more like this: https://invis.io/AX10M9QL74RN#/448585126_Specifications-_Detail_Page

Screenshots from Chrome on Windows.

![Screenshot 2022-03-23 135734](https://user-images.githubusercontent.com/73264129/159765427-cad65ef6-6219-4afc-bab1-dc89d171c630.png)

**Comment by linkfang** [comment]
Good catch!

Fixed them, please preview there:
https://deploy-preview-1449--jakartaee.netlify.app/about/working-group/
https://deploy-preview-1449--jakartaee.netlify.app/specifications/platform/

**Comment by excentrickristy** [comment]
Looks good!

**Comment by linkfang** [comment]
The changes are now live!
