### ISSUE TITLE
Add images to the featured story section of the Jakarta EE homepage via newsroom

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1451]
Currently we are not able to add images in the newsroom to be featured on the homepage's featured story section. Adding images to that section can make the stories more visible to have a greater impact.

**Comment by ericpoirier** [comment]
Shabnam and I talked on Slack and we are waiting for a mockup from Mehrnaz.

**Comment by shabnammayel** [comment]
Hi @ericpoirier Mehrnaz created different mockups but after looking at them and thinking it through further. It's best to change the placement of the featured story and move it to the existing blue banner above the boxes. we can move the existing blurb there below the boxes. Here is the mockup that Mehrnaz created https://xd.adobe.com/view/838f656a-70b4-4b90-b62f-ff6d448a9ee6-d6dc/ thanks

**Comment by ericpoirier** [comment]
@shabnammayel I'm currently looking at the mockup and I don't see any images to the Featured Story?

**Comment by ericpoirier** [comment]
After discussion with @shabnammayel on Zoom, it was decided that we would forget about adding an image to the featured story for now and just move the section where there's a blue background.

We will continue to show multiple featured stories so there will be dots under the elements to navigate between them.

**Comment by shabnammayel** [comment]
The sentence in the mock up: Jakarta EE brings together a global community of leading developers, vendors, and enterprises to collaborate on advancing enterprise Java technologies in the cloud

**Comment by ericpoirier** [comment]
@shabnammayel please review the following page:

https://deploy-preview-1456--jakartaee.netlify.app/

You'll note that the same featured story is showing up but with slightly different content. I had a look at the newsroom and there are 2 different featured story with the same name. That's why we are seeing 2 of them.

**Comment by shabnammayel** [comment]
Looks good, Eric! Thanks. let's keep the one that has the CTA "Take the Survey"

**Comment by ericpoirier** [comment]
> Looks good, Eric! Thanks. let's keep the one that has the CTA "Take the Survey"

@jph152 I don't mind going to newsroom and disabling this featured story but just wanted to keep you in the loop of what needs to be removed from Jakarta EE.

**Comment by ericpoirier** [comment]
@shabnammayel I updated Newsroom, the item should be removed shortly.

In the meantime, I'll get the changes reviewed.
