### ISSUE TITLE
Utilizing newsroom for /resources page

### ISSUE THREAD

**Issue by shanda-eclipse** [jakartaee/jakarta.ee#1455]
See https://gitlab.eclipse.org/eclipsefdn/infrazilla/-/issues/508 for parent issue. 

On https://jakarta.ee/resources/ we would like to us an API that updates SOME sections of https://jakarta.ee/resources/ automatically. The look of the page will remain exactly the same. Here is a rundown of each section and how we would like it managed:

- Case Studies - show the 3 most recent case studies (newest to oldest) for Jakarta EE, with the _landing page link_ and a view more that functions like https://iot.eclipse.org/community/resources/
- Datasheet - this section will remain hardcoded
- Documentation - this section will remain hardcoded
- eBooks - show the 3 most recent ebooks for Jakarta EE, with the _landing page link_ and a view more
- Infographics - this section will remain hardcoded
- Starter for Jakarta EE - this section will remain hardcoded
- JakartaOne Livestream - this section will remain hardcoded
- Presentations - this section will remain hardcoded
- Social Cards - this section will remain hardcoded
- Surveys  - show the 3 most recent survey reports for Jakarta EE, with the _landing page link_ and a view more
- White Papers - show the 3 most recent white papers for Jakarta EE, with the _landing page link_ and a view more

CC/ @shabnammayel

**Comment by linkfang** [comment]
The update is live! 
https://jakarta.ee/resources/
