### ISSUE TITLE
Publishing Steering Committee Meeting minutes

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1460]
Can you please publish Steering Committee Meeting minutes?

https://jakarta.ee/committees/steering/

[Minutes of the Feb 15, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8533744/Minutes.of.the.Feb.15.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the March 1, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8533746/Minutes.of.the.March.1.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the Feb 1, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8533748/Minutes.of.the.Feb.1.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

Many thanks!!

**Comment by linkfang** [comment]
Hi @TanjaObradovic , sorry for the late update, and please preview it here:

https://deploy-preview-1476--jakartaee.netlify.app/committees/steering/

**Comment by linkfang** [comment]
The changes are live!
