### ISSUE TITLE
Add the Jakarta EE 10 page to the compatibility/certification page and download page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1461]
We need to create a page for the Jakarta EE 10 compatibility products here:
https://jakarta.ee/compatibility/certification/9.1/
currently there are 3 tabs on the right sidebar: Jakarta EE 8, Jakarta EE 9, and Jakarta EE 9.1. We should add Jakarta EE 10 above Jakarta EE 9.1
And on that page we need to create another table for Core Profile products that will be certified with Jakarta EE 10. 

We also need to create a table for Jakarta EE 10 compatible products on the Download page here: https://jakarta.ee/compatibility/download/ 
These pages will likely be empty until the release date. We will report back on the compatible product that need to be added here on the release date.

**Comment by njr-11** [comment]
These sound like good ideas, but could you please move this issue/open a new issue for this against https://github.com/jakartaee/jakarta.ee ?
This jakartaee/concurrency project is just for a single one of the Jakarta EE specs and doesn't maintain the pages for the jakarta.ee site.

**Comment by shabnammayel** [comment]
my bad! I asked @ericpoirier to help me with moving this to the website repo.

**Comment by ericpoirier** [comment]
Hi @shabnammayel, I created the pages and tables for Jakarta EE 10 in the Compatibility pages:
https://deploy-preview-1462--jakartaee.netlify.app/compatibility/

Let me know if I got it right.

Thanks.

**Comment by shabnammayel** [comment]
Thanks, please not we need placeholder tables for Web Profile and Core Profile products on this page as well. Core Profile is new for EE 10.
<img width="871" alt="Screen Shot 2022-04-22 at 2 40 51 PM" src="https://user-images.githubusercontent.com/51449073/164775120-17c34117-f24d-44e6-a841-be3df755afcd.png">

Also on the download page we need tables for Jakarta EE 10 Platform  and Jakarta EE 10 Web Profile

**Comment by ericpoirier** [comment]
@shabnammayel I updated the tables. Let me know if there's anything else.

**Comment by shabnammayel** [comment]
I still don't see the tables for the Jakarta EE 10 Webprofile, Platform and Core Profile in the certification results tab @ericpoirier

**Comment by ericpoirier** [comment]
> I still don't see the tables for the Jakarta EE 10 Webprofile, Platform and Core Profile in the certification results tab @ericpoirier

The tables are empty but they are on this page:
https://deploy-preview-1462--jakartaee.netlify.app/compatibility/certification/10/

**Comment by shabnammayel** [comment]
LGTM! thanks @ericpoirier
