### ISSUE TITLE
Please publish my "Getting really close to Jakarta EE 10!" blog to https://jakarta.ee/news

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1466]
Please publish my blog at
https://jakarta.ee/news

Please use text from here
https://blogs.eclipse.org/post/tanja-obradovic/getting-really-close-jakarta-ee-10

The Jakarta EE community teamwork is amazing!  They are completely focused on [Jakarta EE 10 release plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee10/JakartaEE10ReleasePlan) and following the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/) we have more progress on the individual specifications.

The Release Review is now completed for the following specifications:

- Jakarta Persistence 3.1 - https://github.com/jakartaee/specifications/pull/442
- Jakarta Interceptors 2.1 - https://github.com/jakartaee/specifications/pull/450
- Jakarta JSON Processing 2.1 - https://github.com/jakartaee/specifications/pull/432
- Jakarta XML Binding 4.0 - https://github.com/jakartaee/specifications/pull/443
- Jakarta CDI 4.0 - https://github.com/jakartaee/specifications/pull/439
- Jakarta XML Web Services 4.0 - https://github.com/jakartaee/specifications/pull/445
- Jakarta RESTful Web Services 3.1 - https://github.com/jakartaee/specifications/pull/430

Stay tuned for  more progress in the upcoming weeks or monitor[ progress on individual specifications release reviews](https://github.com/jakartaee/specifications/pulls?q=is%3Apr+is%3Aopen)!

Please see the other posts specifications with already completed Release Review:

- [Even closer to Jakarta EE 10!](https://blogs.eclipse.org/post/tanja-obradovic/even-closer-jakarta-ee-10)
- [Getting closer to the Jakarta EE 10 release!](https://blogs.eclipse.org/post/tanja-obradovic/getting-closer-jakarta-ee-10-release)

**Comment by linkfang** [comment]
Hi @TanjaObradovic , please preview the updates here:

https://deploy-preview-1467--jakartaee.netlify.app/news/
https://deploy-preview-1467--jakartaee.netlify.app/news/getting-really-close-jakarta-ee-10/

**Comment by TanjaObradovic** [comment]
Looks great! thanks!
