### ISSUE TITLE
Compatibility certification request for AISWare Flying Server for Full Platform

### ISSUE THREAD

**Issue by AsiainfoAnhui** [jakartaee/jakarta.ee#1470]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The Eclipse Foundation profile [Wang Feng](https://accounts.eclipse.org/users/wangfeng) of Hunan AsiaInfo Anhui Technology Limited**

**[AISWare Flying Server V2.0.0](http://asiainfoah.com/#/product/flyingserver)**

**The Profile (Full Platform) that the Compatible Product is submitted to be listed under**
   Specification Name, Version and download URL:
   [Jakarta EE Platform, Full Profile 8](https://jakarta.ee/specifications/platform/8/)  
   TCK Version, digital SHA-256 fingerprint and download URL:
    [Jakarta EE Platform CTS 8.0.2](http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip) , SHA-256: 14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965
    Public URL of TCK Results Summary:
    [AISWare Flying Server 2.0.0 TCK Results](https://github.com/AsiainfoAnhui/aisware_flyingserver_v2_ee8/blob/master/aisware_flyingserver_v2_ee8.md#tck-results)
   Any Additional Specification Certification Requirements:
    Jakarta Dependency Injection 1.0 TCK  
    See test results in section di.  
    Download URL & SHA-256: [jakarta.inject-tck-1.0-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip), SHA-256: b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f
    Jakarta Contexts and Dependency Injection 2.0 TCK  
    See test results in section cdi.  
    Download URL & SHA-256: [cdi-tck-2.0.6-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip), SHA-256: 75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808
    Jakarta Bean Validation 2.0 TCK,  
    See test results in section beanvalidation.  
[beanvalidation-tck-dist-2.0.5.zip](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip), SHA-256: b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974
    Jakarta Batch 1.0 TCK tests are included in Jakarta EE 8 CTS tests, See test results in section jbatch  
    Java SE Provider & Version tested with:
        OpenJDK Runtime Environment (build 25.262-b02, mixed mode)
    Summary of the information for the certification environment:
        Apache Derby 10.14.2.0, Linux, 4.19.90-17.ky10.aarch64
        Interoperatibility tests carried out against Eclipse Glassfish 5.1.0

**[AISWare FlyingServer Logo](https://github.com/AsiainfoAnhui/aisware_flyingserver_v2_ee8/blob/master/AISWare_FlyingServer_Logo.zip)**

**Hunan AsiaInfo Anhui Technology Limited**

**[Compatibility certification request for [AISWare Flying Server] for [Full Platform] #487](https://github.com/eclipse-ee4j/jakartaee-platform/issues/487)**

**[AISWare FlyingServer Home Page](https://cms.101test.com/ai_sino_info/zh_cn/content_603710660.html)**

**Comment by ericpoirier** [comment]
Please review the following staging page:

https://deploy-preview-1471--jakartaee.netlify.app/compatibility/

Let me know if I missed anything.

Thanks.

**Comment by TanjaObradovic** [comment]
looks good to me!

One thing on the download page - I am not sure the download works, can you please confirm @ericpoirier ?
![image](https://user-images.githubusercontent.com/40073121/168112969-062ae829-65f3-4992-ad87-0e39139171c8.png)


@AsiainfoAnhui please confirms all is in order :)

**Comment by AsiainfoAnhui** [comment]
Hello . 
We will update our website in this weekend, please publish it after I change the product link address in next Monday.
This "Download 2.0.0" need to link to our product page, please update it after I get the product page new address.
I have updated the [product logo](https://github.com/AsiainfoAnhui/aisware_flyingserver_v2_ee8/blob/master/AISWare_FlyingServer_Logo.zip) , please update it . 
Thank you so much Tanja and Ericpoirier.

**Comment by AsiainfoAnhui** [comment]
hello Ericpoirier
I have got the product home address http://asiainfoah.com/#/product/flyingserver
please update it to download link and update the logo https://github.com/AsiainfoAnhui/aisware_flyingserver_v2_ee8/blob/master/AISWare_FlyingServer_Logo.zip
thanks very much

**Comment by AsiainfoAnhui** [comment]
Hello @ericpoirier 
I saw the  update in page, I have checkd it. it  is ok. please publish.
thank you so much
