### ISSUE TITLE
Update the content of the Jakarta EE membership prospectus

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1475]
We need to update page 8 of the prospectus and remove the sentence: Enterprise members have the opportunity to influence in defining Jakarta EE requirements with a seat on a the requirements committe
<img width="1347" alt="Screen Shot 2022-05-18 at 1 26 27 PM" src="https://user-images.githubusercontent.com/51449073/169104952-dd6b8d55-25d5-4d90-8bb3-e568ba2ad16a.png">
e

**Comment by ericpoirier** [comment]
@linkfang assining this issue to you but adding the "Waiting for assets" label since we will need a new PDF from @shabnammayel.

**Comment by shabnammayel** [comment]
[jakarta-ee-membership-prospectus.pdf](https://github.com/jakartaee/jakarta.ee/files/8773699/jakarta-ee-membership-prospectus.pdf)

**Comment by linkfang** [comment]
Hi @shabnammayel , please preview the update here:
https://deploy-preview-1484--jakartaee.netlify.app/membership/

**Comment by linkfang** [comment]
Hi @shabnammayel , just would like to confirm if this is still on your radar, thanks!

**Comment by shabnammayel** [comment]
Thanks for the reminder! :) yes it looks good to me!

**Comment by linkfang** [comment]
NP! The change is now live!
