### ISSUE TITLE
Publish Jakarta EE Steering Committee Meeting Minutes of the Feb 15, Mar 1, Mar 15, Mar 29 Meetings

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1477]
This is not a bug

We need to add new entries for Steering meeting minutes on Feb 15, Mar 1, Mar 15, Mar 29.
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.

I have attached pdf files:
[Minutes of the Feb 15, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8757688/Minutes.of.the.Feb.15.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the March 1, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8757689/Minutes.of.the.March.1.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the March 15, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8757690/Minutes.of.the.March.15.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the March 29, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8757691/Minutes.of.the.March.29.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

Let me know if there are questions.

**Comment by linkfang** [comment]
Hi @will-lyons , please preview the updates here and let me know if everything looks good, thanks!

https://deploy-preview-1476--jakartaee.netlify.app/committees/steering/

**Comment by will-lyons** [comment]
Yes, everything looks good.   Please publish.

Thank you.

Will

From: Zhou Fang ***@***.***>
Reply-To: "jakartaee/jakarta.ee" ***@***.***>
Date: Tuesday, May 24, 2022 at 2:57 PM
To: "jakartaee/jakarta.ee" ***@***.***>
Cc: Will Lyons ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [jakartaee/jakarta.ee] Publish Jakarta EE Steering Committee Meeting Minutes of the Feb 15, Mar 1, Mar 15, Mar 29 Meetings (Issue #1477)


Hi @will-lyons<https://urldefense.com/v3/__https:/github.com/will-lyons__;!!ACWV5N9M2RV99hQ!NKcegzmGyOVYLpQYSLE93J88uGuMkV74VEvHqeWeT2GlGdV5aIqjk7X64sVtvFcbv6tILTr2QtYNfACPVkPLaMp7Iw$> , please preview the updates here and let me know if everything looks good, thanks!

https://deploy-preview-1476--jakartaee.netlify.app/committees/steering/<https://urldefense.com/v3/__https:/deploy-preview-1476--jakartaee.netlify.app/committees/steering/__;!!ACWV5N9M2RV99hQ!NKcegzmGyOVYLpQYSLE93J88uGuMkV74VEvHqeWeT2GlGdV5aIqjk7X64sVtvFcbv6tILTr2QtYNfACPVkOtnoZBLg$>

**Comment by linkfang** [comment]
The changes are live!
