### ISSUE TITLE
Updated Meta Tags & SEO Optimizations for Website

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1478]
Based on SEO targets, new meta tags and minor content and heading level improvements for the existing pages have been recommended in this document here: https://docs.google.com/document/d/1GbnRhvJuOgHHQt0BLke1lg2rs07SV75y1i_OIZ9CXwk/edit?usp=sharing

All approved by @shabnammayel 

Would be nice to implement as soon as possible :)

Thanks!

**Comment by linkfang** [comment]
Hi @excentrickristy , please preview the updates here:

https://deploy-preview-1480--jakartaee.netlify.app/specifications/faces/
https://deploy-preview-1480--jakartaee.netlify.app/release/
https://deploy-preview-1480--jakartaee.netlify.app/specifications/platform/

Let me know if everything looks good, thanks!

**Comment by linkfang** [comment]
Hi @shabnammayel , can you also take a look at the previews when you get a chance? Thanks!

**Comment by excentrickristy** [comment]
Hi @linkfang, everything looks good! Thanks for doing that. Just one thing I noticed on the release pages that I didn't notice the first time around. On all of the release pages we need to switch the contributors names from h4 to h3 tags.

Thanks!

**Comment by linkfang** [comment]
Sounds good, please preview the update here:

https://deploy-preview-1480--jakartaee.netlify.app/release/9.1/
https://deploy-preview-1480--jakartaee.netlify.app/release/9/

**Comment by excentrickristy** [comment]
Looks good, you can push it!

**Comment by linkfang** [comment]
Changes other than specifications are merged and should be live soon! 
Specification related stuff is in a separate repo, will update here once it's merged.

**Comment by linkfang** [comment]
All the changes are now live, closing the issue
