### ISSUE TITLE
Publish Jakarta EE Steering Committee meeting minutes for April 12, 2022 meeting

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1479]
This is not a bug

We need to add new entries for Steering meeting minutes on April 12, 2022.
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.

I have attached a pdf file:
[Minutes of the April 12, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8765137/Minutes.of.the.April.12.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by linkfang** [comment]
Hi @will-lyons , please preview the update here:
https://deploy-preview-1476--jakartaee.netlify.app/committees/steering/

**Comment by linkfang** [comment]
The changes are live!
