### ISSUE TITLE
Typo in  Announcement

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/jakarta.ee#1481]
![Screenshot from 2022-05-25 09-03-25](https://user-images.githubusercontent.com/149188/170200986-d5aac25d-eb6f-40f6-8850-cdd9b5ba92b2.png)

**Comment by ericpoirier** [comment]
Hi @ivargrimstad, please review the following staging page:

https://deploy-preview-1482--jakartaee.netlify.app/

Thanks.
