### ISSUE TITLE
Home page testimonial logos have broken images

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1487]
On the home page: https://jakarta.ee
In the testimonials section, some logos are showing as broken images because the logos are in svg format but being embedded using an img src html tag instead of an svg tag
![Screenshot 2022-06-07 112225](https://user-images.githubusercontent.com/73264129/172418923-e490e9c6-544a-4c07-85c3-a6f847f01000.png)
.

**Comment by linkfang** [comment]
Hi @excentrickristy , please preview the fix here:

https://deploy-preview-1490--jakartaee.netlify.app/

**Comment by excentrickristy** [comment]
Looks good!

**Comment by linkfang** [comment]
Cool, the fixes are live!
