### ISSUE TITLE
Publish Jakarta EE Steering Committee Meeting Minutes of April 26, 2022 and May 24, 2022 Meetings

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1488]
This is not a bug

We need to add new entries for Steering meeting minutes for April 26, 2022 and May 24, 2022.
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.

I have attached two pdf files:
[Minutes of the April 26, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8855422/Minutes.of.the.April.26.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the May 24, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/8855425/Minutes.of.the.May.24.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by linkfang** [comment]
Hi @will-lyons , please preview the update here:

https://deploy-preview-1491--jakartaee.netlify.app/about/meeting_minutes/#steering_committee

**Comment by linkfang** [comment]
Hi @will-lyons , just would like to confirm if this is still on your radar. We would prefer to let you check the preview before we push the change live, though this is a small change.

**Comment by TanjaObradovic** [comment]
Let me help Will here!

Looks great! :)

**Comment by linkfang** [comment]
Thanks @TanjaObradovic , the changes are live!

**Comment by will-lyons** [comment]
Looks good, thank you.

Will

From: Zhou Fang ***@***.***>
Reply-To: "jakartaee/jakarta.ee" ***@***.***>
Date: Thursday, June 9, 2022 at 2:57 PM
To: "jakartaee/jakarta.ee" ***@***.***>
Cc: Will Lyons ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [jakartaee/jakarta.ee] Publish Jakarta EE Steering Committee Meeting Minutes of April 26, 2022 and May 24, 2022 Meetings (Issue #1488)


Hi @will-lyons<https://urldefense.com/v3/__https:/github.com/will-lyons__;!!ACWV5N9M2RV99hQ!NPWJWG3pa7_O4vsH9RPWiev0omWZWbVXKMm8kQjcye0itX61Ow2KShnnmpBiv3AAJwcFp6WkmLfbl-KFVccz3mhZPw$> , please preview the update here:

https://deploy-preview-1491--jakartaee.netlify.app/about/meeting_minutes/#steering_committee<https://urldefense.com/v3/__https:/deploy-preview-1491--jakartaee.netlify.app/about/meeting_minutes/*steering_committee__;Iw!!ACWV5N9M2RV99hQ!NPWJWG3pa7_O4vsH9RPWiev0omWZWbVXKMm8kQjcye0itX61Ow2KShnnmpBiv3AAJwcFp6WkmLfbl-KFVccXTu-BXg$>
