### ISSUE TITLE
Please add a blog post at https://jakarta.ee/news

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1493]
Please use the text from here

https://blogs.eclipse.org/post/tanja-obradovic/almost-there-jakarta-ee-10-nearly-ready-and-celebrations-have-already-started

Thanks!
tanja

**Blog post information**
title: [title]
date: [date]
summary: [summary]
content: [content]

**Comment by linkfang** [comment]
As we are getting all news from our newsroom API, so in theory, all new blogs will be picked up (with some delay time) without us adding any new code. 

Now the blog is live on prod, closing the issue.

https://jakarta.ee/news/
