### ISSUE TITLE
Member Testimonials not showing on /membership page

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1498]
**Describe the bug**
Member Testimonials not showing on  https://jakarta.ee/membership/ page

According to the guide to add a new testimonial: https://github.com/jakartaee/jakarta.ee#how-to-include-a-new-membership-testimonials, the testimonials widget depends on `data/membership/testimonials/ *.yml` but the data/membership folder doesn't exist anymore.

**To Reproduce**
1. Go to https://jakarta.ee/membership/
2. Scroll to the section "MEMBER TESTIMONIALS"

**Expected behavior**
A carousel showing members testimonials should appear. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1454523/176943424-56b7f7aa-d4de-47e3-9e00-e369d646d847.png)

cc: @shabnammayel @chrisguindon @ericpoirier

**Comment by ericpoirier** [comment]
@cesarhernandezgt The testimonials are now showing up on the membership page of the following staging page:

https://deploy-preview-1501--jakartaee.netlify.app/membership/

Let me know if there's anything else.

Thanks.

**Comment by cesarhernandezgt** [comment]
Thank you @ericpoirier for the fix. I navigated the preview site and the testimonials are working fine.
