### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1500]
The following are internal 404s that need to be cleaned up to improve  and user experience. 

On this page:
https://jakarta.ee/zh/committees/
In the 3rd box there is a broken link:
![image](https://user-images.githubusercontent.com/73264129/177048537-b8f5923c-eefe-4bc9-8f10-d3761c41dd38.png)

Should link to: https://jakarta.ee/zh/about/jesp/

----
On this page:
https://jakarta.ee/zh/committees/specification/
The highlighted link is broken:
![image](https://user-images.githubusercontent.com/73264129/177048630-8b2f0af6-2726-4681-ac09-e9ce4b5feccb.png)

Should link to: https://jakarta.ee/zh/about/jesp/

---
On this page:
https://jakarta.ee/about/meeting_minutes/#specification_committee

The link to these specification committee minutes is broken: February 13, 2021 (pdf)

Should link to: https://jakarta.ee/about/meeting_minutes/specification_committee/minutes-specification-february-10-2021.pdf

---

On this page:
https://jakarta.ee/specifications/bean-validation/3.0/jakarta-bean-validation-spec-3.0.html

The "a" tag should be removed from these two URLs because they are registering as broken links
![image](https://user-images.githubusercontent.com/73264129/177048941-3c66327f-791b-402a-9ee6-b51722d37994.png)

---
On this page:
https://jakarta.ee/specifications/enterprise-beans/4.0/jakarta-enterprise-beans-spec-core-4.0.html

There are a number of links in the content that are meant to serve as page anchors but the URL of the page must have changed at some point. You can see highlighted here at example.
![image](https://user-images.githubusercontent.com/73264129/177049297-daf8b0dd-fd30-4dbc-b54f-f87ec963a96b.png)

On this page, there needs to be a search and replace to that any anchor tags written with this href:
./enterprise-beans-spec-opt-4.0.html

are replaced with:
./jakarta-enterprise-beans-spec-opt-4.0.html

There are also references on this page to Ejb.html which much have been a previous name for this document - they need to be replaced:
![image](https://user-images.githubusercontent.com/73264129/177049772-f021dc61-a4ff-4a91-a3b5-12f95a2c5f0b.png)

They should be replaced with this as well to fix these broken links:
./jakarta-enterprise-beans-spec-opt-4.0.html

---

On these pages:
https://jakarta.ee/specifications/cdi/4.0/apidocs/overview-tree.html
https://jakarta.ee/specifications/cdi/4.0/apidocs/allclasses-index.html
https://jakarta.ee/specifications/cdi/4.0/apidocs/allclasses.html
https://jakarta.ee/specifications/cdi/4.0/apidocs/index-all.html
https://jakarta.ee/specifications/cdi/4.0/apidocs/jakarta.cdi/jakarta/enterprise/inject/build/compatible/spi/class-use/buildservices
https://jakarta.ee/specifications/cdi/4.0/apidocs/jakarta.cdi/jakarta/enterprise/inject/build/compatible/spi/package-summary.html
https://jakarta.ee/specifications/cdi/4.0/apidocs/jakarta.cdi/jakarta/enterprise/inject/build/compatible/spi/package-tree.html

The BuildServicesResolver link is broken

Links to: https://jakarta.ee/specifications/cdi/4.0/apidocs/jakarta.cdi/jakarta/enterprise/inject/build/compatible/spi/BuildServicesResolver.html

Not sure what the correct link is though.

---

On this page:
https://jakarta.ee/specifications/faces/3.0/apidocs/com/sun/faces/application/resource/resourcehandlerimpl

There are multiple broken links to the overview summary: 
https://jakarta.ee/specifications/faces/3.0/apidocs/com/sun/overview-summary.html

Not sure what the correct link is though.

**Comment by ericpoirier** [comment]
@excentrickristy For all the changes to pages under /specifications, you should open an issue in the following repo:

https://github.com/jakartaee/specifications

Thanks.

**Comment by ZacharySabourin** [comment]
Hey @excentrickristy! Every broken link that is not under /specification has been updated. You can preview the changes here:
https://deploy-preview-1502--jakartaee.netlify.app/zh/committees/
https://deploy-preview-1502--jakartaee.netlify.app/zh/committees/specification/
https://deploy-preview-1502--jakartaee.netlify.app/about/meeting_minutes/#specification_committee

**Comment by ZacharySabourin** [comment]
Hey @excentrickristy! Just making sure this is still on your radar :)

**Comment by excentrickristy** [comment]
Looks good, thank you!

**Comment by excentrickristy** [comment]
> @excentrickristy For all the changes to pages under /specifications, you should open an issue in the following repo:
> 
> https://github.com/jakartaee/specifications
> 
> Thanks.

Done, thank you!
