### ISSUE TITLE
Redirecting to https on all of www.w3.org

### ISSUE THREAD

**Issue by pzygielo** [jakartaee/jakarta.ee#1505]
**Is your feature request related to a problem? Please describe.**

Tests of [Redirecting to https on all of www.w3.org](https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org/) today caused some problems with DD validation using `xml-maven-plugin`:
- https://github.com/eclipse-ee4j/openmq/pull/1549#issuecomment-1201574549

due to
- https://github.com/jakartaee/jakarta.ee/blob/8981afdf02d15050b1f51e4d3eb9b8ce01654a3f/static/xml/ns/jakartaee/jakartaee_10.xsd#L52 using http
- and https://github.com/mojohaus/xml-maven-plugin/issues/59.

**Describe the solution you'd like**
I'd like jakartaee xsds to use https for w3 locations instead.

**Describe alternatives you've considered**

**Additional context**

**Comment by ivargrimstad** [comment]
We will fix this in the schema sources in https://github.com/eclipse-ee4j/jakartaee-schemas/issues/39 

Keep this issue open to track that the resulting generated schemas are updated on the site

**Comment by ivargrimstad** [comment]
@pzygielo Take a look at #1506
