### ISSUE TITLE
Can't support UTF-8 caracters

### ISSUE THREAD

**Issue by CartierPierre** [jakartaee/jakarta.ee#1509]
Hi
I've lost a very long time to find why my app can't load Jakarta.
Finally, I've found `smtp.fromName` attribute can't support UTF-8 caracters, in my case the "é" letter
Using Jakarta 2.1.0, JDK17, Unix env

**Comment by autumnfound** [comment]
Hi @CartierPierre, this is the site for the Jakarta EE platform only, with no bearing on the actual specification itself. Unfortunately, in this case, your princess is in another castle. @ivargrimstad this looks like a Jakarta Mail issue...would https://github.com/eclipse-ee4j/mail/issues be the best place for this?

**Comment by TanjaObradovic** [comment]
Ivar is out on vacation.
@CartierPierre if this is Jakarta Mail issue as @autumnfound suggested, please log an issue at https://github.com/eclipse-ee4j/mail/issues

**Comment by CartierPierre** [comment]
Oh i'm so sorry, not the right place yes :)
Thanks
