### ISSUE TITLE
Currently published web-facelettaglibrary 3.0 (for JakartaEE 9) references jakartaee_10.xsd

### ISSUE THREAD

**Issue by pzygielo** [jakartaee/jakarta.ee#1510]
This repo - currently published [web-facelettaglibrary](https://jakarta.ee/xml/ns/jakartaee/web-facelettaglibrary_3_0.xsd) for [JakartaEE 9](https://jakarta.ee/xml/ns/jakartaee/#9) references `<xsd:include schemaLocation="jakartaee_10.xsd"/>` which does not seem to be right and should be reverted to 9. Just to clarify - all changes to w-ftl-3.xsd should be reverted, not the single `include` only.

Similar to above - JakartaEE 9 schema including Jakarta EE 10 - for https://jakarta.ee/xml/ns/jakartaee/web-facesconfig_4_0.xsd and https://jakarta.ee/xml/ns/jakartaee/web-facesconfig_3_0.xsd accordingly.

_Originally posted by @pzygielo in https://github.com/jakartaee/jakarta.ee/issues/1497#issuecomment-1168181995_

**Comment by ericpoirier** [comment]
I see that the pull request for this have been merged. Can we close this issue?

Thanks.

**Comment by pzygielo** [comment]
> I see that the pull request for this have been merged.

Check that PR again and you'll see that no change was merged in this repository. It's only presented/recognized as _merged_ by GitHub, due to position of branches.
That's why this issue was created, because problem was not solved there.

> Can we close this issue?

Depends - does [currently published web-facelettaglibrary 3.0 (for JakartaEE 9)](https://jakarta.ee/xml/ns/jakartaee/web-facesconfig_3_0.xsd) reference jakartaee_9.xsd, as it should IMO? For me it's still
```xml
  <xsd:include schemaLocation="jakartaee_10.xsd"/>
```
