### ISSUE TITLE
IBM WebSphere Liberty 21.0.0.12 as a Compatible Software Product for Jakarta EE 9.1

### ISSUE THREAD

**Issue by brideck** [jakartaee/jakarta.ee#1516]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Brian Decker - IBM - Eclipse Profile](https://accounts.eclipse.org/users/bdeckerhdt)

**A product name and version**
[IBM WebSphere Liberty 21.0.0.12](https://www.ibm.com/cloud/websphere-liberty)

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Both Web Profile and Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[websphereliberty.svg.zip](https://github.com/jakartaee/jakarta.ee/files/5467815/websphereliberty.svg.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[IBM Corporation](https://www.ibm.com/)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Web Profile, Java 8: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/527](https://github.com/eclipse-ee4j/jakartaee-platform/issues/527)
Web Profile, Java 11: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/528](https://github.com/eclipse-ee4j/jakartaee-platform/issues/528)
Web Profile, Java 17: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/529](https://github.com/eclipse-ee4j/jakartaee-platform/issues/529)
Full Platform, Java 8: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/530](https://github.com/eclipse-ee4j/jakartaee-platform/issues/530)
Full Platform, Java 11: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/531](https://github.com/eclipse-ee4j/jakartaee-platform/issues/531)
Full Platform, Java 17: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/532](https://github.com/eclipse-ee4j/jakartaee-platform/issues/532)

**The URL where Compatible Software Product is available for download**
Full Platform: [https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EWebSphere&product=ibm/WebSphere/WebSphere+Liberty&release=21.0.0.12&platform=All&function=fixId&fixids=wlp-jakartaee9-21.0.0.12&includeSupersedes=0](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EWebSphere&product=ibm/WebSphere/WebSphere+Liberty&release=21.0.0.12&platform=All&function=fixId&fixids=wlp-jakartaee9-21.0.0.12&includeSupersedes=0)

Web Profile: [https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~WebSphere&product=ibm/WebSphere/WebSphere+Liberty&release=21.0.0.12&platform=All&function=fixId&fixids=wlp-webProfile9-21.0.0.12&includeSupersedes=0](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~WebSphere&product=ibm/WebSphere/WebSphere+Liberty&release=21.0.0.12&platform=All&function=fixId&fixids=wlp-webProfile9-21.0.0.12&includeSupersedes=0)

**Comment by oliviergoulet5** [comment]
Hey @brideck 

Here is a preview link:  
- https://deploy-preview-1518--jakartaee.netlify.app/compatibility/certification/9.1/
- https://deploy-preview-1518--jakartaee.netlify.app/compatibility/

**Comment by brideck** [comment]
https://deploy-preview-1518--jakartaee.netlify.app/compatibility/certification/9.1/ does not look correct.

- The listed version should be 21.0.0.12.
- There should be 3 lines --1 for each Java version, like we see for Open Liberty and WildFly.
- There should also be a multi-line entry for IBM WebSphere Liberty in the Web Profile table.

**Comment by oliviergoulet5** [comment]
https://deploy-preview-1518--jakartaee.netlify.app/compatibility/

@brideck Does this look correct? I fixed the version number, fixed the links, and there is now three bullets for Platform and Web versions.

**Comment by brideck** [comment]
@oliviergoulet5 This looks great, thanks.  Please let me know when the live page is up.

**Comment by brideck** [comment]
@oliviergoulet5 I stand corrected.  The links on the download tab (https://deploy-preview-1518--jakartaee.netlify.app/compatibility/download/) currently point to the TCK, instead of a place to download IBM WebSphere Liberty.

Please use the links specified in the "The URL where Compatible Software Product is available for download" section of the template.

**Comment by oliviergoulet5** [comment]
@brideck I made the change. I hope its good now.

Can I also get a confirmation by @TanjaObradovic or @ivargrimstad if its good to deploy?

**Comment by TanjaObradovic** [comment]
Yes, looks good to me!

**Comment by brideck** [comment]
Agreed.  The new one looks good.  Thanks again.
