### ISSUE TITLE
jakartaee_web_services_metadata_handler_3_0.xsd includes jakartaee_9.xsds which does not exists

### ISSUE THREAD

**Issue by engsyst** [jakartaee/jakarta.ee#1519]
**Describe the bug**
[jakartaee_web_services_metadata_handler_3_0.xsd](https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_metadata_handler_3_0.xsd) includes non-existing schema and references to non-existing type.

**To Reproduce**
1. Create a handler chain xml document as described in `jakartaee_web_services_metadata_handler_3_0.xsd` documentation tag.

```
<handler-chains xmlns="https://jakarta.ee/xml/ns/jakartaee"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee
      https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_metadata_handler_3_0.xsd"
  version="3.0">
  
</handler-chains>
```
2. Eclipse shows the validation errors:

```
Multiple annotations found at this line:
	- There is '1' error in 'https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_metadata_handler_3_0.xsd'.
	- schema_reference.4: Failed to read schema document 'https://jakarta.ee/xml/ns/jakartaee/jakartaee_9.xsds', 
	 because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not 
	 <xsd:schema>.
```

3. Is this correct to remove the last 's' in `<xsd:include schemaLocation="jakartaee_9.xsds"/>` -> `<xsd:include schemaLocation="jakartaee_9.xsd"/>` or to change the value to "jakartaee_10.xsd"? If I do that in the downloaded schema, Eclipse shows the error message in line 55 for both values "jakartaee_9.xsd" and "jakartaee_10.xsd" for the code:

```
<xsd:element name="handler-chains"
               type="jakartaee:service-ref_handler-chainsType">
```
```
Multiple annotations found at this line:
	- src-resolve: Cannot resolve the name 'jakartaee:service-ref_handler-chainsType' to a(n) 'type 
	 definition' component.
	- src-resolve: Cannot resolve the name 'jakartaee:service-ref_handler-chainsType' to a(n) 'type 
	 definition' component.
```
4. `service-ref_handler-chainsType` cannot be found in the files.

**Expected behavior**
`jakartaee_web_services_metadata_handler_3_0.xsd` should includes the correct schema that declares `jakartaee:service-ref_handler-chainsType` and other required components to be used to validate handler chains configurations.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise, Version: 10.0.19044 Build 19044
 - IDE: Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components). 
 - Version: 2022-03 (4.23.0). Build id: 20220310-1457

**Comment by JWT007** [comment]
Same problem... looks like a typo.
<xsd:include schemaLocation="jakartaee_9.xsds"/>
The file 'jakartaee_9.xsd' exists but 'jakartaee_9.xsds' does not.

**Comment by pzygielo** [comment]
Hi @lukasj - it seems this file was introduced with
- #698

1. I can't locate it in https://github.com/eclipse-ee4j/jakartaee-schemas/tree/master/xml/src. Where one could find the source for that file?
2. Is that really just the typo?

**Comment by JWT007** [comment]
@pzygielo Hi Piotrek - here it seems?
https://github.com/eclipse-ee4j/jakartaee-schemas/tree/9/jakartaee9/src

**Comment by pzygielo** [comment]
> @pzygielo Hi Piotrek - here it seems? https://github.com/eclipse-ee4j/jakartaee-schemas/tree/9/jakartaee9/src

~Indeed. Thanks.~

~As it is also referenced by https://jakarta.ee/xml/ns/jakartaee/#10 I expected it to be in master as well.~

**Comment by pzygielo** [comment]
@JWT007 
> here it seems? https://github.com/eclipse-ee4j/jakartaee-schemas/tree/9/jakartaee9/src

I can't find `jakartaee_web_services_metadata_handler_3_0.*` there neither.

**Comment by JWT007** [comment]
yup you are right... things seem to be a bit tweaked :) all moving too fast I guess

**Comment by JWT007** [comment]
just fyi the links here seem to be totally mixed up.
https://jakarta.ee/xml/ns/jakartaee/#9

selecting the Jakarta EE 9 web-services xsd includes the jakartaee_10.xsds.
https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_2_0.xsd

one would expect that the target URL 'https://jakarta.ee/xml/ns/jakartaee/*' contains all versions of the xsds and not just a snapshot of one build

**Comment by pzygielo** [comment]
Similar but for other schemas:
- #1513

> just fyi the links here seem to be totally mixed up. https://jakarta.ee/xml/ns/jakartaee/#9
> 
> selecting the Jakarta EE 9 web-services xsd includes the jakartaee_10.xsds. https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_2_0.xsd

I haven't spotted that in
- #1472

:disappointed:

**Comment by JWT007** [comment]
@pzygielo  looks like some of the other related problems got fixed, any chance of now fixing the bad include in the:
https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_metadata_handler_3_0.xsd
:)

**Comment by pzygielo** [comment]
> any chance of now fixing the bad include in the: https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_metadata_handler_3_0.xsd 

I suppose someone from [metro](https://projects.eclipse.org/projects/ee4j.metro), most probably @lukasj, has to assist with that.

**Comment by pzygielo** [comment]
> 1. I can't locate it in https://github.com/eclipse-ee4j/jakartaee-schemas/tree/master/xml/src. Where one could find the source for that file?

Found it: jakartaee/jws-api#83

> 2. Is that really just the typo?

By comparison with previous version (javaee_web_services_metadata_handler_2_0.xsd) it seems to be just that.

**Comment by lukasj** [comment]
the file exists at https://github.com/eclipse-ee4j/jakartaee-schemas/tree/releases/9/jakartaee9/src That repo contains tests as well. So the main question is: who is right?

**Comment by pzygielo** [comment]
> the file exists at https://github.com/eclipse-ee4j/jakartaee-schemas/tree/releases/9/jakartaee9/src 

no (https://github.com/jakartaee/jakarta.ee/issues/1519#issuecomment-1356846259)

no - as in - there is no `jakartaee_web_services_metadata_handler_3_0.xsd` file.

xsds - it might be included if it is processed to the final xsd. But the jakartaee-schemas repo has no `jakartaee_web_services_metadata_handler_3_0.xsd` there. It contains sources (of other schemas) that are transformed to their final version to be published here.

In the set of published schemas, that this repo provides, there is no xsds file.

**Comment by pzygielo** [comment]
> So the main question is: who is right?

Probably the value of schemaLocation attribute is wrong.

**Comment by JWT007** [comment]
Can someone please check if this was successfully or rather correctly resolved?

There *is* a https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_metadata_handler_3_0.xsd which incorrectly references a non-existent type: <xsd:element name="handler-chains" type="jakartaee:service-ref_handler-chainsType">

In addition this XSD includes the Jakarta 9 EE XSD which is IMHO incorrect because it is used by both Jakarta 9 EE and Jakarta 10 EE.

I believe the include should be for "https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_client_2_0.xsd" and the element type should be <xsd:element name="handler-chains" type="jakartaee:handler-chainsType">.

```
<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:jakartaee="https://jakarta.ee/xml/ns/jakartaee" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="https://jakarta.ee/xml/ns/jakartaee" elementFormDefault="qualified" attributeFormDefault="unqualified" version="3.0">
  <xsd:annotation>
    <xsd:documentation>
This is the XML Schema for the Handler chain configuration descriptor. The configuration file must be in the classpath within the JAR/WAR file. All Handler chain configuration descriptors should indicate the descriptor schema by using the Jakarta EE namespace: https://jakarta.ee/xml/ns/jakartaee and by indicating the version of the schema by using the version element as shown below:
<handler-chains xmlns="https://jakarta.ee/xml/ns/jakartaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_metadata_handler_3_0.xsd" version="3.0"> ... </handler-chains>
The instance documents may indicate the published version of the schema using the xsi:schemaLocation attribute for Jakarta EE namespace with the following location: https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_metadata_handler_3_0.xsd
    </xsd:documentation>
  </xsd:annotation>
  <xsd:include schemaLocation="jakartaee_web_services_client_2_0.xsd"/>
  <xsd:element name="handler-chains" type="jakartaee:handler-chainsType">
    <xsd:annotation>
      <xsd:documentation> The handler-chains element is the root element for defining handlerchains. The Jakarta Web Services Metadata specification defines the @jakarta.jws.HandlerChain annotation that refers to an XML descriptor conforming to this schema. </xsd:documentation>
    </xsd:annotation>
  </xsd:element>
</xsd:schema>
```
