### ISSUE TITLE
Publish Jakarta EE Steering Comm Mtg Mins - June 7, 2022; June 21, 2022; July 5, 2022; July 19, 2022; August 2, 2022; Aug 16, 2022

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1521]
This is not a bug

We need to add new entries for Steering meeting minutes for June 7, 2022; June 21, 2022; July 5, 2022; July 19, 2022; August 2, 2022; Aug 16, 2022
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.

I have attached pdf files:
[Minutes of the June 7, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/9578297/Minutes.of.the.June.7.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the June 21, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/9578298/Minutes.of.the.June.21.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the July 5, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/9578299/Minutes.of.the.July.5.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the July 19, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/9578300/Minutes.of.the.July.19.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the August 2, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/9578301/Minutes.of.the.August.2.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the August 16, 2022 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/9578302/Minutes.of.the.August.16.2022.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by oliviergoulet5** [comment]
Hey @will-lyons 

Here is a preview link for the steering committee meeting minutes: https://deploy-preview-1526--jakartaee.netlify.app/about/meeting_minutes/#steering_committee

/cc @TanjaObradovic

**Comment by TanjaObradovic** [comment]
looks great! please feel free to publish :)

**Comment by will-lyons** [comment]
The preview looks good, please publish.

Thanks

Will

From: Olivier Goulet ***@***.***>
Reply-To: "jakartaee/jakarta.ee" ***@***.***>
Date: Monday, September 19, 2022 at 1:30 PM
To: "jakartaee/jakarta.ee" ***@***.***>
Cc: Will Lyons ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [jakartaee/jakarta.ee] Publish Jakarta EE Steering Comm Mtg Mins - June 7, 2022; June 21, 2022; July 5, 2022; July 19, 2022; August 2, 2022; Aug 16, 2022 (Issue #1521)


Hey @will-lyons<https://urldefense.com/v3/__https:/github.com/will-lyons__;!!ACWV5N9M2RV99hQ!MhMQX_vcHfcNcf7UjndmPNbqOCmO7gukVxvo8ba_Qga_G-TK5gjmRFhNQCHZ90Zro3qF6KWLentIsDGFozbrOoXwZg$>

Here is a preview link for the steering committee meeting minutes: https://deploy-preview-1526--jakartaee.netlify.app/about/meeting_minutes/#steering_committee<https://urldefense.com/v3/__https:/deploy-preview-1526--jakartaee.netlify.app/about/meeting_minutes/*steering_committee__;Iw!!ACWV5N9M2RV99hQ!MhMQX_vcHfcNcf7UjndmPNbqOCmO7gukVxvo8ba_Qga_G-TK5gjmRFhNQCHZ90Zro3qF6KWLentIsDGFozbXOyUFeA$>

/cc @TanjaObradovic<https://urldefense.com/v3/__https:/github.com/TanjaObradovic__;!!ACWV5N9M2RV99hQ!MhMQX_vcHfcNcf7UjndmPNbqOCmO7gukVxvo8ba_Qga_G-TK5gjmRFhNQCHZ90Zro3qF6KWLentIsDGFozaxj4EvZQ$>
