### ISSUE TITLE
Eclipse GlassFish Web Profile 7.0 as Compatible Product of Jakarta EE 10.0 Web Profile

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/jakarta.ee#1523]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

* [Arjan Tijms](https://projects.eclipse.org/content/arjan-tijms-committer-eclipse-glassfish)

**A product name and version**

* Eclipse GlassFish Web Profile 7.0

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**

* Web Profile

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

* On File with Eclipse Foundation

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

* Eclipse Foundation

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

* [Compatibility certification request for Eclipse GlassFish 7.0 M8 for Web Profile 10](https://github.com/eclipse-ee4j/jakartaee-platform/issues/534)

**The URL where Compatible Software Product is available for download**

* https://glassfish.org/download

**Comment by oliviergoulet5** [comment]
Hey @arjantijms 

Here are the staging links:
https://deploy-preview-1525--jakartaee.netlify.app/compatibility/
https://deploy-preview-1525--jakartaee.netlify.app/compatibility/certification/10/
https://deploy-preview-1525--jakartaee.netlify.app/compatibility/download/

**Comment by TanjaObradovic** [comment]
Looks good to me!
