### ISSUE TITLE
Compatible Software Product request for WildFly Preview 27.0.0.Alpha1 Core Profile 10

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#1527]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://www.eclipse.org/membership/showMember.php?member_id=731

**A product name and version**

[WildFly Preview 27.0.0.Alpha1](https://github.com/wildfly/wildfly/releases/download/27.0.0.Alpha1/wildfly-preview-27.0.0.Alpha1.zip)

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**

Core Profile

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

https://github.com/wildfly/certifications/blob/EE8/images/wildfly-logo-stacked-100px-2132977.zip?raw=true

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Red Hat

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

https://github.com/eclipse-ee4j/jakartaee-platform/issues/494 (Java SE 17) is for WildFly Preview 27.0.0.Alpha1

https://github.com/eclipse-ee4j/jakartaee-platform/issues/493 (Java SE 11) is for WildFly Preview 27.0.0.Alpha1

**The URL where Compatible Software Product is available for download**

[WildFly Preview 27.0.0.Alpha1](https://github.com/wildfly/wildfly/releases/download/27.0.0.Alpha1/wildfly-preview-27.0.0.Alpha1.zip)

**Comment by scottmarlow** [comment]
Please note related issue https://github.com/jakartaee/jakarta.ee/issues/1528 also for `WildFly 27.0.0.Alpha5`.

**Comment by TanjaObradovic** [comment]
Looks good to me!

**Comment by scottmarlow** [comment]
Just made a few changes to reference the same product name and version referenced in the TCK results.

**Comment by edbratt** [comment]
This is great news. To avoid confusion, I would recommend the subject of this issue be changed to "Compatible Product ..." (or Compatible Software) instead of Compatibility certification request. The certification request is to the Specification team. This issue is the application to have your product listed on the compatible products page.

**Comment by oliviergoulet5** [comment]
Hey @scottmarlow

WildFly 27.0.0.Alpha1 has been added to the Core profile 

https://deploy-preview-1533--jakartaee.netlify.app/compatibility/certification/10/
https://deploy-preview-1533--jakartaee.netlify.app/compatibility/download/

Let me know if this is good!

/cc @TanjaObradovic

**Comment by TanjaObradovic** [comment]
looks great!

**Comment by scottmarlow** [comment]
@oliviergoulet5 looks great to me as well, thank you for your work on this!
