### ISSUE TITLE
Compatible Software Product request for WildFly 27.0.0.Alpha5 Full Platform/Web Profile 10 

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#1528]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://www.eclipse.org/membership/showMember.php?member_id=731

**A product name and version**

[WildFly 27.0.0.Alpha5](https://wildfly.org/downloads)

**The Profile Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**

Both Full Platform + Web Profile

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

https://github.com/wildfly/certifications/blob/EE8/images/wildfly-logo-stacked-100px-2132977.zip?raw=true

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Red Hat

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

https://github.com/eclipse-ee4j/jakartaee-platform/issues/539 Full Platform 10 (Java SE 11/17)
https://github.com/eclipse-ee4j/jakartaee-platform/issues/540 Web Profile 10 (Java SE 11/17)

**The URL where Compatible Software Product is available for download**

https://wildfly.org/downloads

**Comment by TanjaObradovic** [comment]
Looks good to me!

**Comment by edbratt** [comment]
This is great news. To avoid confusion, I would recommend the subject of this issue be changed to "Compatible Product ..." (or Compatible Software) instead of Compatibility certification request. The certification request is to the Specification team. This issue is the application to have your product listed on the compatible products page.

**Comment by ericpoirier** [comment]
> This is great news. To avoid confusion, I would recommend the subject of this issue be changed to "Compatible Product ..." (or Compatible Software) instead of Compatibility certification request. The certification request is to the Specification team. This issue is the application to have your product listed on the compatible products page.

Hi @edbratt, I'd suggest opening an issue to update the issue template.

Thanks.

**Comment by oliviergoulet5** [comment]
Hey @scottmarlow 

WildFly 27.0.0.Alpha5 has been added to web and full platform profiles:

https://deploy-preview-1533--jakartaee.netlify.app/compatibility/certification/10/
https://deploy-preview-1533--jakartaee.netlify.app/compatibility/download/

Let me know if this is good!

/cc @TanjaObradovic

**Comment by TanjaObradovic** [comment]
looks good!
