### ISSUE TITLE
Compatible Software Product Request for Payara Server Community 6.2022.1.Alpha3 for Core Profile 10.0

### ISSUE THREAD

**Issue by Pandrex247** [jakartaee/jakarta.ee#1529]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://accounts.eclipse.org/users/apielagewgt

**A product name and version**
Payara Server Community 6.2022.1.Alpha3

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**
Core Profile 10.0

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[community-logo-on-white-transparent-RGB.zip](https://github.com/jakartaee/jakarta.ee/files/9605791/community-logo-on-white-transparent-RGB.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Payara Services Ltd

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/533

**The URL where Compatible Software Product is available for download**
https://www.payara.fish/downloads/payara-platform-community-edition/

**Comment by oliviergoulet5** [comment]
Hey @Pandrex247

I have a preview of the change here:
https://deploy-preview-1535--jakartaee.netlify.app/compatibility/certification/8/
https://deploy-preview-1535--jakartaee.netlify.app/compatibility/download/

Let me know if it is good!

/cc @TanjaObradovic

**Comment by TanjaObradovic** [comment]
Looks great!

**Comment by TanjaObradovic** [comment]
Looks great!
