### ISSUE TITLE
Please add RockyAS 1.0 as Jakarta EE 8 Full Platform compatible

### ISSUE THREAD

**Issue by dingjiang838** [jakartaee/jakarta.ee#1532]
The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting
https://www.eclipse.org/membership/showMember.php?member_id=1579

A product name and version
RockyAS 1.0

The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under
Full Platform

A ZIP file with a product logo with a transparent background in SVG format (optional)
https://rockyasfile.obs-cn-shenzhen.pinganyun.com/RockyAS.svg

The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product
Shenzhen Ping An Communication Technology Co., Ltd

The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process
eclipse-ee4j/jakartaee-platform#546

The URL where Compatible Software Product is available for download
https://rockyasfile.obs-cn-shenzhen.pinganyun.com/RockyAS.html

**Comment by oliviergoulet5** [comment]
Hey @dingjiang838 

I have added RockyAS 1.0 to the Full Platform Profile for Jakarta EE 8:

https://deploy-preview-1534--jakartaee.netlify.app/compatibility/certification/8/
https://deploy-preview-1534--jakartaee.netlify.app/compatibility/download/

Let me know if this looks good!

/cc @TanjaObradovic

**Comment by TanjaObradovic** [comment]
Looks good!
