### ISSUE TITLE
Open Liberty 22.0.0.10-beta as a Compatible Software Product for Jakarta EE 10

### ISSUE THREAD

**Issue by brideck** [jakartaee/jakarta.ee#1537]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Brian Decker - IBM - Eclipse Profile](https://accounts.eclipse.org/users/bdeckerhdt)

**A product name and version**
[Open Liberty 22.0.0.10-beta](https://openliberty.io/)

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**
Core Profile

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[https://openliberty.io/certifications/assets/OL_logomark.zip](https://openliberty.io/certifications/assets/OL_logomark.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[IBM Corporation](https://www.ibm.com/)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Core Profile, Java 11: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/544](https://github.com/eclipse-ee4j/jakartaee-platform/issues/544)
Core Profile, Java 17: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/545](https://github.com/eclipse-ee4j/jakartaee-platform/issues/545)

**The URL where Compatible Software Product is available for download**
[https://openliberty.io/start/#runtime_betas](https://openliberty.io/start/#runtime_betas)

**Comment by oliviergoulet5** [comment]
@brideck 

I have added these under Core profile 10. Preview the changes here:
https://deploy-preview-1540--jakartaee.netlify.app/compatibility/certification/10/
https://deploy-preview-1540--jakartaee.netlify.app/compatibility/download/

Let me know if this is good

/cc @TanjaObradovic

**Comment by TanjaObradovic** [comment]
great to see! looks good!
