### ISSUE TITLE
FJ-EAP 1.1.0 as a Compatible Software Product for Jakarta EE 10 Full Platform

### ISSUE THREAD

**Issue by hs536** [jakartaee/jakarta.ee#1538]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

[Fujitsu Limited](https://www.eclipse.org/membership/showMember.php?member_id=685)

**A product name and version**

FUJITSU Software Enterprise Application Platform 1.1.0

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**

Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

[EAP.zip](https://github.com/jakartaee/jakarta.ee/files/9612602/EAP.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Fujitsu Limited

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

https://github.com/eclipse-ee4j/jakartaee-platform/issues/541

**The URL where Compatible Software Product is available for download**

https://www.fujitsu.com/jp/software/applatform/

**Comment by TanjaObradovic** [comment]
@oliviergoulet5 can you please look into this?

**Comment by oliviergoulet5** [comment]
@TanjaObradovic I'll get this done for today.

**Comment by TanjaObradovic** [comment]
Many thanks!

**Comment by oliviergoulet5** [comment]
Here are the previews:
https://deploy-preview-1555--jakartaee.netlify.app/compatibility/
https://deploy-preview-1555--jakartaee.netlify.app/compatibility/certification/10/
https://deploy-preview-1555--jakartaee.netlify.app/compatibility/download/

**Comment by TanjaObradovic** [comment]
Looking good! thx!!
