### ISSUE TITLE
SEO Optimization for Jakarta EE 10 release page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1547]
I've reviewed the new Jakarta EE 10 release page at the request of @shabnammayel for SEO optimization. I have a few recommendations:

We need to make sure heading tags are not separated. Please combine these headings into one header tag using span tags for the different styles and a line break tag. e.g. <h2><span class="blue-text">Jakarta EE 10</span><br><span class="orange-text">Features and Benefits</span><h2>

3 places to fix:

![image](https://user-images.githubusercontent.com/73264129/192609692-1b220665-0dfc-4e5f-8f90-74fc5c338c66.png)

![image](https://user-images.githubusercontent.com/73264129/192610451-bd6d360f-aa2f-454b-9065-4f610059fd21.png)

![image](https://user-images.githubusercontent.com/73264129/192612318-f32f351a-8108-435a-ba55-599915e488b8.png)

Remove the h3 tags from the contributor names under community powered innovation and replace with styled p tags.

Remove heading tags from this section (would be nice visually if all the numbers could be on the same line but not an SEO thing):
![image](https://user-images.githubusercontent.com/73264129/192611117-331f3426-7e1e-43b9-a702-b8ff7848643e.png)

Change the alt tag on this image to read: "New and Updated Specifications in Jakarta EE 10"
![image](https://user-images.githubusercontent.com/73264129/192612905-97b3f0fa-2295-4c3c-bfdb-950a6eb617c6.png)

Add link at the bottom of the main banner "View all Releases" to the main release page: https://jakarta.ee/release/

Remove "New Release" in the main banner on this page: https://jakarta.ee/release/9.1/

Change title tag to read:
Jakarta EE 10 Release | Java EE 10 | Download Compatible Products & Specifications | The Eclipse Foundation

Change meta description tag to read:
The Jakarta EE 10 release is here. Modern, simplified & lightweight, see what's new in the Jakarta EE 10 Specifications.

**Comment by oliviergoulet5** [comment]
Thanks @excentrickristy for the great feedback on the site's SEO. I will begin to make these changes!

**Comment by ericpoirier** [comment]
Hi @excentrickristy, I made the requested changes to the following staging page:

https://deploy-preview-1552--jakartaee.netlify.app/release/10/

Let me know if I missed anything.

Thanks.

**Comment by excentrickristy** [comment]
Hi Eric,
Looking good!! Just a few things outstanding:

All of the h2 header tags that have the blue and orange words still need to be combined into one solid h2 tag so that they aren't treated separately.

The h3 tags from the contributor names need to be removed.

Thanks

**Comment by ericpoirier** [comment]
> Hi Eric, Looking good!! Just a few things outstanding:
> 
> All of the h2 header tags that have the blue and orange words still need to be combined into one solid h2 tag so that they aren't treated separately.
> 
> The h3 tags from the contributor names need to be removed.
> 
> Thanks

Hi @excentrickristy,

I updated the H2 and H3 tags.

https://deploy-preview-1552--jakartaee.netlify.app/release/10/

Let me know if there's anything else.

Thanks.

**Comment by excentrickristy** [comment]
Just one thing - can you add a space at the end of the first line of the h2 tags?
![image](https://user-images.githubusercontent.com/73264129/193666235-3409b9e8-6f57-4a8c-9447-33fb66d4ffb8.png)

**Comment by ericpoirier** [comment]
> Just one thing - can you add a space at the end of the first line of the h2 tags? ![image](https://user-images.githubusercontent.com/73264129/193666235-3409b9e8-6f57-4a8c-9447-33fb66d4ffb8.png)

Hi @excentrickristy, I added spaces to the H2 tags on the staging page.

Let me know if there's anything else.

Thanks.

**Comment by excentrickristy** [comment]
Looks good, thank you!
