### ISSUE TITLE
Compatible Software Product request for WildFly 27.0.0.Alpha5 Core Profile 10

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#1548]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://www.eclipse.org/membership/showMember.php?member_id=731

**A product name and version**

[WildFly 27.0.0.Alpha5](https://github.com/wildfly/wildfly/releases/download/27.0.0.Alpha5/wildfly-27.0.0.Alpha5.zip)

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**

Core Profile

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

https://github.com/wildfly/certifications/blob/EE8/images/wildfly-logo-stacked-100px-2132977.zip?raw=true

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Red Hat

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

https://github.com/eclipse-ee4j/jakartaee-platform/issues/555 (Java SE 17) is for WildFly 27.0.0.Alpha5

https://github.com/eclipse-ee4j/jakartaee-platform/issues/556 (Java SE 11) is for WildFly 27.0.0.Alpha5

**The URL where Compatible Software Product is available for download**

[WildFly 27.0.0.Alpha5](https://github.com/wildfly/wildfly/releases/download/27.0.0.Alpha5/wildfly-27.0.0.Alpha5.zip)

Please note that `WildFly Preview` is a separate product than `WildFly` and for that reason, this is for the `WildFly` product.

**Comment by ZacharySabourin** [comment]
@scottmarlow A preview of the requested changes is available here: https://deploy-preview-1549--jakartaee.netlify.app/compatibility/

**Comment by scottmarlow** [comment]
Thanks @ZacharySabourin!

Question:  Would it be possible to show four separate entries?  Perhaps something like:

```
Product                Certification Results 
-------------------        --------------------------------------------
WildFly                  27.0.0.Alpha5 Java SE 17
                               27.0.0.Alpha5, Java SE 11

WildFly Preview   27.0.0.Alpha1, Java SE 17
                               27.0.0.Alpha1, Java SE 11

```

OR

```
Product                Certification Results 
-------------------        --------------------------------------------
WildFly                   WildFly 27.0.0.Alpha5 Java SE 17
                               WildFly 27.0.0.Alpha5, Java SE 11
                               WildFly Preview 27.0.0.Alpha1, Java SE 17
                               WildFly Preview 27.0.0.Alpha1, Java SE 11

```

Thank you!

**Comment by ZacharySabourin** [comment]
@scottmarlow Not a problem! I've re-added the previous versions to the preview: https://deploy-preview-1549--jakartaee.netlify.app/compatibility/

**Comment by scottmarlow** [comment]
@ZacharySabourin the preview doesn't match either of ^ but is close to the second one.  Under the `Certification Results` column, could the entries for `27.0.0.Alpha5` be changed to not mention `Preview` but do leave the `Preview` next to the Alpha1 ones?

```
Product                Certification Results 
----------             ----------------------------------
WildFly                27.0.0.Alpha5, Java SE 17
                       27.0.0.Alpha5, Java SE 11
                       Preview 27.0.0.Alpha1, Java SE 17
                       Preview 27.0.0.Alpha1, Java SE 11
```

**Comment by ZacharySabourin** [comment]
@scottmarlow My apologies! I must have misread. The preview should reflect the correct changes: https://deploy-preview-1549--jakartaee.netlify.app/compatibility/certification/10/

**Comment by scottmarlow** [comment]
Looks excellent @ZacharySabourin!  Thank you!

**Comment by autumnfound** [comment]
Once the certification is approved, we can merge this in!

**Comment by ericpoirier** [comment]
@scottmarlow will you report back once the certification has been approved?

**Comment by scottmarlow** [comment]
@ericpoirier yes I will!

**Comment by scottmarlow** [comment]
@ericpoirier the https://github.com/eclipse-ee4j/jakartaee-platform/issues/555 + https://github.com/eclipse-ee4j/jakartaee-platform/issues/556 are both marked as `accepted` which I think means they are `approved`.

**Comment by ericpoirier** [comment]
> @ericpoirier the [eclipse-ee4j/jakartaee-platform#555](https://github.com/eclipse-ee4j/jakartaee-platform/issues/555) + [eclipse-ee4j/jakartaee-platform#556](https://github.com/eclipse-ee4j/jakartaee-platform/issues/556) are both marked as `accepted` which I think means they are `approved`.

Ok will look at merging the changes of the website to production.

**Comment by TanjaObradovic** [comment]
yes all is approved!
