### ISSUE TITLE
Updating Committees Participant lists

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1556]
Can you please update 
**https://jakarta.ee/committees/marketing/**, Committee Members list with (the change is in bold text here; on the website no need to need to bold)

Kenji Kazumura - Fujitsu, Yuichi Kusano - alternate
Neil Patterson (chair) - IBM
Ed Bratt - Oracle, Melissa Jacobus - alternate
Dominika Tasarz - Payara, Jadon Ortlepp - alternate
Jonathan Gallimore - Tomitribe, Cesar Hernandez - alternate
Eric (QingYu) Meng - Primeton - Elected Enterprise Representative
**Reza Rehman - Microsoft - Elected Enterprise Representative, Ed Burns - alternate**
Otavio Santana - Elected Committer Member Representative

Also please update 
**https://jakarta.ee/committees/specification/**, Committee Members list with (the change is in bold text here; on the website no need to need to bold)

Kenji Kazumura - Fujitsu
Tom Watson - IBM, Emily Jiang - alternate
Ed Bratt - Oracle, Dmitry Kornilov - alternate
Andrew Pielage - Payara, Petr Aubrecht - alternate
David Blevins - Tomitribe, Jean-Louis Monterio - alternate
Ivar Grimstad - PMC Representative
Marcelo Ancelmo - London Java Community - Elected Participant Member Representative, Martijn Verburg - alternate
Werner Keil - Elected Committer Member Representative
**Scott Stark - Red Hat- Elected Enterprise Representative, Scott Marlow - alternate**
Zhai Luchao - Shandong Cvicse Middleware Co. - Elected Enterprise Representative
Paul Buck - Eclipse Foundation (serves as chair, but is not a voting committee member)

Also please update 
**https://jakarta.ee/committees/steering/**, Committee Members list with (the change is in bold text here; on the website no need to need to bold)

Will Lyons (chair)- Oracle, Ed Bratt - alternate
Kenji Kazumura - Fujitsu, Yuichi Kusano - alternate
Ian Robinson - IBM, Alasdair Nottingham - alternate
Steve Millidge - Payara, Hadar Vorenshtein - alternate
David Blevins - Tomitribe, Cesar Hernandez - alternate
Martijn Verburg - London Java Community - Elected Participant Member Representative, Marcelo Ancelmo - alternate
Arjan Tijms - Elected Committer Member Representative
Dr. Jun Qian - Primeton - Elected Enterprise Representative
**Reza Rahman - Microsoft - Elected Enterprise Representative, Ed Burns - alternate**

**Comment by paulbuck** [comment]
For the Specification Committee, please use the following text for me...
Paul Buck - Eclipse Foundation (serves as its non-voting chair)

**Comment by oliviergoulet5** [comment]
I added your highlighted changes @TanjaObradovic as well as removed some names which did not appear in your list:
- Dr. Jun Qian from https://jakarta.ee/committees/specification/
- Zhao Xin from https://jakarta.ee/committees/steering/ and https://jakarta.ee/zh/committees/marketing/

Let me know if these any of these names should not of been removed.

@paulbuck I also updated your text. 

You can preview the changes here:
- [/marketing page](https://deploy-preview-1557--jakartaee.netlify.app/committees/marketing/)
- [/specification page](https://deploy-preview-1557--jakartaee.netlify.app/committees/specification/)
- [/steering page](https://deploy-preview-1557--jakartaee.netlify.app/committees/steering/)

**Comment by TanjaObradovic** [comment]
I made a mistake!

At the Steering Committee line 

instead of 

Martijn Verburg - London Java Community - Elected Participant Member Representative, Marcelo Ancelmo - alternate

it should be 

**Marcin Kruglik - London Java Community - Elected Participant Member Representative, Martijn Verburg - alternate**

**Comment by shabnammayel** [comment]
Can we please reopen this issue? it looks like the list that is live on the page does not match what @TanjaObradovic provided here

**Comment by shabnammayel** [comment]
the Marketing and Steering Committee information to be adjusted based on the Election Results of Oct 3rd:





The elections closed on Friday, September 30, 2022 , and we are pleased to announce the 2022-2023 elected representatives for the Jakarta EE Committees are:

Steering Committee Representatives:
Enterprise Members
Reza Rehman, Microsoft
Jun Qian, Primeton Information Technologies, Inc
Participant Members
Marcin Kruglik, London Jamocha Community

Specification Committee Representatives:
Enterprise Members
Scott Stark, Red Hat
Zhai Luchao, Shandong Cvicse Middleware Co., Ltd
Participant Members
Marcelo Ancelmo, London Jamocha Community

Marketing and Brand Committee Representatives:
Enterprise Members
Reza Rahman, Microsoft
Eric Meng, Primeton Information Technologies, Inc


Vacant Seats
Committer Representative, Steering Committee
Participant Member Representative, Marketing and Brand Committee
Please note that the aforementioned seats remain vacant due to no nominations.

**Comment by oliviergoulet5** [comment]
Hi @shabnammayel. Let me know if this is correct: https://deploy-preview-1584--jakartaee.netlify.app/committees.

**Comment by oliviergoulet5** [comment]
Hey @shabnammayel, just wondering if you're still tracking this.

/cc @TanjaObradovic

**Comment by shabnammayel** [comment]
Apologies @oliviergoulet5 I thought I replied! yes, LGTM! thanks
