### ISSUE TITLE
Update Meta Title Tag on Release Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1559]
Would like to remove the version from the release page title tag.

New Title Tag: 
Jakarta EE Releases | Download the Latest Version of Jakarta EE (Java EE) | The Eclipse Foundation

**Comment by oliviergoulet5** [comment]
I removed the version number from the meta tag. Please check https://deploy-preview-1560--jakartaee.netlify.app/ to see the changes.

Let me know if its good @excentrickristy.

**Comment by excentrickristy** [comment]
Looks good! Thanks.
