### ISSUE TITLE
SEO Improvements for Specifications Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1562]
I think some of the original meta changes were lost when the new design was applied to the specifications page. 

New Title Tag:
Jakarta EE Specifications | The Eclipse Foundation

New Meta Description:
Browse Jakarta EE Specifications, including Jakarta EE Platform, Profile, and individual specification documents.

H1:
Change from Specifications to Jakarta EE Specifications

The orange titles on the page should be h2 and the specs themselves should be h3
![image](https://user-images.githubusercontent.com/73264129/194611901-a8b3dbb0-30d0-421b-9d5b-2edfcd00d327.png)

**Comment by oliviergoulet5** [comment]
Hey @excentrickristy 

I updated the headings, title, and meta description here: https://deploy-preview-1565--jakartaee.netlify.app/specifications/

Let me know if it's good!

**Comment by excentrickristy** [comment]
Just one thing - the individual specs should be h3
![image](https://user-images.githubusercontent.com/73264129/195373782-6fbd1e07-2e08-4410-925a-db6322ea088f.png)

**Comment by oliviergoulet5** [comment]
My bad. I fixed that here: https://deploy-preview-1565--jakartaee.netlify.app/specifications/

**Comment by excentrickristy** [comment]
Great, thanks!
