### ISSUE TITLE
Content Issue on Specification Pages

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1563]
The static content from the main specifications page is being repeated on every specification page. I don't believe this is intentional.

This is the main spec page:
![image](https://user-images.githubusercontent.com/73264129/194613765-389e2de6-9edd-4c6d-92e8-695b4b5a3ffe.png)

This is the bottom of the platform 10 spec page: https://jakarta.ee/specifications/platform/10/
![image](https://user-images.githubusercontent.com/73264129/194613825-fe19b4e2-35a0-48f0-b255-14bde1be8456.png)

This is the bottom of the jakarta activation page: https://jakarta.ee/specifications/activation/1.2/
![image](https://user-images.githubusercontent.com/73264129/194613948-0bb49467-7f46-4f7d-ba94-372a6479d40a.png)

And the same content can be found on every detailed spec page.

**Comment by ericpoirier** [comment]
I created a pull request to update the specifications section.

https://deploy-preview-1564--jakartaee.netlify.app/specifications/

The duplicate text is now gone on sub pages.

Let me know if there's anything else.

Thanks.

**Comment by excentrickristy** [comment]
Great, looks good!
