### ISSUE TITLE
update to the Steering and Specification Committee list

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1566]
Can we please update the Steering and Specification Committee list
**https://jakarta.ee/committees/specification/**
it should be 
Marcelo Ancelmo - London Java Community - Elected Participant Member Representative
_delete_ 
, Martijn Verburg - alternate

**https://jakarta.ee/committees/steering/**
it should be 
Marcin Kruglik - London Java Community - Elected Participant Member Representative
_delete_ 
, Martijn Verburg - alternate

**Comment by oliviergoulet5** [comment]
Hey @TanjaObradovic here are the preview pages: 

- [Specification Committee](https://deploy-preview-1567--jakartaee.netlify.app/committees/specification/)
- [Steering Committee](https://deploy-preview-1567--jakartaee.netlify.app/committees/steering/)

**Comment by TanjaObradovic** [comment]
I am so sorry, but I got a new update from the community 

https://jakarta.ee/committees/specification/
it should be
Marcelo Ancelmo - London Java Community - Elected Participant Member Representative, Abraham Marin-Perez - alternate

https://jakarta.ee/committees/steering/
it should be
Marcin Kruglik - London Java Community - Elected Participant Member Representative, Abraham Marin-Perez - alternate

this should be final update!

**Comment by oliviergoulet5** [comment]
Here are the links @TanjaObradovic:

Specification Committee: https://deploy-preview-1567--jakartaee.netlify.app/committees/specification/
Steering Committee: https://deploy-preview-1567--jakartaee.netlify.app/committees/steering/

**Comment by TanjaObradovic** [comment]
looks great! thanks!

**Comment by TanjaObradovic** [comment]
@oliviergoulet5 @ericpoirier please note that what's on the website is not what showing at
Specification Committee: https://deploy-preview-1567--jakartaee.netlify.app/committees/specification/
Steering Committee: https://deploy-preview-1567--jakartaee.netlify.app/committees/steering/

Can we correct that please?

**Comment by oliviergoulet5** [comment]
It looks like the list was overwritten. Does this look correct @TanjaObradovic ?

https://deploy-preview-1593--jakartaee.netlify.app/committees/specification/
https://deploy-preview-1593--jakartaee.netlify.app/committees/steering/

Abraham Marin-Perez was added to both committees

**Comment by TanjaObradovic** [comment]
That looks correct. Thanks!
