### ISSUE TITLE
Create a "Why Jakarta EE" page 

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1568]
Please create the "Why Jakarta EE" page on the Jakarta EE website. Here is the mock up for the page: 

https://docs.google.com/document/d/1XotrupJGqbaxfgPYbm9RNFGBZyfHst5oGn1CaFDkSAw/edit#

We have a placeholder for the video as well. I will share the video next week. 

This page should be added under about, below About Jakarta EE. and also on the homepage, in the Get informed box, under Browse specifications. thanks

**Comment by oliviergoulet5** [comment]
Hey Shabnam, you shared a link which I do not have access to. I have sent an email requesting access.

**Comment by shabnammayel** [comment]
done! thanks

**Comment by oliviergoulet5** [comment]
Do we want to convert the bolded text into proper headings? It is more [accessible](https://usability.yale.edu/web-accessibility/articles/headings) and is better for SEO. However, this will require for the bolded text of the last two sections to be separate from their paragraphs. 

Example:

"**Jakarta EE is innovative**, Jakarta EE opens the door to cloud native..."

would become:

## Jakarta EE is innovative
Jakarta EE opens the door to cloud native...

**Comment by shabnammayel** [comment]
Apologies after reading your comment I realized that the link to the mockup has not been pasted! 

https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/470049812


Kindly follow the mockup for the format of the headings, etc. I shared the copy in a google doc to make it easier for you to copy and paste the content. 

but now realized the mock up link has not been added here! my bad!

**Comment by oliviergoulet5** [comment]
No worries! I'll get started now.

**Comment by oliviergoulet5** [comment]
Is there a deadline for this @shabnammayel?

**Comment by shabnammayel** [comment]
It would be great if we can go live by 8 Nov.

**Comment by oliviergoulet5** [comment]
@shabnammayel Sorry for pinging again, hopefully this is the last thing. Do you have the assets for the page?

**Comment by shabnammayel** [comment]
No worries! @excentrickristy can you please help with the assets for this page? thanks

**Comment by excentrickristy** [comment]
Here you go! https://www.dropbox.com/sh/1ee030udxuayir8/AADLBBKopdV8TgDeycvxdgxaa?dl=0

**Comment by oliviergoulet5** [comment]
Just to update you all, I am around 75% done with the page. I should have a preview for you by the first half of next week!

@excentrickristy I'm missing the following assets:
- [x] The icons beside the section headers
- [x] All of the logos under "Jakarta EE is Ubiquitous" (the shirt was provided but it does not have a transparent background)
- [x] The gray & white graph images which are overlapping with the section images
- [x] The icons for the cards at the very last section

@shabnammayel One question:
- Am I making the logos links to their website? If yes, I'll need the URLs.

**Comment by excentrickristy** [comment]
Hi @oliviergoulet5, 
I have exported everything you need into the dropbox folder but I could only get the full patterns to export, not just the patterns that were on the artboard. Let me know if you need me to call on a designer for that.

Thanks!

**Comment by oliviergoulet5** [comment]
Thanks @excentrickristy!

I just need one more icon for the "download compatible products" card on the last section. 

I'm thinking having the full patterns that you provided won't cause any issues. It's probably better this way too.

**Comment by excentrickristy** [comment]
No problem, just added the last icon!

**Comment by oliviergoulet5** [comment]
@shabnammayel here is a preview link of the page:

https://deploy-preview-1577--jakartaee.netlify.app/about/why-jakarta-ee/

**Comment by excentrickristy** [comment]
HI @oliviergoulet5, I think @shabnammayel is out of the office right now but I noticed that the video functionality is missing. The laptop at the top of the page is supposed to have a play button on the screen. When you click, it should open a popup to play a video but I'm not sure if it's been uploaded to YouTube yet.

**Comment by oliviergoulet5** [comment]
Oh, I assumed it was to be an embedded player into the jumbotron. I will update.

I was going to wait for the video before displaying. But what I will do now is display some temporary video for the preview and replace it later when we get the proper one.

**Comment by oliviergoulet5** [comment]
Hi @shabnammayel and @excentrickristy . The video popup modal has been added. For an embedded video player to display, you need to accept cookies. Let me know when the video is uploaded.

**Comment by shabnammayel** [comment]
@oliviergoulet5 thanks, I have shared the final version of the video with Jacob to upload on Jakarta EE YouTube channel. But we have decided to launch and promote the page and the video on Dec 7 after the JakartaOne Livestream event. Currently we have a lot to share on socials (Jakarta EE 10 related content and Livestream). I went through our Jakarta EE website google analytics and looks like traffic to the website is very similar in Dec, January and February. So makes sense to launch on Dec 7. We will have a discussion on the MKT CMTE call tomorrow as there seems to be some suggestion for further edits to the design. I will update you soon! thanks for the updates so far! looks good!

**Comment by excentrickristy** [comment]
Hello,
We have added a sub nav to the design that should anchor to each section within the page.
You can grab the source files here: https://www.dropbox.com/s/5zm9hk9zgruz0pl/why%20jakarta.zip?dl=0

Here is a preview of what it looks like:
![Picture2](https://user-images.githubusercontent.com/73264129/204035776-2bd2f69a-85fb-4ce2-80f3-17a427cf120e.jpg)

**Comment by oliviergoulet5** [comment]
@excentrickristy By "anchor to each section" do you mean it will scroll and snap atop each section?

My apologies if it's animated in the Adobe Illustrator file. I need to figure a way to open it since I don't have the software. Is there any chance that it can be exported as a video or a gif? And if there's no animation then please disregard my comment.

**Comment by excentrickristy** [comment]
@oliviergoulet5 yes just a normal anchor to each section. Smooth scroll would be nice!

You can open an AI file at https://www.photopea.com/ but the linked images don't always come through. The part you need is not a linked image though so it should work for you just for this!

**Comment by oliviergoulet5** [comment]
@shabnammayel @excentrickristy The sub nav is up as well as the video. Do we have a +1 to go live?

**Comment by excentrickristy** [comment]
@oliviergoulet5 looks good, just wondering if we can put some negative top margin on the page content so that the sub nav sits a little higher up?

**Comment by shabnammayel** [comment]
+1 to Kristy's suggestion. We should be good to go live after that.

**Comment by oliviergoulet5** [comment]
@excentrickristy The nav is now higher up. Let me know if its a good height.

**Comment by excentrickristy** [comment]
Much better! I have just one more tiny suggestion. Can we add a hover state to the nav buttons to make it more obvious that they are clickable? I was thinking a solid blue background/border with white text on hover.

**Comment by oliviergoulet5** [comment]
Ok, I added the hover state on the nav buttons.

**Comment by excentrickristy** [comment]
beautiful!! I think it's ready to go live now.

**Comment by oliviergoulet5** [comment]
@excentrickristy @shabnammayel We deployed the page but then realized it wasn't linked anywhere. Should I add it to the _about_ menu here:

![image](https://user-images.githubusercontent.com/17685861/207061492-5c549418-9c1c-45a8-904a-2843d02ed433.png)

**Comment by shabnammayel** [comment]
@oliviergoulet5 yes I mentioned it in the beginning in the description but this issue was created a long time ago so naturally it got lost :) 
Here is what I added: 
This page should be added under about, below About Jakarta EE. and also on the homepage, in the Get informed box, under Browse specifications. thanks

**Comment by oliviergoulet5** [comment]
Oh right. My bad lol

**Comment by oliviergoulet5** [comment]
Here is a preview of the links: https://deploy-preview-1601--jakartaee.netlify.app/

**Comment by oliviergoulet5** [comment]
Here is a preview of the links: https://deploy-preview-1601--jakartaee.netlify.app/

**Comment by shabnammayel** [comment]
LGTM! can we go live today? @oliviergoulet5 FYI @jph152

**Comment by oliviergoulet5** [comment]
Now live @shabnammayel
