### ISSUE TITLE
Remove 1 on the title of the "get involved in Jakarta EE" page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1569]
<img width="679" alt="Screen Shot 2022-10-19 at 1 29 22 PM" src="https://user-images.githubusercontent.com/51449073/196763044-c5c69fc6-4612-43b6-9977-50a95c5feed7.png">
 

As you can see in the screenshot there is "1" after Jakarta EE in the title that should be removed. 

Also I noticed that "Get involved" is not placed on the menu bar on an alphabetic order unlike other items there:
<img width="227" alt="Screen Shot 2022-10-19 at 1 30 40 PM" src="https://user-images.githubusercontent.com/51449073/196763303-67523c4a-f2e0-44d8-a87d-bbb24225c085.png">

Kindly move it after events on the menu bar. thanks

**Comment by autumnfound** [comment]
I have a feeling that 1 is a typo and it was supposed to be a `!`. Do you want to just remove the 1, or replace it with a `!`?

**Comment by shabnammayel** [comment]
Good point! please replace with !

**Comment by oliviergoulet5** [comment]
Here is a preview link of the changes: https://deploy-preview-1570--jakartaee.netlify.app/community/get-involved/

Let me know if it is good to go live!

**Comment by shabnammayel** [comment]
LGTM! thanks
