### ISSUE TITLE
Newsroom API sends broken author data

### ISSUE THREAD

**Issue by Dexmaster** [jakartaee/jakarta.ee#1576]
Related to https://github.com/jakartaee/jakarta.ee/issues/1321 change, eclipse newsroom API sends broken author data and breaks avatars in the news section.

![image](https://user-images.githubusercontent.com/6061000/197808363-af2cfc57-5dff-4106-abb9-a24976fe4eae.png)
URL: https://jakarta.ee/news/

I think the easiest would be UI fix the default avatar. Or never sending an Anonymous author from newsroom API.

P.S. Created new issue as per https://github.com/jakartaee/jakarta.ee/issues/1492 discussion

**Comment by ericpoirier** [comment]
The issue here is that the author of this news item stopped working at the Eclipse Foundation and the user doens't exist in our database anymore which is why we see "Anonymous" as the author. I think we need to alter the news endpoint on newsroom.eclipse.org to remove the author if anonymous.

**Comment by ericpoirier** [comment]
This is now fixed on the news page of the Jakarta EE website.

Let me know if there's anything else.

Thanks.
