### ISSUE TITLE
'Find the Latest Events' link from /resources page seems broken

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1578]
**Describe the bug**
`Find the Latest Events` link in /resources page redirects to /resources. is this intended?

**To Reproduce**
1. Go to https://jakarta.ee/resources/
2. Click on `.Find the Latest Events`
3. The links redirect to `https://jakarta.ee/resources/#`

**Expected behavior**
I don't know what should be the correct page, but the link currently redirects to the same /resources page.

**Comment by ericpoirier** [comment]
@cesarhernandezgt i believe this should go to a page on the jakartaone.org website.

@shabnammayel can you confirm the exact page where this link should go?

Thanks.

**Comment by shabnammayel** [comment]
yes @ericpoirier this link should go to the JakartaOne Livestream page. @cesarhernandezgt thanks for pointing it out.

**Comment by oliviergoulet5** [comment]
Here is a preview of the fix @shabnammayel: 

https://deploy-preview-1580--jakartaee.netlify.app/resources/#livestream

**Comment by shabnammayel** [comment]
LGTM! thanks @oliviergoulet5

**Comment by cesarhernandezgt** [comment]
Thank you all!
