### ISSUE TITLE
Do we have 2021 and 2022 Infographics for https://jakarta.ee/resources/ page?

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1579]
Hello,
Currently, the page https://jakarta.ee/resources/ shows infographics for Jakarta EE Developer Survey Findings 2018 and 2020 [1]. 
Do we have infographics for the 2021 and/or 2022 editions?

cc: @shabnammayel @TanjaObradovic 

[1]
![image](https://user-images.githubusercontent.com/1454523/200952734-4b442a99-beaa-4671-bae4-47df2f1c2fd2.png)

**Comment by shabnammayel** [comment]
Yes we do have the 2021 version and promoted on socials to tease the launch of the 2022 survey but good point, it should be added on the site. Here is the link: https://f.hubspotusercontent30.net/hubfs/4753786/Jakarta%20EE%202021%20Developer%20Survey%20Recap.pdf?utm_campaign=Jakarta%20EE%20Developer%20Survey&utm_content=198861406&utm_medium=social&utm_source=twitter&hss_channel=tw-939323243076259842

the 2022 version of the infographic will be launched and promoted early 2023 before the launch of the 2023 developer survey.

**Comment by shabnammayel** [comment]
and can we please reorder the findings? the latest one should be on the top similar to the Jakarta EE survey box. @ericpoirier thanks

**Comment by shabnammayel** [comment]
Here is the pdf version to be able to host it on Jakarta's domain: [Infographic-V22.pdf](https://github.com/jakartaee/jakarta.ee/files/9983930/Infographic-V22.pdf)

**Comment by oliviergoulet5** [comment]
@shabnammayel Here is a preview link: https://deploy-preview-1581--jakartaee.netlify.app/resources/#surveys

/cc @cesarhernandezgt

**Comment by shabnammayel** [comment]
LGTM! thanks

**Comment by cesarhernandezgt** [comment]
Thank you much @shabnammayel and @oliviergoulet5 !
