### ISSUE TITLE
Update the content of Tthe Jakarta EE membership prospectus 

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1585]
We need to update page 9 of the Prospectus. 

https://jakarta.ee/documents/membership/jakarta-ee-membership-prospectus.pdf

the text under the section for Guest members need to be replaced with the text below: 

Guest Members are organizations which are Associate members of the Eclipse Foundation that wish to participate in particular aspects of the activities of the Working Group. Typical guests include JUGs, R&D partners, universities, academic research centers, etc. Guests may be invited to participate in committee meetings at the invitation of the respective committee, but under no circumstances do Guest members have voting rights. Guest members are required to execute the Jakarta EE Working Group Participation Agreement.

thanks

**Comment by shabnammayel** [comment]
and the steering committee section on page 8 also needs some edits:

on the third paragraph, this section needs to be removed: Strategic Members of the Jakarta EE Working Group are required to commit to strategic membership for a three (3) year period.

**Comment by ericpoirier** [comment]
Hi @shabnammayel, 

Since this is a PDF, marketing will need to update the PDF and then provide the updated version here on this issue.

**Comment by shabnammayel** [comment]
@meKokabi can you please help with this? do we need a gitlab issue for it, Mehrnaz? thanks

**Comment by meKokabi** [comment]
@shabnammayel Yes please make an issue for it, so do I can have a better track on my to-do list.

**Comment by ericpoirier** [comment]
@shabnammayel @meKokabi any news on the new PDF?

Thanks.

**Comment by meKokabi** [comment]
Hi @ericpoirier Thanks for following up, I haven't started to work on it, as was busy with some priorities. will work on it shortly.

**Comment by meKokabi** [comment]
Hi @ericpoirier Here you are: 
[jakarta-ee-membership-prospectus.pdf](https://github.com/jakartaee/jakarta.ee/files/10107115/jakarta-ee-membership-prospectus.pdf)

**Comment by oliviergoulet5** [comment]
Here is a preview of the change @shabnammayel 

https://deploy-preview-1600--jakartaee.netlify.app/membership/#benefits
