### ISSUE TITLE
Review Footer links

### ISSUE THREAD

**Issue by ericpoirier** [jakartaee/jakarta.ee#1586]
While updating the Jekyll theme for Jakarta EE, we noticed that some links in the footer looks off.

In the useful links section, there's a Marketplace link going to the compatibility page. I want to make sure that this is intended and is not an error.

@shabnammayel can you validate all links in this section to make sure they are going to the right place?

Thanks.

**Comment by ivargrimstad** [comment]
Yes, there is no Marketplace for Jakarta EE, and the compatibility page is the closest we get. If possible, change the name of the link.

**Comment by shabnammayel** [comment]
+1 to Ivar's comment, Compatibility page is the closest, but would you be able to change the name to Compatible Products instead of Marketplace? 

Also can Forums be changed to Stay Connected? thanks

**Comment by ericpoirier** [comment]
@shabnammayel @ivargrimstad We'll make those changes, thanks for the follow up.

**Comment by ericpoirier** [comment]
Hi @shabnammayel and @ivargrimstad,

I updated the links in the footer of the production website.

https://jakarta.ee/

Thanks!
