### ISSUE TITLE
Bug: Buttons are not equal height

### ISSUE THREAD

**Issue by oliviergoulet5** [jakartaee/jakarta.ee#1588]
Navigate to https://jakarta.ee/projects/

The button group's dropdown button is expected to have the same height as the download button. Currently it looks like this:
![image](https://user-images.githubusercontent.com/17685861/203370327-53b22a58-9a0a-44c8-a779-ac7642a7bef4.png)

**Comment by gdorsi44** [comment]
Hello @oliviergoulet5 , 

I have seen that this issue is related to this dependency (archived) at this link:
[https://github.com/EclipseFdn/hugo-solstice-them](https://github.com/EclipseFdn/hugo-solstice-theme)
Is there a fixed version from EclispeFdn repository available for main package.json ?

Warm Regards,
Gaetano.

**Comment by oliviergoulet5** [comment]
@Tudor44 Thanks for looking into this. 

Currently there is no version for the hugo theme which fixes this bug (repo now lives here: https://gitlab.eclipse.org/eclipsefdn/it/webdev/hugo-solstice-theme)

~~The hugo theme depends on [solstice assets](https://gitlab.eclipse.org/eclipsefdn/it/webdev/solstice-assets) for styles and is where this bug originates from.~~

~~I created this issue just now to keep track of this: https://gitlab.eclipse.org/eclipsefdn/it/webdev/solstice-assets/-/issues/352~~

edit: Actually, you are right, it completely originates from the hugo theme. One of the buttons is using `btn-sm` class while the other is a normal sized button. It's simply a matter of removing the `btn-sm` class. 

I moved the issue here: https://gitlab.eclipse.org/eclipsefdn/it/webdev/hugo-solstice-theme/-/issues/264

**Comment by gdorsi44** [comment]
Hello @oliviergoulet5
 
happy to be helpful. 
Could we close the issue after the theme's update?

Warm Regards,
Gaetano.
