### ISSUE TITLE
Compatible Software Product Request for Payara Server Community 6.2022.1 For Full Platform 10 and Core Profile 10

### ISSUE THREAD

**Issue by JamesHillyard** [jakartaee/jakarta.ee#1591]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://accounts.eclipse.org/users/jameshillyard

**A product name and version**
Payara Server Community 6.2022.1

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**
Full Platform 10 and Core Profile 10

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/jakartaee/jakarta.ee/files/9605791/community-logo-on-white-transparent-RGB.zip

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Payara Services Ltd

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Full Platform: https://github.com/eclipse-ee4j/jakartaee-platform/issues/577
Core Profile: https://github.com/eclipse-ee4j/jakartaee-platform/issues/579

**The URL where Compatible Software Product is available for download**
https://www.payara.fish/downloads/payara-platform-community-edition/

**Comment by oliviergoulet5** [comment]
Here are the previews for the updated pages @TanjaObradovic: 
- https://deploy-preview-1597--jakartaee.netlify.app/compatibility/certification/10/
- https://deploy-preview-1597--jakartaee.netlify.app/compatibility/download/

**Comment by oliviergoulet5** [comment]
@TanjaObradovic Is this still on your radar?

/cc @ivargrimstad

**Comment by ivargrimstad** [comment]
@oliviergoulet5 Good to go as well

**Comment by TanjaObradovic** [comment]
Sorry to do this, but this is not quite right 
![image](https://user-images.githubusercontent.com/40073121/210868178-ca106f6c-1d6f-4365-8130-2d9c77e05ee4.png)
- we do not need the line that has 

</html>Payara Server Community (Web Profile)	Payara Server Community (Web Profile)	[6.2022.1]


The preview here is right

https://deploy-preview-1597--jakartaee.netlify.app/compatibility/certification/10/


but on the 'live' website it is wrong
