### ISSUE TITLE
Compatible Software Product Request for Payara Server Community (Web Profile) 6.2022.1 For Web Profile 10 and Core Profile 10

### ISSUE THREAD

**Issue by JamesHillyard** [jakartaee/jakarta.ee#1592]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://accounts.eclipse.org/users/jameshillyard

**A product name and version**
Payara Server Community 6.2022.1 (Web Profile)

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**
Web Profile 10 and Core Profile 10

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/jakartaee/jakarta.ee/files/9605791/community-logo-on-white-transparent-RGB.zip

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Payara Services Ltd

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Full Platform: https://github.com/eclipse-ee4j/jakartaee-platform/issues/578
Core Profile: https://github.com/eclipse-ee4j/jakartaee-platform/issues/580

**The URL where Compatible Software Product is available for download**
https://www.payara.fish/downloads/payara-platform-community-edition/

**Comment by oliviergoulet5** [comment]
@TanjaObradovic I have a preview link here: https://deploy-preview-1598--jakartaee.netlify.app/compatibility/download/

I found this one a bit unusual because https://github.com/eclipse-ee4j/jakartaee-platform/issues/580 is worded like:
"Payara Server Community (Web Profile) 6.2022.1 for Core Profile". 

I decided to display this entry in the Jakarta EE 10 Core Profile table. The product name is displayed with Web Profile in parentheses. 

Let me know if this was a good approach.

**Comment by oliviergoulet5** [comment]
@TanjaObradovic I'm going to ping again because it's been a while since we had activity on this issue.

/cc @ivargrimstad

**Comment by ivargrimstad** [comment]
@oliviergoulet5 Good to go Their "Web Profile" product also implement Core Profile, so that is okay

**Comment by TanjaObradovic** [comment]
I am sorry, but looking into this now
the below should say 
"Payara Server Community"  not "Payara Server Community (Web Profile)"
![image](https://user-images.githubusercontent.com/40073121/208480276-f3210c2d-e2be-4ede-a5a5-8ea6c3862502.png)

**Comment by oliviergoulet5** [comment]
@TanjaObradovic There's a bit of confusion on my end on what the fix is. 

According to [the ticket](https://github.com/eclipse-ee4j/jakartaee-platform/issues/580), it's a "Payara Server web profile" to be added to "Jakarta EE 10 core profile". I interpreted this as a separate product than the "Payara Server Community" listed in your screenshot above.

I think this is what https://github.com/jakartaee/jakarta.ee/issues/1592#issuecomment-1357847176 is referring to. 

So should it be left as-is? Or should the "6.2022.1" link from "Payara Server community (web profile)" be listed under "Payara Server Community" as "6.2022.1 (web profile)"? Or deleted?

**Comment by autumnfound** [comment]
To be clear, these are 2 separate offerings from Payara, where Web Profile isn't the Jakarta EE meaning of Web Profile, but their own interpretation of a "Web Profile" that implements the Core profile of Jakarta EE

**Comment by TanjaObradovic** [comment]
My point was to be consistent.
The product name is Payara Server Community and it has 2 implementation options Payara Server Community Jakarta EE Platform implementation and Payara Server Community Jakarta EE Core Profile implementation.

In this section Jakarta EE 10 Web Profile Compatible Products - we do not have Payara Server Community (Web Profile) as product name, we only have Payara Server Community 
![image](https://user-images.githubusercontent.com/40073121/211050653-96ad0a08-92ca-4c4a-80c9-f0d748641412.png)
I believe this is correct.

With the same logic in the Jakarta EE 10 Core Profile Compatible Products we should use product name Payara Server Community; the certification results contain specifics pointing to the Web Profile implementation.

Hope this helps.

**Comment by autumnfound** [comment]
> My point was to be consistent. The product name is Payara Server Community and it has 2 implementation options Payara Server Community Jakarta EE Platform implementation and Payara Server Community Jakarta EE Core Profile implementation.
> 
> In this section Jakarta EE 10 Web Profile Compatible Products - we do not have Payara Server Community (Web Profile) as product name, we only have Payara Server Community ![image](https://user-images.githubusercontent.com/40073121/211050653-96ad0a08-92ca-4c4a-80c9-f0d748641412.png) I believe this is correct.
> 
> With the same logic in the Jakarta EE 10 Core Profile Compatible Products we should use product name Payara Server Community; the certification results contain specifics pointing to the Web Profile implementation.
> 
> Hope this helps.

It looks like that certification result is not yet completed: https://github.com/eclipse-ee4j/jakartaee-platform/issues/578

**Comment by TanjaObradovic** [comment]
I think only accepted label is missing there, I will invite @ivargrimstad to add it
@ivargrimstad can you please add accepted label to this one https://github.com/eclipse-ee4j/jakartaee-platform/issues/578?
The website is updated already, so we should be good for Web Profile certification.

**Comment by oliviergoulet5** [comment]
@TanjaObradovic I agree, there was inconsistencies between the web and core profile.

The link to the web profile of Payara Server Community for Jakarta EE 10 Web and Core Profile are now displayed under "Certification Results".

Here is a link of the preview: https://deploy-preview-1611--jakartaee.netlify.app/compatibility/certification/10/

**Comment by TanjaObradovic** [comment]
Thanks, looks good!
