### ISSUE TITLE
Improvement for jakarta.ee/resources page

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1595]
As a follow up from https://github.com/jakartaee/collateral/issues/22, the purpose of this github issue is to add the Jakarta branding guidelines and the artwork links to the Resource page Jakarta already has: https://jakarta.ee/resources. 

The benefit will be to keep offering a central place for resource gathering by optimizing user experience as described in https://github.com/jakartaee/collateral/issues/22#issuecomment-1248694971

**Comment by ericpoirier** [comment]
Hi @cesarhernandezgt,

We can add a new card on the Resources page to add the Branding Guidelines. Can you provide the links for this if you have them?

@shabnammayel we will need to chose a new icon for this section. We will need to get @meKokabi involved for this I believe.

Thanks.

**Comment by cesarhernandezgt** [comment]
Hi @ericpoirier,
 
Yes, I agree that a new card called "Branding" can contain the following content(links):

* Branding Guidelines: https://jakarta.ee/legal/trademark_guidelines/jakarta-ee-branding-guidelines.pdf
* Artwork: https://www.eclipse.org/org/artwork/

**Comment by shabnammayel** [comment]
+1 to naming it branding and adding the links into a box. @meKokabi can you please help with an icon for this box called "branding"? it's going to be a new addition to the existing boxes on this page: https://jakarta.ee/resources.

**Comment by meKokabi** [comment]
@shabnammayel Hi, for consistency I need access to the icons' source files (Adobe Illustrator files). Can you provide me with that?

**Comment by shabnammayel** [comment]
@meKokabi  I believe you remade the icons in the "Resource" page for consistency. there is a zip file you added in the issue when we were working on it : https://github.com/jakartaee/jakarta.ee/issues/1143

Is that what you are looking for?

**Comment by meKokabi** [comment]
@shabnammayel please let me check again and get back to you shortly.

**Comment by meKokabi** [comment]
Here You Are! 
![icon-6](https://user-images.githubusercontent.com/75500459/210431996-7dd28e08-7a8e-44ca-b3cc-e2241f2d1022.svg)

**Comment by shabnammayel** [comment]
Thanks, @ericpoirier is there anything else you need? thanks

**Comment by ericpoirier** [comment]
> Thanks, @ericpoirier is there anything else you need? thanks

No I think that's it. I'll let you know once I create a PR to add these changes.

**Comment by oliviergoulet5** [comment]
Here is a preview of the changes: https://deploy-preview-1609--jakartaee.netlify.app/resources/

@meKokabi There is an inconsistency in the thickness of the icon provided when compared to the others.

**Comment by meKokabi** [comment]
let me take a look and get back to you.

**Comment by meKokabi** [comment]
Here you are the revised one:
![branding](https://user-images.githubusercontent.com/75500459/210627438-490a29a1-eb28-4d3b-bd18-aafc49ad5adc.svg)

**Comment by oliviergoulet5** [comment]
Thanks @meKokabi, looks a lot better now!

@cesarhernandezgt @shabnammayel Let me know if this is good to go live

**Comment by shabnammayel** [comment]
LGTM! thanks

**Comment by shabnammayel** [comment]
can you please add it to the resources menu bar as well? thanks

**Comment by oliviergoulet5** [comment]
@shabnammayel The preview should now have it listed under the resources menu

**Comment by cesarhernandezgt** [comment]
+1 
Thank you all for the awesome work. The preview looks lovely!
