### ISSUE TITLE
Compatible Software Product Request for Primeton AppServer V7.2 for Full Platform

### ISSUE THREAD

**Issue by otyyyywangwenbin-max** [jakartaee/jakarta.ee#1596]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Primeton AppServer V7.2 as Compatible product of Jakarta EE Full Platform](https://www.eclipse.org/membership/showMember.php?member_id=1401)

**A product name and version**
Primeton AppServer V7.2

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**
Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
http://primeton.com/products/pas/tck_results/images/pas_logo.png

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Primeton Information Technologies, Inc

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/582

**The URL where Compatible Software Product is available for download**
http://www.primeton.com/products/pas/tck_results/pas-7.2-dist.zip

**Comment by otyyyywangwenbin-max** [comment]
@oliviergoulet5  certification issue https://github.com/eclipse-ee4j/jakartaee-platform/issues/582  is accepted

**Comment by oliviergoulet5** [comment]
@TanjaObradovic Here is a preview of this change: 

- [Certification Results tab](https://deploy-preview-1618--jakartaee.netlify.app/compatibility/certification/9.1/)
- [Download Compatible Products tab](https://deploy-preview-1618--jakartaee.netlify.app/compatibility/download/)

**Comment by TanjaObradovic** [comment]
Looks great! Many thanks!
