### ISSUE TITLE
Jakarta EE 9 web-services xsd includes the jakartaee_10.xsd

### ISSUE THREAD

**Issue by pzygielo** [jakartaee/jakarta.ee#1603]
selecting the Jakarta EE 9 web-services xsd includes the jakartaee_10.xsds.
https://jakarta.ee/xml/ns/jakartaee/jakartaee_web_services_2_0.xsd

one would expect that the target URL 'https://jakarta.ee/xml/ns/jakartaee/*' contains all versions of the xsds and not just a snapshot of one build

_Originally posted by @JWT007 in https://github.com/jakartaee/jakarta.ee/issues/1519#issuecomment-1356848194_

**Comment by ivargrimstad** [comment]
How should we handle this situation now (and in the future) when a schema is not updated but is part of a newer release?

In this particular case, WS 2.0 is both Jakarta EE 9 and 10. Should the include be updated to 10, or kept as 9?

**Comment by pzygielo** [comment]
IMO
> when schema is not updated
> Should the include be updated to 10, or kept as 9?

It should not be updated. Like for https://github.com/jakartaee/jakarta.ee/blob/3cac35a61b6f89f64be14dea4cdeb53bd67ed56c/static/xml/ns/jakartaee/ejb-jar_4_0.xsd#L78 is kept.

Otherwise the schema *is* updated, isn't it?

It's not usable in JakartaEE9 environment now.

**Comment by ivargrimstad** [comment]
Makes sense
