### ISSUE TITLE
Publish Jakarta EE Steering Comm Mtg Mins - Aug 30, 2022; Sep 13, 2022; Sep 27, 2022; Oct 11, 2022; Oct 18, 2022; Nov 8, 2022; Nov 22, 2022

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1612]
This is not a bug

We need to add new entries for Steering meeting minutes for Aug 30, 2022; Sep 13, 2022; Sep 27, 2022; Oct 11, 2022; Oct 18, 2022; Nov 8, 2022; Nov 22, 2022
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.

I have attached pdf files:
[Minutes of the August 30, 2022 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/10369574/Minutes.of.the.August.30.2022.Jakarta.EE.Steering.Committee.Meeting.pdf)
[Minutes of the November 8, 2022 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/10369575/Minutes.of.the.November.8.2022.Jakarta.EE.Steering.Committee.Meeting.pdf)
[Minutes of the November 22, 2022 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/10369576/Minutes.of.the.November.22.2022.Jakarta.EE.Steering.Committee.Meeting.pdf)
[Minutes of the October 11, 2022 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/10369577/Minutes.of.the.October.11.2022.Jakarta.EE.Steering.Committee.Meeting.pdf)
[Minutes of the October 18, 2022 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/10369578/Minutes.of.the.October.18.2022.Jakarta.EE.Steering.Committee.Meeting.pdf)
[Minutes of the September 13, 2022 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/10369579/Minutes.of.the.September.13.2022.Jakarta.EE.Steering.Committee.Meeting.pdf)
[Minutes of the September 27, 2022 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/10369580/Minutes.of.the.September.27.2022.Jakarta.EE.Steering.Committee.Meeting.pdf)

**Comment by oliviergoulet5** [comment]
@will-lyons Here is a preview of the changes: https://deploy-preview-1613--jakartaee.netlify.app/about/meeting_minutes/#steering_committee

Let me know whether it's good to go live.

/cc @TanjaObradovic

**Comment by will-lyons** [comment]
Olivier –

Yes, looks good.  Please publish.

Thanks

Will


From: Olivier Goulet ***@***.***>
Reply-To: "jakartaee/jakarta.ee" ***@***.***>
Date: Monday, January 9, 2023 at 3:36 PM
To: "jakartaee/jakarta.ee" ***@***.***>
Cc: Will Lyons ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [jakartaee/jakarta.ee] Publish Jakarta EE Steering Comm Mtg Mins - Aug 30, 2022; Sep 13, 2022; Sep 27, 2022; Oct 11, 2022; Oct 18, 2022; Nov 8, 2022; Nov 22, 2022 (Issue #1612)


@will-lyons<https://urldefense.com/v3/__https:/github.com/will-lyons__;!!ACWV5N9M2RV99hQ!PCFTHVJl0f7pxuQpMQfW1bTueaLF2Al5EgnLe0ioPPSzvhggtvS0w8NpdiG-O4JbLUrd2moq1JMfZZiCtPFgVVRPlw$> Here is a preview of the changes: https://deploy-preview-1613--jakartaee.netlify.app/about/meeting_minutes/#steering_committee<https://urldefense.com/v3/__https:/deploy-preview-1613--jakartaee.netlify.app/about/meeting_minutes/*steering_committee__;Iw!!ACWV5N9M2RV99hQ!PCFTHVJl0f7pxuQpMQfW1bTueaLF2Al5EgnLe0ioPPSzvhggtvS0w8NpdiG-O4JbLUrd2moq1JMfZZiCtPFpR7LIJg$>

Let me know whether it's good to go live.

/cc @TanjaObradovic<https://urldefense.com/v3/__https:/github.com/TanjaObradovic__;!!ACWV5N9M2RV99hQ!PCFTHVJl0f7pxuQpMQfW1bTueaLF2Al5EgnLe0ioPPSzvhggtvS0w8NpdiG-O4JbLUrd2moq1JMfZZiCtPHmpTsHhA$>
