### ISSUE TITLE
Update the Jakarta EE Steering Committee Members for IBM

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1614]
Can we please update 
https://jakarta.ee/committees/steering/

section 
Committee Members

the line should be 
Alasdair Nottingham - IBM, Ian Robinson - alternate  

Many thanks!

**Comment by oliviergoulet5** [comment]
@TanjaObradovic Here is a preview of the change: https://deploy-preview-1616--jakartaee.netlify.app/committees/steering/

The [zh page](https://deploy-preview-1616--jakartaee.netlify.app/zh/committees/steering/) was also updated.

**Comment by TanjaObradovic** [comment]
Looks great! thx!
