### ISSUE TITLE
Publish Jakarta EE Steering Comm Mtg Mins for Dec 13, 2022

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1615]
This is not a bug

We need to add new entries for Steering meeting minutes for Dec 13, 2022 in
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.

I have attached pdf files:
[Minutes of the December 13, 2022 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/10397176/Minutes.of.the.December.13.2022.Jakarta.EE.Steering.Committee.Meeting.pdf)

**Comment by oliviergoulet5** [comment]
Hi @will-lyons 

Here is a preview of the change: https://deploy-preview-1617--jakartaee.netlify.app/about/meeting_minutes/#steering_committee

Let me know whether it's good to go live.

**Comment by oliviergoulet5** [comment]
@TanjaObradovic Are these good to go live?

**Comment by TanjaObradovic** [comment]
looking great! thx!
