### ISSUE TITLE
Update the Jakarta EE Steering Committee Members for IBM; Emily Jiang - alternate

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1621]
Can we please update
https://jakarta.ee/committees/steering/

section
Committee Members

the line should be
Alasdair Nottingham - IBM, Emily Jiang - alternate

Many thanks!

**Comment by oliviergoulet5** [comment]
Hi @TanjaObradovic! Here is a preview link: 

https://deploy-preview-1624--jakartaee.netlify.app/committees/steering/

**Comment by TanjaObradovic** [comment]
Looking good! Many thanks!
