### ISSUE TITLE
Compatible Software Product Request for WebOTX Application Server V11 for Full Platform 8.0

### ISSUE THREAD

**Issue by yoshiasai** [jakartaee/jakarta.ee#1626]
**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=1399

**A product name and version**
WebOTX Application Server V11

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**
Full Platform 8.0

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
![WebOTX_logo](https://user-images.githubusercontent.com/123822526/216862628-51b31280-ac1c-4498-a8f6-f88d87140bbb.svg)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
NEC Corporation

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://jpn.nec.com/webotx/appserver/ee8_tck_result_11100000.html

**The URL where Compatible Software Product is available for download**
https://jpn.nec.com/webotx/appserver/index.html

**Comment by ZacharySabourin** [comment]
@yoshiasai The certification URL does not seem to be pointing to a valid page. Please provide a valid URL. Thanks!

**Comment by yoshiasai** [comment]
@ZacharySabourin 
Sorry, wrong URL.
The correct URL is https://jpn.nec.com/webotx/appserver/ee8_tck_result_exp_11100000.html

**Comment by ZacharySabourin** [comment]
@yoshiasai Here is a preview of the requested changes: https://deploy-preview-1630--jakartaee.netlify.app/compatibility/

**Comment by yoshiasai** [comment]
@ZacharySabourin 
Thank you for your quick response.
I have checked the following two URLs and they are OK.
https://deploy-preview-1630--jakartaee.netlify.app/compatibility/
https://deploy-preview-1630--jakartaee.netlify.app/compatibility/certification/8/

**Comment by ZacharySabourin** [comment]
@TanjaObradovic Here is a preview of this change:
- [Main compatibility page](https://deploy-preview-1630--jakartaee.netlify.app/compatibility/)
- [Certification Results](https://deploy-preview-1630--jakartaee.netlify.app/compatibility/certification/8/)
- [Product Download page](https://deploy-preview-1630--jakartaee.netlify.app/compatibility/download/)

**Comment by yoshiasai** [comment]
@TanjaObradovic
All three of the above pages have been reviewed.
Please review.

**Comment by TanjaObradovic** [comment]
Looks great! Thank you!!
