### ISSUE TITLE
Publish Jakarta EE Steering Comm Mtg Mins for Jan 10, 2023

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1627]
This is not a bug

We need to add new entries for Steering meeting minutes for Jan 10, 2023 in
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.

I have attached pdf files:
[Minutes of the January 10, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/10659661/Minutes.of.the.January.10.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by ZacharySabourin** [comment]
@will-lyons Here is a preview of the requested changes https://deploy-preview-1628--jakartaee.netlify.app/about/meeting_minutes/#steering_committee

**Comment by TanjaObradovic** [comment]
@ZacharySabourin - looks great! Please go ahead.
