### ISSUE TITLE
Update at https://jakarta.ee/connect/ page

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1632]
Please update the for Project Mailing Lists tile to say **Specification** Project Mailing Lists

https://jakarta.ee/connect/

or consider adding all implementation projects mailing lists as well.

**Comment by oliviergoulet5** [comment]
Here is a preview @TanjaObradovic https://deploy-preview-1644--jakartaee.netlify.app/connect/

Let me know if it is good to go live

**Comment by oliviergoulet5** [comment]
@TanjaObradovic This issue has been open for a while. Are we still going live with it?
