### ISSUE TITLE
Update the Jakarta EE Specification Committee Members for IBM

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1633]
Can we please update
https://jakarta.ee/committees/specification/

section
Committee Members

the line should be
 Emily Jiang - IBM, Tom Watson - alternate

**Comment by oliviergoulet5** [comment]
Here is a preview @TanjaObradovic 

https://deploy-preview-1635--jakartaee.netlify.app/committees/specification/

**Comment by TanjaObradovic** [comment]
Looks great!
