### ISSUE TITLE
Meeting minutes missing from https://jakarta.ee/committees/

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1634]
Meeting minutes ae missing from the following pages

https://jakarta.ee/committees/marketing/
https://jakarta.ee/committees/specification/
https://jakarta.ee/committees/steering/

**Comment by oliviergoulet5** [comment]
This is a regression from when we updated the meeting minutes shortcode. Luckily the fix is simple.

**Comment by oliviergoulet5** [comment]
A fix is coming in shortly which will display all the meeting minutes again. However I will leave this open as there is a minor bug that still needs to be dealt with. 

The year 2023 will still show when that specific committee doesn't have minutes.

![image](https://user-images.githubusercontent.com/17685861/219399538-974ddc5a-2f4a-43f3-89f8-b359005fe5ba.png)
