### ISSUE TITLE
Please add BES Application Server v10.0.0 to Jakarta EE 9.1 Compatible Products pag

### ISSUE THREAD

**Issue by liyang960414** [jakartaee/jakarta.ee#1648]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=1506

**A product name and version**
BES Application Server v10.0.0

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**
Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/guojjanjun/bes-tck/blob/main/BES_Application_Server_for_eclipse.zip

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Beijing Baolande Software Corporation

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/jakartaee/jakartaee-platform/issues/615

**The URL where Compatible Software Product is available for download**
https://www.bessystem.com/product/0ad9b8c4d6af462b8d15723a5f25a87d/info?p=101#page-2

**Comment by oliviergoulet5** [comment]
@TanjaObradovic Here is a preview: https://deploy-preview-1651--jakartaee.netlify.app/compatibility/

Let me know if we're good to go live!

**Comment by TanjaObradovic** [comment]
yes - we are! Thanks @oliviergoulet5!
