### ISSUE TITLE
Publish Jakarta EE Steering Committee Minutes for: Jan 17, 2023; Jan 31, 2023; Feb 14, 2023  

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1653]
This is not a bug

We need to add new entries for Steering meeting minutes for 
- Jan 17, 2023
- Jan 31, 2023
- Feb 14, 2023  

...in https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.

I have attached pdf files:
[Minutes of the January 17, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/11194606/Minutes.of.the.January.17.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the January 31, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/11194607/Minutes.of.the.January.31.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the February 14, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/11194608/Minutes.of.the.February.14.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by oliviergoulet5** [comment]
@TanjaObradovic Here is a preview: https://deploy-preview-1654--jakartaee.netlify.app/about/meeting_minutes/#steering_committee

Let me know if we're good to go live!

/cc @will-lyons

**Comment by will-lyons** [comment]
Looks good, ok to go live from my point of view.
