### ISSUE TITLE
Open Liberty 23.0.0.3 as a Compatible Software Product for Jakarta EE 10

### ISSUE THREAD

**Issue by brideck** [jakartaee/jakarta.ee#1657]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Brian Decker - IBM - Eclipse Profile](https://accounts.eclipse.org/users/bdeckerhdt)

**A product name and version**
[Open Liberty 23.0.0.3](https://openliberty.io/)

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**
Platform, Web Profile, Core Profile

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[https://openliberty.io/certifications/assets/OL_logomark.zip](https://openliberty.io/certifications/assets/OL_logomark.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[IBM Corporation](https://www.ibm.com/)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Platform, Java 11 & 17: [https://github.com/jakartaee/jakartaee-platform/issues/644](https://github.com/jakartaee/jakartaee-platform/issues/644)
Web Profile, Java 11 & 17: [https://github.com/jakartaee/jakartaee-platform/issues/645](https://github.com/jakartaee/jakartaee-platform/issues/645)
Core Profile, Java 11 & 17: [https://github.com/jakartaee/jakartaee-platform/issues/646](https://github.com/jakartaee/jakartaee-platform/issues/646)

**The URL where Compatible Software Product is available for download**
[https://openliberty.io/start/#runtime_releases](https://openliberty.io/start/#runtime_releases)

**Comment by oliviergoulet5** [comment]
Here is a preview for this change:

- https://deploy-preview-1659--jakartaee.netlify.app/compatibility/certification/10/
- https://deploy-preview-1659--jakartaee.netlify.app/compatibility/download/

Let me know if we're good to go live.

@TanjaObradovic @brideck

**Comment by brideck** [comment]
> Here is a preview for this change:
> 
>     * https://deploy-preview-1659--jakartaee.netlify.app/compatibility/certification/10/
> 
>     * https://deploy-preview-1659--jakartaee.netlify.app/compatibility/download/
> 
> 
> Let me know if we're good to go live.
> 
> @TanjaObradovic @brideck

Could we remove the old 22.0.0.10-beta entries for EE 10 Core Profile? They're not needed anymore with this addition.

**Comment by oliviergoulet5** [comment]
@brideck Certainly. Beta entries have been removed in the latest preview.

**Comment by TanjaObradovic** [comment]
Thanks @brideck, and yes @oliviergoulet5 it looks good!
