### ISSUE TITLE
IBM WebSphere Liberty 23.0.0.3 as a Compatible Software Product for Jakarta EE 10

### ISSUE THREAD

**Issue by brideck** [jakartaee/jakarta.ee#1658]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Brian Decker - IBM - Eclipse Profile](https://accounts.eclipse.org/users/bdeckerhdt)

**A product name and version**
[IBM WebSphere Liberty 23.0.0.3](https://www.ibm.com/products/websphere-liberty)

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**
Platform, Web Profile, Core Profile

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[websphereliberty.svg.zip](https://github.com/jakartaee/jakarta.ee/files/5467815/websphereliberty.svg.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[IBM Corporation](https://www.ibm.com/)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Platform, Java 11 & 17: [https://github.com/jakartaee/jakartaee-platform/issues/641](https://github.com/jakartaee/jakartaee-platform/issues/641)
Web Profile, Java 11 & 17: [https://github.com/jakartaee/jakartaee-platform/issues/642](https://github.com/jakartaee/jakartaee-platform/issues/642)
Core Profile, Java 11 & 17: [https://github.com/jakartaee/jakartaee-platform/issues/643](https://github.com/jakartaee/jakartaee-platform/issues/643)

**The URL where Compatible Software Product is available for download**
Platform: [https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EWebSphere&product=ibm/WebSphere/WebSphere+Liberty&release=23.0.0.3&platform=All&function=fixId&fixids=wlp-jakartaee10-23.0.0.3&includeSupersedes=0](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EWebSphere&product=ibm/WebSphere/WebSphere+Liberty&release=23.0.0.3&platform=All&function=fixId&fixids=wlp-jakartaee10-23.0.0.3&includeSupersedes=0)

Web Profile / Core Profile: [https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EWebSphere&amp;product=ibm/WebSphere/WebSphere+Liberty&amp;release=23.0.0.3&amp;platform=All&amp;function=fixId&amp;fixids=wlp-webProfile10-23.0.0.3&amp;includeSupersedes=0](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EWebSphere&amp;product=ibm/WebSphere/WebSphere+Liberty&amp;release=23.0.0.3&amp;platform=All&amp;function=fixId&amp;fixids=wlp-webProfile10-23.0.0.3&amp;includeSupersedes=0)

**Comment by oliviergoulet5** [comment]
Here is a preview @brideck @TanjaObradovic: 

- https://deploy-preview-1660--jakartaee.netlify.app/compatibility/certification/10/
- https://deploy-preview-1660--jakartaee.netlify.app/compatibility/download/

**Comment by brideck** [comment]
Looks good to me, thanks.
