### ISSUE TITLE
Jakarta Marketing Committee meeting notes for 2023 are missing in about/meeting_minutes page

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1661]
2023 Jakarta Marketing Committee meeting notes from February up to today are missing from the page:

https://jakarta.ee/about/meeting_minutes/#marketing_committee

CC:
@shabnammayel @TanjaObradovic

**Comment by oliviergoulet5** [comment]
It doesn't seem like issues were created for adding those meeting minutes. If anyone could share the PDFs with me, I will add them to the page.

**Comment by shabnammayel** [comment]
[Jakarta EE Marketing Committee Meeting - January 26, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/11336298/Jakarta.EE.Marketing.Committee.Meeting.-.January.26.2023.11_00.ET.pdf)
[Jakarta EE Marketing Committee Meeting - February 9, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/11336299/Jakarta.EE.Marketing.Committee.Meeting.-.February.9.2023.11_00.ET.pdf)
[Jakarta EE Marketing Committee Meeting - February 23, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/11336307/Jakarta.EE.Marketing.Committee.Meeting.-.February.23.2023.11_00.ET.pdf)

[Jakarta EE Marketing Committee Meeting - March 9, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/11336308/Jakarta.EE.Marketing.Committee.Meeting.-.March.9.2023.11_00.ET.pdf)

[Jakarta EE Marketing Committee Meeting - March 23, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/11336309/Jakarta.EE.Marketing.Committee.Meeting.-.March.23.2023.11_00.ET.pdf)


[Jakarta EE Marketing Committee Meeting - March 30, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/11336351/Jakarta.EE.Marketing.Committee.Meeting.-.March.30.2023.11_00.ET.pdf)
[Jakarta EE Marketing Committee Meeting - April 13, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/11336352/Jakarta.EE.Marketing.Committee.Meeting.-.April.13.2023.11_00.ET.pdf)

**Comment by shabnammayel** [comment]
Thanks @oliviergoulet5

**Comment by oliviergoulet5** [comment]
Here is a preview for the marketing minutes @shabnammayel: https://deploy-preview-1663--jakartaee.netlify.app/about/meeting_minutes/

**Comment by cesarhernandezgt** [comment]
Thank you @oliviergoulet5 @shabnammayel !

**Comment by shabnammayel** [comment]
LGTM @oliviergoulet5 Thanks
