### ISSUE TITLE
Jakarta Specification Committee meeting notes for 2023 are missing in about/meeting_minutes page

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1662]
All the 2023 Jakarta Specification Committee meeting notes are missing from the page:
https://jakarta.ee/about/meeting_minutes/#specification_committee

CC:
@shabnammayel @TanjaObradovic

**Comment by oliviergoulet5** [comment]
It doesn't seem like issues were created for adding those meeting minutes. If anyone could share the PDFs with me, I will add them to the page.

**Comment by paulbuck** [comment]
Thanks. I will provide the PDFs.

**Comment by paulbuck** [comment]
Here are the PDFs for the Jakarta EE Specification Committee meeting minutes July 13th, 2022--> April 4th, 2022. Thanks for posting them to the website!

[Jakarta EE Spec Committee - November 30th, 2022.pdf](https://github.com/jakartaee/jakarta.ee/files/11336011/Jakarta.EE.Spec.Committee.-.November.30th.2022.pdf)
[Jakarta EE Spec Committee - October 5th, 2022.pdf](https://github.com/jakartaee/jakarta.ee/files/11336012/Jakarta.EE.Spec.Committee.-.October.5th.2022.pdf)
[Jakarta EE Spec Committee - October 19th, 2022.pdf](https://github.com/jakartaee/jakarta.ee/files/11336013/Jakarta.EE.Spec.Committee.-.October.19th.2022.pdf)
[Jakarta EE Spec Committee - September 7th, 2022.pdf](https://github.com/jakartaee/jakarta.ee/files/11336014/Jakarta.EE.Spec.Committee.-.September.7th.2022.pdf)
[Jakarta EE Spec Committee - September 21st, 2022.pdf](https://github.com/jakartaee/jakarta.ee/files/11336015/Jakarta.EE.Spec.Committee.-.September.21st.2022.pdf)
[Jakarta EE Spec Committee - April 5th, 2023.pdf](https://github.com/jakartaee/jakarta.ee/files/11336016/Jakarta.EE.Spec.Committee.-.April.5th.2023.pdf)
[Jakarta EE Spec Committee - August 10th, 2022.pdf](https://github.com/jakartaee/jakarta.ee/files/11336017/Jakarta.EE.Spec.Committee.-.August.10th.2022.pdf)
[Jakarta EE Spec Committee - August 24th, 2022.pdf](https://github.com/jakartaee/jakarta.ee/files/11336018/Jakarta.EE.Spec.Committee.-.August.24th.2022.pdf)
[Jakarta EE Spec Committee - February 8th, 2023.pdf](https://github.com/jakartaee/jakarta.ee/files/11336019/Jakarta.EE.Spec.Committee.-.February.8th.2023.pdf)
[Jakarta EE Spec Committee - February 22nd, 2023.pdf](https://github.com/jakartaee/jakarta.ee/files/11336020/Jakarta.EE.Spec.Committee.-.February.22nd.2023.pdf)
[Jakarta EE Spec Committee - January 11th, 2023.pdf](https://github.com/jakartaee/jakarta.ee/files/11336021/Jakarta.EE.Spec.Committee.-.January.11th.2023.pdf)
[Jakarta EE Spec Committee - January 25th, 2023.pdf](https://github.com/jakartaee/jakarta.ee/files/11336022/Jakarta.EE.Spec.Committee.-.January.25th.2023.pdf)
[Jakarta EE Spec Committee - July 13th, 2022.pdf](https://github.com/jakartaee/jakarta.ee/files/11336023/Jakarta.EE.Spec.Committee.-.July.13th.2022.pdf)
[Jakarta EE Spec Committee - July 27th, 2022.pdf](https://github.com/jakartaee/jakarta.ee/files/11336024/Jakarta.EE.Spec.Committee.-.July.27th.2022.pdf)
[Jakarta EE Spec Committee - March 8th, 2023.pdf](https://github.com/jakartaee/jakarta.ee/files/11336025/Jakarta.EE.Spec.Committee.-.March.8th.2023.pdf)
[Jakarta EE Spec Committee - March 22nd, 2023.pdf](https://github.com/jakartaee/jakarta.ee/files/11336026/Jakarta.EE.Spec.Committee.-.March.22nd.2023.pdf)
[Jakarta EE Spec Committee - November 2nd, 2022.pdf](https://github.com/jakartaee/jakarta.ee/files/11336027/Jakarta.EE.Spec.Committee.-.November.2nd.2022.pdf)
[Jakarta EE Spec Committee - November 16th, 2022.pdf](https://github.com/jakartaee/jakarta.ee/files/11336028/Jakarta.EE.Spec.Committee.-.November.16th.2022.pdf)

**Comment by oliviergoulet5** [comment]
Thanks @paulbuck, here is the preview of the change: https://deploy-preview-1664--jakartaee.netlify.app/about/meeting_minutes/#specification_committee

/cc @shabnammayel @TanjaObradovic 

Let me know if we're good to push this live!

**Comment by paulbuck** [comment]
+1. Looks good. Thanks!

**Comment by cesarhernandezgt** [comment]
Thank you @oliviergoulet5 @paulbuck !
