### ISSUE TITLE
searching inside java doc for jakarata ee 10 return 404

### ISSUE THREAD

**Issue by Just-some-one** [jakartaee/jakarta.ee#1665]
the returned link from the search add extra path to the correct link

1. Go [jakarta ee 10 javadoc](https://jakarta.ee/specifications/platform/10/apidocs/)
2. use the search for any class/method (but not package)
3. click on the returned link 
4. will return the `404 Page Not Found `

cause of the issue that the returned link add extra path to correct link`undefined`

for example searching for `jaxbcontext` then click on the link it return 
https://jakarta.ee/specifications/platform/10/apidocs/undefined/jakarta/xml/bind/JAXBContext.html
while it should return 
https://jakarta.ee/specifications/platform/10/apidocs/jakarta/xml/bind/JAXBContext.html

thanks for your help and have a nice day :)

**Comment by oliviergoulet5** [comment]
Thanks for bringing this bug to our attention and spending the time to create this issue @Just-some-one! 

However, this is not the repository for the API docs. That would be located here: https://github.com/jakartaee/specifications/issues. 

Could you please recreate this issue in that repository?

**Comment by Just-some-one** [comment]
Thanks for you @oliviergoulet5  and here the[ issue link](https://github.com/jakartaee/jakartaee-platform/issues/676) in case if others come here by mistake as me
