### ISSUE TITLE
Publish Jakarta EE Steering Committee Meeting Minutes for March 28, 2023

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1666]
This is not a bug

We need to add new entries for Steering meeting minutes for
Mar 28, 2023
...in https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.

I have attached a pdf file:
[Minutes of the March 28, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/11362091/Minutes.of.the.March.28.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by oliviergoulet5** [comment]
@will-lyons Here is the preview for adding March 28: https://deploy-preview-1667--jakartaee.netlify.app/about/meeting_minutes/#steering_committee

Let me know if we're good to go live

/cc @TanjaObradovic

**Comment by will-lyons** [comment]
Olivier -

Good to go live.  Thank you.

Will

From: Olivier Goulet ***@***.***>
Reply-To: "jakartaee/jakarta.ee" ***@***.***>
Date: Monday, May 1, 2023 at 11:27 AM
To: "jakartaee/jakarta.ee" ***@***.***>
Cc: Will Lyons ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [jakartaee/jakarta.ee] Publish Jakarta EE Steering Committee Meeting Minutes for March 28, 2023 (Issue #1666)


@will-lyons<https://urldefense.com/v3/__https:/github.com/will-lyons__;!!ACWV5N9M2RV99hQ!MPMK5VsoyKpMa836q5QOMPfVlAnmnNKIAeMZfFTldQyuNvQMrmvDgclAeSPuebNiSoSCIWEGqOQmFlqUmIqDZjGZuw$> Here is the preview for adding March 28: https://deploy-preview-1667--jakartaee.netlify.app/about/meeting_minutes/#steering_committee<https://urldefense.com/v3/__https:/deploy-preview-1667--jakartaee.netlify.app/about/meeting_minutes/*steering_committee__;Iw!!ACWV5N9M2RV99hQ!MPMK5VsoyKpMa836q5QOMPfVlAnmnNKIAeMZfFTldQyuNvQMrmvDgclAeSPuebNiSoSCIWEGqOQmFlqUmIo9y4C7yA$>

Let me know if we're good to go live

/cc @TanjaObradovic<https://urldefense.com/v3/__https:/github.com/TanjaObradovic__;!!ACWV5N9M2RV99hQ!MPMK5VsoyKpMa836q5QOMPfVlAnmnNKIAeMZfFTldQyuNvQMrmvDgclAeSPuebNiSoSCIWEGqOQmFlqUmIoD6JEuVg$>
