### ISSUE TITLE
JEUS 21 as Compatible product of Jakarta EE Platform

### ISSUE THREAD

**Issue by TmaxEE** [jakartaee/jakarta.ee#1668]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting

https://www.eclipse.org/membership/showMember.php?member_id=1391

A product name and version
JEUS 21

The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under
Full Platform

A ZIP file with a product logo with a transparent background in SVG format (optional)
[bi_jeus.zip](https://github.com/jakartaee/jakarta.ee/files/4285662/bi_jeus.zip)

The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product
TmaxSoft Co., Ltd

The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process
[https://github.com/jakartaee/jakartaee-platform/issues/614](https://github.com/jakartaee/jakartaee-platform/issues/614)

The URL where Compatible Software Product is available for download
[https://kr.tmaxsoft.com/jakee/jeus8-b425-SNAPSHOT.zip](https://kr.tmaxsoft.com/jakee/jeus21-b425-SNAPSHOT.zip)

**Comment by oliviergoulet5** [comment]
@TanjaObradovic Here is a preview of JEUS 21 being added for Jakarta EE 8 full platform: 

- https://deploy-preview-1674--jakartaee.netlify.app/compatibility/download/
- https://deploy-preview-1674--jakartaee.netlify.app/compatibility/certification/8/

/cc @TmaxEE

**Comment by TanjaObradovic** [comment]
Looks good! Thanks!

**Comment by arjantijms** [comment]
Tiny cosmetic remark. Link has as text "https://kr.tmaxsoft.com/jakee/jeus8-b425-SNAPSHOT.zip" but links to "https://kr.tmaxsoft.com/jakee/jeus21-b425-SNAPSHOT.zip".

I guess the text should say "21" instead of "8" as well.

@TmaxEE just out of curiosity, what happened to JEUS 10 to 20?
