### ISSUE TITLE
Update the link for TongWeb Application Server on the compatible products page

### ISSUE THREAD

**Issue by tongtech-web** [jakartaee/jakarta.ee#1669]
Due to a major upgrade of our official website, some of the historical links are inaccessible, so we would like to update the links to the TongWeb Application Server on the compatible products page. The following are the relevant links:
> 1.Jakarta EE  compatible products
> https://www.tongtech.com/dft/pctype/25.html
> 2.certification  results 
> Jakarta EE9.1Platform Compatible Products(TongWeb Application Server9):http://www.tongtech.com/tw9.jakarta-full-platform-9.1.html
> Jakarta EE 8 Platform Compatible Products(TongWeb Application Server7&8):http://www.tongtech.com/tw8.jakarta-full-platform-8.html; http://www.tongtech.com/tw7.jakarta-full-platform-8.html
> 3.download  compatible products
> Jakarta EE 9.1 Platform(TongWeb Application Server 9)&Jakarta EE 8 Platform(TongWeb Application Server7&8):https://www.tongtech.com/dft/contactus.html

**Comment by oliviergoulet5** [comment]
The links have been updated. Here is a preview: https://deploy-preview-1677--jakartaee.netlify.app/compatibility/

@tongtech-web @TanjaObradovic Let me know if we're good to go live with the changes!

**Comment by TanjaObradovic** [comment]
Looks good to me! Thanks!
