### ISSUE TITLE
Introduction of Beta ECA app into Jakartaee GH organization

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1676]
As part of an upcoming migration activity for the ECA status check, the Webdev team looked for organizations that we could use to help us do early testing before updating the main application to use the new version of the code. @chrisguindon and I discussed it, and we fell on Jakartaee as a good organization to use as final validation before we start the process of informing the community and performing the full migration. The webdev team regularly interacts with this organization to update the sites and has a higher-than-average communication line with the community in this project/organization.

This update would not change the current ECA check but add a second Beta app that would work alongside the currently live version. This would appear within the "Checks" section of any pull request created in the organization. This shouldn't impact the daily operation of pull requests, though, as we consider the main `eclipsefdn/eca` check to be the source of truth in the case of any conflicts. The current plan is to introduce this in 2 weeks from now.

We are currently doing some internal testing to do some final testing before introducing this to the community and plan to be done by next week. If there are any larger issues, we would push back the date that this would go live, and I'd update this issue in that case.

cc @TanjaObradovic @ivargrimstad @shabnammayel - please let us know if there are any questions or concerns about this, though this change should not impact the operation of the Github organization, as I mentioned earlier!

**Comment by autumnfound** [comment]
I made the request to add the beta app to the organization this afternoon, and it should be active now. This app will appear under checks as `eclipsefdn/eca-beta` under new pull requests in any repository under the Jakartaee organization. I encourage anyone who encounters problems to be directed here so that we can collect any feedback or look into issues encountered by the committers! I plan on addressing issues encountered as soon as possible during the test period so I'll be watching for comments.

Thanks in advance!

**Comment by oliviergoulet5** [comment]
Can we close this issue @autumnfound?

**Comment by autumnfound** [comment]
Yes we can, as the production version was released a while back!
