### ISSUE TITLE
Publish Jakarta EE Steering Committee Meeting Minutes for April 11, 2023 and April 25, 2023

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1683]
This is not a bug

We need to add new entries for Steering meeting minutes for
April 11, 2023
April 25, 2023
...in https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.

I have attached two pdf files:
[Minutes of the April 11, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/11665426/Minutes.of.the.April.11.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the April 25, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/11665430/Minutes.of.the.April.25.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by oliviergoulet5** [comment]
@will-lyons Here is a preview: https://deploy-preview-1684--jakartaee.netlify.app/about/meeting_minutes/#steering_committee

Let me know if we're good to go live!

**Comment by will-lyons** [comment]
Olivier -

Good to go live.

Thanks

Will

From: Olivier Goulet ***@***.***>
Date: Wednesday, June 7, 2023 at 2:11 PM
To: jakartaee/jakarta.ee ***@***.***>
Cc: Will Lyons ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [jakartaee/jakarta.ee] Publish Jakarta EE Steering Committee Meeting Minutes for April 11, 2023 and April 25, 2023 (Issue #1683)

@will-lyons<https://urldefense.com/v3/__https:/github.com/will-lyons__;!!ACWV5N9M2RV99hQ!M8mAOrka79-vyLOQvzUSX3oLaO0JzsMmcG2gVh_vYq4YQT8OxLcF2DcwGtUPm4JQF8Upfc2mysrS0dyThqV_wLeKkQ$> Here is a preview: https://deploy-preview-1684--jakartaee.netlify.app/about/meeting_minutes/#steering_committee<https://urldefense.com/v3/__https:/deploy-preview-1684--jakartaee.netlify.app/about/meeting_minutes/*steering_committee__;Iw!!ACWV5N9M2RV99hQ!M8mAOrka79-vyLOQvzUSX3oLaO0JzsMmcG2gVh_vYq4YQT8OxLcF2DcwGtUPm4JQF8Upfc2mysrS0dyThqViMGGKFw$>

Let me know if we're good to go live!
