### ISSUE TITLE
Cloud Native Java eBook link is broken

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakarta.ee#1687]
**Describe the bug**
When you click on the Download button for the Cloud Native Java eBook, you get a 404 Not Found error.

**To Reproduce**
1. Go to  https://jakarta.ee/release/10/
2. Scroll down to the text "NEW CLOUD NATIVE JAVA EBOOK"
3. Click on the Download button
4. You'll see a 404 error from this link: https://outreach.eclipse.foundation/open-source-cloud-native-java-ebook?hs_preview=vUXuuJeF-64105276785

**Expected behavior**
You're presented with a PDF book download.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Brave 
 - Version:  [Version 1.52.117 Chromium: 114.0.5735.90 (Official Build) (arm64)](https://brave.com/latest/)

**Additional context**

**Comment by oliviergoulet5** [comment]
Removing the `hs_preview` parameter on the url seems to work.

The fix would be to update the link to not include it.
