### ISSUE TITLE
Add the Jakarta EE Platform video on the website

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1688]
Please add the following video on the Jakarta EE Platform, web profile and core profile boxes on the specification page here: https://jakarta.ee/specifications/

https://www.youtube.com/watch?v=wK5Uis9QnFU

Can you please add a button called "Latest Updates" and add a "play" icon on that box so it indicates that it's a video?

<img width="1079" alt="Screen Shot 2023-06-29 at 8 01 10 AM" src="https://github.com/jakartaee/jakarta.ee/assets/51449073/409ae061-d467-4d96-bc7e-28951ac9f9bb">

**Comment by shabnammayel** [comment]
@oliviergoulet5 is there any updates on this?

**Comment by oliviergoulet5** [comment]
No progress as of yet @shabnammayel. I was on vacation during the last two weeks. 

I'll aim to get this done within the upcoming week if that works for you.

**Comment by oliviergoulet5** [comment]
@shabnammayel Here is a preview: https://deploy-preview-1692--jakartaee.netlify.app/specifications/

Let me know if we're good to go live or if there are changes needed

**Comment by oliviergoulet5** [comment]
Hi @shabnammayel. Wondering if you had the chance to look at this yet?

**Comment by shabnammayel** [comment]
Thanks for the reminder @oliviergoulet5 yes, LGTM! thanks

**Comment by oliviergoulet5** [comment]
No problem @shabnammayel. It is now deploying!
