### ISSUE TITLE
Add Jakarta EE 10 Tools Vendor Datasheet to the website & also create & add the HTML version 

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1696]
Can you please add the Jakarta EE 10 Datasheet on the website? here is the Pdf. doc: 
[Jakarta EE Datasheet_Updated (1).pdf](https://github.com/jakartaee/jakarta.ee/files/12244327/Jakarta.EE.Datasheet_Updated.1.pdf)

It should be added on the datasheet section of the resource page here: https://jakarta.ee/resources/#datasheets above the Jakarta EE 9 datasheet. 

Also can you please create the HTML version of the EE 10 datasheet? it's okay if we are not able to add the images and only add the content. thanks

**Comment by oliviergoulet5** [comment]
@shabnammayel Just to clarify: do you want both PDF and HTML on the website? Or only the HTML page?

And if both, should we link the HTML in the datasheet section, and link the PDF on the HTML page? A button with the text "Download PDF version"? Or should both just be linked under datasheets section?

**Comment by shabnammayel** [comment]
Yes, please add both HTML & Pdf. version: 

- Jakarta EE 9 Tools Vendor Datasheet
       - Download PDF version

So the HTML link is the main bullet point and as you suggested, we can add the Pdf version as a sub bullet point

**Comment by shabnammayel** [comment]
Also I just realized this error on the page on the whitepaper box:

After today it's supposed to be "'s" but it's there are some number's being displayed instead. Can you please fix that too? thanks

<img width="355" alt="Screen Shot 2023-08-02 at 5 32 38 PM" src="https://github.com/jakartaee/jakarta.ee/assets/51449073/663de995-2bb3-4046-861a-e9ad4ad3b7e1">

**Comment by oliviergoulet5** [comment]
@shabnammayel Here is a preview: https://deploy-preview-1697--jakartaee.netlify.app/resources

I will need to investigate the White Papers bug further.

**Comment by oliviergoulet5** [comment]
That widget for newsroom resources comes from Solstice Assets. I created the following issue to track the bug: https://gitlab.eclipse.org/eclipsefdn/it/webdev/solstice-assets/-/issues/372.

**Comment by oliviergoulet5** [comment]
@shabnammayel Are we good to go live?

**Comment by shabnammayel** [comment]
LGTM! thanks
