### ISSUE TITLE
Why Jakarta Page Changes

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1698]
https://jakarta.ee/about/why-jakarta-ee/

Below are some SEO and content changes we would like to implement for the Why Jakarta Page, as discussed with @shabnammayel 

**New Meta Title** 
Why Jakarta EE for Enterprise Java Application Development

**New Meta Description** 
Discover the benefits of Jakarta EE for enterprise Java application development. Move your apps to the cloud & enjoy stability, compatibility, & long-term support.

**Links at bottom of the page**
Please replace "Browse Specifications" with "Get Started"
Replace "Find Jakarta EE Platform, Profile and Individual specification documents." with "Generate a Jakarta EE project to get started."

**Add link to specifications in first paragraph**
![image](https://github.com/jakartaee/jakarta.ee/assets/73264129/9fdd73a1-ced4-40ad-a86b-85ae1ba87ec3)
Link the highlighted specifications word to https://jakarta.ee/specifications/

**Add link to specifications in the Jakarta EE is the Standard section**
![image](https://github.com/jakartaee/jakarta.ee/assets/73264129/91a83d99-eedc-4ef8-8e56-a9b88d4af517)
Link the orange highlighted specifications word to https://jakarta.ee/specifications/

**Comment by shabnammayel** [comment]
@oliviergoulet5 can you please switch the section of Jakarta EE is continuation with Jakarta EE is the standard? We want to move the "Standard" section to the top and add a blurb to the second paragraph of the standard section: 

But being the standard does not mean being riding. Jakarta EE **avoids single vendor lock-in** **and is** modular 

I bolded the new words we want to be added.

**Comment by oliviergoulet5** [comment]
@shabnammayel @excentrickristy Here is the preview for the updated content and SEO: https://deploy-preview-1700--jakartaee.netlify.app/about/why-jakarta-ee/

**Comment by excentrickristy** [comment]
Everything looks good! Thanks :)
