### ISSUE TITLE
Unlocking Potential: Persuading Your Employer to Support Your Contribution to Jakarta EE

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1702]
Please replace the placeholder text by the proper content.

**Blog post information**
title: Unlocking Potential: Persuading Your Employer to Support Your Contribution to Jakarta EE
date: today
summary: "In this blog post, we will explore the numerous benefits that arise when employees are encouraged to contribute to Jakarta EE as part of their normal work activities. These compelling arguments will help you convince your employer of the value it brings to your organisation while respecting the demands of your everyday work."
content: https://docs.google.com/document/d/1HyoN1OG2jKvAAyya45RojsomVs8mov_IZKw4v0Cb1MI/edit

**Comment by chrisguindon** [comment]
@TanjaObradovic Not sure I understand your request. Are you asking us to update an existing blog post or create a new one on the site?

**Comment by TanjaObradovic** [comment]
This is to create a new one on the site.

**Comment by chrisguindon** [comment]
Thank @TanjaObradovic - That's what I was thinking but "Please replace the placeholder text by the proper content." confused me :)

**Comment by TanjaObradovic** [comment]
Oh - I am sorry - that is from the template :)

**Comment by ZacharySabourin** [comment]
@TanjaObradovic Here is a preview of the requested changes:
- https://deploy-preview-1703--jakartaee.netlify.app/blogs/
- https://deploy-preview-1703--jakartaee.netlify.app/blogs/unlocking-potential-persuading-your-employer-to-support-your-contribution-to-jakarta-ee/

**Comment by TanjaObradovic** [comment]
Looks great! Many thanks!!

**Comment by TanjaObradovic** [comment]
Many thx Zach - sorry about this!

**Comment by ZacharySabourin** [comment]
@TanjaObradovic Not a problem. Here's a preview of the author changes: https://deploy-preview-1704--jakartaee.netlify.app/blogs/unlocking-potential-persuading-your-employer-to-support-your-contribution-to-jakarta-ee/

**Comment by TanjaObradovic** [comment]
Looks great! Many thx!!
