### ISSUE TITLE
FJ-EAP 1.2.0 as a Compatible Software Product for Jakarta EE 10 Full Platform

### ISSUE THREAD

**Issue by tnagao7** [jakartaee/jakarta.ee#1711]
Could you add the version [1.2.0](https://www.fujitsu.com/jp/products/software/middleware/business-middleware/middleware/applatform/jakartaee-report/eap120-ee10full-tck-results/#top) of "FUJITSU Software Enterprise Application Platform" in [Jakarta EE 10 Platform Compatible Products](https://jakarta.ee/compatibility/certification/10/), as shown in the image below?

![fj-eap-1 2 0](https://github.com/jakartaee/jakarta.ee/assets/32282211/9912ae4c-0d54-4016-8bdd-412a8999efb6)

The details are as follows (only "A product name and version" and "The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process" are updated from [the previous request](https://github.com/jakartaee/jakarta.ee/issues/1538)):

---

To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

[Fujitsu Limited](https://www.eclipse.org/membership/showMember.php?member_id=685)

**A product name and version**

FUJITSU Software Enterprise Application Platform 1.2.0

**Where to list the Compatible Product (Platform, Web Profile, Core Profile)**

Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

[EAP.zip](https://github.com/jakartaee/jakarta.ee/files/9612602/EAP.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Fujitsu Limited

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

https://github.com/jakartaee/jakartaee-platform/issues/716

**The URL where Compatible Software Product is available for download**

https://www.fujitsu.com/jp/software/applatform/

**Comment by ZacharySabourin** [comment]
@tnagao7 Here is a preview of the requested changes: https://deploy-preview-1716--jakartaee.netlify.app/compatibility/

**Comment by TanjaObradovic** [comment]
Looks great! Thanks!!
