### ISSUE TITLE
New Meta Data

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1718]
Some of the pages on the site have been flagged for having duplicate meta data. Here are some new meta descriptions to use instead:

https://jakarta.ee/community/adopt-a-spec/

Meta Description:
Adopt a Specification and empower your Java User Group (JUG) to shape the future of Jakarta EE. Learn how to participate, get recognition, and enjoy exclusive benefits.

https://jakarta.ee/committees/specification/operations/

Meta Description: 
Learn about the Jakarta EE specifications committee processes. Find out how to initiate reviews, create release plans, & ensure compliance with naming conventions. Read guidelines for distributing specifications & creating final releases.

https://jakarta.ee/committees/specification/guide/

Meta Description: 
A comprehensive guide to the Jakarta EE Specification Process (JESP). Learn the steps involved in creating, planning, releasing, and reviewing Jakarta EE specifications. 

https://jakarta.ee/committees/

Meta Description:
Learn about the Jakarta EE Committees and their different roles and responsibilities in the Jakarta EE Working Group.

https://jakarta.ee/committees/specification/

New Title: 
Jakarta EE Specification Committee | The Eclipse Foundation

Meta Description: 
Learn about the Jakarta EE Specification Committee and find related documents, meeting minutes, and committee members.

https://jakarta.ee/community/developer-advocate/

New Title: 
Ivar Grimstad - Jakarta EE Developer Advocate | The Eclipse Foundation

Meta Description: 
Learn more about Ivar Grimstad, our Jakarta EE Developer Advocate. Find conferences where he will be speaking or connect with him on social media.

https://jakarta.ee/committees/steering/brand_use_by_projects/

Meta Description:
Learn the proper usage of the Jakarta® EE brand by Eclipse Projects. Understand the guidelines for naming specifications & projects to comply with trademark regulations.

https://jakarta.ee/community/get-involved/

Meta Description:
Find out how to get involved in Jakarta EE. Join the conversation, learn how to contribute, become a committer, or join the Jakarta EE Working Group. Gain valuable experience & make an impact.

**Comment by excentrickristy** [comment]
Bumping this as well

**Comment by oliviergoulet5** [comment]
Hi @excentrickristy, here are the updated pages:

- https://deploy-preview-2015--jakartaee.netlify.app/community/adopt-a-spec/
- https://deploy-preview-2015--jakartaee.netlify.app/specification/operations/
- https://deploy-preview-2015--jakartaee.netlify.app/specification/guide/
- https://deploy-preview-2015--jakartaee.netlify.app/committees/
- https://deploy-preview-2015--jakartaee.netlify.app/committees/specification/
- https://deploy-preview-2015--jakartaee.netlify.app/community/developer-advocate/
- https://deploy-preview-2015--jakartaee.netlify.app/committees/brand_use_by_projects/
- https://deploy-preview-2015--jakartaee.netlify.app/community/get-involved/

**Comment by excentrickristy** [comment]
Thank you! 

These pages give me a 404:
https://deploy-preview-2015--jakartaee.netlify.app/specification/operations/
https://deploy-preview-2015--jakartaee.netlify.app/specification/guide/
https://deploy-preview-2015--jakartaee.netlify.app/committees/brand_use_by_projects/

But the rest look good!

**Comment by oliviergoulet5** [comment]
My bad, I typed the URLs manually and got some wrong.

- https://deploy-preview-2015--jakartaee.netlify.app/committees/specification/operations/ 
- https://deploy-preview-2015--jakartaee.netlify.app/committees/specification/guide/
- https://deploy-preview-2015--jakartaee.netlify.app/committees/steering/brand_use_by_projects/

**Comment by excentrickristy** [comment]
those look good, thank you!
