### ISSUE TITLE
New Title Tag Template

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1719]
The title tag in the template for new pages on the jakarta.ee site uses the format:

*Page title* | The Eclipse Foundation

For SEO, can we change this to:

*Page title* | Jakarta EE | The Eclipse Foundation ?

**Comment by excentrickristy** [comment]
Hello, just hoping for an update on this!

**Comment by oliviergoulet5** [comment]
I began working on this patch in September but have yet to revisit it. I'll make some time for it this week @excentrickristy.

**Comment by excentrickristy** [comment]
Revisiting this old issue - I noticed that the new spec pages for Jakarta EE 11 still use the old template.

**Comment by oliviergoulet5** [comment]
Hi @excentrickristy. 

The simplest way to manage this was to automatically append " | Jakarta EE | The Eclipse Foundation" to all the site title tags. All existing and future pages will be consistent regarding title tags, including the specification pages.

We can make certain exceptions for specific pages (e.g. the home page is slightly different "Jakarta EE | Cloud Native Enterprise Java | Java EE | The Eclipse Foundation", where Jakarta EE is at the forefront.)

Feel free to browse the preview site, and please let me know if this works for you!

https://deploy-preview-2014--jakartaee.netlify.app/

**Comment by excentrickristy** [comment]
This is great! Let's launch it.
