### ISSUE TITLE
Add starter guides page and related articles

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1720]
Please add "Learn" in the navigation bar between Resource and Starter button. 

We need a dropdown from learn named "Starter Guides"

We need a page for the Starter Guides that lists the following articles:
Main description for this page is: These guides provide quick, hands-on instructions for building different applications using Jakarta EE. FYI @TanjaObradovic 

 
[How to Build a RESTful Web Service Using Jakarta EE
](https://docs.google.com/document/d/1FncLrhXdM4InL2858jkwgrH5V553vXaJzC2EJ2AbqzY/edit)
[How to store and retrieve data using Jakarta Persistence of Jakarta EE
](https://docs.google.com/document/d/1kclCOJwd7wmMe-jR7OLDtqcoGOFCzloOF0CuT6CedFk/edit#heading=h.hu748k3te9rx)
[How to Secure a RESTful Web Service Using Jakarta EE
](https://docs.google.com/document/d/1xFJ3lIOuiQjgsqzPMX26MyKWoiOXBI3iNDpUJJFe3zo/edit#heading=h.s7i7i0uke1g5)
[How to Start with Servlets Using Jakarta EE 10](https://docs.google.com/document/d/1pCyLnLIoMMr_QV04fqTyIIh9q_qqlUbwwlpiH0PrmhE/edit)

We need a page for each of the articles above with Jakarta EE's usual banner and title would be the same as mentioned above for each of the articles

**Comment by oliviergoulet5** [comment]
I find that the navbar is getting too many top-level items. I suggest that we add "Learning Resources" as a submenu under "Resources" similar to how we have submenus for "About":

![image](https://github.com/jakartaee/jakarta.ee/assets/17685861/130f4a8c-a3a7-44e9-bffc-4a4a90e9fd94)

We could also add the "Jakarta EE Overview Course" menu item under that submenu.

Something like this:

![image](https://github.com/jakartaee/jakarta.ee/assets/17685861/28b7838a-efae-4c94-9793-4ff38fffa9d4)

@shabnammayel @TanjaObradovic

**Comment by oliviergoulet5** [comment]
Also do we want to display the starter guides like this:

![image](https://github.com/jakartaee/jakarta.ee/assets/17685861/45f966b7-4f27-4cc6-bae3-384f719693ce)

We would need images for this look. If we don't want images, we can show them like below:

![image](https://github.com/jakartaee/jakarta.ee/assets/17685861/2de089a9-ec61-4465-b656-393bc94bf936)

**Comment by shabnammayel** [comment]
@oliviergoulet5 Can you please rename the "Resources" In the navigation bar to "Learn" instead?

We can add a dropdown similar to your screenshot and have "Resources" first and then below resources add "Jakarta EE Starter Guides" below it 

We can add the articles without the images for now, but I will work with Mehrnaz/Excentric to add some images later or maybe a mockup to make the page look nicer! For now would be great to add these articles on the website asap. thanks

**Comment by oliviergoulet5** [comment]
@shabnammayel I will do the articles without images!

I'll implement what you suggest for the navbar for the sake of time. However, I find it misleading to have "Resources" as a sub-menu to "Learn" when not all resources are for learning purposes (e.g., branding, datasheets, etc..) It would take more work to navigate as someone looking for such a resource.

I understand that the goal is to bring focus and attention to the new starter guides. Is there a place on the homepage where we could also link it? A new section with a CTA? We can involve Mehrnaz/Excentric if we decide to go this route.

**Comment by shabnammayel** [comment]
@oliviergoulet5 as mentioned on slack we will have time to think it through more carefully regarding the placement of the learn or starter guides main page. However, it would be great if we can get one or two of the articles published today or tomorrow so we can promote it on socials.

**Comment by oliviergoulet5** [comment]
Here is a preview of the starter guide page and two of the four articles @shabnammayel:

- https://deploy-preview-1723--jakartaee.netlify.app/learn/starter-guides/
- https://deploy-preview-1723--jakartaee.netlify.app/learn/starter-guides/how-to-build-a-restful-web-service/
- https://deploy-preview-1723--jakartaee.netlify.app/learn/starter-guides/how-to-store-and-retrieve-data-using-jakarta-persistence/

Please let me know if there are any changes required!

**Comment by shabnammayel** [comment]
thanks @oliviergoulet5 LGTM!

**Comment by oliviergoulet5** [comment]
This is still in review, but it will be live tomorrow morning and available for promotion.

**Comment by oliviergoulet5** [comment]
I added the remaining guides @shabnammayel:

- https://deploy-preview-1725--jakartaee.netlify.app/learn/starter-guides/
- https://deploy-preview-1725--jakartaee.netlify.app/learn/starter-guides/how-to-start-with-servlets/
- https://deploy-preview-1725--jakartaee.netlify.app/learn/starter-guides/how-to-store-and-retrieve-data-using-jakarta-persistence/

**Comment by shabnammayel** [comment]
LGTM! thanks @oliviergoulet5

**Comment by oliviergoulet5** [comment]
@shabnammayel The remaining articles are being deployed. They will be available here shortly:

https://jakarta.ee/learn/starter-guides

**Comment by oliviergoulet5** [comment]
All that remains is figuring out where the starter guides page will be linked.

**Comment by shabnammayel** [comment]
Can we add a link here on the starter page for now while I figure out the permanent placement? https://start.jakarta.ee
it can be added below the issue tracker in the right corner box

**Comment by oliviergoulet5** [comment]
>Can we add a link here on the starter page for now while I figure out the permanent placement? https://start.jakarta.ee/
it can be added below the issue tracker in the right corner box

@shabnammayel Can you create an issue for this in the starter page repo? https://github.com/eclipse-ee4j/starter

I'll close this issue since there is nothing left to be done with the main jakarta.ee website.
