### ISSUE TITLE
Please update the Jakarta EE Specification Committee members

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1739]
Can you please update the Jakarta EE Specification Committee members on the https://jakarta.ee/committees/specification/? 

Please delete
Scott Stark - Red Hat - Elected Enterprise Representative, Scott Marlow - alternative
instead please add
Jun Qian - Primeton Information Technologies - Elected Enterprise Representative

Thanks,
Tanja

**Comment by oliviergoulet5** [comment]
Here is a preview @TanjaObradovic: https://deploy-preview-1741--jakartaee.netlify.app/committees/specification/

**Comment by TanjaObradovic** [comment]
many thx! looks good
