### ISSUE TITLE
New Design for Starter Guides Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1742]
We have created an updated design for the Starter Guides page: https://jakarta.ee/learn/starter-guides/

New Design Preview: https://invis.io/2D13DAXWGWK5#/475076175_Starter_Guides_-2-

Design File (2nd artboard): https://www.figma.com/file/Qx9ZrAztX66Rl5wqmWuFUV/Jakarta-EE-Learn-%2B-Starter-Guides?type=design&node-id=0%3A1&mode=design&t=EM3JExlb9Sgl8mU7-1 

I can invite someone to the figma file if needed.

**Comment by oliviergoulet5** [comment]
Hi @excentrickristy, can you provide the image asset for this background?

![image](https://github.com/jakartaee/jakarta.ee/assets/17685861/b89ba96e-53e8-49ab-8efb-d5e9db9af289)

**Comment by excentrickristy** [comment]
![bg-banner](https://github.com/jakartaee/jakarta.ee/assets/73264129/b3142284-e3f2-42b8-8d24-2bb8cb4ad5fa)
Here you go!

**Comment by oliviergoulet5** [comment]
Here is  a preview @excentrickristy @shabnammayel: https://deploy-preview-1759--jakartaee.netlify.app/learn/starter-guides/

**Comment by excentrickristy** [comment]
Looks good! Can you add a bit more whitespace after the guides and before the blue section with 3 columns of links?

On mobile, could you add a little more space after each link in the 3 column blue section as well?

Thanks!

**Comment by oliviergoulet5** [comment]
I updated the preview with the extra whitespace in the areas you have mentioned @excentrickristy

**Comment by excentrickristy** [comment]
perfect! ready to go.

**Comment by oliviergoulet5** [comment]
This is part of the same patch as the learning page changes @excentrickristy @shabnammayel. And the learning page is currently blocked until we have a place to link it. Is this something that can go live after New Year? 

Otherwise, I'll need to split my patch - which isn't a big deal.

**Comment by excentrickristy** [comment]
@oliviergoulet5 hopefully there is time to get it all launched before the new year, I know that was the goal. I just sent the changes on the other ticket!

**Comment by ZacharySabourin** [comment]
These changes are now live! https://jakarta.ee/
