### ISSUE TITLE
Update the Jakarta EE Tutorial link point to a new version of the tutorial hosted under the jakarta.ee domain

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakarta.ee#1746]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently, the Jakarta EE Tutorial link points to https://eclipse-ee4j.github.io/jakartaee-tutorial/. We are planning to release a new version of the tutorial, which is currently hosted at https://jakartaee.github.io/jakartaee-documentation/. We'd like (a) to make sure the link from jakarta.ee goes to the new tutorial, and (b) for the new tutorial to use the jakarta.ee domain. For (b), I presume using [Github Pages with a custom domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site) is best, but I'm open to other options.

@shabnammayel will be assisting with this.

**Comment by shabnammayel** [comment]
@chrisguindon can you please let us know what approach you think is best to help go live with the tutorial the soonest? thanks FYI @TanjaObradovic

**Comment by chrisguindon** [comment]
I think the easiest way would be to create a proxy rule in netlify as we did with start.eclipse.org:
https://github.com/jakartaee/jakarta.ee/blob/src/static/_redirects#L2

What URL do we want to use for this?

@oliviergoulet5 When the URL is shared, can you work with @kito99 and @shabnammayel on this issue to get this done?

Thanks

**Comment by shabnammayel** [comment]
If possible, can we have it in a same mechanism as the specification pages and use this URL for it?: Jakarta.ee/learn/tutorial? @chrisguindon

**Comment by chrisguindon** [comment]
> If possible, can we have it in a same mechanism as the specification pages and use this URL for it?: Jakarta.ee/learn/tutorial? @chrisguindon

In theory, we can use any "path" we want. However, it might require some changes in the tutorial code depending if they are using relative URLs or not.

We should be able to test this out using the netlify preview to see how it will behave. 

I will create an MR shortly.

**Comment by chrisguindon** [comment]
Actually, I am not sure I understand what you mean by same mechanism.

To make sure we are on the same page, I should be able to setup Jakarta.ee/learn/tutorial to load the code from  https://jakartaee.github.io/jakartaee-documentation/.

**Comment by shabnammayel** [comment]
Correct, that's what I meant as well. thanks @chrisguindon

**Comment by chrisguindon** [comment]
I created a patch to test this:
https://github.com/jakartaee/jakarta.ee/pull/1760

It's working but it's also broken:
https://deploy-preview-1760--jakartaee.netlify.app/learn/tutorial/

The CSS and JS are broken since they are outside of https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/current/

@kito99 Is this something you can fix on your end? 

The Netlify proxy that I am currently going with is:

`/learn/tutorial/* https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/current/:splat 200!
`

**Comment by kito99** [comment]
@chrisguindon thanks for doing this! what if we changed it to this:

`/learn/docs/* https://jakartaee.github.io/jakartaee-documentation/:splat 200!`

Then on the website, we link to:

`jakarta.ee/learn/docs/tutorial`

We may be hosting other docs underneath this path eventually, so this would work well and hopefully fix the path issue.

**Comment by chrisguindon** [comment]
Thanks @kito99!

I just made the change in my PR to show the site will behave:
https://github.com/jakartaee/jakarta.ee/pull/1760/files#diff-16b6401519950c5f36e2548e217df9174771c97bbfb0c8ead59906fe108d28fe

The preview URL should update in the next 5 to 10 minutes!

**Comment by chrisguindon** [comment]
I made the change but this triggers a redirect from https://deploy-preview-1760--jakartaee.netlify.app/learn/docs to https://deploy-preview-1760--jakartaee.netlify.app/learn/jakartaee-tutorial/current/index.html

**Comment by chrisguindon** [comment]
Just added the following rule to see if I can't improve the situation:

`/learn/jakartaee-tutorial/* https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/:splat 200!
`

https://github.com/jakartaee/jakarta.ee/pull/1760/files#diff-16b6401519950c5f36e2548e217df9174771c97bbfb0c8ead59906fe108d28fe

**Comment by kito99** [comment]
@chrisguindon the latter rules seems to do a redirect. If I go to `https://deploy-preview-1760--jakartaee.netlify.app/learn/jakartaee-tutorial/current` it redirects to `https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/current/`. 

However, this URL works properly: https://deploy-preview-1760--jakartaee.netlify.app/learn/docs/jakartaee-tutorial/current/. So once it's live, the URL would be https://jakarta.ee/learn/docs/jakartaee-tutorial/current/. Would that work, @shabnammayel? It'd be nice if https://deploy-preview-1760--jakartaee.netlify.app/learn/docs/jakartaee-tutorial would redirect to https://deploy-preview-1760--jakartaee.netlify.app/learn/docs/jakartaee-tutorial/current/, but currently the site doesn't do that.

**Comment by shabnammayel** [comment]
do we have to keep /current when it's live?

**Comment by kito99** [comment]
@shabnammayel Yes, although we can look into a way to change it so that `/learn/docs/jakartaee-tutorial/` redirects to  `/learn/docs/jakartaee-tutorial/current/` . Perhaps @chrisguindon can do that; we may able to do it at the tutorial level, but not until at least next week. 

FYI, `learn/docs/` works for now: https://deploy-preview-1760--jakartaee.netlify.app/learn/docs/

**Comment by shabnammayel** [comment]
@TanjaObradovic and @ivargrimstad are you good with this?

**Comment by chrisguindon** [comment]
Thanks @kito99 for checking that this works.

Let me know if you need me to make more changes and if we are good to push live!

**Comment by kito99** [comment]
Thanks @chrisguindon. Let's see what @TanjaObradovic  and @ivargrimstad have to say.

Just as a reminder, the Jakarta EE Tutorial link on this page (https://deploy-preview-1760--jakartaee.netlify.app/resources/#documentation) needs to be updated to point to this URL.

**Comment by TanjaObradovic** [comment]
all looks good, however I am not clear on /current is that path indicating that right now old style Tutorial will be shown and then with out it the new updated Tutorial style will be shown?

**Comment by kito99** [comment]
@TanjaObradovic not exactly. Basically here's the deal:

https://deploy-preview-1760--jakartaee.netlify.app/learn/docs/ => forwards to https://deploy-preview-1760--jakartaee.netlify.app/learn/docs/jakartaee-tutorial/current/ 
https://deploy-preview-1760--jakartaee.netlify.app/learn/docs/jakartaee-tutorial/current/ => displays docs for 10
https://deploy-preview-1760--jakartaee.netlify.app/learn/docs/jakartaee-tutorial/9.1/ => displays docs for 9.1 
https://deploy-preview-1760--jakartaee.netlify.app/learn/docs/jakartaee-tutorial/ => doesn't currently work but we can address this later.

Note these are all the, new refreshed site, not the old one (https://eclipse-ee4j.github.io/jakartaee-tutorial/#eclipse-glassfish-server-tools).

**Comment by TanjaObradovic** [comment]
Sounds good! Thanks for the clarification @kito99 !

**Comment by chrisguindon** [comment]
> Thanks @chrisguindon. Let's see what @TanjaObradovic and @ivargrimstad have to say.
> 
> Just as a reminder, the Jakarta EE Tutorial link on this page (https://deploy-preview-1760--jakartaee.netlify.app/resources/#documentation) needs to be updated to point to this URL.

@kito99 Thanks for the reminder. I made an update to my patch to update that link! 

https://github.com/jakartaee/jakarta.ee/pull/1760/commits/69dacee95b0076a729b5824385a186a936e00160

**Comment by kito99** [comment]
Looks good, @chrisguindon. I'll let you know when we're ready to switch over (probably Monday morning).

**Comment by chrisguindon** [comment]
> Looks good, @chrisguindon. I'll let you know when we're ready to switch over (probably Monday morning).

@kito99 Sounds good! I am available all day. I will push this to prod once you let me know that you are ready!

**Comment by shabnammayel** [comment]
FYI @kito99 our team has scheduled the first social post to go out tomorrow morning promoting this URL: https://jakarta.ee/learn/docs/jakartaee-tutorial/current/

So please let me know if for any reason we won't be able to go live with the page by then to pause the promotion.

**Comment by kito99** [comment]
@shabnammayel  sorry I missed that message!

@chrisguindon can you push to production now?

**Comment by chrisguindon** [comment]
@kito99 It's now merged. The site should be rebuilding now.

**Comment by chrisguindon** [comment]
I see that https://jakarta.ee/learn/docs/jakartaee-tutorial/current/ is working now. Closing this issue!
