### ISSUE TITLE
New Home Page Banner

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1747]
At @shabnammayel's request we have created a new home page banner design that includes a link to the latest release. It can link to https://jakarta.ee/release/

Design preview: https://invis.io/MZ13C3UGTXD6#/475114437_Jakarta-Design-New_Home_Banner_V2_11-2023

Design Files: https://www.dropbox.com/scl/fo/sqbi74fafmcwkket4tzbq/h?rlkey=kig1mdgay4dmfi9kb3b2cczd8&dl=0

If you need help cutting specific design assets please let me know!

**Comment by oliviergoulet5** [comment]
@excentrickristy Could I have the jumbotron background asset, please?

**Comment by excentrickristy** [comment]
![jakarta-banner](https://github.com/jakartaee/jakarta.ee/assets/73264129/d0f371a9-479e-4e86-9b9f-cbaf99d29536)

**Comment by oliviergoulet5** [comment]
Here is a preview: https://deploy-preview-1759--jakartaee.netlify.app/ @excentrickristy @shabnammayel

**Comment by excentrickristy** [comment]
Almost there, just a few picky tweaks to match the design:

On 
.header-wrapper .featured-jumbotron-default
Can you change padding-top to 164px 

And take the left margin off the text in the banner at desktop size so it aligns with the content further down the page.

On the background image I would do background-position: left center; for min-width: 1400px and then for 769px - 1400px switch to background-position: -230px 0; and then use background-position: 90% 0; for  max-width: 768px;

**Comment by oliviergoulet5** [comment]
Do you mean this margin?:

![image](https://github.com/jakartaee/jakarta.ee/assets/17685861/4521b71c-efd7-4e73-b462-10685a71c2e7)

**Comment by excentrickristy** [comment]
yes please!

**Comment by oliviergoulet5** [comment]
@excentrickristy The preview has been updated.

The CTA cards have also been updated - something I missed.

**Comment by excentrickristy** [comment]
looks amazing!! great work. Looks ready to go to me 👍

**Comment by ZacharySabourin** [comment]
These changes are now live! https://jakarta.ee/
