### ISSUE TITLE
Add Content to Jakarta Concurrency Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1748]
On this page: https://jakarta.ee/specifications/concurrency/

Can we add this content to the bottom of the page? It should go underneath the list of links to the releases.

https://docs.google.com/document/d/10FB__u7wbiH0NERyAo8iM8TuPvpSmRcTZMEackgBiz8/edit?usp=sharing

Please use an h2 tag for the title of the document and h3 tags for the headings within the document

The JUG Spec Adopters section should be moved to the bottom of the page, this content should be inserted above it.

**Comment by ZacharySabourin** [comment]
@excentrickristy  @shabnammayel. Here is a preview of the requested changes: https://deploy-preview-685--jakartaee-specifications.netlify.app/specifications/concurrency/

**Comment by excentrickristy** [comment]
beautiful! ready to go.

**Comment by shabnammayel** [comment]
is this live now? @oliviergoulet5

**Comment by oliviergoulet5** [comment]
We won't go live with this since we decided to create specification guides instead of updating the spec pages.

However, the specification guide page is already live. You can find it here: https://jakarta.ee/learn/specification-guides/concurrency-explained/.
