### ISSUE TITLE
Add Content to Contexts and Dependency Injection Spec Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1749]
On this page: https://jakarta.ee/specifications/cdi/

Can we add this content to the page? It should go underneath the list of links to the releases.

https://docs.google.com/document/d/1wcQJftZ4kK4NccVmXG7UivBsrH2xBG1nh5SGdSZZpnk/edit?usp=sharing

Please use an h2 tag for the title of the document and h3 tags for the headings within the document

The JUG Spec Adopters section should be moved to the bottom of the page, this content should be inserted above it.

**Comment by ZacharySabourin** [comment]
Hey, @excentrickristy @shabnammayel. Here is a preview of the requested changes: https://deploy-preview-683--jakartaee-specifications.netlify.app/specifications/cdi/

**Comment by excentrickristy** [comment]
@ZacharySabourin can we add a little more space before each sub-heading in the new section?

Let's switch the JUG adopters heading to an h2, and can we add an even bigger space above that section to separate it from the explained section?

Meta looks great!

**Comment by ZacharySabourin** [comment]
@excentrickristy I've modified the spacing on the sub-sections. https://deploy-preview-683--jakartaee-specifications.netlify.app/specifications/cdi/

I can't modify the heading size of the JUG section from this project. You would have to create an issue in the https://github.com/jakartaee/jakarta.ee repository and I could update it through a PR. Bear in mind that changing the header size will affect all other pages where the JUG section is displayed.

**Comment by excentrickristy** [comment]
Looks good, let's go live on that then.
I would like to pursue the change for the JUG section, I will create a separate issue. thanks!

**Comment by oliviergoulet5** [comment]
Closing, see https://github.com/jakartaee/jakarta.ee/issues/1847
