### ISSUE TITLE
Add Content to Jakarta Faces Spec Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1750]
On this page: https://jakarta.ee/specifications/faces/

Can we add this content to the page? It should go underneath the list of links to the releases.

https://docs.google.com/document/d/1_wMu1MIOYqBTeCITnfQvw3bIiSAXX9I4GIKUGRlh_oo/edit?usp=sharing

Please use an h2 tag for the title of the document and h3 tags for the headings within the document

**Comment by oliviergoulet5** [comment]
Here is a preview @excentrickristy: https://deploy-preview-680--jakartaee-specifications.netlify.app/specifications/faces

This current build does not have the updated styles for the specification pages. It will have the updated styles once deployed.

I'm sure you'll want to change the metatag description. Could you please add the desired metatag description to the other open issues?

**Comment by excentrickristy** [comment]
Can we add the margin to the subheadings here as well (see https://github.com/jakartaee/jakarta.ee/issues/1749) and we are good to go!

**Comment by ZacharySabourin** [comment]
@excentrickristy Here is a preview with the updated spacing: https://deploy-preview-680--jakartaee-specifications.netlify.app/specifications/faces

**Comment by excentrickristy** [comment]
looks good, ready to go! thanks.

**Comment by oliviergoulet5** [comment]
Closing, see https://github.com/jakartaee/jakarta.ee/issues/1847
