### ISSUE TITLE
Add Content to the Jakarta Servlet Spec Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1751]
On this page: https://jakarta.ee/specifications/servlet/

Can we add this content to the page? It should go underneath the list of links to the releases.

https://docs.google.com/document/d/19t0M9h11NVaibkwWdNr8l3M5BBi_2XnnRcO45rla_Cg/edit?usp=sharing

Please use an h2 tag for the title of the document and h3 tags for the headings within the document

**Comment by ZacharySabourin** [comment]
@excentrickristy  @shabnammayel Here is a preview of the requested changes: https://deploy-preview-684--jakartaee-specifications.netlify.app/specifications/servlet/

**Comment by excentrickristy** [comment]
Looks good! ready to go :)

**Comment by oliviergoulet5** [comment]
Closing, see https://github.com/jakartaee/jakarta.ee/issues/1847
