### ISSUE TITLE
Add Content to the Jakarta Server Pages Spec Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1752]
On this page: https://jakarta.ee/specifications/pages/

Can we add this content to the page? It should go underneath the list of links to the releases.

https://docs.google.com/document/d/10eCWeTfo2R3JQ4h7nINVF36RQqOeH70TltKJWLpza-M/edit?usp=sharing

Please use an h2 tag for the title of the document and h3 tags for the headings within the document

**Comment by oliviergoulet5** [comment]
Here is a preview @excentrickristy @shabnammayel https://deploy-preview-682--jakartaee-specifications.netlify.app/specifications/pages

**Comment by oliviergoulet5** [comment]
@excentrickristy @shabnammayel  Here is a preview https://deploy-preview-682--jakartaee-specifications.netlify.app/specifications/pages

Sadly, the JSP code snippets do not have syntax highlighting.

**Comment by excentrickristy** [comment]
Can we add a little more space before each sub heading? Then we will be good to go!

**Comment by ZacharySabourin** [comment]
@excentrickristy The preview now has the updated spacing: https://deploy-preview-682--jakartaee-specifications.netlify.app/specifications/pages

**Comment by excentrickristy** [comment]
looks good, ready to go!

**Comment by oliviergoulet5** [comment]
Closing, see https://github.com/jakartaee/jakarta.ee/issues/1847
