### ISSUE TITLE
Add Content to the Jakarta Security Spec Page 

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1753]
On this page: https://jakarta.ee/specifications/security/

Can we add this content to the page? It should go underneath the list of links to the releases.

https://docs.google.com/document/d/13qmhCbM0B1eT2VCdAjbtbLm17f4Jhx3G-p8sNk6D0eY/edit?usp=sharing

Please use an h2 tag for the title of the document and h3 tags for the headings within the document

**Comment by oliviergoulet5** [comment]
Hey @excentrickristy, is there a concrete deadline for the Security Spec page updates (this and the others)?


cc @shabnammayel

**Comment by shabnammayel** [comment]
@oliviergoulet5 for all the issues that Kristy created recently, we want to get them live before the end of the year. Does that work? Can we get the homepage banner updated this week though? thanks,

**Comment by oliviergoulet5** [comment]
I am on vacation between the 18th and the new year, but it should be enough time to complete these.

**Comment by oliviergoulet5** [comment]
Here is a preview @excentrickristy @shabnammayel https://deploy-preview-675--jakartaee-specifications.netlify.app/specifications/security

**Comment by excentrickristy** [comment]
My only change:
Can you add this new meta to the page?

Title:
Jakarta Security Specification | Jakarta EE | The Eclipse Foundation

Meta Description:
Find all releases of the Jakarta Security specification. Jakarta Security defines a standard for creating secure Jakarta EE applications.

**Comment by shabnammayel** [comment]
+1 LGTM! thanks

**Comment by oliviergoulet5** [comment]
@excentrickristy The preview has been updated with the new meta description and title

**Comment by excentrickristy** [comment]
Can we add the margin to the subheadings here as well (see https://github.com/jakartaee/jakarta.ee/issues/1749) and we are good to go!

**Comment by ZacharySabourin** [comment]
@excentrickristy Here is the updated spacing on the preview: https://deploy-preview-675--jakartaee-specifications.netlify.app/specifications/security

**Comment by excentrickristy** [comment]
looks good, ready to go!

**Comment by oliviergoulet5** [comment]
Closing, see https://github.com/jakartaee/jakarta.ee/issues/1847
