### ISSUE TITLE
Add Content to the Jakarta Authorization Spec Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1754]
On this page: https://jakarta.ee/specifications/authorization/

Can we add this content to the page? It should go underneath the list of links to the releases.

https://docs.google.com/document/d/16hoA8QF7ozdnSt_5XcdWm9pgTKyCEBqynB_COY7dvNA/edit?usp=sharing

Please use an h2 tag for the title of the document and h3 tags for the headings within the document

**Comment by oliviergoulet5** [comment]
Here is a preview @excentrickristy https://deploy-preview-678--jakartaee-specifications.netlify.app/specifications/authorization/

**Comment by excentrickristy** [comment]
@oliviergoulet5 do we have control over the meta on these pages? Title and meta description? yes?

**Comment by oliviergoulet5** [comment]
Yes I do @excentrickristy

**Comment by excentrickristy** [comment]
Can you please update the following meta data?

Title:
Jakarta Authorization Specification | Jakarta EE | The Eclipse Foundation

Meta Description:
Find all releases of the Jakarta Authentication specification. This specification defines a low-level SPI for authorization modules in Jakarta EE.


---

On the specification template as a whole can we apply the following style change?

For the main h1 title on the page, can you add the class big-text so that it looks like this:

![image](https://github.com/jakartaee/jakarta.ee/assets/73264129/9e9f6dbb-24ff-4607-9aff-548196e51502)

In the new Jakarta Authorization Explained Section can we add a 60px top margin to the h2 id jakarta-authorization-explained, and remove the Jakarta Authorization heading within the text?

**Comment by oliviergoulet5** [comment]
Here is a preview of the style changes @excentrickristy:

- https://deploy-preview-1791--jakartaee.netlify.app/specifications/authorization/

Includes the big-text class on h1. I added the margin to the list because it's easier to target. This is a separate patch from the spec page content update due to it being in a separate repository.

**Comment by excentrickristy** [comment]
Looks good! I'd love to bring the h1 size down by a few points though - is it easy to bring it down to 34px? If not we can leave it.

**Comment by oliviergoulet5** [comment]
@excentrickristy I would stay away from making more exceptions from our base styles. If we want to lower the `h1` to 34px, we should apply it to all `h1`s as their default.

**Comment by excentrickristy** [comment]
that's what I thought you might say! Let's leave it as is then. good to go!

**Comment by oliviergoulet5** [comment]
Closing, see https://github.com/jakartaee/jakarta.ee/issues/1847
