### ISSUE TITLE
Add Content to the Jakarta Authentication Spec Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1755]
On this page: https://jakarta.ee/specifications/authentication/

Can we add this content to the page? It should go underneath the list of links to the releases.

https://docs.google.com/document/d/1GYR62TQLWMHe3mqojMApgPahAkFOdDPO_VU-2y-CLXE/edit?usp=sharing

Please use an h2 tag for the title of the document and h3 tags for the headings within the document

**Comment by oliviergoulet5** [comment]
Hi, @excentrickristy @shabnammayel. I added the text content for the Authentication specification:

https://deploy-preview-679--jakartaee-specifications.netlify.app/specifications/authentication

I also included a meta title and description.

**Comment by oliviergoulet5** [comment]
@excentrickristy, I noticed you wanted to change the styles for the page (#1754). I'll create a separate preview that will update all specification pages simultaneously. Let's use this issue to review the text content.

**Comment by excentrickristy** [comment]
@oliviergoulet5 can you please remove the Jakarta Authentication heading under Jakarta Authentication Explained?

I split a document that had multiple specs and didn't think about how it would look on the website like this.

Can you change the meta description to this: 
Find all releases of the Jakarta Authentication specification which defines a general low-level SPI for authentication mechanisms in Jakarta EE.

Appreciate you updating the meta for me!

**Comment by oliviergoulet5** [comment]
Updated the preview with the suggested changes! @excentrickristy

**Comment by excentrickristy** [comment]
great! thanks!

**Comment by oliviergoulet5** [comment]
Closing, see https://github.com/jakartaee/jakarta.ee/issues/1847
