### ISSUE TITLE
Add Content to the Jakarta RESTful Web Services Spec Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1756]
On this page: https://jakarta.ee/specifications/restful-ws/

Can we add this content to the page? It should go underneath the list of links to the releases.

https://docs.google.com/document/d/1zIw6hO1mQRobFg8023dBnNN4do4DJTc3T_aoh_e9UAQ/edit?usp=sharing

Please use an h2 tag for the title of the document and h3 tags for the headings within the document

**Comment by oliviergoulet5** [comment]
Here is a preview @excentrickristy @shabnammayel https://deploy-preview-681--jakartaee-specifications.netlify.app/specifications/restful-ws

**Comment by excentrickristy** [comment]
Can we just add the margin on the sub headings (like here: https://github.com/jakartaee/jakarta.ee/issues/1749) and then we are good to go!

**Comment by ZacharySabourin** [comment]
@excentrickristy Here is a preview with the updated spacing https://deploy-preview-681--jakartaee-specifications.netlify.app/specifications/restful-ws

**Comment by excentrickristy** [comment]
great, ready to go!

**Comment by oliviergoulet5** [comment]
Closing in favour of #1847
