### ISSUE TITLE
Grant Commit Access to Kenji (Fujitsu) to implement the Japanese Translations

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1766]
@kazumura and his team are helping with implementing the Japanese translations. Can we grant him commit access to implement the Japanese translations on the website? 

GitHub Account : kazumura
Eclipse Account : kkazumura

Some background from Kenji: "We (Fujitsu) allocate some resource for this work only in short term (by the end of this year).

In order that more than one person are going to work parallelly, we divide all contents into small tasks.

In my experience, Hugo sometime did not compile and produces unrecognizable messages.

If such a case happens in monolithic approach,  all tasks are blocked until that problem is resolved.

Small PRs enable us to work independently and efficiently.

Only problem of this approach is that there may be some merge conflicts when PRs are not merged for a long time."

As Chris and his team might not be able to approve the MRs within the requested time (every 12hrs), we want to grant Kenji access.

**Comment by oliviergoulet5** [comment]
CC @chrisguindon

**Comment by ivargrimstad** [comment]
+1

**Comment by chrisguindon** [comment]
I added @kazumura to the community-jakarta.ee-website team which has write access to the jakarta.ee website repo!
