### ISSUE TITLE
Please update Payara alternate for the Steering Committee

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1788]
New Payara alternate for the Steering Committee is Ilias Efstathiou. Can you please update the webpage https://jakarta.ee/committees/steering/ ?

The line for Payara should be
 
Steve Millidge - Payara, Ilias Efstathiou - alternate

Thanks,
Tanja

**Comment by oliviergoulet5** [comment]
Here is a preview @TanjaObradovic:

- [English](https://deploy-preview-1790--jakartaee.netlify.app/committees/steering/)
- [Chinese](https://deploy-preview-1790--jakartaee.netlify.app/zh/committees/steering/)
- [Japanese](https://deploy-preview-1790--jakartaee.netlify.app/ja/committees/steering/)

**Comment by TanjaObradovic** [comment]
looks great! many thx!!
