### ISSUE TITLE
Modification to JUG heading on Specification pages

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1792]
On the specification pages, can we change the JUG Spec Adopters heading from an h3 to an h2?

For example on this page: https://jakarta.ee/specifications/cdi/

**Comment by ZacharySabourin** [comment]
@excentrickristy Here are some preview pages using the requested change: 
- https://deploy-preview-1793--jakartaee.netlify.app/specifications/cdi/
- https://deploy-preview-1793--jakartaee.netlify.app/specifications/jsonb/

**Comment by excentrickristy** [comment]
great, thank you!
