### ISSUE TITLE
Publish the Jakarta EE MKT CMTE Meeting mins

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1812]
I noticed that the mins have not been published since July 2023: https://jakarta.ee/about/meeting_minutes/

here are the pdfs of the meetings mins to be added to the website: 

[Jakarta EE Marketing Committee Meeting - July 27, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/13831947/Jakarta.EE.Marketing.Committee.Meeting.-.July.27.2023.11_00.ET.pdf)

[Jakarta EE Marketing Committee Meeting - August 10, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/13831986/Jakarta.EE.Marketing.Committee.Meeting.-.August.10.2023.11_00.ET.pdf)

[Jakarta EE Marketing Committee Meeting - August 24, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/13832039/Jakarta.EE.Marketing.Committee.Meeting.-.August.24.2023.11_00.ET.pdf)

[Jakarta EE Marketing Committee Meeting - September 7, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/13832043/Jakarta.EE.Marketing.Committee.Meeting.-.September.7.2023.11_00.ET.pdf)

[Jakarta EE Marketing Committee Meeting - September 21, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/13832046/Jakarta.EE.Marketing.Committee.Meeting.-.September.21.2023.11_00.ET.pdf)

[Jakarta EE Marketing Committee Meeting - October 5, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/13832048/Jakarta.EE.Marketing.Committee.Meeting.-.October.5.2023.11_00.ET.pdf)

[Jakarta EE Marketing Committee Meeting - October 12, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/13832049/Jakarta.EE.Marketing.Committee.Meeting.-.October.12.2023.11_00.ET.pdf)

[Jakarta EE Marketing Committee Meeting - November 2, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/13832050/Jakarta.EE.Marketing.Committee.Meeting.-.November.2.2023.11_00.ET.pdf)

[Jakarta EE Marketing Committee Meeting - November 16, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/13832053/Jakarta.EE.Marketing.Committee.Meeting.-.November.16.2023.11_00.ET.pdf)

[Jakarta EE Marketing Committee Meeting - November 30, 2023 (11_00 ET).pdf](https://github.com/jakartaee/jakarta.ee/files/13832055/Jakarta.EE.Marketing.Committee.Meeting.-.November.30.2023.11_00.ET.pdf)

**Comment by oliviergoulet5** [comment]
@shabnammayel Here is a preview: https://deploy-preview-1815--jakartaee.netlify.app/about/meeting_minutes/

I also changed the date format on the links to match the [new writing style guide](https://www.eclipse.org/org/documents/writing-style-guide/).

**Comment by oliviergoulet5** [comment]
@shabnammayel @TanjaObradovic Bumping this issue

**Comment by shabnammayel** [comment]
LGTM! thanks @oliviergoulet5
