### ISSUE TITLE
Order the releases at the specification pages is incorrect 

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1818]
For all the the specifications pages can you please help order the releases from the latest to the oldest please?

for example for this specification
https://jakarta.ee/specifications/platform/
<img width="370" alt="image" src="https://github.com/jakartaee/jakarta.ee/assets/40073121/4990b230-4b7e-434b-a995-81f97182cbca">

we should see 
Jakarta EE Platform 11 (Under development)
Release of the Jakarta EE 11 Platform

Jakarta EE Platform 10
Release of the Jakarta EE 10 Platform

Jakarta EE Platform 9.1
Jakarta EE Platform 9.1 defines a standard platform for …

Jakarta EE Platform 9
Jakarta EE Platform 9 defines a standard platform for …

Jakarta EE Platform 8
Jakarta EE Platform 8 defines a standard platform for …

**Comment by oliviergoulet5** [comment]
The problem was that the sorting was happening on a character-by-character basis. The first character of `11` is `1`, which comes before `8` alphanumerically.

@TanjaObradovic I fixed the sorting on all specification pages to treat numbers as proper numbers.

Here is a preview of a few specification pages which had this issue: 

- https://deploy-preview-1819--jakartaee.netlify.app/specifications/platform/
- https://deploy-preview-1819--jakartaee.netlify.app/specifications/webprofile/
- https://deploy-preview-1819--jakartaee.netlify.app/specifications/coreprofile/

**Comment by shabnammayel** [comment]
LGTM! @TanjaObradovic are you good with the changes too?

**Comment by TanjaObradovic** [comment]
For these three it looks good, however for individual specifications does not - it is in revers order
<img width="461" alt="image" src="https://github.com/jakartaee/jakarta.ee/assets/40073121/0c2cbf74-206e-4226-b4bb-6f42aa163b10">

**Comment by oliviergoulet5** [comment]
@TanjaObradovic I don't see that ordering on the preview site. The previews show the versions in descending order for every specification:

![image](https://github.com/jakartaee/jakarta.ee/assets/17685861/cfcd7c6c-7f1a-4885-922a-a0ab76354bf9)

**Comment by TanjaObradovic** [comment]
Hmmmm strange!
@shabnammayel what do you see?
here is for Activation in in another browser
<img width="392" alt="image" src="https://github.com/jakartaee/jakarta.ee/assets/40073121/b8a8544c-668f-4c77-835f-9124c7d53eae">

**Comment by ivargrimstad** [comment]
@TanjaObradovic as @oliviergoulet5 points out, you need to see it in the preview. If you click between the sessions you end up on the real site. Try this one:

https://deploy-preview-1819--jakartaee.netlify.app/specifications/activation/ 

(note that the root URL is NOT jakarta.ee)

**Comment by shabnammayel** [comment]
Yes, they look good to me as well!

**Comment by TanjaObradovic** [comment]
Ok - looks good to me! I thought this was previously implemented  and live already - @ivargrimstad Ivar know me the best :)
Sorry for the hold up! Thanks @oliviergoulet5 for your patience!
