### ISSUE TITLE
Add the Jakarta RESTful Web Services Video to the spec page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1820]
Please add the new video about the Jakarta RESTful web service to the spec page on the RESTful Web service box, similar to what we did with the Platform video: https://www.youtube.com/watch?v=7mfVyPI360k

Please add a box next to the website box on the Jakarta RESTful Web service section and call it "Latest Updates" and add the link to the video there: https://jakarta.ee/specifications/ 

We will soon create an issue to add all these learning videos on the new "Learn" Page as well. thanks

**Comment by shabnammayel** [comment]
@oliviergoulet5 and @chrisguindon can we please move forward with this? thanks

**Comment by oliviergoulet5** [comment]
The video guide went live on the site yesterday: https://jakarta.ee/specifications/
