### ISSUE TITLE
Please include Red Hat JBoss Enterprise Application Platform 8.0.0 as Jakarta EE 10 Platform, Web Profile, Core Profile compatible

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#1823]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
<br>
[Eclipse.org account for Scott Marlow](https://accounts.eclipse.org/users/smarlowsxi)<br>
[github.com account for Scott Marlow](https://github.com/scottmarlow)<br>
[Eclipse.org membership for Red Hat](https://www.eclipse.org/membership/showMember.php?member_id=731)<br><br>

**Product name and version**<br>
Name: JBoss Enterprise Application Platform (JBoss EAP)<br>
Version: 8.0.0<br><br>

**Where to list the Compatible Product (Platform, Web Profile, Core Profile)**
<br>
Jakarta EE 10 Platform<br>
Jakarta EE 10 Web Profile<br>
Jakarta EE 10 Core Profile<br><br>

**ZIP file with a product logo with a transparent background in SVG format (optional)**<br>
[JBoss EAP](https://github.com/RedHatOfficial/jbosseap-certifications/blob/EE8/images/Logo-Red_Hat-JBoss_Enterprise_Application_Platform-B-Standard-RGB.png)<br><br>

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**<br>
Red Hat<br><br>

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**<br>
[Jakarta EE 10 Platform](https://github.com/jakartaee/platform/issues/798)<br>
[Jakarta EE 10 Web Profile](https://github.com/jakartaee/platform/issues/799)<br>
[Jakarta EE 10 Core Profile](https://github.com/jakartaee/platform/issues/800)<br><br>

**The URL where Compatible Software Product is available for download**<br>
https://www.redhat.com/en/technologies/jboss-middleware/application-platform

**Comment by oliviergoulet5** [comment]
Here are previews of this change: 

- https://deploy-preview-1834--jakartaee.netlify.app/compatibility/
- https://deploy-preview-1834--jakartaee.netlify.app/compatibility/certification/10/
- https://deploy-preview-1834--jakartaee.netlify.app/compatibility/download/

Please let me know if it is good to go live @scottmarlow @TanjaObradovic

**Comment by scottmarlow** [comment]
Thank you @oliviergoulet5, I will respond soon with my feedback after I ask a few others at Red Hat for feedback.  I appreciate your help!

**Comment by scottmarlow** [comment]
I did notice that https://github.com/jakartaee/platform/issues/798 was pointing at the Core Profile TCK results (https://github.com/RedHatOfficial/jbosseap-certifications/blob/EE10/EAP-8.0.0/jakarta-core-jdk17.adoc#tck-results + https://github.com/RedHatOfficial/jbosseap-certifications/blob/EE10/EAP-8.0.0/jakarta-core-jdk11.adoc#tck-results) but should of been pointing at the Platform TCK results (https://github.com/RedHatOfficial/jbosseap-certifications/blob/EE10/EAP-8.0.0/jakarta-full-platform-jdk17.adoc#tck-results + https://github.com/RedHatOfficial/jbosseap-certifications/blob/EE10/EAP-8.0.0/jakarta-full-platform-jdk11.adoc#tck-results).

The ^ error also shows up on https://deploy-preview-1834--jakartaee.netlify.app/compatibility/certification/10 page in the `Jakarta EE 10 Platform Compatible Products` section which should be changed to refer to https://github.com/RedHatOfficial/jbosseap-certifications/blob/EE10/EAP-8.0.0/jakarta-full-platform-jdk17.adoc#tck-results + https://github.com/RedHatOfficial/jbosseap-certifications/blob/EE10/EAP-8.0.0/jakarta-full-platform-jdk11.adoc#tck-results

@oliviergoulet5 we are still reviewing the content in general and will respond with more feedback in a few days.

**Comment by scottmarlow** [comment]
@oliviergoulet5 
Is there anything that I can do to help with making the correction I mentioned in my previous comment here and on https://github.com/jakartaee/jakarta.ee/pull/1834?

I should be getting more feedback on Monday morning February 5, 2024 and will comment again on Monday.  Thanks for your patience!

**Comment by scottmarlow** [comment]
@oliviergoulet5 I can now confirm that the only change needed is correcting the Platform TCK result link as mentioned in the [above comment](https://github.com/jakartaee/jakarta.ee/issues/1823#issuecomment-1906771362) and my feedback on https://github.com/jakartaee/jakarta.ee/pull/1834

Thank you very much for the help!

**Comment by oliviergoulet5** [comment]
Great! I updated the PR with the proper links @scottmarlow.
