### ISSUE TITLE
Typo in website

### ISSUE THREAD

**Issue by eclipsewebmaster** [jakartaee/jakarta.ee#1826]
From the webmaster inbox:

Take a look at https://jakarta.ee/specifications/faces/2.3/apidocs/?javax/faces/application/ResourceHandler.html

You will see "Jakarta Server Fages API v2.3.2"

**Comment by ivargrimstad** [comment]
Not likely to be fixed as it would require a service release of the JavaDoc for a very old release. 
Anyway, it should be filed with the Faces project (for some reason, I can't transfer the issue).

https://github.com/jakartaee/faces/issues
