### ISSUE TITLE
Add 2023 Jakarta EE Survey report Infographics on the resource page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1833]
Please add the Infographic on the resource page under the Infographic section:
[Infographic-JakartaEE-2023.pdf](https://github.com/jakartaee/jakarta.ee/files/14024457/Infographic-JakartaEE-2023.pdf)

on the resource page: https://jakarta.ee/resources/

above the 2022 version here: 
<img width="1240" alt="Screen Shot 2024-01-23 at 8 15 07 AM" src="https://github.com/jakartaee/jakarta.ee/assets/51449073/da65f05f-c2a7-4038-8e28-f4826d077564">

Thanks

**Comment by oliviergoulet5** [comment]
Here is a preview @shabnammayel https://deploy-preview-1844--jakartaee.netlify.app/resources/

**Comment by shabnammayel** [comment]
LGTM! thanks
