### ISSUE TITLE
Adding New Content Type - Specification Guides

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1847]
Requesting on behalf of @shabnammayel 

We would like to add a new type of content to the Jakarta EE website, specification guides. 

Here you can access the design we are proposing for the specification guides:https://www.figma.com/file/lkN8FwRkbf4ZxaYQaeElot/Jakarta-Pages?type=design&node-id=58%3A2&mode=dev&t=OPiTMWPhED7u4Wve-1

It is based on the starter guides templates. We would like to update the Starter Guides template to match, but I will open a separate issue for that.

There will be 7 guides:

Jakarta Servlet, Jakarta Faces and Jakarta Server Pages Explained
https://docs.google.com/document/d/1HStt7QWZhUjEWJpe1r0DKaW3joUUEcWGNdiraHwj3q4/edit?usp=sharing

Jakarta Security, Jakarta Authorization, and Jakarta Authentication Explained
https://docs.google.com/document/d/1s4r286XJ3KtaOIOOEVgJ2Rxi1cgJQc41SYZ7iyMeTX4/edit?usp=sharing

Jakarta RESTful Web Services Explained
https://docs.google.com/document/d/1zIw6hO1mQRobFg8023dBnNN4do4DJTc3T_aoh_e9UAQ/edit?usp=sharing

Jakarta Persistence Explained
https://docs.google.com/document/d/1iSEPhb3gFozIxo7CxfS8lkDWo1mMF1J8e3jZLLV_8RE/edit?usp=sharing

Jakarta EE Platform
https://docs.google.com/document/d/1gGMntQRjq2xOpARsbkEfPszq__zQme3TbC2wwXyv_14/edit?usp=sharing

Jakarta Contexts Dependency Injection Explained
https://docs.google.com/document/d/1wcQJftZ4kK4NccVmXG7UivBsrH2xBG1nh5SGdSZZpnk/edit?usp=sharing

Jakarta Concurrency Explained
https://docs.google.com/document/d/10FB__u7wbiH0NERyAo8iM8TuPvpSmRcTZMEackgBiz8/edit?usp=sharing

We will also need to add a Specification Guide overview page. We would like that page to follow the format of this page: https://jakarta.ee/learn/starter-guides/ but using the new icon that you see in the design for the spec guide pages.

**Comment by oliviergoulet5** [comment]
Hi @excentrickristy and @shabnammayel. I'm beginning to implement these pages.

Could you please provide a description and relevant keywords for the specification guides overview page? We'll need it for SEO

**Comment by excentrickristy** [comment]
@oliviergoulet5 

Title Tag:
Jakarta EE Specification Guides | The Eclipse Foundation

Meta Description: 
Our spec guides provide in-depth explanations about how Jakarta EE specifications work. Get code examples and learn more about what you can do with Jakarta EE.

**Comment by oliviergoulet5** [comment]
Here is a preview of the specification guide list page and the guides themselves: https://deploy-preview-1876--jakartaee.netlify.app/learn/specification-guides/

@excentrickristy @shabnammayel 

I had to use a different (but similar) icon offered by [FontAwesome 4](https://fontawesome.com/v4/icons/) which is the icon library used by our sites.

**Comment by excentrickristy** [comment]
Thank you - this is good to go!

**Comment by oliviergoulet5** [comment]
I'll now revisit the learn page redesign to have these linked. I plan to deploy these specification guides for now without having them linked to the site. They may still show up in Google Search. 

Do you see any issues with @excentrickristy? If you do, I will leave it in a development branch and release it along with the learn page.

**Comment by excentrickristy** [comment]
Won't be a problem! They will just get a head start to rank :)
