### ISSUE TITLE
Add a prominent join button on Jakarta EE's membership page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1851]
Please see the screenshot below:

![image (16)](https://github.com/jakartaee/jakarta.ee/assets/51449073/5e5f21a5-a3f5-40d9-adfb-6eb5088b26d1)

Can you please add a "Join" button in the area that's highlighted in the screenshot (top section of the page) which should link to: https://jakarta.ee/membership/join-us/ 

thanks

**Comment by shabnammayel** [comment]
@chrisguindon can you please assign someone to this issue to make the change? thanks

**Comment by autumnfound** [comment]
> Can you please add a "Join" button in the area that's highlighted in the screenshot (top section of the page) which should link to: https://jakarta.ee/membership/join-us/

Putting a button above the content would mean that "Join" would have no context and would likely break up the flow of the page. Would you be open to moving the button to below the content in the first section, something like below?

![image](https://github.com/jakartaee/jakarta.ee/assets/23018241/95234fb5-8769-41cb-95f2-c6734cf984f1)

**Comment by shabnammayel** [comment]
Yes, I think that looks good too! thanks

**Comment by oliviergoulet5** [comment]
Here is a preview https://deploy-preview-1856--jakartaee.netlify.app/membership/ @shabnammayel

**Comment by oliviergoulet5** [comment]
Hello @shabnammayel, have you had a chance to take a look at the preview?

**Comment by shabnammayel** [comment]
Apologies @oliviergoulet5 I thought I already gave a +1. LGTM, thanks
