### ISSUE TITLE
Change Projects Link in Main Navigation

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1870]
In the main menu:

Specifications -> Specification Projects links to https://projects.eclipse.org/list-of-projects?combine=jakarta&field_project_techology_types_tid=1102&field_state_value_2=All

Instead, Specification Projects should link to https://jakarta.ee/projects/

**Comment by oliviergoulet5** [comment]
I updated the link here: https://deploy-preview-1871--jakartaee.netlify.app/

@excentrickristy

**Comment by excentrickristy** [comment]
perfect, thanks!

**Comment by oliviergoulet5** [comment]
My pleasure. This is going live!
