### ISSUE TITLE
Update the Jakarta EE prospectus

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1877]
Please replace the prospectus with this updated pdf on this page https://jakarta.ee/membership/
[Jakarta EE Membership prospectus.pdf](https://github.com/jakartaee/jakarta.ee/files/14640224/Jakarta.EE.Membership.prospectus.pdf)

CC @TanjaObradovic

**Comment by oliviergoulet5** [comment]
Here is a preview of the membership page with the updated prospectus: https://deploy-preview-1878--jakartaee.netlify.app/membership/

@shabnammayel Let me know when we're good to go live!

**Comment by shabnammayel** [comment]
LGTM! thanks @oliviergoulet5 FYI @TanjaObradovic

**Comment by oliviergoulet5** [comment]
Going live!
