### ISSUE TITLE
Publish May 2023 - Dec 2023 Jakarta EE Steering Committee Meeting Minutes

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1883]
This is not a bug

We need to add new entries for Steering meeting minutes for May 2023 - Dec 2023, in https://jakarta.ee/meeting_minutes/ , under the tab: Jakarta EE Steering Committee, in the same way as other files with just adding a date with the link.

I have attached  pdf files:
[Minutes of the May 9, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747613/Minutes.of.the.May.9.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the May 23, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747615/Minutes.of.the.May.23.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the June 6, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747621/Minutes.of.the.June.6.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the June 20, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747622/Minutes.of.the.June.20.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the July 11, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747624/Minutes.of.the.July.11.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the July 18, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747626/Minutes.of.the.July.18.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the August 1, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747627/Minutes.of.the.August.1.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the August 15, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747631/Minutes.of.the.August.15.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the August 29, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747634/Minutes.of.the.August.29.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the September 12, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747640/Minutes.of.the.September.12.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the October 10, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747642/Minutes.of.the.October.10.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the October 24, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747643/Minutes.of.the.October.24.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the November 21, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747644/Minutes.of.the.November.21.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the December 19, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747645/Minutes.of.the.December.19.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

I do not have tracking of approval of the Nov 7 meeting minutes and will follow up

**Comment by ZacharySabourin** [comment]
@will-lyons Here is a preview of the requested changes: https://deploy-preview-1885--jakartaee.netlify.app/about/meeting_minutes/#steering_committee

I've combined the changes requested in https://github.com/jakartaee/jakarta.ee/issues/1884 as well

**Comment by will-lyons** [comment]
I have reviewed.  Looks good.  Please publish.   Thank you.

**Comment by will-lyons** [comment]
Zachary - The Jan - Feb 2024 meeting minutes are published here: https://jakarta.ee/about/meeting_minutes/#steering_committee (which is good) 

But the Jan - Feb 2024 meeting minutes are NOT published here:
https://jakarta.ee/committees/steering/ (which is not good, or inconsistent with the above) 

I don't know why we're publishing the minutes in two places, but as we are we should keep both of the above current.
