### ISSUE TITLE
Publish Jan - Feb 2024 Jakarta EE Steering Committee Meeting Minutes

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1884]
This is not a bug

We need to add new entries for Steering meeting minutes for Jan 2024 - Feb 2024, in https://jakarta.ee/meeting_minutes/ , under the tab: Jakarta EE Steering Committee, in the same way as other files with just adding a date with the link.

I have attached pdf files:
[Minutes of the February 27, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747731/Minutes.of.the.February.27.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the February 13, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747732/Minutes.of.the.February.13.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the January 30, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747733/Minutes.of.the.January.30.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the January 16, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/14747734/Minutes.of.the.January.16.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by will-lyons** [comment]
Zachary - The Jan - Feb 2024 meeting minutes are published here: https://jakarta.ee/about/meeting_minutes/#steering_committee (which is good)

But the Jan - Feb 2024 meeting minutes are NOT published here:
https://jakarta.ee/committees/steering/ (which is not good, or inconsistent with the above)

I don't know why we're publishing the minutes in two places, but as we are we should keep both of the above current.

**Comment by will-lyons** [comment]
Zachary
The Jan - Feb 2024 meeting minutes are published here: https://jakarta.ee/about/meeting_minutes/#steering_committee (which is good)
But the Jan - Feb 2024 meeting minutes are NOT published here:
https://jakarta.ee/committees/steering/ (which is not good, or inconsistent with the above)
I don't know why we're publishing the minutes in two places, but as we are we should keep both of the above current.

I made the same comment in https://github.com/jakartaee/jakarta.ee/issues/1883 and https://github.com/jakartaee/jakarta.ee/issues/1884.

Thanks

Will

From: Zachary Sabourin ***@***.***>
Date: Monday, April 1, 2024 at 2:45 PM
To: jakartaee/jakarta.ee ***@***.***>
Cc: Will Lyons ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [jakartaee/jakarta.ee] Publish Jan - Feb 2024 Jakarta EE Steering Committee Meeting Minutes (Issue #1884)

Closed #1884<https://urldefense.com/v3/__https:/github.com/jakartaee/jakarta.ee/issues/1884__;!!ACWV5N9M2RV99hQ!JaW_YDejNir22rDEYKphqMyYpnnLJDtcV3DMuO6W8x-Vt2MXRRQvUsovwy8Pz1C4Q54kDa4CKGDj092JTpt_MCxspg$> as completed via #1885<https://urldefense.com/v3/__https:/github.com/jakartaee/jakarta.ee/pull/1885__;!!ACWV5N9M2RV99hQ!JaW_YDejNir22rDEYKphqMyYpnnLJDtcV3DMuO6W8x-Vt2MXRRQvUsovwy8Pz1C4Q54kDa4CKGDj092JTptHjI4XKQ$>.

**Comment by ZacharySabourin** [comment]
Hey @will-lyons! My apologies! It appears I overlooked a property that allowed the 2024 minutes to display on the committee pages.

Here is a preview with the fix: https://deploy-preview-1890--jakartaee.netlify.app/committees/steering/

**Comment by will-lyons** [comment]
Zachary –

Looks good, please publish.

Thanks

Will

From: Zachary Sabourin ***@***.***>
Date: Monday, April 8, 2024 at 9:27 AM
To: jakartaee/jakarta.ee ***@***.***>
Cc: Will Lyons ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [jakartaee/jakarta.ee] Publish Jan - Feb 2024 Jakarta EE Steering Committee Meeting Minutes (Issue #1884)

Hey @will-lyons<https://urldefense.com/v3/__https:/github.com/will-lyons__;!!ACWV5N9M2RV99hQ!I-yoiHgPDESpGnCYGKwow5SIeic9EBgwKoYw9zlt3mq8g4f48EpucHP4bprgp1wWmSlQoAdJE03sqbzmMDrUMIwqRg$>! My apologies! It appears I overlooked a property that allowed the 2024 minutes to display on the committee pages.

Here is a preview with the fix: https://deploy-preview-1890--jakartaee.netlify.app/committees/steering/<https://urldefense.com/v3/__https:/deploy-preview-1890--jakartaee.netlify.app/committees/steering/__;!!ACWV5N9M2RV99hQ!I-yoiHgPDESpGnCYGKwow5SIeic9EBgwKoYw9zlt3mq8g4f48EpucHP4bprgp1wWmSlQoAdJE03sqbzmMDrLSJRl3g$>
