### ISSUE TITLE
Create a "Become a Jakarta EE Sponsor" page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1887]
We have the mockup for the page: https://projects.invisionapp.com/share/PK13G87RRDG3#/screens/476181790_Become_A_Sponsor
 
@excentrickristy is making some minor updates to this page and will share the latest one here once ready. 

We want to add the page under the membership drop down bellow "Members" and name it "Become a Sponsor". But we also want to change the name of membership in navigation to "Supporters" instead similar to what we have in the EF site and IDE WG website. 

Would it be possible for this page to be implemented by next week Monday before the Devnexus Conference so we can share it with potential community members that might be interested to Sponsor? @chrisguindon

**Comment by chrisguindon** [comment]
@shabnammayel While we can accommodate this exception, please ensure to provide us with more advanced notice in the future. In order to prioritize this request, we'll need to postpone a project for SDV.

@oliviergoulet5 can you work with @shabnammayel and @excentrickristy on this project this week!

**Comment by excentrickristy** [comment]
I just updated the invision link with the latest edits. 

@oliviergoulet5 I will cut some assets for you.

**Comment by excentrickristy** [comment]
![sponsor-banner](https://github.com/jakartaee/jakarta.ee/assets/73264129/d4d5b8c6-e76a-448c-8170-c8015ff8c1d5)
![icon-4](https://github.com/jakartaee/jakarta.ee/assets/73264129/d7b07037-1bd5-4079-b938-2feefc40eb2b)
![icon-3](https://github.com/jakartaee/jakarta.ee/assets/73264129/195c342f-88cd-4ce3-bfdf-a7a9e769f582)
![icon-2](https://github.com/jakartaee/jakarta.ee/assets/73264129/51e17a05-754b-4157-b512-7e61f5f5e04b)
![icon-1](https://github.com/jakartaee/jakarta.ee/assets/73264129/a6dbea70-a726-412a-b5ae-71e72f1bc013)

There are 4 white SVGs here.. you can right click to grab them hopefully! email me if you have trouble.

Here is the figma link: https://www.figma.com/file/4KdOpTvmODLbnW0r2fyQ1X/Jakarta-EE-Sponsor?type=design&node-id=0%3A1&mode=design&t=fTDzYUjByzM9XMsB-1

Let me know if there's anything else you need.

**Comment by oliviergoulet5** [comment]
@excentrickristy Thanks! 

I believe I need the icons used here (without the blue background):
![image](https://github.com/jakartaee/jakarta.ee/assets/17685861/39ca6299-65d0-4ec5-805a-4a1fe1a02a5a)

And the Jakarta EE Sponsor logo:

![image](https://github.com/jakartaee/jakarta.ee/assets/17685861/24888884-dfab-4fd5-82d3-750fbc5c3414)

**Comment by oliviergoulet5** [comment]
@shabnammayel I have two more questions:
1. Can I get the URLs for the links? For "contact us" and "become a sponsor"
2. What will the URL be?

e.g.

https://jakarta.ee/membership/become-a-sponsor
https://jakarta.ee/sponsor
https://jakarta.ee/supporters/sponsor
https://jakarta.ee/sponsor/become-a-sponsor

**Comment by excentrickristy** [comment]
![icon-1-banner](https://github.com/jakartaee/jakarta.ee/assets/73264129/120508e7-abcd-4772-a604-c55a73e83b87)![logo](https://github.com/jakartaee/jakarta.ee/assets/73264129/e89ca1e6-9cb3-4511-a310-b3a0d3e3c6e9)
![icon-3-banner](https://github.com/jakartaee/jakarta.ee/assets/73264129/a08db299-39e3-46d1-8132-ee1a6a4168d4)
![icon-2-banner](https://github.com/jakartaee/jakarta.ee/assets/73264129/c579e8a4-9d6a-4961-9f0e-92cf564f0b9f)
white icons here^

**Comment by shabnammayel** [comment]
@oliviergoulet5 

Can I get the URLs for the links? For "contact us": https://jakarta.ee/membership/join-us/
 and "become a sponsor": https://www.eclipse.org/org/workinggroups/sponsorship/working-group-sponsorship-agreement.pdf
What will the URL be? https://jakarta.ee/supporters/sponsor

Thanks

**Comment by oliviergoulet5** [comment]
Here is a preview of the page: https://deploy-preview-1888--jakartaee.netlify.app/supporters/sponsor/

@shabnammayel @excentrickristy

**Comment by chrisguindon** [comment]
That was quick @oliviergoulet5! Great job!

**Comment by excentrickristy** [comment]
great work!!!

**Comment by shabnammayel** [comment]
This is great! thanks so much @oliviergoulet5 
Can you only add the link to OCX where we mention it?https://www.opencode-x.org/event/778b82cc-6834-48a4-a58e-f883c5a7b8c9/summary 
It's under the Sponsor Perks. 

Thanks

**Comment by oliviergoulet5** [comment]
Updated the preview with a link! @shabnammayel

I'll put the patch into review with the rest of the webdev team

**Comment by shabnammayel** [comment]
Perfect! thanks @oliviergoulet5

**Comment by oliviergoulet5** [comment]
Going live!
