### ISSUE TITLE
Publish Jakarta EE Steering Committee Meeting Minutes - Nov 9, 2023; Mar 12, 2024; Mar 26, 2024

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1903]
This is not a bug

We need to add new entries for Steering meeting minutes in https://jakarta.ee/meeting_minutes/ , under the tab: Jakarta EE Steering Committee, in the same way as other files with just adding a date with the link.

The meeting minutes in question are for the following dates:
November 9, 2023
March 12, 2024
March 26, 2024

I have attached pdf files:
[Minutes of the November 7, 2023 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/15155296/Minutes.of.the.November.7.2023.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the March 12, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/15155297/Minutes.of.the.March.12.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the March 26, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/15155299/Minutes.of.the.March.26.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

Thanks

**Comment by oliviergoulet5** [comment]
Hi Will, here is a preview @will-lyons https://deploy-preview-1905--jakartaee.netlify.app/about/meeting_minutes/#steering_committee

Please let me know if we're good to go live

**Comment by will-lyons** [comment]
Olivier –

Yes, we’re good to go live.

I assume you will also update https://jakarta.ee/committees/steering/.

Thanks

Will

From: Olivier Goulet ***@***.***>
Date: Tuesday, April 30, 2024 at 9:16 AM
To: jakartaee/jakarta.ee ***@***.***>
Cc: Will Lyons ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [jakartaee/jakarta.ee] Publish Jakarta EE Steering Committee Meeting Minutes - Nov 9, 2023; Mar 12, 2024; Mar 26, 2024 (Issue #1903)

Hi Will, here is a preview @will-lyons<https://urldefense.com/v3/__https:/github.com/will-lyons__;!!ACWV5N9M2RV99hQ!KkyKP__Iu_coA43D0JJGXba1YuwH0yML21nCBYHv0Lt8l6qHjc3aR-8-NE97Od-PqCP5Y_kpdVA6pK6vi1yaIla6gw$> https://deploy-preview-1905--jakartaee.netlify.app/about/meeting_minutes/#steering_committee<https://urldefense.com/v3/__https:/deploy-preview-1905--jakartaee.netlify.app/about/meeting_minutes/*steering_committee__;Iw!!ACWV5N9M2RV99hQ!KkyKP__Iu_coA43D0JJGXba1YuwH0yML21nCBYHv0Lt8l6qHjc3aR-8-NE97Od-PqCP5Y_kpdVA6pK6vi1x5UWCCwg$>

Please let me know if we're good to go live

**Comment by oliviergoulet5** [comment]
Yep, that page is getting updated as well! 

The patch is going live. Closing the issue!
