### ISSUE TITLE
Update Community Overview Page

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1914]
At Shabnam's request, we would like to update the [Community Overview page](https://jakarta.ee/community/) and menu so that we can align them a little better.

We would like to re-arrange the community menu to display in this order:
Overview
Resources
Blog
Events
Stay Connected
Videos
JakartaOne Livestream
Tech Talk Meetups
Developer Advocate

Please remove Adopt a Spec from the menu but keep it on the community overview page

For the community overview, we would like to add the following 4 items:

**Resources**
- Branding
- Case Studies
- Datasheets
- eBooks
- Infographics
- Presentations
- Social Cards
- Surveys
- White Papers

**Blog**
- Read community blog posts about Jakarta EE

**Get Involved**
- Read about all the ways you can get involved in Jakarta EE

**Developer Advocate**
- Learn about Ivar Grimstad, our Jakarta EE Developer Advocate

Please arrange the items on the Community overview page in the same order as the menu as well. I have included the 4 extra icons you will need. [Jakarta-Icons.zip](https://github.com/jakartaee/jakarta.ee/files/15254537/Jakarta-Icons.zip)

**Comment by oliviergoulet5** [comment]
Here is a preview @excentrickristy https://deploy-preview-1916--jakartaee.netlify.app/community/

Please let me know if there's anything else.

I moved the items from the community page that didn't have a menu item to the bottom.

**Comment by oliviergoulet5** [comment]
cc @shabnammayel

**Comment by excentrickristy** [comment]
Ahhh I missed Get Involved in my menu list. It was supposed to be after Blog and before Events. Sorry about that.

Can you increase the padding on the boxes from 20px to 30px? 

Also, the description for Developer Advocate should be: Learn about Ivar Grimstad, our Jakarta EE Developer Advocate

Thank you!

**Comment by oliviergoulet5** [comment]
The Get Involved card and menu item have been ordered accordingly.

The description for Developer Advocate has been fixed.

And the padding of the cards have been increased from 20px to 30px across the website. For e.g. the resources page: https://deploy-preview-1916--jakartaee.netlify.app/resources/

@excentrickristy @shabnammayel Please let me know if there's anything else!

**Comment by excentrickristy** [comment]
Looks great @oliviergoulet5. Let's get it launched!

**Comment by oliviergoulet5** [comment]
The updated community overview page is going live!
