### ISSUE TITLE
get response body from the  jakarta.servlet.http HttpServletResponse

### ISSUE THREAD

**Issue by kalungedamaji** [jakartaee/jakarta.ee#1941]
we added interceptor to intercept the request and response and need to get the response body  in string format 
How should I access the response body.

    class RequestResponseInterceptor(private val messageSender: AuditMessageSender) : HandlerInterceptor {

    override fun afterCompletion(request: HttpServletRequest, response: HttpServletResponse, handler: Any, ex: Exception?) {
    
    } 
    
    }

**Comment by oliviergoulet5** [comment]
Hi @kalungedamaji. This is the repository for the Jakarta EE website.

I imagine the Slack workspace is a better place to ask this question. You can find the link to the Slack workspace on the following page: https://jakarta.ee/connect/
