### ISSUE TITLE
Please update Jakarta EE Steering Committee page

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1944]
https://jakarta.ee/committees/steering/
(the only change is  replacing "Arjan Tijms" with "vacant"  in this line Elected Committer Member Representative)

The page should look like this

Will Lyons (chair)- Oracle, Ed Bratt - alternate
Kenji Kazumura - Fujitsu, Yuichi Kusano - alternate
Alasdair Nottingham - IBM, Emily Jiang - alternate
Steve Millidge - Payara, Ilias Efstathiou - alternate
David Blevins - Tomitribe, Cesar Hernandez - alternate
Marcin Kruglik - London Jamocha Community - Elected Participant Member Representative - Abraham Marin-Perez - alternate
vacant - Elected Committer Member Representative
Dr. Jun Qian - Primeton - Elected Enterprise Representative
Reza Rahman - Microsoft - Elected Enterprise Representative, Ed Burns - alternate

FYI @ZahraFazli

**Comment by oliviergoulet5** [comment]
Here is a preview of the change @TanjaObradovic @ZahraFazli https://deploy-preview-1945--jakartaee.netlify.app/committees/steering/

**Comment by TanjaObradovic** [comment]
looks great! thanks!

**Comment by oliviergoulet5** [comment]
NP! This is going live
