### ISSUE TITLE
Application to list Helidon 4, EE 10 Core Profile compatible implementation

### ISSUE THREAD

**Issue by edbratt** [jakartaee/jakarta.ee#1957]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:
The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting

- [Ed Bratt](https://accounts.eclipse.org/users/ebratt)

A product name and version

- Helidon 4

The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under

- Jakarta EE 10, Core Profile

A ZIP file with a product logo with a transparent background in SVG format (optional)

- [Helidon-frank-profile-RGB.zip](https://github.com/user-attachments/files/16351209/Helidon-frank-profile-RGB.zip)

The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product

- Oracle Corporation

The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process

- Compatibility certification request for Helidon 4.0 for Jakarta EE 10 Core Profile [#869](https://github.com/jakartaee/platform/issues/869) 

The URL where Compatible Software Product is available for download

- https://helidon.io

**Comment by TanjaObradovic** [comment]
@oliviergoulet5 please let me know if you need anything else for publishing this ?

**Comment by oliviergoulet5** [comment]
Sorry for the delay @TanjaObradovic @edbratt 

Here is a preview of the change:

- https://deploy-preview-1965--jakartaee.netlify.app/compatibility/
- https://deploy-preview-1965--jakartaee.netlify.app/compatibility/certification/10/
- https://deploy-preview-1965--jakartaee.netlify.app/compatibility/download/

**Comment by TanjaObradovic** [comment]
+1
thanks!

**Comment by edbratt** [comment]
LGTM. Thank you!
