### ISSUE TITLE
Please include WildFly 33.0.0.Final as Jakarta EE 10 Platform, Web Profile, Core Profile compatible on Java 21, 17, 11

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#1958]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://www.eclipse.org/membership/showMember.php?member_id=731

**A product name and version**

[WildFly 33.0.0.Final](https://github.com/wildfly/wildfly/releases/download/33.0.0.Final/wildfly-33.0.0.Final.zip)

**The Profile (Full Platform, Web Profile, Core Profile) that the Compatible Product is submitted to be listed under**

All three, `Full Platform`, `Web Profile`, `Core Profile`

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

https://github.com/wildfly/certifications/blob/EE8/images/wildfly-logo-stacked-100px-2132977.zip?raw=true

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Red Hat

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

https://github.com/jakartaee/platform/issues/924 (Java 21) is for WildFly 33.0.0.Final `Full Platform` compatibility (also passes testing on Java 17/11 as well so please note `WildFly  33.0.0.Final  Java 21, 17, 11`).

https://github.com/jakartaee/platform/issues/925 (Java 21) is for WildFly 33.0.0.Final `Web Profile` compatibility (also passes testing on Java 17/11 as well so please note `WildFly  33.0.0.Final  Java 21, 17, 11`).

https://github.com/jakartaee/platform/issues/923  (Java 21) is for WildFly 33.0.0.Final `Core Profile` compatibility (also passes testing on Java 17/11 as well so please note `WildFly  33.0.0.Final  Java 21, 17, 11`).

**The URL where Compatible Software Product is available for download**

[https://github.com/wildfly/wildfly/releases/download/33.0.0.Final/wildfly-33.0.0.Final.zip)

Please note that `WildFly Preview` is a separate product than `WildFly` and for that reason, this is for the `WildFly` product.

**Comment by oliviergoulet5** [comment]
Here is a preview of WildFly 33 being added as a compatible product @scottmarlow @TanjaObradovic 

- https://deploy-preview-1959--jakartaee.netlify.app/compatibility/certification/10/
- https://deploy-preview-1959--jakartaee.netlify.app/compatibility/download/

**Comment by scottmarlow** [comment]
If you can, please replace WildFly `Java SE` with just `Java` to be more consistent with other entries.  

> Here is a preview of WildFly 33 being added as a compatible product @scottmarlow @TanjaObradovic
> 
>     * https://deploy-preview-1959--jakartaee.netlify.app/compatibility/certification/10/

For Java SE 17, please update the `33.0.0.Final, Java SE 17` link to reference https://github.com/wildfly/certifications/blob/EE10/WildFly_33.0.0.Final/jakarta-full-platform-jdk17.adoc

For Java SE 11, please update the `33.0.0.Final, Java SE 17` link to reference https://github.com/wildfly/certifications/blob/EE10/WildFly_33.0.0.Final/jakarta-full-platform-jdk11.adoc

Also  as mentioned above, please remove the `SE` text.
> 
>     * https://deploy-preview-1959--jakartaee.netlify.app/compatibility/download/

As mentioned above, please change `Java SE` to `Java`.

Thank you very much!

**Comment by scottmarlow** [comment]
Also for reference, I consider including https://github.com/wildfly/certifications/blob/EE10/WildFly_33.0.0.Final/jakarta-full-platform-jdk11.adoc as part of an Jakarta EE implementation self validating that they are still Jakarta EE 10 compatible on that version of Java as previously reported.

The same for https://github.com/wildfly/certifications/blob/EE10/WildFly_33.0.0.Final/jakarta-full-platform-jdk17.adoc

**Comment by oliviergoulet5** [comment]
Hi @scottmarlow, I have dropped all the `SE`'s from the preview above. The links have also been corrected.

**Comment by scottmarlow** [comment]
> Hi @scottmarlow, I have dropped all the `SE`'s from the preview above. The links have also been corrected.

@oliviergoulet5 , the updated preview looks great!  Thank you!

**Comment by ivargrimstad** [comment]
The CCRs are approved, so this should be good to go

**Comment by scottmarlow** [comment]
Thank you very much @ZacharySabourin + @ivargrimstad!
