### ISSUE TITLE
Publish Marketing Committee meeting mins

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1966]
Please publish the following MKT Meeting mins here: https://deploy-preview-1949--jakartaee.netlify.app/about/meeting_minutes/

[Jakarta EE Marketing Committee Meeting - 13 June, 2024 (11_00 ET).pdf](https://github.com/user-attachments/files/16552019/Jakarta.EE.Marketing.Committee.Meeting.-.13.June.2024.11_00.ET.pdf)
[Jakarta EE Marketing Committee Meeting - 25 July, 2024 (11_00 ET).pdf](https://github.com/user-attachments/files/16552020/Jakarta.EE.Marketing.Committee.Meeting.-.25.July.2024.11_00.ET.pdf)
[Jakarta EE Marketing Committee Meeting - 11 July, 2024 (11_00 ET).pdf](https://github.com/user-attachments/files/16552021/Jakarta.EE.Marketing.Committee.Meeting.-.11.July.2024.11_00.ET.pdf)
[Jakarta EE Marketing Committee Meeting - 27 June, 2024 (11_00 ET).pdf](https://github.com/user-attachments/files/16552022/Jakarta.EE.Marketing.Committee.Meeting.-.27.June.2024.11_00.ET.pdf)

**Comment by oliviergoulet5** [comment]
Hi @shabnammayel 

Here is a preview: https://deploy-preview-1967--jakartaee.netlify.app/about/meeting_minutes/

**Comment by oliviergoulet5** [comment]
Hi @shabnammayel, have you had the chance to look at the preview?

**Comment by shabnammayel** [comment]
LGTM! thanks
