### ISSUE TITLE
Publish Jakarta EE Steering Committee Minutes: Apr 9, Apr 23. May 7, May 21, June 4, June 18, July 2, 2024

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#1968]
This is not a bug

We need to add new entries for Steering meeting minutes in https://jakarta.ee/meeting_minutes/ , under the tab: Jakarta EE Steering Committee, in the same way as other files with just adding a date with the link.

The meeting minutes in question are for the following dates:
April 9, 2024
April 16, 2024
May 7, 2024
May 21, 2024
June 4, 2024
June 18, 2024
July 2, 2024

I have attached PDF files
[Minutes of the April 9, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/user-attachments/files/16591187/Minutes.of.the.April.9.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the April 23, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/user-attachments/files/16591189/Minutes.of.the.April.23.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the May 7, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/user-attachments/files/16591191/Minutes.of.the.May.7.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the May 21, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/user-attachments/files/16591193/Minutes.of.the.May.21.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the June 4, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/user-attachments/files/16591194/Minutes.of.the.June.4.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the June 18, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/user-attachments/files/16591196/Minutes.of.the.June.18.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the July 2, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/user-attachments/files/16591198/Minutes.of.the.July.2.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

Thanks

**Comment by oliviergoulet5** [comment]
Hi @will-lyons, here is a preview of the change:

- https://deploy-preview-1974--jakartaee.netlify.app/about/meeting_minutes/#steering_committee
- https://deploy-preview-1974--jakartaee.netlify.app/committees/steering/

**Comment by will-lyons** [comment]
Olivier, the changes look good.  Please publish.

**Comment by will-lyons** [comment]
And thank you.
