### ISSUE TITLE
Java Server Faces doesn't recognize my comment but somehow tries to compile it.

### ISSUE THREAD

**Issue by nobee49** [jakartaee/jakarta.ee#1969]
**Describe the bug**
I run normal Java Server Faces Code, that works on Tomcat 10.1.4 with Maven but suddenly when I add a comment, that has code inside, Jakarta somehow tries to compile this code (but it's a outcommented code!!!)

See this public Repo (branch):
https://github.com/nobee49/javaee-studium/tree/jakarta-ee-error

**To Reproduce**
1. Build the code with maven -> you will see it fail, because of the "remove" Method, that is commented out:
<img width="940" alt="Screenshot 2024-08-13 at 10 47 02" src="https://github.com/user-attachments/assets/f7cc249d-65bb-48df-bfc8-c24bbb8f753c">
2. Remove the comment and rebuild -> everything works perfectly fine...

**Expected behavior**
Comment is comment and doesn't affect the result (build)

**Desktop:**
 - MacOS
Vivaldi | 6.8.3381.53 (Stable channel) (x86_64)
-- | --
Revision | c703aba8689f98dfc36a017440f3a6765f5e6141
OS | macOS Version 13.3.1 (a) (Build 22E772610a)
JavaScript | V8 12.6.228.30
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Command Line | /Applications/Vivaldi.app/Contents/MacOS/Vivaldi --flag-switches-begin --flag-switches-end --restore-last-session --disable-smooth-scrolling --save-page-as-mhtml
Executable Path | /Applications/Vivaldi.app/Contents/MacOS/Vivaldi
Profile Path | /Users/mari/Library/Application Support/Vivaldi/Profile 1
Linker | lld
Variations Seed Type | Null

- java version "21.0.4" 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 21.0.4+8-LTS-274)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.4+8-LTS-274, mixed mode, sharing)

**Comment by arjantijms** [comment]
Thanks for posting this issues, but this issue is better posted on the Mojarra Github, which specifically deals with the implementation of Faces you are using. See https://github.com/eclipse-ee4j/mojarra

You can also ask this on Stackoverflow perhaps, or look at an existing question such as https://stackoverflow.com/a/17321066/472792

**Comment by dmatej** [comment]
1. This is wrong repository to create such issue - if you know it is [Faces](https://github.com/jakartaee/faces) (the API specification) or [MyFaces](https://github.com/apache/myfaces) or [Mojarra](https://github.com/eclipse-ee4j/mojarra), you can save some time to other devs when you create an issue in the right place. But it seems to me this is a mistake in your code, so they would probably close it (however they would still try to help you, you know we are all nice to each other).
2. `<!-- Aufgabe 8 ` is a HTML comment and it is OK that it was processed, however you can disable the processing too. [Here](https://mkyong.com/jsf2/how-to-use-comments-in-jsf-2-0/) is a blog about comments in Faces.
3. https://github.com/nobee49/javaee-studium/blob/jakarta-ee-error/Artikelverwaltung/pom.xml - you combine incompatible dependencies, some are from Jakarta EE 9, some Jakarta EE 10. You can check major versions [here](https://jakarta.ee/specifications/). Also consider which dependencies are already served by Tomcat, you should have tam as `<provided>` in your project so they would not overlap with Tomcat. Seems Mojarra even have some [howto](https://github.com/eclipse-ee4j/mojarra?tab=readme-ov-file#non-maven) for combination of Tomcat with Mojarra.

**Comment by OndroMih** [comment]
According to the [Jakarta Faces specification](https://jakarta.ee/specifications/faces/4.1/jakarta-faces-4.1), ignoring XML  comments can be enabled with the `jakarta.faces.FACELETS_SKIP_COMMENTS`. As described in the [blog](https://mkyong.com/jsf2/how-to-use-comments-in-jsf-2-0/) linked in the previous comment. However the blog shows using a shorter `facelets.SKIP_COMMENTS` parameter, which is not standard and may not work everywhere.
