### ISSUE TITLE
Please add InforSuite Application Server V10.0.10 as Compatible product of Jakarta EE 10 Full Platform

### ISSUE THREAD

**Issue by wminfors** [jakartaee/jakarta.ee#1990]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=1487
**A product name and version**
InforSuite Application Server V10.0.10

The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under Full Platform.

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/codff/InforSuite/archive/main.zip
**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Shandong Cvicse Middleware Co.,Ltd.
**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Full Platform:https://github.com/jakartaee/platform/issues/941
**The URL where Compatible Software Product is available for download**
http://www.inforbus.com/as.html

**Comment by TanjaObradovic** [comment]
@oliviergoulet5 please let me know if you need anything else for this one. Thanks!

**Comment by oliviergoulet5** [comment]
Apologies for the delay! @wminfors @TanjaObradovic 

Here is a preview: https://deploy-preview-1994--jakartaee.netlify.app/compatibility/

Please review whether or not the links are correct

**Comment by wminfors** [comment]
I apologize for the delay in my response.  @oliviergoulet5 @TanjaObradovic 
The link you provided is correct.  If our certification materials are complete, will our information subsequently appear at the link https://deploy-preview-1845--jakartaee.netlify.app/compatibility/certification/10/?

**Comment by oliviergoulet5** [comment]
@wminfors The preview link should have included InforSuite, but I'm noticing it isn't there. 

I believe there was an issue when building the preview. I'll look into this!

**Comment by oliviergoulet5** [comment]
It should now appear @wminfors

**Comment by TanjaObradovic** [comment]
@oliviergoulet5 based on the https://github.com/jakartaee/platform/issues/941 it looks good for the Jakarta EE 10 Platform!

I do not see a separate issue for the Jakarta EE 10 WebProfile. @wminfors  we would need a separate issue  https://github.com/jakartaee/platform/issues/ for WebProfile. Thanks!

**Comment by wminfors** [comment]
@TanjaObradovic , thank you for your attention and feedback regarding Jakarta EE 10 WebProfile.  We are currently in an active testing phase.  Once we have completed the testing and organized our results, we will create a separate issue for the WebProfile as you have suggested.  
Thank you for your understanding and support!
