### ISSUE TITLE
JEUS 9 as a Compatible Software Product for Jakarta EE 9.0

### ISSUE THREAD

**Issue by TmaxEE** [jakartaee/jakarta.ee#2001]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[https://www.eclipse.org/membership/show-member/?member_id=1391](https://www.eclipse.org/membership/show-member/?member_id=1391)

**A product name and version**
JEUS 9

**Where to list the Compatible Product (Platform, Web Profile, Core Profile)**
Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[bi_jeus.zip](https://github.com/user-attachments/files/17127801/bi_jeus.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
TmaxSoft Co., Ltd

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
[https://www.tmaxsoft.com/jakee/JEUS9_JakartaEE9_Certification_Summary.html](https://www.tmaxsoft.com/jakee/JEUS9_JakartaEE9_Certification_Summary.html)

**The URL where Compatible Software Product is available for download**
[http://www.tmaxsoft.com/jakee/install/jeus9/jeus9-b15.zip](http://www.tmaxsoft.com/jakee/install/jeus9/jeus9-b15.zip)

**Comment by oliviergoulet5** [comment]
Thanks for opening the issue @TmaxEE! I will wait for your certification request to be accepted before listing it to the site: https://github.com/jakartaee/platform/issues/958

**Comment by TmaxEE** [comment]
https://github.com/jakartaee/platform/issues/958 has been accepted. Please let us know if any further work is need before listing JEUS 9 as a compatible software product.

**Comment by oliviergoulet5** [comment]
Hi @TmaxEE 

Here is a preview of how it will look on the website:

- Certification: https://deploy-preview-2005--jakartaee.netlify.app/compatibility/certification/9/
- Download: https://deploy-preview-2005--jakartaee.netlify.app/compatibility/download/

Please let me know if any changes need to be made!

**Comment by TmaxEE** [comment]
> Hi @TmaxEE
> 
> Here is a preview of how it will look on the website:
> 
> * Certification: https://deploy-preview-2005--jakartaee.netlify.app/compatibility/certification/9/
> * Download: https://deploy-preview-2005--jakartaee.netlify.app/compatibility/download/
> 
> Please let me know if any changes need to be made!

Confirmed. No problem.
Thanks.
