### ISSUE TITLE
Publish Jakarta EE Steering Committee Minutes: July 16, July 30, Aug 13, Aug 27

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#2004]
This is not a bug

We need to add new entries for Steering meeting minutes in https://jakarta.ee/meeting_minutes/ , under the tab: Jakarta EE Steering Committee, in the same way as other files with just adding a date with the link.

The meeting minutes in question are for the following dates:
- July 16, 2024
- July 30, 2024
- Aug 13, 2024
- Aug 27. 2024

I have attached PDF files below:
[Minutes of the July 16, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/user-attachments/files/17282864/Minutes.of.the.July.16.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the July 30, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/user-attachments/files/17282865/Minutes.of.the.July.30.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the August 13, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/user-attachments/files/17282867/Minutes.of.the.August.13.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the August 27, 2024 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/user-attachments/files/17282870/Minutes.of.the.August.27.2024.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

Thank you

**Comment by oliviergoulet5** [comment]
Hi @will-lyons, here is a preview of the change: https://deploy-preview-2012--jakartaee.netlify.app/about/meeting_minutes

**Comment by oliviergoulet5** [comment]
I submitted the change since it was pretty straight forward! Please re-open if there's any issue.

**Comment by will-lyons** [comment]
Thanks Olivier. Looks good.  

Will
