### ISSUE TITLE
Update to Jakarta EE Specification Committee page

### ISSUE THREAD

**Issue by paulbuck** [jakartaee/jakarta.ee#2023]
Update request to Jakarta EE Specification Committee page https://jakarta.ee/committees/specification/

Please delete "Paul Buck - Eclipse Foundation (serves as its non-voting chair)"

And change:

"Andrew Pielage - Payara, Petr Aubrecht - alternate"

To:

"Andrew Pielage (**chair**) - Payara, Petr Aubrecht - alternate" 

The word "chair" needs to be in bold.

Thanks ... Paul

**Comment by oliviergoulet5** [comment]
Hi @paulbuck, here is a preview of the changes:

https://deploy-preview-2028--jakartaee.netlify.app/committees/specification/

Note that the meeting minutes you reviewed earlier are not synced with this patch. When it goes live on prod, it will have the up-to-date minutes.

**Comment by paulbuck** [comment]
Looks great! Thanks for making these updates :-)

**Comment by oliviergoulet5** [comment]
My pleasure! This is going live
