### ISSUE TITLE
Can you please update the page Steering Cmte page

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#2032]
Please change the alternate for Payara 

It should be 
**Steve Millidge - Payara, Steve Butler - alternate**

not 
Steve Millidge - Payara, Ilias Efstathiou - alternate

**Comment by oliviergoulet5** [comment]
Here is a preview @TanjaObradovic https://deploy-preview-2033--jakartaee.netlify.app/committees/steering/

**Comment by TanjaObradovic** [comment]
Looking good! Many thx!!
