### ISSUE TITLE
Compatible Software Product Request for TongWeb Application Server 7 For Full Platform 10

### ISSUE THREAD

**Issue by tongtech-web** [jakartaee/jakarta.ee#2036]
**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/show-member/?member_id=1458

**A product name and version**
TongWeb Application Server 7

**Where to list the Compatible Product (Platform, Web Profile, Core Profile)**
Full Platform 10

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
logo(jpg): http://www.tongtech.com/tongweb/images/tongweb-logo.jpg
logo(svg): http://www.tongtech.com/tongweb/images/tongweb-logo.svg

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Beijing TongTech Co., Ltd.

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/jakartaee/platform/issues/979

**The URL where Compatible Software Product is available for download**
https://www.tongtech.com/service.html

**Comment by TanjaObradovic** [comment]
Please process this issue - it is good to go! Many thanks!!

**Comment by oliviergoulet5** [comment]
Here is a preview of this change @TanjaObradovic @tongtech-web : https://deploy-preview-2039--jakartaee.netlify.app/compatibility/

**Comment by tongtech-web** [comment]
> Here is a preview of this change @TanjaObradovic @tongtech-web : https://deploy-preview-2039--jakartaee.netlify.app/compatibility/

LGTM, Thanks!
