### ISSUE TITLE
Change Nav on Jakarta.ee

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#2043]
After taking community feedback into consideration, @shabnammayel and the marketing committee have approved a change in the main menu navigation.

Can we please move “Learn” to the first place main menu position, and move “About” to 4th place - before community and after compatible products.

**Comment by oliviergoulet5** [comment]
Hi @excentrickristy, I made the change in this preview: https://deploy-preview-2045--jakartaee.netlify.app/

**Comment by excentrickristy** [comment]
Perfect, thanks!
