### ISSUE TITLE
Compatible Software Product Request for AliEE 1.0.0 for Web Profile 8

### ISSUE THREAD

**Issue by AliyunAliEE** [jakartaee/jakarta.ee#2051]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Alibaba Cloud](https://www.eclipse.org/membership/show-member/?member_id=1428)

**A product name and version**
Aliee 1.0.0

**Where to list the Compatible Product (Platform, Web Profile, Core Profile)**
Web Profile 8

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
logo(jpg): [aliee.png](https://edas-hz.oss-cn-hangzhou.aliyuncs.com/demo/test/aliee/images/aliee.png)
logo(svg): [aliee.svg](https://edas-hz.oss-cn-hangzhou.aliyuncs.com/demo/test/aliee/images/aliee.svg)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[Alibaba Cloud Computing](https://help.aliyun.com/zh/edas/product-overview/what-is-alibaba-cloud-application-server?spm=a2c4g.11186623.0.0.72385806mPZpST)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
[jakartaee/platform#974](https://github.com/jakartaee/platform/issues/974)

**The URL where Compatible Software Product is available for download**
[Aliee 1.0.0](https://help.aliyun.com/zh/edas/product-overview/what-is-alibaba-cloud-application-server?spm=a2c4g.11186623.0.0.72385806mPZpST)

**Comment by oliviergoulet5** [comment]
Hi @AliyunAliEE and @TanjaObradovic. Here is a preview of the change:

- https://deploy-preview-2052--jakartaee.netlify.app/compatibility/
- https://deploy-preview-2052--jakartaee.netlify.app/compatibility/certification/8/
- https://deploy-preview-2052--jakartaee.netlify.app/compatibility/download/

Please let me know if it looks good! We can go live afterwards.

**Comment by TanjaObradovic** [comment]
looks great!

**Comment by TanjaObradovic** [comment]
@oliviergoulet5 we are good to go with this, right?

**Comment by oliviergoulet5** [comment]
Yep, it is going live now @TanjaObradovic. I was waiting for approval for the code review here https://github.com/jakartaee/jakarta.ee/pull/2052

**Comment by TanjaObradovic** [comment]
@AliyunAliEE it is on the website! thanks @oliviergoulet5 !!
