### ISSUE TITLE
Change the "Supporters" in the navigation bar to "Join"

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#2063]
Can you please change "supporters" in the navigation bar to "Join" and change the drop down from 
<img width="150" alt="Screen Shot 2024-12-12 at 1 59 29 PM" src="https://github.com/user-attachments/assets/694723b5-7e20-40a3-8702-f6ec7b37c0e8" />
to: 
Become a member
Members
Become a Sponsor

We have received feedback that supporters is a bit confusing. thanks

**Comment by Musashi-Mahito** [comment]
could you please assign me this task

**Comment by oliviergoulet5** [comment]
@Musashi-Mahito Certainly! 

The menus are managed via the [menu.toml](https://github.com/jakartaee/jakarta.ee/blob/src/config/_default/menu.toml) file.

**Comment by oliviergoulet5** [comment]
The website is deploying with the new changes. Thanks @Musashi-Mahito!
