### ISSUE TITLE
Remove output files from source code

### ISSUE THREAD

**Issue by oliviergoulet5** [jakartaee/jakarta.ee#2067]
The output files which get placed into the static directory are being tracked by Git. We should not be committing any output files.

The following directories should be added to .gitignore:

- `static/css/`
- `static/js/`

**Comment by InocencioC** [comment]
Could you assign this issue to me ?

**Comment by oliviergoulet5** [comment]
I did more investigation and the directories are in fact in the .gitignore. I thought I saw these types of files being committed in a past pull request. My mistake.

There is nothing to do here. Closing!
