### ISSUE TITLE
Improve the process of adding news on the website

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#218]
Adding news on the website is harder than it should.

For example, we need to create a markdown file within a folder under news/community-news/ or news/announcements:

https://github.com/jakartaee/jakartaee.github.io/blob/src/content/news/community-news/2018-07-27-understanding-jakarta-ee-series-eisele/index.md

I think we could reduce this burden by creating a data file for  community-news and announcements.

https://gohugo.io/templates/data-templates/

**Comment by ericpoirier** [comment]
I'm starting to look into this issue and one thing I'm realizing is that the data files works well for news items that are hosted on another website. But for news items that are internal to the Jakarta EE website, we still need to create a page.

There is currently around 60 news items (announcements and community news) and there is only 4 of them that needs a page on the site. We could simply create a page in the content section for the news items that require one.

**Comment by chrisguindon** [comment]
As we discussed, I expect to create a markdown file if the link goes to an internal page.

This process would be similar to what we do on www.eclipse.org. We currently need to create a page for hosting a Press Release and once that's done we create an entry in the news RSS feed.

**Comment by TanjaObradovic** [comment]
@chrisguindon can we close this one? is this done?

**Comment by chrisguindon** [comment]
+1 We've decided to address this problem with a new separate content management system which will allow us to share news items across all our web properties!
