### ISSUE TITLE
Update the picture in our header

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#219]
The background image in our header is blurry and pixelated. I wonder if we could find or create something better.

@stephanieswart what do you think?

**Comment by chrisguindon** [comment]
Laura, from the EclipseFdn Marketing, team created 3 mockups for the new header:

![6](https://user-images.githubusercontent.com/893942/54558701-c58f4880-4994-11e9-9d67-66464720d89a.png)
![7](https://user-images.githubusercontent.com/893942/54558702-c58f4880-4994-11e9-9c62-aa1bb0aad0c2.png)
![8](https://user-images.githubusercontent.com/893942/54558704-c627df00-4994-11e9-9aee-3b76ff59f581.png)

We should try them to see if these new images look better on the website!

**Comment by ericpoirier** [comment]
![Screen Shot 2019-03-20 at 10 56 07 AM](https://user-images.githubusercontent.com/623165/54694593-d360dd00-4afe-11e9-89b9-d0a37274d60f.png)
![Screen Shot 2019-03-20 at 10 53 50 AM](https://user-images.githubusercontent.com/623165/54694606-d6f46400-4afe-11e9-941c-262210c3f2fd.png)

Here are screenshots of one of the backgrounds you submitted above.

In my second screenshot, I tried using the same image but darker. Let me know what you guys think. We could also go with a lighter background image but we would have to change the text colour and we could use the coloured logo as well.

**Comment by stephanieswart** [comment]
I think the waves and dark background make it look ominous and don't really connect to the idea of community, code and cloud native java. Could we try this one I've attached?

![11](https://user-images.githubusercontent.com/34580334/54699235-08712d80-4b07-11e9-995f-371d7be3326c.png)

**Comment by chrisguindon** [comment]
Is it possible that use a blue that is closer to what we use in the logo? #1d2496

**Comment by stephanieswart** [comment]
That is the correct blue, it's just because it's more opaque, we can make it darker

**Comment by stephanieswart** [comment]
Try this!

![jakartaEE](https://user-images.githubusercontent.com/34580334/54712064-be497580-4b21-11e9-81e5-bf409c1fd7df.png)

**Comment by ericpoirier** [comment]
Here is a screenshot using the latest image:

![Screen Shot 2019-03-27 at 10 32 03 AM](https://user-images.githubusercontent.com/623165/55084496-b175d600-507b-11e9-90a5-0f6250dececa.png)

I'm re-reading the first comment for this issue and the reason why the picture appears blurry/pixelated, is to put the focus on the text/content of the header rather than on the picture in the background. We do the same thing on eclipse.org.

**Comment by stephanieswart** [comment]
I think that image looks great! I will confirm with Thabang on Monday with changing it. Will keep you posted. Thanks!

**Comment by ltran016** [comment]
Here are two more mock-ups for the Jakarta EE Jumbotron. Steph and I like the first one! 
![13](https://user-images.githubusercontent.com/48952273/55483064-d6c29100-55f3-11e9-8091-7c8836afb0c0.png)
![14](https://user-images.githubusercontent.com/48952273/55483065-d6c29100-55f3-11e9-8c64-c06fd6785456.png)

**Comment by autumnfound** [comment]
I've updated the image on the site locally, and this is how the first image looks. Is that alright with you folks?
![image](https://user-images.githubusercontent.com/23018241/60517711-232e7300-9cae-11e9-81bf-86f5ea1e6304.png)

**Comment by chrisguindon** [comment]
Is it just me or the text is harder to read now?

There might be a bit too much details in this new image. 

@stephanieswart what do you think?

**Comment by ltran016** [comment]
Hi guys, I made this photo darker with less contrast so the white should pop out more than in the previous. Let me know if this works better.

![jakartaEE](https://user-images.githubusercontent.com/48952273/60604860-7a077b80-9d86-11e9-9d1c-604a70ed8c61.png)

**Comment by autumnfound** [comment]
Looks a bit muddled now (more noticeable when at full size on the image I sent), but the text is fully legible.
![image](https://user-images.githubusercontent.com/23018241/60724327-16a35800-9f04-11e9-96be-a82695395e9e.png)

**Comment by autumnfound** [comment]
@stephanieswart @ltran016 commenting for visibility in case it got lost in the shuffle last week

**Comment by stephanieswart** [comment]
@autumnfound do you need a higher resolution for the image?

**Comment by autumnfound** [comment]
That would help make it less blurry yeah

**Comment by stephanieswart** [comment]
Lol, yes that is what high res means 😄 

Here you go!

![jakartaEE (1)](https://user-images.githubusercontent.com/34580334/61398930-02177600-a89b-11e9-80c9-c53a29a8f3b4.png)

**Comment by autumnfound** [comment]
![image](https://user-images.githubusercontent.com/23018241/61458894-920bfd00-a939-11e9-8a5c-83be20401eec.png)
There we go. Doesn't make me feel like I need glasses while wearing my glasses! The change is in another repo, and I'll link it here

**Comment by stephanieswart** [comment]
+1, this looks good! Feel free to push the update!

**Comment by autumnfound** [comment]
This is live
