### ISSUE TITLE
Jakarta EE Compatible Product page

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#255]
**Is your feature request related to a problem? Please describe.**
Can we please create 
 jakarta.ee/compatibility
a page where we would list all products that are Jakarta EE certified? 

**Describe the solution you'd like**
Once we have the page we want to list all Compatible Implementations of Jakarta EE.
For Compatible Software Products to be listed on the Jakarta EE official list of Software Products must provide, as a minimum:
- A product name and version,
- A product logo (optional)
- The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product,
- The URL to the published public TCK test results demonstrating compatibility as defined in the TCK Process,
- The URL where Compatible Software Product is available for download

A request to list a product can be made by creating a GitHub issue that will request the above information.

**Comment by ericpoirier** [comment]
Hi Tanja,

Do you have some content that we can add to this page. The reason I'm asking, is so we don't create an empty page on the website.

Thanks.

**Comment by TanjaObradovic** [comment]
Can we just put some text, description on what this page is going to contain?
Something like: "This page is to list Jakarta EE downloadable compatible implementations once Jakarta EE 8 release becomes available". If you think we need more then this, let's involve Thabang and Stephanie.

Thanks!

**Comment by TanjaObradovic** [comment]
Hi Eric,
can we put something like this on the page:

This page is to list downloadable Compatible Implementations of Jakarta EE. For a Compatible Implementation to be listed on the Jakarta EE official list please follow this two-step process:
1. Send an email to tck@eclipse.org with a pointer to the GitHub issue described in the next step
2. Open a Git Hub issue
For Compatible Software Products to be listed on the Jakarta EE official list of Software Products must provide, as a minimum:
A product name and version,
A product logo (optional)
The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product,
The URL to the published public TCK test results demonstrating compatibility as defined in the TCK Process,
The URL where Compatible Software Product is available for download

Thanks,
Tanja

**Comment by ericpoirier** [comment]
Hi Tanja,

Would you like this new page to have a link in the main menu or only in the sidebar of subpages?

Thanks

**Comment by TanjaObradovic** [comment]
We could have an item next to "blog" column up top  (About, Membership, Connect, Resources, Blog) that will lead to the page on its own. I will ping Stephanie to review and let us know if she disagrees.

Thanks!

**Comment by ericpoirier** [comment]
Ok sounds good, I'll will wait for what Stephanie has to say. 

Thanks.

**Comment by ericpoirier** [comment]
Hi Tanja,

Can I suggest that we switch the order the steps that the user needs to do to submit a compatible implementation. It might be less confusing for users to ask them to open a Github issue first and then ask them to send an email with a link of that Github issue.

**Comment by TanjaObradovic** [comment]
yes. 
we may get a push back as email should be the primary communication per legal papers, but I agree it'll be less confusing if we do it the other way around.

**Comment by stephanieswart** [comment]
+1, this idea sounds good to me! Let me know if we need a mock-up of this page for further development

**Comment by ericpoirier** [comment]
Hi Stephanie,

Here is a screenshot of what I made so far. Let me know what you think and if you have any suggestions.

I tried putting the blocks in the center but it looks a bit off since everything else is left aligned.

![Screen Shot 2019-04-23 at 8 47 00 AM](https://user-images.githubusercontent.com/623165/56582064-65e41880-65a4-11e9-9157-869b0c331035.png)

**Comment by stephanieswart** [comment]
+1, this looks good thus far! I like it left aligned

**Comment by ericpoirier** [comment]
Yeah me too, thanks for the feedback. I'll submit a pull request with this layout.

**Comment by TanjaObradovic** [comment]
thanks to both! looks great to me as well!!

**Comment by ericpoirier** [comment]
Hi Tanja,

The Compatibility page is now on production.
