### ISSUE TITLE
Add upcoming events to events section

### ISSUE THREAD

**Issue by ltran016** [jakartaee/jakarta.ee#263]
Devoxx United Kingdom 
London, United Kingdom
May 8-10, 2019
https://www.devoxx.co.uk/

GeeCon Krakow
Krakow, Poland
May 15-17 2019
https://2019.geecon.org/

J on the Beach
Malaga, Spain
May 15-17 2019
https://jonthebeach.com/

Oracle Code New York
New York, USA
May 21 2019
https://developer.oracle.com/code/newyork-may-2019

Glue Conference
Broomfield, CO
May 22-23 2019
http://gluecon.com/

JBCNConf
Barcelona, Spain
May 27-29 2019
https://www.jbcnconf.com/2019/

JNation 2019
Coimbra, Portugal
June 4 2019
https://jnation.pt/

Dev Talks Bucharest
Bucharest, Romania
June 6-7 2019
https://www.devtalks.ro/bucharest/

The Lead Developer London
London, United Kingdom
June 11-12 2019
https://london2019.theleaddeveloper.com

GOTO Amsterdam
June 11-14 2019
Amsterdam, Netherlands
https://gotoams.nl/

**Comment by ericpoirier** [comment]
Hi Laura,

These events have been added to the production website. They should appear in a few minutes.
