### ISSUE TITLE
Add new links to Community News

### ISSUE THREAD

**Issue by ltran016** [jakartaee/jakarta.ee#264]
1. https://dzone.com/articles/using-jakarta-eemicroprofile-to-connect-to-apache
2. https://www.theserverside.com/news/252461945/Red-Hat-replaces-Oracle-as-OpenJDK-8-OpenJDK-11-steward
3. https://dzone.com/articles/configuring-microservices-with-microprofile-and-ku
4. http://adambien.blog/roller/abien/entry/microprofile_and_jakarta_ee_the
5. https://www.kodnito.com/posts/microprofile-jwt-with-keycloak

**Comment by ericpoirier** [comment]
Hi Laura,

The new community news items have been added to the production website. They should appear in a few minutes.
