### ISSUE TITLE
Please add news items

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#269]
Announcements
https://blogs.eclipse.org/post/mike-milinkovich/update-jakarta-ee-rights-java-trademarks
https://blogs.eclipse.org/post/tanja-obradovic/jakarta-ee-community-engagement

Community News
https://developer.ibm.com/announcements/jakarta-ee-has-landed/
https://dzone.com/articles/microprofile-what-you-need-to-know
https://blog.payara.fish/jakarta-ee-8-and-beyond

**Comment by ericpoirier** [comment]
Hi Stephanie,

Those news items have been added to the production website. They should appear in a few minutes.
