### ISSUE TITLE
Please post Dev survey results Afternoon of May 8

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#272]
Opening bug for Jakarta EE Developer Survey Results 
Post on this page: https://jakarta.ee/resources/#surveys
Please make sure the URL is the following:
https://jakarta.ee/documents/insights/2019-jakarta-ee-developer-survey.pdf

I will upload the PDF to this bug after final feedback (Tuesday, May 7)

**Comment by stephanieswart** [comment]
[2019-jakarta-ee-developer-survey.pdf](https://github.com/jakartaee/jakarta.ee/files/3154639/2019-jakarta-ee-developer-survey.pdf)

**Comment by chrisguindon** [comment]
This is now live!
