### ISSUE TITLE
Please update 2nd community news item's title 

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#274]
The second title on Community news should read "MicroProfile: What You Need to Know"

![image (1)](https://user-images.githubusercontent.com/34580334/57325189-7e415080-70d7-11e9-9212-4d739a7c5085.png)

**Comment by ericpoirier** [comment]
Hi Stephanie,

I just merged a patch to change the title of this community news. We should see the change in a few minutes.
