### ISSUE TITLE
Please add 3 new announcements

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#280]

**Comment by stephanieswart** [comment]
https://youtu.be/bCK3kRiYz-o

https://www.globenewswire.com/news-release/2019/05/09/1820952/0/en/New-Eclipse-Foundation-Community-Survey-of-Java-Developers-Shows-Cloud-Native-Adoption-Accelerating-Dramatically-with-Jakarta-EE.html

**Comment by ericpoirier** [comment]
Hi Stephanie,

I added those announcements to the production website.
