### ISSUE TITLE
Please add featured banner to promote the Jakarta EE Dev survey results

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#283]
See mockup attached
![1](https://user-images.githubusercontent.com/34580334/57659665-17c5a200-75b1-11e9-8916-6f58d1d6d60f.png)
![2](https://user-images.githubusercontent.com/34580334/57659666-17c5a200-75b1-11e9-94df-457d37b0c14d.png)

Text: The 2019 Jakarta EE Developer Survey results are out!
Button: See the report!
Link: https://jakarta.ee/documents/insights/2019-jakarta-ee-developer-survey.pdf

**Comment by ericpoirier** [comment]
Hi Stephanie,

I added the banner in the featured story block on the production website.
