### ISSUE TITLE
need link to JESP

### ISSUE THREAD

**Issue by bshannon** [jakartaee/jakarta.ee#286]
On the page header, the Resources pull down has an entry for Specification Process
that points to https://jakarta.ee/resources/#specification_process.  That page has
no information about the JESP.

The right navbar has a Specification Process entry that points to
https://jakarta.ee/about/jesp/.  There should also be entries linking to that on the page above.

**Comment by chrisguindon** [comment]
Should we remove this section from the resources page?

I see two links:

1. Introducing the EFSP:
This google doc is not publicly available and does not work for most users.

2. Director’s Pick: Introducing The Eclipse Foundation Specification Process: 
Is a sessions submission from ECE 2018. I don't think that this page is very useful now that the event is passed.

**Comment by chrisguindon** [comment]
Adding @stephanieswart since we need to decide if we need to remove the "Introducing the EFSP" link or replace the google drive link with a publicly available link.

**Comment by stephanieswart** [comment]
[Introducing the EFSP (ECE2018).pdf](https://github.com/jakartaee/jakarta.ee/files/3355119/Introducing.the.EFSP.ECE2018.pdf)

Here is the presentation @chrisguindon

**Comment by waynebeaton** [comment]
I've made the presentation viewable by the general public. If we believe that there is still value in the presentation, I'd rather put a PDF of it somewhere.

**Comment by chrisguindon** [comment]
+1 for pdf. 

I don't think we should be linking to Google drive on our website.

**Comment by autumnfound** [comment]
This is now live
