### ISSUE TITLE
Please add two items to announcements

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#288]
1) https://blogs.eclipse.org/post/thabang-mashologu/cloud-native-java-innovation-eclipse-foundation

2) https://blogs.eclipse.org/post/thabang-mashologu/cloud-native-java-innovation-eclipse-foundation

**Comment by ericpoirier** [comment]
Hi Stephanie,

These two links are the same. Did you mean to add a different one for the second link?

**Comment by stephanieswart** [comment]
These are two separate articles. Would it be better if I just opened 2 separate issues?

**Comment by ericpoirier** [comment]
No one issue is fine but the links from your comment #1 are the same.

**Comment by ericpoirier** [comment]
Is this the second link you wanted to add:
https://blogs.eclipse.org/post/tanja-obradovic/update-jakarta-ee-community-may-2019

**Comment by stephanieswart** [comment]
Ah yes! My bad. Yes Tanja and Thabangs blog please

**Comment by ericpoirier** [comment]
Sounds good, no worries. I added the 2 announcements to the website. We should see them in a few minutes.
