### ISSUE TITLE
Please add community news items

### ISSUE THREAD

**Issue by ltran016** [jakartaee/jakarta.ee#291]
1. http://mydailyjava.blogspot.com/2019/05/jakarta-ee-without-javax-world-wont-end.html
2. https://jaxenter.de/javax-jakarta-ee-9-big-bang-84101
3. https://adtmag.com/articles/2019/05/22/eclipse-survey.aspx
4. https://dzone.com/articles/jakarta-ee-and-docker-what-you-should-know
5. https://blogs.eclipse.org/post/tanja-obradovic/update-jakarta-ee-community-may-2019

**Comment by chrisguindon** [comment]
@ltran016 https://jaxenter.de/javax-jakarta-ee-9-big-bang-84101 is in German. Do you still want us to post that on the website?

Also, could you include a summary that we can use for each post!

**Comment by ericpoirier** [comment]
Hi Laura,

I added all the community news listed in your first comment at the exception of the German one. Let us know if you would still like to add it and if so, can you provide a summary for it? Thanks.

**Comment by ericpoirier** [comment]
Hi Laura,

I added the community news item you provided in your last comment. It should appear in a few minutes.
