### ISSUE TITLE
Define the means by which we promote Final Specifications

### ISSUE THREAD

**Issue by waynebeaton** [jakartaee/jakarta.ee#302]
We need to define a means by which specification content is delivered. As core content, Final Specifications (as defined by the Eclipse Foundation Specification Process) must must be hosted on Eclipse Foundation supported infrastructure (with qualities of services that include, for example, backups).

With the successful conclusion of a release review for a specification project, the project team will deliver a Final Specification package that includes a specification document in PDF and HTML; and a collection of technical artifacts that may include API JARs, a TCK, and Javadoc.

Here's what I propose that we do:

To make that content available to consumers, I propose that we configure a directory structure on the web server along these lines: specs/[short-name]/[version]/*. Note that this is per-specification, not per-project. 

e.g. specs/faces/2.3/* for Jakarta Server Faces 2.3, and specs/faces/2.4/* for Jakarta Server Faces 2.4.

The specification document, and technical artifacts will just be files in the directory; the Javadoc (HTML files) will be expanded out in a directory so that they can be browsed and index as normal. No access restrictions are required for any of this content. 

I believe that it would be best that we not check these into a Git repository to stage them: accepting a pull request against this content would be fundamentally wrong. The content is not going to be maintained here, this is exclusively a distribution channel. Changes to this content must be managed via the Eclipse Foundation Specification Process. Also note that some of this content will be huge (I believe that the TCK for Jakarta EE Platform is something like 800GB).

For each specification, we will create a landing page. That landing page will be a Hugo file in a directory in this repository. That file will initially contain information about only the Jakarta EE 8 release of the specification, but will be expanded to include all future release versions of the specification (Final Specification).

For each version, we'll capture pointers to the aforementioned content, along with other related metadata, for example:

* Specification name and version;
* Name and URL for specification license (Eclipse Foundation Specification License);
* Project name and URL to project website;
* Contact/communication channel links;
* Pointer to normative document (the PDF); pointer to the HTML (labeled as "non-normative");
* Pointer to the TCK and TCK instructions content;
* Name and URL for TCK license (Eclipse Foundation TCK License);
* List of Compatible Implementations (which can be updated);
* ...

For each version, we will also need to provide a public record of results from various votes related to the project.

At some point, we should consider creating a custom Hugo content type. This will allow us to specify this metadata in a manner that is machine readable. This will make it easier to build aggregation pages, and manipulate the data in other ways (e.g. provide a JSON feed of specification information). 

I expect that a member from the project team that produced the Final Specification will update the specification landing page by pull request. Ideally, a member from the Specification Committee will sign-off before pull requests are accepted.

**Comment by waynebeaton** [comment]
This proposal puts the specifications in focus. My expectation is that specifications may possibly (though infrequently) move from one project to another (there's some history of JSRs splitting specifications, for example). From the perspective of an adopter of a specification, the project structure is "inside baseball" and not particularly useful or interesting.

So, for example, we would create a landing page for each of the separate specifications defined in the Eclipse Project for Stable Jakarta EE APIs. I'm thinking that there is also a separate page for each of the separate profiles defined in the platform project.

It might be useful to include some sort of "see also" metadata (e.g. when looking at the Full Profile, you might want to "see also" the Web Profile).

**Comment by bshannon** [comment]
This is a good start at a requirements document.  I'm still looking forward to the Users Guide.

How exactly do I get stuff in that specs directory?  Do I need a particular kind of Jenkins job
using a particular Maven plugin in a particular way to copy/publish content to that directory?

Can I update that content whenever I want?  Will there be any restrictions on who can update
the content when?

Can I put non-final specifications there as well?

Can you provide an example of the files in the specs directory for the Jakarta Wombat 1.0
specification?  I want to be clear on the naming conventions you want to use for the files
in the specs directory.

Some specs may not have a PDF file, and some specs may not have javadocs, so those
need to be optional.

I don't know what a Hugo file is so that needs to be explained in more detail.

I was initially confused about the difference between the specs directory and the per-spec
landing page.  These seem to be two different things, on different web sites, maintained in
different ways.

**Comment by waynebeaton** [comment]
I've cobbled together a little prototype (I cloned the website repository and created [the prototype](https://github.com/waynebeaton/jakarta.ee/tree/specs/content/specs) in a new branch).

The "Specifications" landing page:

![Screenshot from 2019-06-23 22-38-37](https://user-images.githubusercontent.com/555569/59987220-ec01f700-9607-11e9-9ce9-65fbc6d69710.png)

Click on one of the specification boxes, and it takes you to a list of versions:

![Screenshot from 2019-06-23 22-39-10](https://user-images.githubusercontent.com/555569/59987246-01772100-9608-11e9-8504-45cc56a5f465.png)

Click on a version, and it takes you to a page that describes that version, include various links, the results of ballots,  lists of compatible implementations, etc.

![Screenshot from 2019-06-23 22-39-37](https://user-images.githubusercontent.com/555569/59987293-3f744500-9608-11e9-99e9-e4e6202a5a12.png)

This is all pretty easy to implement using Hugo. I've created a directory tree under "specs"

```
[specs]$ tree
.
├── _index.md
├── jeb
│   ├── 3.0.0.md
│   └── _index.md
├── pages
│   ├── 2.1.0.md
│   ├── 2.2.0.md
│   └── _index.md
├── platform-full
│   └── _index.md
├── platform-web
│   └── _index.md
└── servlet
    ├── 4.0.1.md
    ├── 4.1.0.md
    └── _index.md
```

Each Final Specification is represented by a single markdown file with some metadata at the top:

```
---
title: "Jakarta Servlet 4.1.0"
date: 2018-12-12T16:10:38-04:00
summary: "Change to the Jakarta EE namespace."
---
Jakarta Servlet defines server-side handling for HTTP requests and responses.

* [Jakarta Servlet 4.1.0 Specification Document](./servlet_4.1.0.pdf) (PDF)
* [Jakarta Servlet 4.1.0 Specification Document](./servlet_4.1.0.html) (HTML)
* [Jakarta Servlet 4.1.0 Javadoc](./javadoc)
* [Jakarta Servlet 4.1.0 TCK](http://downloads.eclipse.org/jakarta/servlet/3.0.1/servlet_tck_4.1.0.zip)
* Maven coordinates
 * jakarta.servlet:servlet:jar:4.1.0

# Ballots

## Release Review
...
```

Hugo takes care of setting up things like navigation, the breadcrumbs, formatting, etc.

The example I'm showing is very basic, using only markdown to represent content. It's possible to create data-driven pages as well (or add more information to the metadata).

I can give a live walk through of the prototype.

Note that these pages are different from the flashier page being discussed by the marketing committee to list official compatible implementations of profiles with product logos and such.

**Comment by waynebeaton** [comment]
I should point out that I know that most of the content in the prototype is bogus.

**Comment by bshannon** [comment]
(Hmmm...  I wonder why I didn't get notified of this update since I'm watching this repo?)

This seems like a reasonable start to me, although see all my questions above.

(Note that specifications only have major.minor version numbers, no micro/patch.)

**Comment by dblevins** [comment]
This is a great start. +1

**Comment by starksm64** [comment]
I think @dblevins idea with the template @waynebeaton has would be a good approach for the first release. That addresses a number of @bshannon questions about who can do what. The PR would be exactly what triggers the final review.

**Comment by waynebeaton** [comment]
> Git supports submodules (basically symlinks). What do we think about making the `specs` directory a link to a potential [git@github.com](mailto:git@github.com):jakartaee/jakartaee-specs.git repo that the specification committee maintains?

I was thinking that. But I'm never sure whether or not it's okay to talk about submodules in polite company...

That would make managing access control a lot easier, and would mean that contributors don't have to clone the entire website. The data could also be more easily leveraged in other ways (I have nothing in particular in mind).

**Comment by ggam** [comment]
This looks fantastic, Wayne. Thanks a lot.

**Comment by waynebeaton** [comment]
We've created a [specifications repository](https://github.com/jakartaee/specifications) in the jakartaee organization. In this directory, we will have a directory for each specification, and information about individual versions of specifications ("final specifications") in each. We've set up a team for The Jakarta EE Specification Committee, and have assigned that team "write" permission on the repository. @dblevins is creating a script to provide the initial population.

The @jakartaee/eclipsefdn-webdev team is investigating the best approach to "stitch" this repository into the jakartaee repository (as a subdirectory of ./content/). ETA for implementation is the week of July 22.

**Comment by chrisguindon** [comment]
I created a PR and decided to leverage the postinstall script in npm to `git clone https://github.com/jakartaee/specifications.git content/specs`

To avoid any errors, I am deleting content/specs before the clone. 

I decided to use this workflow since our developers already  run `npm install` to install dependencies.

**Comment by bshannon** [comment]
We've been expecting the content to appear in jakarta.ee/specifications.
If you want it to appear in jakarta.ee/specs instead, we need to know NOW.
Thanks.

**Comment by chrisguindon** [comment]
+1 for jakarta.ee/specifications

I am currently using jakarta.ee/specs because this was the path used by @waynebeaton on github
![Screen Shot 2019-07-17 at 11 21 32 AM](https://user-images.githubusercontent.com/893942/61387930-0d5fa700-a885-11e9-9bc1-c7c185d37be2.png)
:
https://github.com/waynebeaton/jakarta.ee/tree/specs/content/specs

**Comment by chrisguindon** [comment]
@bshannon I made the required change in my PR to reflect your recommendation of using jakarta.ee/specifications

**Comment by waynebeaton** [comment]
I think that we're done here.
