### ISSUE TITLE
Please add Brand Usage Handbook to this page at the bottom: https://jakarta.ee/legal/trademark_guidelines/

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#303]
Subtitle: Proper usage of the Jakarta EE Brand
Text: To ensure the consistency of the Jakarta EE brand, please see our Brand Usage Handbook (link to PDF). This style guide outlines usage standards to ensure that the Jakarta EE logo is instantly and consistently recognizable however and wherever it is used by Foundation members and the community.

https://jakarta.ee/legal/trademark_guidelines/
[JakartaEE_BrandUsageHandbook_v2.pdf](https://github.com/jakartaee/jakarta.ee/files/3272299/JakartaEE_BrandUsageHandbook_v2.pdf)

**Comment by ericpoirier** [comment]
This is now on production

**Comment by stephanieswart** [comment]
Just noticed the link was never updated with the new usage handbook. Please update this link:
https://jakarta.ee/legal/trademark_guidelines/jakarta-ee-branding-guidelines.pdf

with this PDF:
[JakartaEE_BrandUsageHandbook_v2.pdf](https://github.com/jakartaee/jakarta.ee/files/3418082/JakartaEE_BrandUsageHandbook_v2.pdf)

**Comment by ericpoirier** [comment]
I just merged a patch to update this PDF. We should see the new document in a few minutes on the production page.
