### ISSUE TITLE
JakartaOne Livestream Program Committee Bio and Pictures

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#307]
Reza:
![reza_professional](https://user-images.githubusercontent.com/51449073/59281338-18476c00-8c35-11e9-8aa5-c5908456a900.jpg)

Hi,

Here are the edited program committee bio and pictures;

Arun Gupta is a Principal Technologist at Amazon Web Services. He is responsible for the Cloud Native Computing Foundation (CNCF) strategy within AWS, and participates at CNCF Board and technical meetings actively. He works with different teams at Amazon to help define their open source strategy. He has built and led developer communities for several years. He has extensive speaking experience in 45+ countries on myriad topics. Gupta also founded the Devoxx4Kids chapter in the US and continues to promote technology education among children. A prolific writer, author of several books, an avid runner, a globe trotter, a Docker Captain, a Java Champion, a JUG leader, he is easily accessible at @arungupta on twitter.

Java (SE/EE) developer Adam Bien (adambien.blog) has been using Java since JDK 1.0 and JavaScript since LiveScript and still enjoys writing Java and web (standards) code.
Adam regularly organizes Java EE / WebStandards / JavaScript workshops at Munich’s airport (http://airhacks.com).

Ivar Grimstad is a Java Champion, Oracle Groundbreaker Ambassador and JUG Leader working as Principal Consultant for Cybercom Group in Sweden.

He is the PMC Lead for Eclipse Enterprise for Java (EE4J) and was involved in the forming of Jakarta EE. He is also involved in the Java Community Process as a member of the Executive Committee, Spec Lead for JSR 371 (MVC 1.0) and has served as Expert Group Member for a number of JSRs, such as JSR 375 (Java EE Security API).

Ivar is also involved in Eclipse MicroProfile. He is an Apache NetBeans Committer and a frequent speaker at international developer conferences.

Josh Juneau works as an application developer, system analyst, and database administrator. He primarily develops using Java and other Java Virtual Machine (JVM) languages. He is a frequent contributor to the Oracle Technology Network and Java Magazine and has written several books on Java and Java EE for Apress. Josh was a JCP Expert Group member for JSR 372 and JSR 378. 

He is a member of the Apache NetBeans developer community, a Java Champion, the leader of the Chicago Java Users Group OSS Initiative, and a regular on the Java OffHeap podcast.

Reza Rahman is a Java EE old-timer who still cares about the technology and the community. These days, he works as a Principal Program Manager for Java on Azure at Microsoft.

Reza was previously an official Java technologist at Oracle. He is the author of the popular book EJB 3 in Action. Reza has been a frequent speaker at Java User Groups and conferences worldwide including JavaOne and Devoxx. He has been the lead for the Java EE track at JavaOne as well as a JavaOne 
Reza is the recipient of a Rock Star Speaker award. He is an avid contributor to industry journals like JavaLobby/DZone and TheServerSide. He has been a member of the Java EE, EJB and JMS expert groups over the years. Reza implemented the EJB container for the Resin open source Java EE application server. 
He helps lead the Philadelphia Java User Group.
Arun:
![Arun-683x1024](https://user-images.githubusercontent.com/51449073/59281001-88092700-8c34-11e9-9aa9-5dd779efdce1.jpg)
Adam:
![Adam](https://user-images.githubusercontent.com/51449073/59281085-aff88a80-8c34-11e9-897e-873389153b21.jpg)
Ivar: 
![ivar_jc_982_988](https://user-images.githubusercontent.com/51449073/59281212-dfa79280-8c34-11e9-99fc-4fc45f7acd6b.png)
Josh:
![Josh](https://user-images.githubusercontent.com/51449073/59281298-082f8c80-8c35-11e9-94d2-335007a3401b.jpg)

**Comment by autumnfound** [comment]
I've done a first pass at adding these folks to the page, and there are a few things that I need:
1. What professional taglines (i.e. Senior Director of Strategic Projects at Linux Foundation) should I put for each? I've taken first crack at it, but there may be more appropriate lines than what I have.  
2. Adam Bien doesn't have a linkedin, but all of the carousels have traditionally had a link to their profile. I've updated the glyph to be for twitter and linked to his account (one of his few points of contact available). Should we do something different?

**Comment by ericpoirier** [comment]
The program committee is on production now.

Next time, can you open the issue on the Jakarta One repo? Thanks.
