### ISSUE TITLE
ECE Call for Papers featured story

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#312]
Requested by Paul W.

Can we put a banner on ECE Call for Papers up on jakarta.ee.  It would need to be customized to submit to the track “Cloud Native Java”.  We also need an Announcement on Jakarta EE noting the CFP.

**Comment by autumnfound** [comment]
Currently on hold until Jul 2nd as we cannot queue in current functionality (upcoming)

**Comment by autumnfound** [comment]
Do we have an image for this?

**Comment by ltran016** [comment]
Background and mock up here!
![2](https://user-images.githubusercontent.com/48952273/60725936-4eac9a00-9f08-11e9-86f7-b41f0793bb29.png)
![1](https://user-images.githubusercontent.com/48952273/60725938-4eac9a00-9f08-11e9-95e2-8916de6aecb1.png)
![backgroundececfp](https://user-images.githubusercontent.com/48952273/60726235-12c60480-9f09-11e9-9dcd-139e7f2c9f41.png)

**Comment by chrisguindon** [comment]
+1

and to clarify, I would expect that we keep the sign up to our newsletter on the right side.

**Comment by ltran016** [comment]
Yes, the newsletter sign-up should be on the right side!

**Comment by autumnfound** [comment]
This is live
