### ISSUE TITLE
Unpublish compatibility page

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#313]
Requested by Shabnam,

We are working on the compatibility page content https://jakarta.ee/compatibility/ and in the meantime, can we block the page and make it indiscoverable?

since the current information there is confusing.

Can you kindly remove the link in the main menu and keep the page unpublished for now. Thanks

**Comment by shabnammayel** [comment]
Thank you Chris

**Comment by chrisguindon** [comment]
I committed a change that will remove the link from the main menu and set the compatibility to draft mode!
