### ISSUE TITLE
Featured Banner for JakartaOne Livestream CFP

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#316]
Please add a featured banner for JakartaOne Livestream CFP. Background and mockup images attached:
![2](https://user-images.githubusercontent.com/34580334/59633682-0d9c4380-911b-11e9-9f96-35e2a153b6c9.png)
![jakarta_CFP_banner](https://user-images.githubusercontent.com/34580334/59633718-2147aa00-911b-11e9-840f-a7206215b79d.png)

Rotation schedule for jakarta.ee:
JakartaOneLivestream CFP - Now until July 1st
ECE CFP Banner - July 2nd to July 15

**Comment by chrisguindon** [comment]
@autumnfound The requirements for the ECE Call for Papers featured story are defined on Issue #312
