### ISSUE TITLE
Please add new announcement: https://blogs.eclipse.org/post/tanja-obradovic/update-jakarta-ee-community-june-2019

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#317]
title: Update for Jakarta EE community: June 2019
text:  Get the latest monthly email update on the Jakarta EE community from news highlights to various meetings and events related to the platform!
link: https://blogs.eclipse.org/post/tanja-obradovic/update-jakarta-ee-community-june-2019

**Comment by chrisguindon** [comment]
@autumnfound patch has been merged! Closing this issue!
