### ISSUE TITLE
Publishing Specification Committee meeting minutes

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#326]
This is not a problem; we need to add new entries for Specification meeting minutes on
https://jakarta.ee/meeting_minutes/

under tab
Jakarta EE Specification Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached
[Spec Committee Meeting Minutes May 22th, 2019.pdf](https://github.com/jakartaee/jakarta.ee/files/3330219/Spec.Committee.Meeting.Minutes.May.22th.2019.pdf)
[Spec Committee Meeting Minutes May 15th, 2019.pdf](https://github.com/jakartaee/jakarta.ee/files/3330220/Spec.Committee.Meeting.Minutes.May.15th.2019.pdf)
[Spec Committee Meeting Minutes May 8th, 2019.pdf](https://github.com/jakartaee/jakarta.ee/files/3330221/Spec.Committee.Meeting.Minutes.May.8th.2019.pdf)
[Spec Committee Meeting Minutes June 5th, 2019.pdf](https://github.com/jakartaee/jakarta.ee/files/3330222/Spec.Committee.Meeting.Minutes.June.5th.2019.pdf)
[Spec Committee Meeting Minutes May 29th, 2019.pdf](https://github.com/jakartaee/jakarta.ee/files/3330223/Spec.Committee.Meeting.Minutes.May.29th.2019.pdf)

pdf files. Please let me know if you need anything else from me.

**Comment by autumnfound** [comment]
Now live. https://jakarta.ee/meeting_minutes/#specification_committee
