### ISSUE TITLE
Publishing Steering  Committee meeting minutes

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#327]
This is not a problem; we need to add new entries for Steering meeting minutes on
https://jakarta.ee/meeting_minutes/

under tab
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached
[Minutes of June 4 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3330248/Minutes.of.June.4.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of June 11 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3330249/Minutes.of.June.11.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of May 7 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3330250/Minutes.of.May.7.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of May 14 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3330251/Minutes.of.May.14.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of May 21 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3330252/Minutes.of.May.21.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of May 28 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3330253/Minutes.of.May.28.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of April 30 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/3330254/Minutes.of.April.30.Jakarta.EE.Steering.Committee.Meeting.pdf)

pdf files. Please let me know if you need anything else from me.

**Comment by autumnfound** [comment]
This is now live! https://jakarta.ee/meeting_minutes/#steering_committee
