### ISSUE TITLE
Updating the Jakarta EE Trademark Guidelines 1.0 to 1.1

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#332]
Kindly replace the content of the following page

https://jakarta.ee/legal/trademark_guidelines/ 

**to (Jakarta EE Trademark Guidelines 1.1)**;

https://docs.google.com/document/d/10Q8IPpnbU5E1671bnRkMZsPkLU1aWfL6PkP4kzVPqLE/edit#heading=h.njmsb6fbebb3

I have also attached the **"Jakarta EE Brand Usage Handbook"**  and "**Jakarta EE Trademark License**" that needs to be linked to the updated content.

[JakartaEE_BrandingGuidelines_v1.0.pdf](https://github.com/jakartaee/jakarta.ee/files/3339462/JakartaEE_BrandingGuidelines_v1.0.pdf)
 
I will attach the "Jakarta EE Trademark license" shortly

**Comment by shabnammayel** [comment]
[Jakarta EE Trademark License.pdf](https://github.com/jakartaee/jakarta.ee/files/3339592/Jakarta.EE.Trademark.License.pdf)

**Comment by autumnfound** [comment]
Hi Shabnam, I've updated the page locally, but I'm not seeing what resources you want me to update on the site for the PDFs. Could you provide links to the pages/documents you need me to update for the PDFs?

**Comment by shabnammayel** [comment]
So in the content of the https://docs.google.com/document/d/10Q8IPpnbU5E1671bnRkMZsPkLU1aWfL6PkP4kzVPqLE/edit#heading=h.njmsb6fbebb3

you can see there are two parts that are highlighted: **"Jakarta EE Brand Usage Handbook" and "Jakarta EE Trademark License"** 

So the PDFs should be linked to these two highlighted parts once you publish them in the website

**Comment by autumnfound** [comment]
This is now live
