### ISSUE TITLE
Publishing Marketing Committee meeting minutes (June 13, 2019)

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#333]
This is not a problem; we need to add new entries for Marketing meeting minutes on
https://jakarta.ee/meeting_minutes/

under section
Jakarta EE Marketing Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached

[Jakarta EE Marketing Committee Meeting - June 13, 2019.pdf](https://github.com/jakartaee/jakarta.ee/files/3347971/Jakarta.EE.Marketing.Committee.Meeting.-.June.13.2019.pdf)

pdf files. Please let me know if you need anything else from me.

**Comment by autumnfound** [comment]
This is now live
