### ISSUE TITLE
Remove SAP from Jakarta EE webpage

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#336]
SAP has refused to participate in the WG. Please remove their logo from the Jakarta EE website. Thanks
https://jakarta.ee/membership/members/

**Comment by autumnfound** [comment]
This is now live!

**Comment by ggam** [comment]
SAP is also mentioned on https://jakarta.ee/membership/ as a WG member

**Comment by aeiras** [comment]
Guillermo, good meticulous eye Latino! :)

**Comment by chrisguindon** [comment]
Latest PR was merged!
