### ISSUE TITLE
Remove Google + from the website

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#339]
<img width="295" alt="image" src="https://user-images.githubusercontent.com/10731224/60608579-9d292f80-9d74-11e9-8608-fc4d91a6c2bd.png">

**Comment by chrisguindon** [comment]
@stephanieswart is this something we want to do? Please advise.

**Comment by chrisguindon** [comment]
I took a look at our Google+ link and it does not work anymore:
https://plus.google.com/+Eclipse

@autumnfound you can remove it from Jakarta.ee. Also, please open a bug on Eclipse Bugzilla for removing google plus on all our websites.

**Comment by aeiras** [comment]
Thanks for quick follow up awesome Chris! :)

**Comment by autumnfound** [comment]
Change has been made in hugo-solstice-theme, where the footer links are defined:
https://github.com/EclipseFdn/hugo-solstice-theme/pull/63

**Comment by chrisguindon** [comment]
PR for this has been merged!
