### ISSUE TITLE
Jakarta EE Youtube:  is there a plan to create the  official medium for the project videos? 

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#342]
Currently the Jakarta EE calls and Jakarta Tech Talks are being housed under the EF youtube account. 
Is there a plan for the project to have its own Youtube account and move all its content there? 

Question for the EF team in charged of managing the project media. 
Thanks for the follow up,

**Comment by stephanieswart** [comment]
Hi @aeiras, all of the working groups content is housed under the Eclipse Foundation YouTube account. If you have content you'd like uploaded to the channel, feel free to send it to me to add!

Thank you,
Stephaine
