### ISSUE TITLE
monthly email update for Jakarta EE community [format feedback]

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#347]
On July 2nd/ 2019 a email with subject `[jakarta.ee-community] July 2nd 2019, monthly email update for Jakarta EE community` was sent to jakarta.ee-community@eclipse.org mailing list.

The information is valuable and appreciated, but I think we can improve the format of further communication:

1. The current communication has different fonts and size which make it unpolished.  **Proposal**: Usage of the same font and size can be applied. 

2. The email communicated 7 sections, each section felt to me more like a potential individual blog post. Take for instance the section "JakartaOne LiveStream: All eyes on Cloud Native Java" which had 283 words 1,726 characters:
![image](https://user-images.githubusercontent.com/1454523/60819218-71cf8780-a15c-11e9-8ca7-ec6bea490901.png).  **Proposal**:  keep as many sections as need it but summarize in max 50 word the overview and provide 1 link only to an individual blog post that can contain any number of links, images, and embedded document that are not displayed on mailing list easily. 

3. The email had 4 attachments, one of them being a GD folder with +5 files inside. This makes even more hard to digest a monthly update. **Proposal**: the individual blog post can still have the reference to any multimedia, but the monthly email to the list will only contain the proposal described in feedback the previous point describes.

**Comment by TanjaObradovic** [comment]
Thanks for much for your feedback @cesarhernandezgt! We are now working on our August email/blog and will take your input into consideration.
I will also mention that the same email is turned into a blog, like this one
https://blogs.eclipse.org/post/tanja-obradovic/update-jakarta-ee-community-july-2019
in hope, it reaches an even bigger audience.

**Comment by cesarhernandezgt** [comment]
Thanks for the feedback @TanjaObradovic .
Thank you for your awesome community-driven-focused work done so far :)!
