### ISSUE TITLE
Host Jakarta EE tutorial and First Cup

### ISSUE THREAD

**Issue by ggam** [jakartaee/jakarta.ee#350]
Jakarta EE tutorial is currently hosted at its own page: https://eclipse-ee4j.github.io/jakartaee-tutorial/toc.html

Besides that, both tutorial and First Cup should also be hosted on jakarta.ee

https://github.com/eclipse-ee4j/jakartaee-tutorial/issues/147 needs to be resolved first, but we can start discussing right now.

**Comment by chrisguindon** [comment]
Would these be links under our resources page?
https://jakarta.ee/resources/

**Comment by bshannon** [comment]
There's a job that republishes the tutorials when changes are made.
If you can figure out how to publish to jakarta.ee instead, or how to
trigger another job to copy the data to jakarta.ee, that would be great.

**Comment by ggam** [comment]
@chrisguindon I prefer a new "Docs" top level item, with a projects like layout, listing:
* Getting Started tutorial: First Cup
* The complete user guide: Jakarta EE tutorial (based on GlassFish, at least for now).
* Complete example project: CargoTracker. I think this donation of this project hasn't been yet completed. It had a simple website and some documentation that would need to be enhanced to fit the website.
* Other random examples: there are already some examples repositories, and I know at least one more is being donated (https://github.com/manorrock/jakartaee-examples). Hopefully one way we'll evne be able to get the Java EE 8 Samples (https://github.com/javaee-samples/javaee8-samples/) moved to Jakarta, although that depends on its individual contributors.

Currently both Tutorial and First Cup has legacy standalone layouts which doesn't integrate with jakarta.ee but I'd like to explore a more tight visual integration once the content is completefly updated for Jakarta EE.

@bshannon maybe overkill, but we could create a "documentation" repository which is referenced a a submodule form the website (in the same vein that specifications) and grant specific projects push access to that repository. A new tutorial build job would copy the generated html content there.

**Comment by chrisguindon** [comment]
A possible solution would be to write an npm script similar to what I am proposing via https://github.com/jakartaee/jakarta.ee/issues/302#issuecomment-512270427

The script here would be a bit more complex since it seems that we would need to extract content from files instead of simply copying them.

**Comment by ggam** [comment]
Your proposal looks great. We can simply download the rendered html
tutorial and unzip it on the desired path.

**Comment by ggam** [comment]
FYI and the tutorial content has been upgraded to Jakarta EE. There's still work to do on branding and design. Would be great if we can retake this item now.

As a very first step, we can add a new Documentation page that links to https://eclipse-ee4j.github.io/jakartaee-tutorial/toc.html while we find the proper way to integrate the tutorial on the website.

Thoughts?

**Comment by ggam** [comment]
Any idea how we could move this forward?

**Comment by chrisguindon** [comment]
@ggam How about we include a link for this page on https://jakarta.ee/resources/#surveys?

**Comment by ggam** [comment]
That would be a first step, yes!

**Comment by chrisguindon** [comment]
Great! Can we expect a PR from you? 

I am asking since you've made some contributions to the site before!

**Comment by ggam** [comment]
@chrisguindon sure, #520. But please keep this issue open until we finish all related work and create a proper page for it.

**Comment by TanjaObradovic** [comment]
@ggam should we still have this one opened? maybe open a new one later if needed?

**Comment by ggam** [comment]
Yes this can be closed for now. Thanks!
