### ISSUE TITLE
please add to announcements: https://blogs.eclipse.org/post/tanja-obradovic/update-jakarta-ee-community-july-2019

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#354]
Title: Update for Jakarta EE community: July 2019
Subtext: Get the latest email update for the Jakarta EE community which highlights news from various committee meetings related to this platform.
https://blogs.eclipse.org/post/tanja-obradovic/update-jakarta-ee-community-july-2019

**Comment by autumnfound** [comment]
This is now live
