### ISSUE TITLE
Switch out banner text on jakarta.ee to promote JakartaOne Livestream

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#360]
Title: Join us for JakartaOne Livestream! 
Subtitle: You won't want to miss out on this free, one-day virtual conference focused on all things cloud native Java. 
Button: Register
Link: https://jakartaone.org/

**Comment by autumnfound** [comment]
Did you want me to remove the current link buttons on the home page, or add a fifth button?

**Comment by stephanieswart** [comment]
Banner background 
![livestream_banner_background](https://user-images.githubusercontent.com/34580334/61468515-701b7600-a94b-11e9-961e-304ea141e03b.png)

Banner mockup
[livestream_banner.zip](https://github.com/jakartaee/jakarta.ee/files/3407121/livestream_banner.zip)

**Comment by stephanieswart** [comment]
> Did you want me to remove the current link buttons on the home page, or add a fifth button?

I'm not sure what you mean, this is for the banner under the jumbotron header. It currently displays EclipseCon Europe CFP, but it's now out of date. So let's update to Livestream promo

**Comment by autumnfound** [comment]
This is live
