### ISSUE TITLE
Publishing Jakarta EE Working Group Committee Members

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#362]
Can you please publish the Jakarta EE Working Group Committee Members under 
jakarta.ee/about and maybe a drop-down with the item "Committee Members"?
here is the list

**Steering Committee** 
Will Lyons (**chair**)- Oracle, Ed Bratt - alternate
Kenji Kazumura - Fujitsu, Michael DeNicola - alternate
Dan Bandera - IBM, Ian Robinson - alternate
Steve Millidge - Payara, Mike Croft - alternate
Mark Little - Red Hat, Scott Stark - alternate
David Blevins - Tomitribe, Richard Monson-Haefel alternate
Martijn Verburg - London Java Community - Elected Participant Representative
Ivar Grimstad - Elected Committer Representative

**Specifications Committee**
Kenji Kazumura - Fujitsu, Michael DeNicola - alternate
Dan Bandera - IBM, Kevin Sutter - alternate
Bill Shannon - Oracle, Ed Bratt - alternate
Steve Millidge - Payara, Arjan Tijms - alternate
Scott Stark - Red Hat, Mark Little - alternate
David Blevins - Tomitribe, Richard Monson-Haefel - alternate
Ivar Grimstad - PMC Representative
Alex Theedom - London Java Community Elected Participant Representative
Werner Keil - Elected Committer Representative
Paul Buck - Eclipse Foundation (serves as interim chair, but is not a voting committee member)

**Marketing and Brand Committee**
Michael DeNicola - Fujitsu, Kenji Kazumura - alternate 
Dan Bandera - IBM, Neil Patterson - alternate
Ed Bratt - Oracle, David Delabassee - alternate
Dominika Tasarz - Payara, Jadon Orglepp - alternate
Cesar Saavedra - Red Hat, Paul Hinz - alternate
David Blevins - Tomitribe, Jonathan Gallimore - alternate
Theresa Nguyen - Microsoft Elected Participant Representative
VACANT - Elected Committer Representative
Thabang Mashologu - Eclipse Foundation (serves as interim chair, but is not a voting committee member)

**Comment by autumnfound** [comment]
This is live
