### ISSUE TITLE
Fix HTML tables

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#365]
HTML table would look nicer on a page if we would apply the .table class on them:
https://getbootstrap.com/docs/3.4/css/#tables

Hopefully, we can find a way to automatically append this class each time hugo generates an html table.

**Comment by chrisguindon** [comment]
Example:
https://jakarta.ee/specifications/enterprise-beans/3.2/

**Comment by chrisguindon** [comment]
As discussed, this is something that should be fix in our hugo-solstice-theme.

**Comment by autumnfound** [comment]
This is now fixed and live

**Comment by autumnfound** [comment]
Reopened, as I caught up on emails and saw this was reverted

**Comment by autumnfound** [comment]
Closed as the change for this issue was merged back in outside of this bug
