### ISSUE TITLE
Publishing Marketing Committee meeting minutes (11 July, 2019)

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#374]
This is not a problem; we need to add new entries for Marketing meeting minutes on
https://jakarta.ee/meeting_minutes/

under section
Jakarta EE Marketing Committee

in the same way as other files with just adding a date with the link.
e.g, June 25, 2018 (pdf)
I have attached

[Jakarta EE Marketing Committee Meeting - July 11, 2019.pdf](https://github.com/jakartaee/jakarta.ee/files/3432511/Jakarta.EE.Marketing.Committee.Meeting.-.July.11.2019.pdf)

**Comment by autumnfound** [comment]
This is live
