### ISSUE TITLE
Publish Steering Committee Minutes June 18, June 25, July 2

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#378]
This is not a bug. 

We need to add new entries for Steering meeting minutes on
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached pdf files:
[Minutes of the July 2 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/3437189/Minutes.of.the.July.2.Jakarta.EE.Steering.Committee.Meeting.pdf)
[Minutes of June 25 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/3437190/Minutes.of.June.25.Jakarta.EE.Steering.Committee.Meeting.pdf)
[Minutes of June 18 Jakarta EE Steering Committee Meeting.pdf](https://github.com/jakartaee/jakarta.ee/files/3437191/Minutes.of.June.18.Jakarta.EE.Steering.Committee.Meeting.pdf)

Please let me know if you need anything else from me.

**Comment by autumnfound** [comment]
This is live

**Comment by will-lyons** [comment]
Thank you.

Will
