### ISSUE TITLE
Updating the link of Jakarta EE Trademark license in the 'Jakarta EE trademark guidelines page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#385]
In this page 
https://jakarta.ee/legal/trademark_guidelines/ 

Please update the link of **"Jakarta EE Trademark license"** from https://jakarta.ee/legal/trademark_guidelines/jakarta-ee-trademark-license.pdf 

to the new Hello Sign link

https://app.hellosign.com/s/DQ9uVw4b

**Comment by chrisguindon** [comment]
We are holding off on this issue for now. EMO will let us know if we can move forward with this.

**Comment by autumnfound** [comment]
This is now live
