### ISSUE TITLE
Developing the "Get Listed" page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#388]
**Is your feature request related to a problem? Please describe.**
Creating the "Get listed" page
https://jakarta.ee/compatibility/getlisted
or
https://jakarta.ee/getlisted

Here is the mock up Stephanie has created;

![compatible_productsv1 2 (3)](https://user-images.githubusercontent.com/51449073/62335402-b61f2080-b499-11e9-99db-254bf31dc8e9.png)

 The text and links for the page;

Benefits of Getting Listed

There are several benefits associated with completing the process to get listed on the Compatible Products page, including:

- Provide your enterprise customers and prospects with the confidence that your product meets their quality, portability, and scalability requirements 
- Demonstrate your organization is collaborating with industry leaders to advance Jakarta EE technologies 
- Strengthen your brand in partnership with Jakarta EE Working Group
- Demonstrate your support for the Jakarta EE developer community

How to Get Listed

To get your product listed on the Compatible Products page, please follow these steps:

1.  [Join](https://jakarta.ee/membership/) the Jakarta EE Working Group

2.  Complete the steps outlined in the [Jakarta EE Trademark Guidelines](https://jakarta.ee/legal/trademark_guidelines/), including:

a. Follow the Jakarta EE TCK process to completely run and satisfy all of the requirements of the applicable TCK test

b. Email the TCK results to tck@eclipse.org
c. Execute (digitally sign) the [Jakarta EE Trademark License Agreement](https://app.hellosign.com/s/DQ9uVw4b) (or print the PDF and return the signed agreement to emo-records@eclipse.org)

3. Open a [GitHub issue](https://github.com/jakartaee/jakarta.ee/issues/new?template=compatibility.md) and fill in the required information

**Comment by autumnfound** [comment]
@shabnammayel @stephanieswart looks good to me! Could I have the image assets used for the Beneftis section?

**Comment by stephanieswart** [comment]
[icons_benefitspage.zip](https://github.com/jakartaee/jakarta.ee/files/3471966/icons_benefitspage.zip)
Here is a zip file with all the icons for this page

**Comment by autumnfound** [comment]
How does this look? I can keep the SVGs black, or I can recolor them to match exactly the mock:
![image](https://user-images.githubusercontent.com/23018241/62558826-bb88bc00-b847-11e9-9301-b649b5237419.png)

**Comment by stephanieswart** [comment]
Please recolor the symbols and make them smaller, they are much too big.

**Comment by shabnammayel** [comment]
Can we have the titles in blue similar to the mock up, and can u please add some spacing, between the titles and sentences, and also from the last sentence (3. Open a GitHub issue and fill in the required information) and the footer
We will also need the link of the GitHub template in the point 3 where it says Github issue

**Comment by autumnfound** [comment]
Changing the header colours breaks our colour branding for the site and I'd advise against it, unless we planned to change all header colours over. We can look at replacing one of the current branding colours if that's wanted, but it should be as part of a separate bug.

One other change I've made is the link to the page. Throughout the site, we use what's called snake case for page names. This is all lower case letters, with words separated by underscores. This means that this page should be `get_listed` rather than `getlisted` for consistency.

Otherwise, I've implemented feedback on the look of this section locally:
![image](https://user-images.githubusercontent.com/23018241/62882906-eddf6100-bd00-11e9-84f1-7000af9bbb1a.png)

I'll be pushing a patch for this later today. Along with these changes is the promised link on the compatibility page

**Comment by stephanieswart** [comment]
The icons are still too big, it makes the page look odd. Please make them smaller.

**Comment by autumnfound** [comment]
Talked w/ Stephanie, will be making them 80px wide, and will be adding some padding to the text above the icons to give them some room to breathe

**Comment by autumnfound** [comment]
This is live

**Comment by shabnammayel** [comment]
Thanks Martin, I just noticed since we changed the name of the  "Jakarta EE Trademark License Agreement" to "Jakarta EE Compatibility Trademark License Agreement" in the guidelines page, can we change it here too, please?

**Comment by shabnammayel** [comment]
and also kindly include the link to the Pdf version in the text, sorry my bad, I did not include it before: 

[jakarta-ee-trademark-license.pdf](https://github.com/jakartaee/jakarta.ee/files/3501217/jakarta-ee-trademark-license.pdf)

**Comment by shabnammayel** [comment]
Can you please add two more buttons in this page: 

Button 1: How to
Goes the the How to Get Listed section

Button 2: Benefits 
Goes to the Benefits of Getting Listed section

Keep the Compatible products button 

Can we change /benefits of getting listed to /Get-Listed or /get-listed ?

<img width="1024" alt="Screen Shot 2019-08-16 at 12 51 21 PM" src="https://user-images.githubusercontent.com/51449073/63185391-eaf9ae80-c027-11e9-8907-7714c66467d4.png">

**Comment by chrisguindon** [comment]
> Can we change /benefits of getting listed to /Get-Listed or /get-listed ?

I would recommend keeping the url to compatibility/get_listed or compatibility/get-listed as this is a sub-page of the compatibility section. 

Changing the url would remove the Compatible Products link in the breadcrumbs.

**Comment by autumnfound** [comment]
For the buttons, I could see the handiness of the `How to` button, as the content is below the fold, but not as much for the `Benefits` button. The section it would link to is directly below it, and doesn't provide a lot of value to the end user. I recommend that we don't include the Benefits button, and save the real estate for other links or to give more prominence to the existing buttons.

**Comment by shabnammayel** [comment]
+1 to keeping the URL as compatibility/get_listed, can we change the highlighted part in the screenshot into that too? instead of benefits of getting listed

<img width="1194" alt="Screen Shot 2019-08-18 at 7 45 27 PM" src="https://user-images.githubusercontent.com/51449073/63231953-e0d6dc00-c1f0-11e9-9838-b2f549928dd9.png">

**Comment by shabnammayel** [comment]
+1 to creating the "How to" button, thanks
