### ISSUE TITLE
Developing the "Compatible Products" page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#389]
**Is your feature request related to a problem? Please describe.**
Creating the "Compatible Products" page
https://jakarta.ee/compatibility

Mock up:
![_compatible_productsv3 2 (1)](https://user-images.githubusercontent.com/51449073/62336151-ffbd3a80-b49c-11e9-93cd-bff8a1eedc2e.png)

The text:

Compatible Product page

The success of Jakarta EE technology relies on compatibility to ensure application portability, security, stability, and resiliency. Compatibility will allow more technology providers to leverage and strengthen the Jakarta EE brand in the enterprise Java community. If you are interested in featuring your product here, follow the steps on the **Get Listed** page.

Note: the Get Listed in the last sentence should be link to the Get Listed page once created, no quotes is required and Get Listed can be a clickable link to that page

**Comment by autumnfound** [comment]
This is live

**Comment by shabnammayel** [comment]
@autumnfound once the Get Listed page is also live, can we add its link to this page in the text where it is mentioning Get Listed in the last sentence? thanks

**Comment by autumnfound** [comment]
You bet! The plan is to make that change as part of the Get Listed changes

**Comment by shabnammayel** [comment]
Great, then we are planning to add the "get listed" button in the heather once we have Get listed page live, too. right?
Also can we add more spacing between the title and the sentence, the last sentence and Stay tuned, and also stay tuned and the footer?

**Comment by shabnammayel** [comment]
Also can we change the the title colour as we have in the mockups. @stephanieswart what do u think?

**Comment by stephanieswart** [comment]
+1 to all suggestions @shabnammayel !
