### ISSUE TITLE
Updating headings/text styles color

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#393]
Please update the headings/text styles to the Jakarta EE blue: #1b208b

**Comment by autumnfound** [comment]
After talking with Stephanie about some of the other issues in Jakarta.ee (#388), we discussed some of the changes to be made as part of this change set:

## Font size
The font size should be upped from 14px to 16px across the site.

## Branding colours
Right now branding colours in the styling don't match the branding in the [trademark guidelines](https://jakarta.ee/legal/trademark_guidelines/jakarta-ee-branding-guidelines.pdf). To this end, the brand colours in the base theme will be updated to reflect the available colours in the guidelines.

## Additional changes
As part of these changes, the heading colours on the Get Listed page (at the very least) should match the Jakarta EE blue referenced by @stephanieswart in her initial comment (![#1b208b](https://placehold.it/15/1b208b/000000?text=+) #1b208b)

If there are additional changes, please flag them as a comment, and I'll include them in these changes once they go live!

**Comment by autumnfound** [comment]
Here is a first round set of images of switching the branding colours. What do you guys think? I tried to keep things as similar as possible to the current state. 

The biggest changes are that the branding colours on a whole are darker than the current colours. This is a good thing for accessibility, as it brings it closer to the desired contrast ratio. Additionally, you'll see in the mobile screenshot that the buttons in the jumbotron are the same font size. Before they were being shrunk to 12px font for some reason which made them incredibly hard to read.

Desktop:
![desktop](https://user-images.githubusercontent.com/23018241/63616339-5ce86f80-c5b5-11e9-8603-4785ced66886.png)

Mobile:
![mobile](https://user-images.githubusercontent.com/23018241/63616362-6d98e580-c5b5-11e9-83bb-ae2308daef94.png)

**Comment by autumnfound** [comment]
Theme is being updated to include new colours as part of #443. The footer link changes will be investigated as a separate issue in our theme project.

**Comment by autumnfound** [comment]
This is now live! Much more pop with the higher contrast! Thanks for your help+input Stephanie
