### ISSUE TITLE
Update the name of "Jakarta EE Trademark License" to "Jakarta EE Compatibility Trademark License Agreement" in the guidelines

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#394]
**Describe the bug**
To update the name of "Jakarta EE Trademark License" in this link 
https://jakarta.ee/legal/trademark_guidelines/
to "Jakarta EE Compatibility Trademark License Agreement"

**To Reproduce**
1. Go to 'https://jakarta.ee/legal/trademark_guidelines/'
2. Go to the second paragraph where we have this sentence "Participant, Enterprise or Strategic Members of the Jakarta EE WG who are also licensees under the Jakarta EE Trademark License; or"
3. Please change the name of "Jakarta EE Trademark License" to "Jakarta EE Compatibility Trademark License Agreement" (please see the screenshot)

<img width="904" alt="Screen Shot 2019-08-07 at 11 36 47 AM" src="https://user-images.githubusercontent.com/51449073/62636586-ce62c580-b907-11e9-91bd-f409c2683133.png">

**Comment by shabnammayel** [comment]
I will be contacting Sharon C. to confirm the changes to the name

**Comment by sharonlcorbett** [comment]
+1 for the name change of the document.

**Comment by autumnfound** [comment]
This is live
