### ISSUE TITLE
Jakarta EE 8 Pillar Page

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#397]
Pillar page w/o release section
![jakarta8pillar_v2_1](https://user-images.githubusercontent.com/34580334/62949879-0315c780-bdb5-11e9-8bfc-2a2804d06304.png)

Pillar page with release section
![jakarta8pillar_1](https://user-images.githubusercontent.com/34580334/62949878-0315c780-bdb5-11e9-9e20-58e6ff60d519.png)

Backgound Images:
[jakartaee8_images.zip](https://github.com/jakartaee/jakarta.ee/files/3497349/jakartaee8_images.zip)

Icons for webpage:
[jakartaee8_icons.zip](https://github.com/jakartaee/jakarta.ee/files/3497399/jakartaee8_icons.zip)

**Comment by stephanieswart** [comment]
Here is the copy for the landing page. @shabnammayel will confirm when it is finalized:
https://docs.google.com/document/d/1e1amTzRuttQLEM7GO3kUQHGaEk3168TFYdasYBC3fO8/edit?usp=sharing

**Comment by chrisguindon** [comment]
@shabnammayel could you share our timeline for delivering this project whenever you get a chance?

**Comment by shabnammayel** [comment]
Sure, Here is the link:

https://docs.google.com/spreadsheets/d/1SPZyTrbYgQslFGVPre3Gq_qPTE3jLX27w8zIKfUWMk0/edit#gid=1786037210

Please feel free to adjust as u see fit. thanks

**Comment by shabnammayel** [comment]
Content is finalized, please use the link for the updated content https://docs.google.com/spreadsheets/d/1SPZyTrbYgQslFGVPre3Gq_qPTE3jLX27w8zIKfUWMk0/edit#gid=1786037210
Thanks

**Comment by stephanieswart** [comment]
Sorry, here is the updated version of the mockup
![jakarta8pillar_1 (1)](https://user-images.githubusercontent.com/34580334/63108124-275bda80-bf54-11e9-9479-b4243cc3eef1.png)

**Comment by shabnammayel** [comment]
kindly change the tagline to 
An open, community-driven baseline for the evolution of Java enterprise technologies
thanks

**Comment by shabnammayel** [comment]
Please change the URL to Jakarta.ee/release
thanks

**Comment by ericpoirier** [comment]
I updated the path of the Pillars page which is now:

https://deploy-preview-401--jakartaee.netlify.com/release/

Let me know if there are other changes.

Thanks.

**Comment by shabnammayel** [comment]
Can you please centralize the tagline in jumbotron from what we have to:
    An open, community-driven baseline for
 the evolution of enterprise Java technologies

so in two lines and centralized similar to the above, thanks

**Comment by shabnammayel** [comment]
Can you please update Git Repositories number to 129 @ericpoirier thanks

**Comment by stephanieswart** [comment]
Can you please update the social media links to be the following:
**Twitter:** https://twitter.com/JakartaEE
**Facebook:** https://www.facebook.com/JakartaEE
**LinkedIn:** https://www.linkedin.com/groups/13597511/
**YouTube:** https://www.youtube.com/user/EclipseFdn

**Comment by ericpoirier** [comment]
Hi Stephanie and Shabnam,

I updated the number of repos and the social links.

Let me know if there's anything else.

**Comment by ericpoirier** [comment]
> @ericpoirier Can you please centralize the tagline in jumbotron from what we have to:
> An open, community-driven baseline for
> the evolution of enterprise Java technologies
> 
> so in two lines and centralized similar to the above, thanks

Not sure what you mean here.

You would like me to add a line break in the sentence like your example, or you would like the sentence to be centred as well?

**Comment by shabnammayel** [comment]
both please

**Comment by stephanieswart** [comment]
@ericpoirier, here is a mockup of what @shabnammayel is referring to:
![Annotation 2019-09-06 091547](https://user-images.githubusercontent.com/34580334/64430773-fb310680-d086-11e9-8ffd-a0655e66b915.jpg)

I played around with the source code, made 2 paragraphs rather than used a line break and center aligned the paragraphs to achieve this mockup

**Comment by shabnammayel** [comment]
Please add a button under the eBook section as "Download" , it will link to the hubspot landing page https://app.hubspot.com/content/4753786/edit/12738827126/content
the URL of the landing page should be: 
https://www.eclipse.org/lpg2/jakarta/cloud-native-java-eBook

**Comment by ericpoirier** [comment]
Hi Stephanie and Shabnam,

I've made the 2 last changes on the staging page.

https://deploy-preview-401--jakartaee.netlify.com/release/

Let me know if there's anything else.

Thanks.

**Comment by chrisguindon** [comment]
Thanks All! The page is now live!
