### ISSUE TITLE
Add to Community News

### ISSUE THREAD

**Issue by ltran016** [jakartaee/jakarta.ee#399]
1. https://jaxenter.de/jakarta-ee-cloud-native-java-85986

Description: Tanja Obradovic (Jakarta EE Program Manager) and Mikael Barbero (Team Lead) explain what will change in detail with Jakarta EE and how to join the community to help shape the future of Cloud Native Java.

2. https://www.tomitribe.com/blog/jakartaee-39-project-and-where-they-are-at/?utm_content=buffer5a45f&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

Description: If you are wondering what the heck is going on with Java EE and Jakarta EE, watch this awesome 40 minutes video by Triber Jean-Louis Monteiro (@JLouisMonteiro) in collaboration with Jean-Francois James recorded at JNation 2019 in Portugal.

3. http://blog.rahmannet.net/2019/08/why-you-should-attend-jakartaone.html?utm_content=98206930&utm_medium=social&utm_source=twitter&hss_channel=tw-2599580401

Description: If you are a server-side Java developer, you should be attending JakartaOne Livestream. As the name implies, it is a virtual conference to cover all things Jakarta EE (in case you weren't paying attention, Jakarta EE is Java EE transferred to the Eclipse Foundation from Oracle). 

4. https://t.co/AYyNJq69qw?amp=1

Description: Now Available! In the MicroProfile Technical White Paper, Lars Röwekamp 
explains why NOW is the best time for developers & users to adopt the MicroProfile APIs when developing microservices. 

5. https://dzone.com/articles/how-to-develop-open-liberty-microservices-on-opens

Description: Open Liberty is a flexible Java application server. It comes with Eclipse MicroProfile, which is a set of tools and APIs to build microservices.

**Comment by autumnfound** [comment]
This is live
