### ISSUE TITLE
Update the Jakarta EE Banner and Footer

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#404]
Header banner:
Title: Get IBM's new O'Reilly eBook
Subtext: Developing Open Cloud Native Microservices: Your Java Code in Action" is up and available to download!
Button: Download: https://www.ibm.com/account/reg/signup?formid=urx-40233

Footer text:
Join us for JakartaOne Livestream!
You won't want to miss out on this free, one-day virtual conference focused on all things cloud native Java.
Button: Register https://jakartaone.org/

**Comment by autumnfound** [comment]
Are there images for the banners? Or should we maintain current styling and just update copies?

**Comment by shabnammayel** [comment]
We can update the copies and maintain the current styling

**Comment by shabnammayel** [comment]
Please make these changes and plan for this:  ECE Registration and JakartaOne Livestream in rotation on the heather and IBM eBook promo banner and LiveStream in rotations on the footer of jakarta.ee

**Comment by chrisguindon** [comment]
Martin is currently unavailable. I will take over this issue.

**Comment by chrisguindon** [comment]
This request has been merged and the update should appear on production in about 5-10 minutes!
