### ISSUE TITLE
Publish Jakarta EE Meeting Minutes for July 9, 16, 23

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#407]
This is not a bug.

We need to add new entries for Steering meeting minutes on
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached pdf files:
[Minutes of July 23 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3511118/Minutes.of.July.23.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of July 16 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3511119/Minutes.of.July.16.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of the July 9 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3511120/Minutes.of.the.July.9.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

Please let me know if you need anything else.  Thanks

**Comment by autumnfound** [comment]
These minutes are now live
