### ISSUE TITLE
Delete irrelevant content on the "compatible products" page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#409]
Please remove the highlighted content from this page:
https://jakarta.ee/compatibility/

The section below "Stay tuned" is wrongly added to this page:

<img width="1259" alt="Screen Shot 2019-08-18 at 7 40 56 PM" src="https://user-images.githubusercontent.com/51449073/63231917-6ad27500-c1f0-11e9-8c4c-715a3ff2feb2.png">

**Comment by autumnfound** [comment]
This was caused due to a product update changing how subpages are handled by the site. I've updated the layout used for that page to one that doesn't list sub content.

**Comment by autumnfound** [comment]
@shabnammayel this fix is now live
