### ISSUE TITLE
Link to EFSP v1.2 on https://jakarta.ee/about/jesp/

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#415]
Looks like the displayed text should be "hereby adopts the Eclipse Foundation Specification Process v1.2" with an inserted link to https://www.eclipse.org/projects/efsp/?version=1.2[Eclipse

Right now it is hard to read: 

<img width="896" alt="Screen Shot 2019-08-20 at 8 17 14 AM" src="https://user-images.githubusercontent.com/51449073/63346415-ed5b5180-c322-11e9-851a-c067fce792d9.png">

**Comment by autumnfound** [comment]
This is live!
