### ISSUE TITLE
Create prototype of a compatible product 

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#428]
In an effort to be ready for September 10, 2019, we should implement the look and feel of a product example for our Compatible Products page:
https://jakarta.ee/compatibility/index.html

Mock up created by @stephanieswart:

![compatible_productsv2 2 (2)](https://user-images.githubusercontent.com/893942/64200445-86798480-ce5a-11e9-9a6f-1563f38b5a91.png)

Let's use Eclipse Glassfish as an example for this bug and it should be listed under both categories.

Logo: 
https://projects.eclipse.org/sites/default/files/glassfish.png

Text:
Eclipse Foundation | Eclipse GlassFish
Version 5.1.0

Jakarta EE 8 Full Platform Compatible Implementations
[Download](https://www.eclipse.org/downloads/download.php?file=/glassfish/glassfish-5.1.0.zip)

Jakarta EE 8 Web Profile Compatible Implementations
[Download](https://www.eclipse.org/downloads/download.php?file=/glassfish/web-5.1.0.zip)

**Comment by shabnammayel** [comment]
Please take the straight line out from the mockup Eclipse Foundation Eclipse GlassFish
Version 5.1.0

**Comment by shabnammayel** [comment]
please change Full Profile to Full Platform

**Comment by autumnfound** [comment]
This has been pushed live with no content. The default empty functionality set to maintain current functionality.
