### ISSUE TITLE
Add "releases" CFA in header of every page

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#432]
This request should go live on Sept 10.

1. Remove Compatible products from main menu.
2. Add a "Releases" CFA, similar to what we have on www.eclipse.org and that should link to our new /releases page which will be deployed to production at the same time.

**Comment by chrisguindon** [comment]
Here's a preview:
https://deploy-preview-433--jakartaee.netlify.com/

I am also moving Blogs under resources to reduce the number of menu items

**Comment by shabnammayel** [comment]
looks good, thanks

**Comment by chrisguindon** [comment]
Done!
