### ISSUE TITLE
Update Social Media links in jakarta.ee footer

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#435]
Could you please update the Social Media links in jakarta.ee footer to point to Jakarta EE channels rather than our foundation channels:

Twitter: https://twitter.com/JakartaEE
Facebook: https://www.facebook.com/JakartaEE
LinkedIn: https://www.linkedin.com/groups/13597511/
YouTube: https://www.youtube.com/user/EclipseFdn

**Comment by chrisguindon** [comment]
Thanks @autumnfound
