### ISSUE TITLE
Add a 'Get Social' section to the Connect page

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#436]
Title: Get Social
Subtitle: Stay up-to-date with all things Jakarta EE by following us on social media!
Links:
Twitter: https://twitter.com/JakartaEE
Facebook: https://www.facebook.com/JakartaEE
LinkedIn: https://www.linkedin.com/groups/13597511/
YouTube: https://www.youtube.com/user/EclipseFdn

Mockup:
![getsocial](https://user-images.githubusercontent.com/34580334/64374736-6da3d700-cff2-11e9-9ce2-987d34475155.png)

**Comment by autumnfound** [comment]
This is live!
