### ISSUE TITLE
changes in "GitHub issue template" in Get Listed page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#438]
Please change the sentence: 

"Corporate email address to confirm that you are an authorized representative of the company whose product information you are submitting"
To
"The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting"

and also change this: 
A product logo(optional)

to this: 
A product logo with a transparent background in SVG format (optional)

**Comment by autumnfound** [comment]
This is live
