### ISSUE TITLE
Open Liberty as a Compatible Software Product for Jakarta EE

### ISSUE THREAD

**Issue by shighbar** [jakartaee/jakarta.ee#439]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**A corporate email address to confirm that you are an authorized representative of the company whose product information you are submitting**
[shighbar@us.ibm.com](mailto:shighbar@us.ibm.com)

**A product name and version**
[Open Liberty 19.0.0.6](https://openliberty.io)

**A product logo (optional)**
https://openliberty.io/certifications/OL_logo_navy.png

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[IBM Corporation](https://www.ibm.com)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/114

**The URL where Compatible Software Product is available for download**
https://openliberty.io/downloads/

**Comment by chrisguindon** [comment]
Thanks!

Done: https://jakarta.ee/compatibility/
