### ISSUE TITLE
eBook: upload document

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#445]
@chrisguindon 

Please upload the newest version of the Cloud Native Java eBook
[cloud_native_java_ebook.pdf](https://github.com/jakartaee/jakarta.ee/files/3591905/cloud_native_java_ebook.pdf)

**Comment by stephanieswart** [comment]
updated. Please re-upload
[ebook_cloudnative_final.pdf](https://github.com/jakartaee/jakarta.ee/files/3592019/ebook_cloudnative_final.pdf)

**Comment by stephanieswart** [comment]
Updated, please upload again:
[cloud_native_java_ebook.pdf](https://github.com/jakartaee/jakarta.ee/files/3592024/cloud_native_java_ebook.pdf)

**Comment by chrisguindon** [comment]
Done!

**Comment by chrisguindon** [comment]
https://jakarta.ee/documents/insights/cloud_native_java_ebook.pdf
