### ISSUE TITLE
Update the footer & header featured stories

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#447]
title: Jakarta EE 8 is here!
content: Check out all the info and updates about the Jakarta EE 8 release today!
link: jakarta.ee/release
bgImgSrc: ![jakartaee8_background](https://user-images.githubusercontent.com/34580334/64557123-e666a400-d30e-11e9-9c7c-5d61ec6024d9.png)
startDate: 2019-09-10
endDate: 2019-10-07
type: header

header mockup: ![1](https://user-images.githubusercontent.com/34580334/64556896-5cb6d680-d30e-11e9-8287-a777b815bfa3.png)

title: Jakarta EE 8 is here!
content: Check out all the info and updates about the Jakarta EE 8 release today!
link: jakarta.ee/release
bgImgSrc: ![jakartaee8_background](https://user-images.githubusercontent.com/34580334/64557123-e666a400-d30e-11e9-9c7c-5d61ec6024d9.png)
startDate: 2019-09-10
endDate: 2019-10-07
type: footer

footer mockup:
![2](https://user-images.githubusercontent.com/34580334/64557085-d0f17a00-d30e-11e9-8cba-efbe05d369c3.png)

**Comment by autumnfound** [comment]
@stephanieswart while the footer looks alright, the header looks...weird next to jumbotron imho. WDYT?
![image](https://user-images.githubusercontent.com/23018241/64561334-7eb55680-d318-11e9-8a5b-1dfb760b8ed5.png)

**Comment by autumnfound** [comment]
Preview is here: https://deploy-preview-451--jakartaee.netlify.com/
Just refresh until you get the right stories :)

**Comment by stephanieswart** [comment]
I agree it doesn't look good. @autumnfound could you please use this background instead and use blue font?
![jakartaee8_background (1)](https://user-images.githubusercontent.com/34580334/64563790-3305ab80-d31e-11e9-9ffe-bd29db232749.png)

**Comment by autumnfound** [comment]
Preview has been updated, looks better than before

**Comment by stephanieswart** [comment]
Can we make "Sign up to our Newsletter" white?

**Comment by autumnfound** [comment]
Updated!

**Comment by chrisguindon** [comment]
> I agree it doesn't look good. @autumnfound could you please use this background instead and use blue font?

I think the black font looks better and it's easier to read:
https://deploy-preview-451--jakartaee.netlify.com/

Can we revert that font color change?

**Comment by chrisguindon** [comment]
<img width="868" alt="Screen Shot 2019-09-10 at 11 44 55 AM" src="https://user-images.githubusercontent.com/893942/64629050-7add0f00-d3c0-11e9-9d40-55f3bff9b406.png">

<img width="852" alt="Screen Shot 2019-09-10 at 11 45 46 AM" src="https://user-images.githubusercontent.com/893942/64629075-8c261b80-d3c0-11e9-8231-8e7b50d09d88.png">

**Comment by autumnfound** [comment]
I think the black font contrasts better and looks more consistent with the rest of the site as well

**Comment by stephanieswart** [comment]
+1, updating to black is good

**Comment by autumnfound** [comment]
This is live
