### ISSUE TITLE
WildFly 17.0.1.Final as Compatible product of Jakarta EE Full Profile

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#452]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=731

**A product name and version**
WildFly 17.0.1.Final

**A product logo with a transparent background in SVG format (optional)**
https://github.com/wildfly/certifications/blob/EE8/images/wildfly-logo-stacked-100px-2132977.png

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Red Hat

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/116

**The URL where Compatible Software Product is available for download**
https://wildfly.org/downloads

**Comment by chrisguindon** [comment]
Done! The product should appear on the website in the next 10 minutes.
