### ISSUE TITLE
Compatible product request must explicitly state the profile

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#454]
So far, requests are including the profile in the subject of the issue. To make it easier for me, I would like to standardize this question and require folk to state the profile as question in the issue template.

@shabnammayel could you help with the copy?

**Comment by shabnammayel** [comment]
Please add:
"-The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under "
after 
"a product name and version"

**Comment by TanjaObradovic** [comment]
@chrisguindon and @shabnammayel I think this one can be closed as well, correct?

**Comment by chrisguindon** [comment]
+1
