### ISSUE TITLE
Improve Jakarta.EE website navigation

### ISSUE THREAD

**Issue by waynebeaton** [jakartaee/jakarta.ee#457]
We need to make the specification index pages easier to find.

Can we add a link under the "Resources" menu and, perhaps, in the "Innovate with us" block?

**Comment by chrisguindon** [comment]
I know that I am outside of the scope of your request but I really feel that we should completely rethink the navigation on jakarta.ee.

**Comment by chrisguindon** [comment]
@shabnammayel and I are planning to get together tomorrow to chat about the current navigation on jakarta.ee. 

We are hoping to draft some recommendations to make some important pages easier to find.

**Comment by waynebeaton** [comment]
> I know that I am outside of the scope of your request but I really feel that we should completely rethink the navigation on jakarta.ee.

+1

Can you make an incremental improvement to make the specifications a little easier to find in the meantime?

**Comment by chrisguindon** [comment]
Sure, how about this:

Replace the Specification Process link under resources with a link to the specifications?

If we do so, should we move the following content on the specification page?

Specification Process
Talks & presentations:

- [Introducing the EFSP](https://jakarta.ee/resources/introducing-the-efsp-ece-2018.pdf)

**Comment by waynebeaton** [comment]
> Replace the Specification Process link under resources with a link to the specifications?

That works.

> If we do so, should we move the following content on the specification page?

In principle, yes. But these links are going to be pretty useless if they're at the bottom of the page.

The "Specification Process" link already appears in the right nav. That's really all that we need. I'm thinking that maybe the presentation link might fit at the bottom of the /about/jesp/ (but we need to be sure to delineate the presentation link(s) from the spec process itself; i.e., the links are not part of the JESP).

**Comment by chrisguindon** [comment]
@shabnammayel and I made some changes to the previous sitemap. 

This is a draft and we would like some feedback on the proposed sitemap before we make a final decision. 

1. About
-- [About Jakarta EE](https://jakarta.ee/about/)
-- [Connect](https://jakarta.ee/connect/)
-- [Charter](https://www.eclipse.org/org/workinggroups/jakarta_ee_charter.php)
-- [Technical Direction](https://www.eclipse.org/ee4j/direction.php)
-- [Trademark Guidelines](https://jakarta.ee/legal/trademark_guidelines/)
-- [Frequently Asked Questions](https://jakarta.ee/about/faq/)
-- [Specification Process](https://jakarta.ee/about/jesp/)
-- [Meeting Minutes](https://jakarta.ee/meeting_minutes/)

---
2. [Projects](https://projects.eclipse.org/projects/ee4j)
Eventually, we would link to a page on jakarta.ee but this page is currently a work in progress: https://github.com/jakartaee/jakarta.ee/pull/371

-- OR --

2. Specifications (Based off @ggam [comment](https://github.com/jakartaee/jakarta.ee/issues/457#issuecomment-530996882))
-- [List of specifications](https://jakarta.ee/specifications/)
-- [Projects](https://projects.eclipse.org/projects/ee4j)

---

3. [Compatible Products](https://jakarta.ee/compatibility/)

4. [Membership](https://jakarta.ee/membership/)

5. Resources
-- Getting Started *This page will need to be created first.
-- [Specifications](https://jakarta.ee/specifications/)
-- [Video](https://jakarta.ee/resources/#videos) 
-- [Infographic](https://jakarta.ee/resources/#infographics)
-- [Survey](https://jakarta.ee/resources/#surveys)
-- [Blog](https://jakartablogs.ee)
-- [Newsletter](https://jakarta.ee/newsletter/)

6. Releases [CFA: Orange Button]

**Comment by ggam** [comment]
I generally like the proposal. Two comments:
* We'll need a documentation page. We might want to rename "Getting Started" to "Documentation", and then add a big button on the front page saying "Getting Started" and linking to that same page.
* New users will search for a Download page and won't find it. Jakarta EE is about specifications and compatible products, but we need to educate users. Similar to the "About JEE" page on the Java EE website (https://javaee.github.io/javaee-spec/JEE), I popose we add a Download page that briefly explains Jakarta EE cannot be downloaded, but you need to look for a compatible product.

**Comment by chrisguindon** [comment]
The PR that I posted is a quick fix. 

I am adding a link to the specification page on the homepage jumbotron:
https://deploy-preview-473--jakartaee.netlify.com/ 

I don't consider this PR to be a long term fix for this issue.

**Comment by chrisguindon** [comment]
I am renaming this bug since this initial issue was addressed by adding a link in the jumbotron.

**Comment by TanjaObradovic** [comment]
@chrisguindon this one can be closed

**Comment by chrisguindon** [comment]
@TanjaObradovic I am re-opening this issue! I think we still have some work do to around the navigation of the jakarta.ee website.

**Comment by ericpoirier** [comment]
@chrisguindon @TanjaObradovic now that we have updated the main menu while implementing the redesign of Jakarta EE, is this issue still needed?

**Comment by chrisguindon** [comment]
I would argue that this has been covered by the website re-design!

I am closing this bug! @TanjaObradovic Please re-open if you think we still need this issue!
