### ISSUE TITLE
Add news items to community news

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#458]
Jakarta EE now operates under open community driven process
 After transitioning from Oracle to the Eclipse Foundation in 2017, Jakarta EE (previously known as Java EE), has reached another major milestone. 
https://sdtimes.com/java/jakarta-ee-now-operates-under-open-community-driven-process/

Enterprise Java spec packs bags, ready for new life under assumed name – Jakarta
Enterprise Java, known as Java Enterprise Edition 8 (Java EE 8) under Oracle's implementation of the platform specification, has finally packed up and moved out of Big Red's basement under a new name, so it won't bear the burden of its heritage.
https://www.theregister.co.uk/2019/09/10/java_spec_jakarta/

The Future is Now
Jakarta EE 8 is finally here! It heralds a new era for Enterprise Java, as finally the community can look forward to the platform’s faster development.
https://jaxenter.com/jakarta-ee-8-release-interview-eclipse-161955.html

Jakarta EE 8 is sprinting towards an exciting future for enterprise Java
After what seemed like eternity, the time has finally come – the long awaited first release of Jakarta EE is now officially in the hands of the public.
https://jaxenter.com/jakarta-ee-8-future-enterprise-java-161984.html

Open Source Enterprise Java Specification Jakarta EE 8 launches
Java Community and Eclipse Foundation introduce the designated Java EE successor, including Web Profiles, TCKs and Certified Eclipse GlassFish 5.1.
https://www.heise.de/developer/meldung/Quelloffene-Enterprise-Java-Spezifikation-Jakarta-EE-8-geht-an-den-Start-4519179.html

Java finally goes all in on open source with the Jakarta EE 8 release
The Eclipse Foundation has announced the release of the Jakarta EE 8, the first truly open-source, vendor-neutral version of Java Enterprise Edition.
https://www.zdnet.com/article/java-finally-goes-all-in-on-open-source-with-the-release-of-jakarta-ee-8/

Eclipse Foundation Delivers on Jakarta EE Promise
The Eclipse Foundation today announced the general availability of Jakarta Enterprise Edition (EE) 8 Full Platform and Web Profile specifications and associated technology compatibility kits (TCKs).
https://devops.com/eclipse-foundation-delivers-on-jakarta-ee-promise/

The Eclipse Foundation Releases Jakarta EE 8 Specifications
The Eclipse Foundation today announced during the JakartaOne Livestream virtual conference the release of the Jakarta EE 8 Full Platform and Web Profile specifications and related Technology Compatibility Kits (TCKs). 
https://www.linux.com/news/the-eclipse-foundation-releases-jakarta-ee-8-specifications/

Java EE Move to Eclipse foundation Makes Way for Cloud Native Java 
The Eclipse Foundation has finally completed the transition of Java Enterprise Edition (EE) over to Jakarta with the release of the Jakarta EE 8 specification. 
https://thenewstack.io/java-ee-move-to-eclipse-foundation-makes-way-for-cloud-native-java/

Eclipse Jakarta EE Arrives
Two years after taking over Java EE from Oracle, the Eclipse Foundation has shipped its implementation of Java EE 8
https://www.infoworld.com/article/3437783/eclipse-jakarta-ee-arrives.html

**Comment by chrisguindon** [comment]
thanks @autumnfound
