### ISSUE TITLE
Add to annoucements

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#459]
Welcome to the Future of Cloud Native Java
Today, with the release of Jakarta EE 8, we’ve entered a new era in Java innovation.
https://blogs.eclipse.org/post/mike-milinkovich/welcome-future-cloud-native-java

Update for Jakarta EE community: September 2019
We hope you’re enjoying the Jakarta EE monthly email update, which seeks to highlight news from various committee meetings related to this platform.
https://blogs.eclipse.org/post/tanja-obradovic/update-jakarta-ee-community-september-2019

**Comment by chrisguindon** [comment]
thanks @autumnfound
