### ISSUE TITLE
Update the footer & header featured stories

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#470]
Right now in the heather we have:
- Jakarta EE 8 is here!
- Join us for JakartaOne Livestream!

and in the footer only:
-get IBM’s new O’Reilly eBook
- sign up to our Newsletter

In the heather, can we remove:
- Join us for JakartaOne Livestream!

and in the footer:
Remove: -get IBM’s new O’Reilly eBook
Remove: - Join us for JakartaOne Livestream!
Add: - Jakarta EE 8 is here!
Keep: - sign up to our Newsletter

**Comment by shabnammayel** [comment]
Please remove the word: "today"from the blurb about "Jakarta EE 8 is here!":

please remove today in this sentence: Check out all the info and updates about the Jakarta EE 8 release today!

**Comment by autumnfound** [comment]
this is live
