### ISSUE TITLE
Remove Microsoft from jakarta.ee

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#472]
Please remove the following instances where Microsoft is mentioned:
Join Us
Working together, the world’s Java ecosystem leaders, including Fujitsu, IBM, Microsoft, Oracle, Red Hat, and Tomitribe, are advancing Java EE and Jakarta EE to support moving mission-critical applications and workloads to the cloud.

Remove logo from this page: https://jakarta.ee/membership/members/

**Comment by autumnfound** [comment]
Has there been changes in the marketing committee (which contains a MS employee), and do we want to remove the testimonial of Bruno Borges (An MS employee)?

**Comment by stephanieswart** [comment]
Yes, please remove the quote as well. Thanks!

**Comment by autumnfound** [comment]
For clarification, should I leave the marketing committee for now?

**Comment by stephanieswart** [comment]
Could you please add a link as to what you're referring to?
Thank you

**Comment by autumnfound** [comment]
https://jakarta.ee/about/#marketing-brand-committee

At the bottom of the content, tab includes `Theresa Nguyen - Microsoft Elected Participant Representative`

**Comment by stephanieswart** [comment]
Yes, please remove her. Thanks!

**Comment by autumnfound** [comment]
This is live!
