### ISSUE TITLE
typos in dependencies version for jms and persistance

### ISSUE THREAD

**Issue by ah1508** [jakartaee/jakarta.ee#474]
Problems in jakarta ee BOM for persistence and JMS : 

jakarta.jakartaee-bom : 

```xml
<dependency>
    <groupId>jakarta.persistence</groupId>
    <artifactId>jakarta.persistence-api</artifactId>
    <version>${jakarta-persistence-api.version}</version>
</dependency>
```

and 

```xml
<dependency>
    <groupId>jakarta.jms</groupId>
    <artifactId>jakarta.jms-api</artifactId>
    <version>${jakarta.messaging-api.version}</version>
</dependency>
```
but in parent POM (jakartaee-api-parent) the 2 properties do not exist. Instead :

```xml
<jakarta.persistence-api.version>2.2.3</jakarta.persistence-api.version>
<jakarta.jms-api.version>2.0.3</jakarta.jms-api.version>
```

**Comment by chrisguindon** [comment]
@ah1508 What page on the website are you reporting an issue for?

**Comment by ggam** [comment]
I think this issue is for the Jakarta EE API tracker: https://github.com/eclipse-ee4j/jakartaee-api/blob/master/jakartaee-bom/pom.xml#L157

@ah1508 would you please reopen the issue there?

**Comment by chrisguindon** [comment]
Thanks @ggam 

Closing this issue.

**Comment by mikethecalamity** [comment]
@chrisguindon It looks like `8.0.0` is still bad in Maven: https://mvnrepository.com/artifact/jakarta.platform/jakarta.jakartaee-bom/8.0.0

![image](https://github.com/jakartaee/jakarta.ee/assets/4815011/ad4d082c-0da9-4304-ba9b-0ca1d1041a29)

Is it possible to publish a new `8.0.0` or even an `8.0.1`?

**Comment by chrisguindon** [comment]
@mikethecalamity I am not the right person that can help here.

@ggam Can you help reply to @mikethecalamity question, please?
