### ISSUE TITLE
Link to requests from compatible products page

### ISSUE THREAD

**Issue by ggam** [jakartaee/jakarta.ee#475]
**Is your feature request related to a problem? Please describe.**
The compatible products page doesn't link to the request issue that proofs the implementation is compatible. It only lists accepted products and their download page.

**Describe the solution you'd like**
Link to the compatibility request issue for each product. Por example, for WildFly: https://github.com/jakartaee/jakarta.ee/issues/452

**Additional context**
Jakarta EE aims to be transparent. We need to make it easy for people to verify compatibility requests.

**Comment by shabnammayel** [comment]
+1 @chrisguindon can we add the text: "Compatibility Request" under the "Download" button of each product in the [compatible products ](https://jakarta.ee/compatibility/)page?

then link the Compatibility Request issue related to that product to the text. 

e.g. under Download button of WildFly, add "[Compatibility Request](https://github.com/jakartaee/jakarta.ee/issues/452)"

and under Download button of Open Liberty, add "[Compatibility Request](https://github.com/jakartaee/jakarta.ee/issues/439)"

**Comment by shabnammayel** [comment]
and under Download button of GlassFish WebProfile, add "[Compatibility Request](and under Download button of Open Liberty, add "Compatibility Request")"

and under Download button of GlassFish FullPlatform, add "[Compatibility Request](https://github.com/jakartaee/jakarta.ee/issues/440)"

**Comment by chrisguindon84** [comment]
@shabnammayel are you thinking of something like this?

![Screen Shot 2019-09-25 at 12 09 04 PM](https://user-images.githubusercontent.com/666503/65618982-4d31c180-df8d-11e9-93dd-d50861c853b9.png)

**Comment by ggam** [comment]
I think the "compatibility request" text might be misread as "request compatibilty". What about "Proof of compatibily"?

**Comment by chrisguindon** [comment]
> I think the "compatibility request" text might be misread as "request compatibilty". What about "Proof of compatibily"?

+1 for Proof of compatibility

**Comment by shabnammayel** [comment]
+1

**Comment by chrisguindon** [comment]
Preview:
https://deploy-preview-482--jakartaee.netlify.com/compatibility/

**Comment by chrisguindon** [comment]
This was committed last week.
