### ISSUE TITLE
Please remove "releases" button from https://jakarta.ee/release/ 

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#479]
This button returns to the same page when you're on https://jakarta.ee/release/ 
Please remove the button from the home page.

Also, I do not think the button should include a download icon as again, it only returns you to the home page. Maybe we should change it from "Releases" to "Home"

**Comment by chrisguindon** [comment]
To clarify the request:

I think this is is something we should fix in the base theme. This should be a feature that we can turn on where the CFA button is hidden if the user is on the page the CFA is linking to.

www.eclipse.org/downloads is a good example.

**Comment by autumnfound** [comment]
Working PR: EclipseFdn/hugo-solstice-theme#85

**Comment by chrisguindon** [comment]
Fix committed! thanks @autumnfound
