### ISSUE TITLE
Publishing Marketing Committee meeting minutes September 12

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#483]
This is not a problem; we need to add new entries for Marketing meeting minutes on
https://jakarta.ee/meeting_minutes/

under section
Jakarta EE Marketing Committee

in the same way as other files with just adding a date with the link.
e.g, June 25, 2018 (pdf)

I have attached the latest one:

[Jakarta EE Marketing Committee Meeting - September 12, 2019 (1).pdf](https://github.com/jakartaee/jakarta.ee/files/3659702/Jakarta.EE.Marketing.Committee.Meeting.-.September.12.2019.1.pdf)

**Comment by chrisguindon** [comment]
Done! Thanks @autumnfound
