### ISSUE TITLE
Include the short video interviews to the Jakarta.ee/release page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#486]
Please add the following videos: 

Reza: https://www.youtube.com/watch?v=ebja1buuorA&list=PLy7t4z5SYNaRKVxm1UolSf9wBsVi7wZ_v

Josh: https://www.youtube.com/watch?v=4ct05M4ywek&list=PLy7t4z5SYNaRKVxm1UolSf9wBsVi7wZ_v&index=2

Ivar: https://www.youtube.com/watch?v=9Itg99QaOLc&list=PLy7t4z5SYNaRKVxm1UolSf9wBsVi7wZ_v&index=3

Tanja: https://www.youtube.com/watch?v=v11r-GxIuys&list=PLy7t4z5SYNaRKVxm1UolSf9wBsVi7wZ_v&index=4 (edited) 
 to the Jakarta.ee/release page, under the section "Powered by Participation"

@stephanieswart has already created the mockups for these when we submitted the mockups for the release page I think. thanks

**Comment by chrisguindon** [comment]
Thanks for the pr @ericpoirier
