### ISSUE TITLE
Publish Steering Committee Mtg Mins: 7/30, 8/6, 8/13, 8/20, 8/27, 9/3

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#488]
This is not a bug.

We need to add new entries for Steering meeting minutes on
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached pdf files:
[Minutes of July 30 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3695157/Minutes.of.July.30.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of August 6 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3695158/Minutes.of.August.6.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of August 13 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3695159/Minutes.of.August.13.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of August 20 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3695161/Minutes.of.August.20.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of August 27 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3695162/Minutes.of.August.27.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes for September 3 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3695163/Minutes.for.September.3.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by chrisguindon** [comment]
@will-lyons A change for this has been committed. The website should update in the next few minutes!

Thanks @autumnfound for pushing a patch for this request!
