### ISSUE TITLE
Please add events to event list

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakarta.ee#489]
JVM-Con 
Köln, Germany
25-11-2019
https://www.jvm-con.de/

Jakarta EE / MicroProfile Microservices
Munich Airport
10-12-2019
http://workshops.adam-bien.com/microservices.htm

*Change event on December 11th title from Jakarta EE, Eclipse Microprofile and Clouds to 
Building cloud applications with Jakarta EE and MicroProfile

**Comment by chrisguindon** [comment]
Event added and committed!
