### ISSUE TITLE
Payara 5.193.1 as a Compatible product of Jakarta EE Full Profile

### ISSUE THREAD

**Issue by smillidge** [jakartaee/jakarta.ee#492]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=1238

**A product name and version**
Payara Server 5.193.1

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Full Platform 

**A product logo with a transparent background in SVG format (optional)**
GH does not accept SVG attachments on issues so PNG attached below.

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Payara Services Limited

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/119

**The URL where Compatible Software Product is 
available for download**
https://www.payara.fish/software/downloads/

**Comment by smillidge** [comment]
![payara-server-logo](https://user-images.githubusercontent.com/939073/66403054-d3162980-e9dd-11e9-82ca-f3e60cb2d28a.png)

**Comment by chrisguindon** [comment]
@smillidge We need to update our documentation but you should be able to send us a svg by including it in a zip file.

**Comment by smillidge** [comment]
[server-logo-on-white-transparent-RGB.zip](https://github.com/jakartaee/jakarta.ee/files/3703123/server-logo-on-white-transparent-RGB.zip)

**Comment by chrisguindon** [comment]
@smillidge Thanks for posting this request!

@autumnfound was unable to use the svg and we decided to use the png since we've been using a png for other products. 

We will need to update the issue template to reflect this change.
