### ISSUE TITLE
Posting Payara's press release on Jakarta.ee Announcement section

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#497]
Please post Payara's press release (see attachment) on Jakarta.ee Announcements section:

[Payara Server is Jakarta EE 8 Compatible Press Release_v2_10.8.19_JN DTS edits.docx](https://github.com/jakartaee/jakarta.ee/files/3704918/Payara.Server.is.Jakarta.EE.8.Compatible.Press.Release_v2_10.8.19_JN.DTS.edits.docx)

They are planning to make the announcement tomorrow at 7a.m. ET.but I mentioned that we won't be done by then and will do it over the course of tomorrow depending on webdev. 

Title: Payara Server is Jakarta EE 8 Compatible

Copy: Payara Services and the Eclipse Foundation, Inc. today announced the application server ,Payara Server, a Jakarta EE 8 compatible implementation.

And also post their blog on Announcement section:
https://blog.payara.fish/payara-server-is-jakarta-ee-compatible

**Comment by chrisguindon** [comment]
thanks @autumnfound
