### ISSUE TITLE
Upload Membership Prospectus 

### ISSUE THREAD

**Issue by ltran016** [jakartaee/jakarta.ee#503]
Please upload the Jakarta EE Membership Prospectus - next to the flyer button (prospectus goes first): 
[Jakarta_Membership_Prospectus_final.pdf](https://github.com/jakartaee/jakarta.ee/files/3729419/Jakarta_Membership_Prospectus_final.pdf)

**Comment by ltran016** [comment]
Also, please link to it in the Contact Us form: https://accounts.eclipse.org/contact/membership/jakarta-ee

Add: "To learn more about the benefits of joining the Jakarta EE Working Group, download the [Jakarta EE Membership Prospectus]" before the Key Benefits section.

Change: "If you are looking for more information on all of the benefits of Eclipse Foundation memberships, download the Membership Prospectus" to "If you are looking for more information on all of the benefits of Eclipse Foundation memberships, download the Eclipse Foundation Membership Prospectus"

**Comment by autumnfound** [comment]
Both changes are live! Sorry for the delay
