### ISSUE TITLE
Adding a quote in the https://jakarta.ee/membership/

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#506]
please add the following quote from David Blevins:

In 20 years working in open source and Java standards I've never seen such a truly diverse and equally shared effort as that required to ship Jakarta EE 8.  Source code has been donated, but what emerged is a community that bravely accepts change, innovates open processes and repeatedly choses shared victory over individual success.  When we look back in 10 years at all we've accomplished in Jakarta, everyone will agree this was the singular moment in time that shaped our future.

**-David Blevins, Founder and CEO of Tomitribe**

in this pages: https://jakarta.ee/membership/

**Comment by aeiras** [comment]
Thank you both! :)

**Comment by chrisguindon** [comment]
PR was committed!
