### ISSUE TITLE
Please include WildFly 18.0.0.Final as both Web Profile + Full Platform compatible

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#508]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://www.eclipse.org/membership/showMember.php?member_id=731

**A product name and version**

WildFly 18.0.0.Final

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**

Both

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

https://github.com/wildfly/certifications/blob/EE8/images/wildfly-logo-stacked-100px-2132977.zip?raw=true

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Red Hat

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/121
https://github.com/eclipse-ee4j/jakartaee-platform/issues/120

**The URL where Compatible Software Product is available for download**

https://wildfly.org/downloads

**Comment by autumnfound** [comment]
I've created a PR, removing the previous version of WildFly and added this version to both profiles. A preview of the site will soon be available if you'd like to see the update.

**Comment by autumnfound** [comment]
This is live!
