### ISSUE TITLE
Add Duke's Choice Award logo to Jakarta.ee website

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakarta.ee#510]
On Sep 10, 2019, Jakarta EE was awarded a 2019 Duke's Choice Award in recognition for open source contributions to the Java ecosystem.

Please add the 2019 Duke's Choice Award Winner logo to the Jakarta.ee homepage similar to https://microprofile.io/.

**Comment by ThabangMash** [comment]
Adding Duke Award logo
![duke award](https://user-images.githubusercontent.com/40362390/68084086-f24a8000-fdfe-11e9-86b6-5b73cf04dfe9.png)

**Comment by chrisguindon** [comment]
As discussed, Laura will create a mock for how this is going to look on the website before we implement the update.

**Comment by ltran016** [comment]
Mock Up:
![JakartaEE_Dukes](https://user-images.githubusercontent.com/48952273/68145388-acc3ab00-ff03-11e9-9122-51ac3ca8a493.png)

**Comment by ltran016** [comment]
Please link the button to: https://www.globenewswire.com/news-release/2019/09/17/1916531/0/en/The-Eclipse-Foundation-Wins-Duke-s-Choice-Award-for-Open-Source-Contributions-to-the-Java-Ecosystem.html

**Comment by ltran016** [comment]
Mockup v2
![JakartaEE_Dukes (3)](https://user-images.githubusercontent.com/48952273/68146746-a682fe00-ff06-11e9-9641-79897c6882e2.png)

**Comment by ericpoirier** [comment]
Hi Laura,

I created a PR to add the Duke's choice award image a link on the home page which is also on staging:

https://deploy-preview-516--jakartaee.netlify.com/

I decided to put the title right between the image and the link. It felt like it makes more sense there.

Let me know if you'd like to change anything.

**Comment by ltran016** [comment]
Looks great, thanks!

**Comment by ericpoirier** [comment]
Hi Laura, this is now live on production.
