### ISSUE TITLE
Publish Steering Committee Minutes - October 15 Meeting 

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#519]
This is not a bug.

We need to add new entries for Steering meeting minutes on
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached a pdf file:
[Minutes of October 15 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3810676/Minutes.of.October.15.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by autumnfound** [comment]
This is live! https://jakarta.ee/meeting_minutes/#steering_committee
