### ISSUE TITLE
Link to Developer Survey Landing Page

### ISSUE THREAD

**Issue by ltran016** [jakartaee/jakarta.ee#522]
Please link this landing page to the link for the 2019 developer survey under resources. Thanks!

http://jakarta-4753786.hs-sites.com/jakarta-ee-2019-developer-survey

**Comment by autumnfound** [comment]
Something to keep in mind with this change. This is an external site, with an _incredibly_ suspicious URL. This may drive some people away from requesting the PDF as they may think that the URL has somehow been hijacked. Is there an alternative way to include the request form on a page?

**Comment by chrisguindon** [comment]
Martin, please use http://www.eclipse.org/lpg2/jakarta/jakarta-ee-2019-developer-survey

**Comment by autumnfound** [comment]
I've uploaded a patch for this, using Christopher's link, and adding a note under the link that its provided through an external vendor. Please see below for a preview of the change! 

https://deploy-preview-528--jakartaee.netlify.com/resources/#surveys

**Comment by autumnfound** [comment]
This is live! https://jakarta.ee/resources/#surveys
