### ISSUE TITLE
Adding the bulletin announcement under Jakarta.ee announcement section

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#523]
Title: Election Updates, Fall 2019

Copy: We are happy to announce Arjan Tijms as Elected Committer representative for the Steering Committee who is acclaimed to this role, as the only nominee. The seats at Marketing and Brand Committee will stay empty until the next election period since we did not have nominees

**Comment by autumnfound** [comment]
This is live!
https://jakarta.ee/
https://jakarta.ee/news/announcements/2019/11/06/election-updates-fall-2019/
