### ISSUE TITLE
[Jakarta EE website update] Remove G+ 

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#529]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/10731224/68903120-f32cbd00-06ee-11ea-870f-45b83eb7a62a.png">

**Comment by autumnfound** [comment]
Hi Amelia! I've checked the page + the code but I couldn't find anything for G+ (see below screenshot). Could you load the site in either a private window or clear your browser cache, refresh, and let me know if you still have the issue? Thanks!

![image](https://user-images.githubusercontent.com/23018241/69250984-a7f72c00-0b7e-11ea-986c-753c862005c2.png)

**Comment by aeiras** [comment]
Hola Martin, 

Just checked and the G+ is finally gone! :) thanks for the follow up.
