### ISSUE TITLE
Feature The Jakarta EE monthly update call under Jakarta.ee, the announcement section

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#531]
Here is the schedule sheet of all upcoming Jakarta EE monthly update calls:

https://docs.google.com/spreadsheets/d/1t6av4do76hlUGfBeErbo74VJldV7XlRoQIxe08Y3d6o/edit#gid=0

I have included the date that they should be featured under the announcement section of Jakarta.ee and also the title and copy of each announcement, thanks

**Comment by shabnammayel** [comment]
Excel file: [Jakarta EE Update Call Schedule.xlsx](https://github.com/jakartaee/jakarta.ee/files/3865967/Jakarta.EE.Update.Call.Schedule.xlsx)

**Comment by chrisguindon** [comment]
The plan is to create news items with a date in the future. We will leverage our cron jobs to publish these news item automatically.

If the plan is to publish an article on November 26, we should set the date to the previous day at 11pm to make sure that the article is available to be published when the cron job starts:

For example: 
 2019-11-25T23:00:00-05:00

**Comment by chrisguindon** [comment]
@shabnammayel thanks for uploading the file to this issue!

**Comment by autumnfound** [comment]
This is live! The first entry should become live on the 3rd of December at midnight.

**Comment by shabnammayel** [comment]
Please note that The Jakarta EE update call in January 8 is reschedule to January 15th. so can you please reflect this change in featuring this under Announcement. So the date to be featured under announcement should be changed from 31 Dec, 2019 to January 7. thanks

**Comment by autumnfound** [comment]
This is live! Thanks @ericpoirier!
