### ISSUE TITLE
Add a section for Jakarta EE Monthly Update Calls in Jakarta.ee/connect

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#532]
To promote The Jakarta EE monthly update calls, please create a section in the Jakarta.ee/connect after the "Updates" section:

Title: Jakarta EE Monthly Update Calls

Copy: Join the Jakarta EE Monthly Update calls  to learn more about Jakarta EE-related plans
Subscribe (link to [Jakarta EE Community Calendar](https://calendar.google.com/calendar/embed?src=eclipse-foundation.org_3281qms6riu4kdf354jn5idon0%40group.calendar.google.com&ctz=America%2FToronto) )

**Comment by autumnfound** [comment]
This is live!
