### ISSUE TITLE
Publish Steering Committee Minutes - October 29 and Nov 5 Meetings

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#533]
This is not a bug.

We need to add new entries for Steering meeting minutes on
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached pdf files
[Minutes of October 29 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3866934/Minutes.of.October.29.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of November 5 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3866932/Minutes.of.November.5.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

:

**Comment by autumnfound** [comment]
This is live!
