### ISSUE TITLE
Adding the link to presentations in the Jakarta EE slideshare in "Resources" section of Jakarta.ee

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#540]
Please add the link to  presentations of the Jakarta EE slideshare account in "Resources" section of Jakarta.ee under the "Infographic" section of the jakarta.ee/resources/:

Title: Presentations

Copy: [Jakarta EE presentations](https://www.slideshare.net/Jakarta_EE)

**Comment by autumnfound** [comment]
This is live!
