### ISSUE TITLE
Add Jakarta Tech Talk under Announcements

### ISSUE THREAD

**Issue by ltran016** [jakartaee/jakarta.ee#546]
Please help promote upcoming Jakarta Tech Talk under announcements. 

Title: Best practices for modern Enterprise Java projects - Jakarta Tech Talk
Description: Join us for Sebastian Daschner's Jakarta Tech Talk on Dec 10! 
Link: https://www.crowdcast.io/e/dec10_19_jakartatechtalks

**Comment by autumnfound** [comment]
This is live!
