### ISSUE TITLE
Add ™ on jakarta.ee website 

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#548]
We should  add the  ™ (trademark) symbol on our jakarta.ee website!

Once this trademark is officially registered, we will want to replace the ™ (trademark) symbol with the  ® (registered trademark) symbol. Please take this into consideration while implementing the required changes.

With the help of Sharon M, @ChristieWittEclipse, and @shabnammayel, we came up with a list of action items for the website:

- Replace the jakarta.ee logo on the website with a version that include  the ™ (trademark) symbol. (@ChristieWittEclipse will create the logo and she will upload it here once it's ready!)

- Replace the Call to action button text in the header to say Download instead of Release.

- On https://jakarta.ee/release: Please replace the call to action button in the jumbotron to say **Download Compatible Product** instead of Compatible Product.

- On https://jakarta.ee/compatibility/ , please add the Jakarta™ compatible logo on the right side of the introduction text (before the list of products).

- Add the ™ (trademark) symbol on every page where the name Jakarta™ EE is used in the jumbotron. 

-  Update page title of https://jakarta.ee/compatibility/ from Compatible Products to  Jakarta™ EE Compatible Products

**Important:** The ™ (trademark) symbol must be included in this order: **Jakarta™ EE**

**Comment by shabnammayel** [comment]
TM notations that are added are very big, can we make them a lot smaller? thanks

**Comment by waynebeaton** [comment]
The plan LGTM, but I defer to Sharon's judgement on the details.

**Comment by shabnammayel** [comment]
I think adding the TM on The first Jakarta word in the jumbotron should be sufficient, do we need to use it in the buttons and banner too?

**Comment by ChristieWittEclipse** [comment]
[Jakarta Logos for site.zip](https://github.com/jakartaee/jakarta.ee/files/3929182/Jakarta.Logos.for.site.zip)
I've attached the logos including "TM" and "R" symbols.

**Comment by autumnfound** [comment]
@ChristieWittEclipse could you send color versions of the logo? I need to put the logo on white background. Thanks!

**Comment by ChristieWittEclipse** [comment]
See attached!

[Jakarta-EE-clr-TM-R.zip](https://github.com/jakartaee/jakarta.ee/files/3932883/Jakarta-EE-clr-TM-R.zip)

**Comment by autumnfound** [comment]
@shabnammayel I've done a quick hack of values to test size of the TM before making larger changes to accomodate it. What do you think? Should we make it smaller, or does this match what you were thinking?

![image](https://user-images.githubusercontent.com/23018241/70335698-ca8f7300-1815-11ea-974e-0be20183bfa6.png)

**Comment by ChristieWittEclipse** [comment]
@shabnammayel @autumnfound I think it would be best if we shrink "TM" to about 75% of its current size and ensure that it's aligned with the top of the other "Jakarta" letters, but Shabnam, let me know if you agree before @autumnfound makes further edits. (see screenshot)
![70335698-ca8f7300-1815-11ea-974e-0be20183bfa6 png  1198×562 ](https://user-images.githubusercontent.com/58480647/70337243-aa14e800-1818-11ea-9f77-11a22f9830e4.png)

**Comment by autumnfound** [comment]
I think that it looks nice aligning it and shrinking it. Heres a quick screenshot of what that would look like. 

![image](https://user-images.githubusercontent.com/23018241/70339266-88b5fb00-181c-11ea-87c6-40ecc65a031b.png)

**Comment by ChristieWittEclipse** [comment]
Looks perfect!

**Comment by ChristieWittEclipse** [comment]
[Jakarta Compatible Logos for site.zip](https://github.com/jakartaee/jakarta.ee/files/3933426/Jakarta.Compatible.Logos.for.site.zip)
@autumnfound See attached Jakarta compatible logos as requested. They are only available in color when I download the files, so let me know if you need them in white.

**Comment by autumnfound** [comment]
Hey guys, live preview is up! If you guys want to look through the changes on the site, you can use the following URL: https://deploy-preview-552--jakartaee.netlify.com/

**Comment by shabnammayel** [comment]
+1 looks good to me too, thanks

**Comment by chrisguindon** [comment]
@autumnfound are now live on production!

**Comment by chrisguindon** [comment]
Thank you everyone!
