### ISSUE TITLE
Add under Events

### ISSUE THREAD

**Issue by ltran016** [jakartaee/jakarta.ee#551]
Devnexus 
Atlanta, GA
Feb 19-21 2020 
https://devnexus.com/

Javaland
Phantasialand, Brühl
March 17-19
https://www.javaland.eu/en/home/

KubeCon + CloudNativeCon Europe
Amsterdam, The Netherlands
March 30-April 2 2020
https://events19.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2020/

**Comment by chrisguindon** [comment]
Thanks!
