### ISSUE TITLE
Publish Steering Committee Minutes - November 12 and 19

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#554]
This is not a bug.

We need to add new entries for Steering meeting minutes on
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached pdf files
[Minutes of November 19 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3941691/Minutes.of.November.19.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of November 12 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3941692/Minutes.of.November.12.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by autumnfound** [comment]
This is live! Thanks @ericpoirier!
