### ISSUE TITLE
[IO website: Tab improvement] ABOUT

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#555]
[about tab]https://jakarta.ee/about/)

I recommend that after the Cmte inventory section, a Committers list gets git_automatically populated in the page. if it needs a human to police it, lets figure out other forms to make it "not human" debt.

**Comment by TanjaObradovic** [comment]
@aeiras considering we have moved Committees and information about them to https://jakarta.ee/committees/
can we close this issue? Or this is suggesting something else.

**Comment by TanjaObradovic** [comment]
I will close this one, Amelia let me know if any concerns.
