### ISSUE TITLE
Add under community news

### ISSUE THREAD

**Issue by ltran016** [jakartaee/jakarta.ee#556]
Kickstart a Jakarta EE 8 Application
Jakarta EE 8 starter is a boilerplate project to help you to bootstrap a new Java EE 8/Jakarta EE 8 application in seconds.
https://medium.com/@hantsy/kickstart-a-jakarta-ee-8-application-d1b6ff32213b

**Comment by autumnfound** [comment]
This is live! Thanks @ericpoirier!
