### ISSUE TITLE
Replace all the ™ symbol with the ® (registered) symbol when using Jakarta

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#557]
Sharon Macdonald has confirmed that we can now utilize the ® (registered) symbol when using Jakarta.

Please replace all the ™ symbol with the ® (registered) symbol when using Jakarta.

@autumnfound I believe that @ChristieWittEclipse already shared with us the Jakarta ® logo via issue #548

**Comment by autumnfound** [comment]
I've converted 90% of the content to use ® instead of TM. The only thing left is the stacked Jakarta EE images, which are used in share thumbnails. Do we want to convert those?

**Comment by chrisguindon** [comment]
Yes, we should update all images!

**Comment by autumnfound** [comment]
@ChristieWittEclipse do you have registered versions of the following images? (stacked logo)

https://jakarta.ee/images/jakarta/jakarta_ee_400x400.png
https://jakarta.ee/images/jakarta/jakarta_ee_200x200.png

**Comment by ChristieWittEclipse** [comment]
@autumnfound See attached!
[jakarta_ee_logo_schooner_color_stacked_default-r.svg.zip](https://github.com/jakartaee/jakarta.ee/files/3950881/jakarta_ee_logo_schooner_color_stacked_default-r.svg.zip)

**Comment by chrisguindon** [comment]
@autumnfound could you please make the following changes:

1. The Jakarta logo should be reverted to the one with tm
2. Remove all instances of tm/r in the content of the website expect the one in the heading of the homepage jumbotron
3. Shrink the size of the r symbol in the  in the heading of the homepage jumbotron

**Comment by autumnfound** [comment]
> @autumnfound See attached!
> [jakarta_ee_logo_schooner_color_stacked_default-r.svg.zip](https://github.com/jakartaee/jakarta.ee/files/3950881/jakarta_ee_logo_schooner_color_stacked_default-r.svg.zip)

@ChristieWittEclipse  Could you send over the version with the TM when you get the chance? The ZIP you sent only has the ® mark which has been switched for TM

**Comment by ChristieWittEclipse** [comment]
@autumnfound see attached.
[jakarta_ee_logo_schooner_color_stacked_default-tm.svg.zip](https://github.com/jakartaee/jakarta.ee/files/3963117/jakarta_ee_logo_schooner_color_stacked_default-tm.svg.zip)

**Comment by autumnfound** [comment]
This is live! Could we verify this complies with what is required for registered guidelines?

**Comment by ChristieWittEclipse** [comment]
From a quick review, I still see that the ® symbol is embedded in the body content on this page: https://jakarta.ee/membership/ I believe that it only needs to be included in the first instance on the home page only.

**Comment by chrisguindon** [comment]
@ChristieWittEclipse Nice catch!

**Comment by autumnfound** [comment]
These changes are live, thanks everyone!

**Comment by chrisguindon** [comment]
> @autumnfound could you please make the following changes:
> 
> 1. The Jakarta logo should be reverted to the one with tm
> 2. Remove all instances of tm/r in the content of the website expect the one in the heading of the homepage jumbotron
> 3. Shrink the size of the r symbol in the  in the heading of the homepage jumbotron

https://github.com/jakartaee/jakarta.ee/issues/557#issuecomment-565127856

I am re-opening since the Jakarta logo is showing the r symbol.

**Comment by chrisguindon** [comment]
Thanks for the update @autumnfound
