### ISSUE TITLE
Change the content copy of the banner in Jakarta.ee

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#559]
Please change the content under the title in the screenshot to the following: "Download compatible products, get involved, and stay in the know!”

<img width="753" alt="Screen Shot 2019-12-10 at 3 19 35 PM" src="https://user-images.githubusercontent.com/51449073/70565616-7b707780-1b60-11ea-9887-6db098b2c450.png">

**Comment by autumnfound** [comment]
This is live! Thanks @ericpoirier!
