### ISSUE TITLE
[Jakarta Budget Transparency] Via its website

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#569]
While listening to Jakarta EE 2019 last Community call update, I wonder if there is a plan to increase transparency to the broader Community on how 2020 budget is allocated?  

Under budget the Resources Tab **preferred suggestion** with at least:

1. Program Expenditures shown yearly by **percentage** &/or exact USD $ amount:  
 **The transparency Inventory includes:** 

- Legal fees including Trademarks/Registered Marks

- INFRA

- Mktg Budget

- Specification Budget

- Buffer budget

- Eclipse Head Count (including full-time & part time paid Human Resources)

- the increase or decrease from the previous year

**Comment by TanjaObradovic** [comment]
The 2020 Program Plan, including an overview of the budget, was recorded.  We do not publish the program plan or the budget as stand-alone items on the website.

**Comment by chrisguindon** [comment]
Thanks for the clarifications @TanjaObradovic

**Comment by aeiras** [comment]
Percentage transparency not possible?  That is problematic for a project that is OSS in many levels. 

**Often**, I get asked by potential Vendors, start ups and large entities about budget spent and budget transparency.  My reply is, please send your request to the jakarta community forum to ask WHY, WHERE, HOW the budget - at least the % is being dedicated to the project itself. 

When I reply like that, those potential individuals drop joining the project as paying partners (Strategic partners have access to the budget) but to my knowledge none else, Participants don't get budget transparency. Thanks EF Team!

**Comment by ggam** [comment]
I agree with Amelia and I think this deserves at least some more
discussion.

Would you please reopen the issue?

**Comment by TanjaObradovic** [comment]
As per the previous response, the information is available in the recording. We do not publish the program plan or the budget as stand-alone items on the website.

**Comment by nmcl** [comment]
Hi Tanja. If the information is available in the recording then is there any problem with someone else pulling that out an writing it up so there's a version upon which comments could be made?

**Comment by TanjaObradovic** [comment]
Hi Mark, I think this is not my call really. It would be best to discuss this topic in the Jakarta EE Steering Committee and seek out their input.
