### ISSUE TITLE
improve formatting of /specifications page

### ISSUE THREAD

**Issue by bshannon** [jakartaee/jakarta.ee#572]
We have a lot of specifications on the /specifications page.
Can we "tighten up" the formatting of that page so that I
don't need to do quite as much scrolling to see all the specifications?

We could consider moving the scope statements to a popup,
or move them to the top of each specification page, leaving
just the specification name on the top level "index" page.
Or maybe just getting rid of some of the whitespace and using
a smaller font for the scope statement would be enough?

Eventually we might want to mark specifications as "deprecated"
or "under development" or "experimental" or other similar attributes,
so we might want to think about how to include that information on
this page.

**Comment by chrisguindon** [comment]
+1 The specifications list page is currently using our default list layout. I think it's time for us we create a custom layout for specifications.

@ChristieWittEclipse Can you help us build the design layout for this page?

**Comment by ChristieWittEclipse** [comment]
Sure thing, I've added this to my backlog.

**Comment by ChristieWittEclipse** [comment]
@bshannon I've attached mockups of the top level /specifications page, using a 3 column grid and moving the scope statements to the top of each individual specification page.

I've also attached a sample of  an individual specifications page, using a bulleted list for the items. Please note that the color coding for "Under Development", "Experimental", and "Deprecated" is just a concept for deployment at a later date, as all individual specifications are currently "Under Development" from my understanding.

@paulbuck please add this as a discussion item for the next Specification Committee meeting and let me know if you need anything else.

[Jakarta-Specifications-page-mockups.zip](https://github.com/jakartaee/jakarta.ee/files/4439409/Jakarta-Specifications-page-mockups.zip)

**Comment by chrisguindon** [comment]
I will need a +1 from the spec committee to +1 @ChristieWittEclipse mockups before I assign someone on my team to work on the implementation!

**Comment by ChristieWittEclipse** [comment]
@bshannon @paulbuck @chrisguindon  FYI – I've attached a V2 mockup of the specifications page, that includes an 8 word placeholder description for each spec. We can discuss this further in the next committee meeting on April 29th.
[jakarata-specifications-page-v2.jpg.zip](https://github.com/jakartaee/jakarta.ee/files/4510688/jakarata-specifications-page-v2.jpg.zip)

**Comment by chrisguindon** [comment]
@ChristieWittEclipse To make it easier for all, I am posting the content of your zip in this comment:

![jakarata-specifications-page-v2](https://user-images.githubusercontent.com/893942/79895542-072ec600-83d5-11ea-92ed-2d6c0afdb996.jpg)

**Comment by chrisguindon** [comment]
@ChristieWittEclipse 

From my perspective, this looks great but I think we will need to restrict the number of characters for the description text to make sure that all the boxes in a same row are the same height.

**Comment by ChristieWittEclipse** [comment]
@chrisguindon that's true, we would restrict the number of characters, in this case to 57 characters.

**Comment by kwsutter** [comment]
Based on our discussion today on the Spec Committee call, we indicated that we would define a new field for this "short description".  Currently, the _index.md file at the top level has this type of content:

```
---
title: "Jakarta EE Platform"
weight: -10
summary: "The Jakarta EE Platform defines a standard platform for hosting Jakarta EE applications."
project_id: "ee4j.jakartaee-platform"
---
```

To allow for a more readable Summary on the Specifications page, we would need an additional field in the top-level _index.md file.  Maybe call it "shortSummary:"?  But, how do we communicate the 60 character limit?  Maybe call it "60CharSummary"?  Open to suggestions.

And, to follow up on our priority discussion on the call...  First process the first 60 characters of the "shortSummary".  If the "shortSummary" is longer than 60 characters, then the ellipses (...) would be used at the end.  If the "shortSummary" is not available, then the first 60 characters for the "Summary" would be used with the ellipses (...).

Once we have this in place, then I have volunteered to communicate this to the wider team to get them to "own" this update.  At least with the default processing, we can put this in place without waiting for these additional PRs.

Thanks!

**Comment by ChristieWittEclipse** [comment]
@kwsutter I've also attached the updated mockups as discussed. @chrisguindon no action for your team just yet.

![jakarata-specifications-page-v3](https://user-images.githubusercontent.com/58480647/80632020-a03c8d00-8a24-11ea-9a49-32abd2df73f5.jpg)
![jakarata-specifications-platform-page-v2](https://user-images.githubusercontent.com/58480647/80632034-a468aa80-8a24-11ea-9ecc-7c0575a897b0.jpg)

**Comment by kwsutter** [comment]
Looks good, @ChristieWittEclipse.  It definitely shows that the 60 character limit truncates a lot of information (due to the name of the project taking up almost half of it already..).  But, at least by having the fallback processing, projects can update this information any time they wish to make it more readable.

Would it be possible to have the first row only contain two items -- Platform and Web Profile?  And, have those two centered over the other three columns?  That would really help differentiate the Platform-related projects from all of the other "component" projects that make up the Platform.

**Comment by ChristieWittEclipse** [comment]
Thanks for reviewing @kwsutter. I think it may be off balanced to have the word "Specifications" left aligned, and then to center align the Platform and Web Profile boxes. The 3 column grid is also fluid, so it will also shrink and decrease the number of columns based on the screen size (for example, on mobile it will display a one column grid). Let me know your thoughts on this before I create another mockup.

**Comment by kwsutter** [comment]
Sorry, @ChristieWittEclipse, I missed your question... I can understand the fluidity of the three column approach across multiple screen types.  So, one last idea... What if the Platform and Web Profile occupied the first two columns and then the last spot on the first row was left blank?  With Activation starting in row 2, column 1?  This would still differentiate these two key Specifications from the rest of the pack without disrupting the three column approach (too much)...  Is that doable?

**Comment by ChristieWittEclipse** [comment]
@kwsutter I've attached a mockup of your idea. This layout could work for desktop view, but again, these 2 and 3 columns will all stack to a single column grid on a mobile device. Let me know what you think.

![jakarata-specifications-page-v3 1](https://user-images.githubusercontent.com/58480647/81306460-80711e80-904d-11ea-98cb-930f29905492.png)
![jakarata-specifications-platform-page-v2](https://user-images.githubusercontent.com/58480647/81306468-82d37880-904d-11ea-951d-d34db08ba6f3.jpg)

**Comment by kwsutter** [comment]
+1, @ChristieWittEclipse.  I like this.  It's not perfect due to the multiple screen renderings, but it's much better than what we had.  Thanks!

**Comment by ChristieWittEclipse** [comment]
@kwsutter great thanks for reviewing. Please proceed with giving the owner of each specification summary the opportunity to provide short descriptions (57 to 60 characters in length) in the _index.md file. Once that is done, let us know here and I will coordinate the new layout implementation with @chrisguindon.

**Comment by kwsutter** [comment]
Decided on the Spec Committee call today to call the new attribute "60CharSummary".  And, then follow the processing as documented in my previous comment: https://github.com/jakartaee/jakarta.ee/issues/572#issuecomment-621335349

**Comment by ChristieWittEclipse** [comment]
@kwsutter I wanted to check in and see how the new (shorter) specification descriptions are going.
Let us know when those will be ready and then we can coordinate internally on the timing of the page update.

**Comment by ivargrimstad** [comment]
@ChristieWittEclipse I don't think we should wait for the specifications to add their short description. I have added one to the Jakarta MVC specification as an example for how it can be done.
The fallback should be to use the 57 first characters of the "summary" attribute suffixed by three dots ("...").

**Comment by ChristieWittEclipse** [comment]
@ivargrimstad +1. In that case I will loop in @chrisguindon. Chris – We seem to be ready for implementing this new layout to the Jakarta Specifications page. Please work this into your schedule as I know the web team has a lot on the go.

**Comment by chrisguindon** [comment]
Thanks @chrisguindon 

@autumnfound please add this to your queue!

**Comment by chrisguindon** [comment]
Quick update: @ericpoirier  will take over this project as I need @autumnfound to focus on a few other tasks.

**Comment by ericpoirier** [comment]
I created a pull request to update the specifications page.

You can have a look at the result here:
https://deploy-preview-791--jakartaee.netlify.app/specifications/

Let me know if there's anything you'd like to change.

Thanks.

**Comment by ericpoirier** [comment]
Also note that on the following page I decided to make the links blue (like other links on the website) so that it's obvious that they are links.

https://deploy-preview-791--jakartaee.netlify.app/specifications/platform/

Let me know if that's an issue.

Thanks.

**Comment by ChristieWittEclipse** [comment]
Thanks @ericpoirier! Some minor feedback on the squares:
-Can we vertical-align: middle; the text within the boxes?
-Can we round the corners of the boxes?
-Can we fill the boxes with this light blue instead of grey: #F2F3F7

**Comment by ChristieWittEclipse** [comment]
@ericpoirier I had some minor feedback on this page that I posted a couple weeks ago. It's not urgent, but I wanted to check in to make sure we don't forget about it!
-Can we vertical-align: middle; the text within the boxes?
-Can we round the corners of the boxes?
-Can we fill the boxes with this light blue instead of grey: #F2F3F7

**Comment by chrisguindon** [comment]
@autumnfound No rush but can you take over this task now that Eric is gone on leave for the next 5 weeks?

I think we simply need to apply @ChristieWittEclipse and we are ready to go live with this.

**Comment by kwsutter** [comment]
Is there something we're waiting on for this Issue?  It would be nice to get this one done and out of the way.  Thanks! @ChristieWittEclipse

**Comment by ChristieWittEclipse** [comment]
@kwsutter I left a few revisions for @autumnfound to work on when he has the chance. Our web team is working through a big backlog of work at the moment, but we will update this issue as soon as we can.

**Comment by autumnfound** [comment]
@ChristieWittEclipse @kwsutter I've updated the preview with the requested changes https://deploy-preview-838--jakartaee.netlify.app/specifications/

**Comment by ChristieWittEclipse** [comment]
![Specifications_The_Eclipse_Foundation](https://user-images.githubusercontent.com/58480647/87804806-652b4800-c822-11ea-9e13-a3586c94c9eb.png)
@autumnfound looks good! Please increase the padding below each block, to be the same as the space on the right side of each block (see screenshot).

**Comment by autumnfound** [comment]
Please see https://deploy-preview-791--jakartaee.netlify.app/specifications/ for the final change (had some struggles pushing up the fix last time so I ended up with multiple links, oops!)

**Comment by ChristieWittEclipse** [comment]
@autumnfound +1 this is good for me. I'll let @kwsutter make the final approval.

**Comment by chrisguindon** [comment]
@kwsutter Do you think we can go live with these changes?

**Comment by kwsutter** [comment]
Sorry!  Didn't know I was the bottleneck for this change...  I just reviewed the latest mockup (https://deploy-preview-791--jakartaee.netlify.app/specifications/) and it looks good!  Much, much better than what we had.  Thanks!
