### ISSUE TITLE
Publishing meeting minutes for Specification Committee 

### ISSUE THREAD

**Issue by paulbuck** [jakartaee/jakarta.ee#573]
We need to add new entries for Jakarta EE Specification Committee meeting minutes on the "Specification Committee" tab on https://jakarta.ee/meeting_minutes/

I have attached pdf files. 

[Spec Committee Agenda December 4, 2019 - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3984818/Spec.Committee.Agenda.December.4.2019.-.Google.Docs.pdf)
[Spec Committee Agenda November 20, 2019 - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/3984820/Spec.Committee.Agenda.November.20.2019.-.Google.Docs.pdf)

Thanks ... Paul

**Comment by chrisguindon** [comment]
Thanks @paulbuck!

**Comment by paulbuck** [comment]
Thanks!
