### ISSUE TITLE
Change Copy of Banner in Jakarta.ee

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#581]
Title: Cloud Native for Java Day
Subtitle: Build Enterprise Java on Kubernetes!
Body: A co-located event with KubeCon + CloudNativeCon EU on March 30, 2020
Button: Register Today
Link: http://eclipse-5413615.hs-sites.com/cn4j-day

**Comment by autumnfound** [comment]
Should this banner be for the header, footer, or both?

**Comment by autumnfound** [comment]
Also do we want to use the existing image, or use the image that we have for the main site?

**Comment by GraehamHui** [comment]
I'll talk to Laura about it when she comes into the office later this
afternoon.

**Comment by GraehamHui** [comment]
For Jakarta, use exiting cloud background only for the header
For EF, change it to the clouds Laura uploaded for both the header and footer

Thanks!

**Comment by chrisguindon** [comment]
Thanks @autumnfound
