### ISSUE TITLE
Create Press Release on Eclipse.org

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#584]
https://docs.google.com/document/d/1M-_rYorlHGnddPGtXwzn_fYXL6V_kH31FZIk5SB6s6E/edit?usp=sharing

Please put on:
1. eclipse.org Announcements section on home page
2. https://www.eclipse.org/org/press-release/

For eclipse.org announcements section please use this description: "We are pleased to announce the Eclipse Foundation’s new Bylaws went into effect on January 1, 2020."

**Comment by autumnfound** [comment]
This was meant to be created in Infrazilla, closing
