### ISSUE TITLE
Publish Steering Committee Minutes - December 3, 10, 17

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#588]
This is not a bug.

We need to add new entries for Steering meeting minutes on
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached pdf files
[Minutes of December 3 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/4052498/Minutes.of.December.3.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of December 10 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/4052500/Minutes.of.December.10.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of Dec 17 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/4052501/Minutes.of.Dec.17.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by autumnfound** [comment]
This is live!
