### ISSUE TITLE
XML Namespace under Jakarta

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/jakarta.ee#592]
**Is your feature request related to a problem? Please describe.**
We need to replace the JCP namespaces in the XML documents with Jakarta, which means we need a location for the XML Schemas (XSDs).

**Describe the solution you'd like**
Make the schemas from https://github.com/eclipse-ee4j/jakartaee-schemas available under https://jakarta.ee/xml/ns/jakartaee/

As an example, look at how it was done under the JCP here: http://xmlns.jcp.org/xml/ns/javaee

**Describe alternatives you've considered**
Consider creating a subdomain like https://xmlns.jakarta.ee/...

**Additional context**

**Comment by kwsutter** [comment]
Since @chrisguindon took ownership of this Issue, I'm assuming that we're just trying to define the expected namespace and the desired location.  The solution described in the Description sounds like you are asking the schemas just to move from the github repo to the designated location that Chris defines.  But, don't we need a release process for these schemas that will eventually get promoted to this desired location?  Maybe I'm just reading too much into your Description.  Can you clarify the intent, @ivargrimstad?

**Comment by gunnarmorling** [comment]
In terms of a namespace (i.e. separate from the location of *hosting* these files), does it really have to be a resolveable URL to begin with, or was it also considered to use an [URN namespace](https://www.w3.org/TR/uri-clarification/#urn-namespaces)? Such as "urn:jakartaee:validation:configuration"?

I've been bitten a few times in the past where misconfigured tools or libraries would try and download a schema from the given namespace URL instead of using a local version of the file. That issue is avoided by using URN namespaces which don't create the perception of being resolveable URLs to begin with. 

Related to this, and something I always had been wondering: why was it the same namespace (http://xmlns.jcp.org/xml/ns/javaee) for most of the EE schemas? Wouldn't it make more sense to have distince namespaces for the different specs, so to tell their types unambiguously apart from each other.

**Comment by chrisguindon** [comment]
@kwsutter I was too eager to get started! I've removed myself from the issue. 

We need to define requirement and some content for these pages before I implement a solution for this!

**Comment by kwsutter** [comment]
Just to clarify what needs to be done...  Here's a snippet from the current application_8.xsds:

```
<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xmlns.jcp.org/xml/ns/javaee"
            xmlns:javaee="http://xmlns.jcp.org/xml/ns/javaee"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            version="8">
```

For Jakarta EE 9, we need to find a new home for the targetNamespace and xmlns:javaee references.  And, of course, we'll need to update the "version".  But, we have a [separate Issue #45](https://github.com/eclipse-ee4j/jakartaee-platform/issues/45) to get that work done.  We just need to do the Eclipse work via this Issue.

As Ivar suggested, maybe this is ```https://xmlns.jakarta.ee/xml/ns/jakartaee```.  Other suggestions are welcome, but this works for me.

I'd like to keep this change as simple as possible for Jakarta EE 9.  The use or "urn:" or creating new subdirectories for the various schemas can be the subjects of other Issues.  But, I'd like to keep it simple with the least impact across the board for Jakarta EE 9.

I didn't mean to scare you off, @chrisguindon!  :-)  I like the enthusiasm to pick up Issues and run with them.

**Comment by hantsy** [comment]
If use a subdomain `xmlns.jakarta.ee`, why not remove the path prefix `/xml/ms` in the url.

`https://xmlns.jakarta.ee/xml/ns/jakartaee`

to 

`https://xmlns.jakarta.ee/jakartaee`

**Comment by bshannon** [comment]
> In terms of a namespace (i.e. separate from the location of _hosting_ these files), does it really have to be a resolveable URL to begin with, or was it also considered to use an [URN namespace](https://www.w3.org/TR/uri-clarification/#urn-namespaces)? Such as "urn:jakartaee:validation:configuration"?

It doesn't *have* to be, but our experience is that enough people have come to expect it that doing otherwise would just cause unnecessary confusion.  If I wanted to find the schema document for "urn:jakartaee:validation:configuration", I really have no idea where I would start looking.

> I've been bitten a few times in the past where misconfigured tools or libraries would try and download a schema from the given namespace URL instead of using a local version of the file. That issue is avoided by using URN namespaces which don't create the perception of being resolveable URLs to begin with.

Yes, that's absolutely an issue, and we need to do whatever we can to make sure tools have local copies of whatever schemas they need.

> Related to this, and something I always had been wondering: why was it the same namespace (http://xmlns.jcp.org/xml/ns/javaee) for most of the EE schemas? Wouldn't it make more sense to have distince namespaces for the different specs, so to tell their types unambiguously apart from each other.

Most of the deployment descriptors share a large number of common elements.  There would be no advantage to have these elements be defined differently for Servlet vs EJB.  Some of the non-deployment descriptors do use their own namespace.

**Comment by bshannon** [comment]
> If use a subdomain `xmlns.jakarta.ee`, why not remove the path prefix `/xml/ms` in the url.
> 
> `https://xmlns.jakarta.ee/xml/ns/jakartaee`
> 
> to
> 
> `https://xmlns.jakarta.ee/jakartaee`

I think we're into "painting the bike shed" territory now.  :-)

A reason to include it is to allow virtual hosting where multiple jakarta.ee subdomains share a filesystem.  It also provides for more flexibility if the domains need to be rearranged and redirects put in place.

**Comment by chrisguindon** [comment]
We might not need to implement this for hugo.

We could create a jenkins job in https://github.com/eclipse-ee4j/jakartaee-schemas/tree/master/ that generate static html based of the content of the repository. We would then host these static html files under https://xmlns.jakarta.ee/

This solution would give complete control to the platform project on how the content is displayed in this new sub-domain!

Is this something that we can do?

**Comment by chrisguindon** [comment]
Another solution would to create a Jenkins job  in https://github.com/eclipse-ee4j/jakartaee-schemas/tree/master/ that would generate a data file (json) with metadata for each schema that my team can use to generate a list on the website.

**Comment by kwsutter** [comment]
Since we haven't heard any dissenting views on the proposed namespace ```https://xmlns.jakarta.ee/xml/ns/jakartaee```, can we at least get confirmation from the Eclipse Foundation that this name is acceptable?  The mechanics of how we populate it can be figured out later.  But, if we can agree on a name, then we can continue to make progress on the affected Spec Projects.  Thanks!  @chrisguindon

**Comment by gunnarmorling** [comment]
> Since we haven't heard any dissenting views on the proposed namespace...

Hum, that's a bit disappointing to read, as I very clearly brought up an
alternative suggestion in form of URNs. If there's agreement on not going
for that, that's fine, but let's please not pretend there was no
alternative proposal.

**Comment by gsmet** [comment]
@kwsutter that means my BV XSD would have something like: `https://xmlns.jakarta.ee/xml/ns/jakartaee/validation/mapping`?

FTR, the old ones used to be `http://xmlns.jcp.org/xml/ns/validation/mapping` (so no intermediate `jakartaee` segment).

BTW, for the Bean Validation spec, we need the final download destination of the XSD files as they are referenced in several of the examples.

**Comment by ivargrimstad** [comment]
> Since we haven't heard any dissenting views on the proposed namespace...
> Hum, that's a bit disappointing to read, as I very clearly brought up an alternative suggestion in form of URNs. If there's agreement on not going for that, that's fine, but let's please not pretend there was no alternative proposal.

As I recall, it was briefly discussed in one of the platform calls. I am not an expert on this, but couldn't we have both URLs and URNs? The schemas will need to be hosted somewhere anyway. So this issue is more about where to put them? Adding URNs to the schemas could be done in https://github.com/eclipse-ee4j/jakartaee-schemas. Or am I misunderstanding this?

**Comment by chrisguindon** [comment]
`https://xmlns.jakarta.ee/xml/ns/jakartaee, can we at least get confirmation from the Eclipse Foundation that this name is acceptable?`

We don't have any problem with providing a sub-domain for xmlns.jakarta.ee.

**Comment by kwsutter** [comment]
> Since we haven't heard any dissenting views on the proposed namespace...
> Hum, that's a bit disappointing to read, as I very clearly brought up an alternative suggestion in form of URNs. If there's agreement on not going for that, that's fine, but let's please not pretend there was no alternative proposal.

Sorry, @gunnarmorling.  I thought @bshannon's response kind of nixed that idea.  I know Bill is only voice, but he does have a ton of history with these XSD files, so I kind of took his answer as "gospel".  Since there was no further discussion on the use of URNs, I thought it was done.  Since you just brought it up again, I guess it's not...  ;-)

**Comment by kwsutter** [comment]
> @kwsutter that means my BV XSD would have something like: `https://xmlns.jakarta.ee/xml/ns/jakartaee/validation/mapping`?
> 
> FTR, the old ones used to be `http://xmlns.jcp.org/xml/ns/validation/mapping` (so no intermediate `jakartaee` segment).

The javaee namespace used to be:  "http://xmlns.jcp.org/xml/ns/javaee".  So, if bean validation didn't use the "javaee", then maybe that was a mistake that slipped through the cracks?  I really have no history with this to understand why the "javaee" was not used for bean validation.  Is the same thing true for cdi?

> 
> BTW, for the Bean Validation spec, we need the final download destination of the XSD files as they are referenced in several of the examples.

Yes, I posted this proposal yesterday based on @starksm64's note.  We need to finalize the location to allow Projects to continue to make progress.

**Comment by starksm64** [comment]
CDI has used the http://xmlns.jcp.org/xml/ns/javaee in the past while BV has always used a http://xmlns.jcp.org/xml/ns root. Note that the CDI and BV schemas have never been hosted under the http://xmlns.jcp.org/xml/ns/javaee location. If you go there, you find this statement referring to their hosted location:

"The Java EE specification also requires support for the Java Persistence API and the Bean Validation API. The Java Persistence API Schemas are available at http://xmlns.jcp.org/xml/ns/persistence/. The Bean Validation API Schemas are available at http://www.jboss.org/xml/ns/javax/validation/configuration/."

We can certainly update the namespace to a common one where all schemas will be hosted. I was trying to do a milestone release yesterday but permission issues have prevented that, so I can revisit the location once the permissions have been fixed.

**Comment by bshannon** [comment]
> > Since we haven't heard any dissenting views on the proposed namespace...
> > Hum, that's a bit disappointing to read, as I very clearly brought up an alternative suggestion in form of URNs. If there's agreement on not going for that, that's fine, but let's please not pretend there was no alternative proposal.
> 
> Sorry, @gunnarmorling. I thought @bshannon's response kind of nixed that idea. I know Bill is only voice, but he does have a ton of history with these XSD files, so I kind of took his answer as "gospel". Since there was no further discussion on the use of URNs, I thought it was done. Since you just brought it up again, I guess it's not... ;-)

I don't now what problem URNs solve (other than delaying the choice of publishing
location), but I do know what problem they cause.  Thus, I don't see the advantage.

**Comment by bshannon** [comment]
> > @kwsutter that means my BV XSD would have something like: `https://xmlns.jakarta.ee/xml/ns/jakartaee/validation/mapping`?
> > FTR, the old ones used to be `http://xmlns.jcp.org/xml/ns/validation/mapping` (so no intermediate `jakartaee` segment).
> 
> The javaee namespace used to be: "http://xmlns.jcp.org/xml/ns/javaee". So, if bean validation didn't use the "javaee", then maybe that was a mistake that slipped through the cracks? I really have no history with this to understand why the "javaee" was not used for bean validation. Is the same thing true for cdi?
> 
> > BTW, for the Bean Validation spec, we need the final download destination of the XSD files as they are referenced in several of the examples.
> 
> Yes, I posted this proposal yesterday based on @starksm64's note. We need to finalize the location to allow Projects to continue to make progress.

Some specs are intimately tied to the platform and some have wide use outside of the
platform.  The latter don't need the extra "jakartaee" in the file name.  Obviously this
is somewhat of a judgment call, but lacking a strong motivation to do otherwise I
would just take the same approach that we took for Java EE schemas.

**Comment by bshannon** [comment]
> CDI has used the http://xmlns.jcp.org/xml/ns/javaee in the past while BV has always used a http://xmlns.jcp.org/xml/ns root. Note that the BV schemas have never been hosted under the http://xmlns.jcp.org/xml/ns/javaee location. If you go there, you find this statement referring to their hosted location:
> 
> "The Java EE specification also requires support for the Java Persistence API and the Bean Validation API. The Java Persistence API Schemas are available at http://xmlns.jcp.org/xml/ns/persistence/. The Bean Validation API Schemas are available at http://www.jboss.org/xml/ns/javax/validation/configuration/."
> 
> We can certainly update the namespace to a common one where all schemas will be hosted. I was trying to do a milestone release yesterday but permission issues have prevented that, so I can revisit the location once the permissions have been fixed.

At this point I see no reason not to move all the Jakarta EE related schemas to the
xmlns.jakarta.ee location.

**Comment by gunnarmorling** [comment]
I never understood the motivation for having (almost) all spec schemas within one single namespace; if anything, I'd suggest to move them to distinct namespaces, allowing tools to apply validation without having to jump through hoops and apply out-of-bands knowledge to derive which "flavour" of the EE namespace a particular descriptor is.

Re URNs, yes, they solve the issue of tieing schema identity and physical hosting location together;  I've experienced more than one case where tools fetched the schema from the namespace URL upon validation, causing performance issues. That's avoided by not creating that perception that the schema is neccessarily available at the URL resembling its id. Would be interesting to learn about the disadvantages you experienced, @bshannon.

That said, I brought this up now mainly to raise awareness, as it in particular means that we might do one change now (jcp.org -> jakarta.ee) and another one in 10 (URNs, moving to distinct namespaces, should we want to do that), creating migration friction twice. That's not a problem of course if we agree that the jcp.org -> jakarta.ee change is all we want to do.

**Comment by bshannon** [comment]
> I never understood the motivation for having (almost) all spec schemas within one single namespace; if anything, I'd suggest to move them to distinct namespaces, allowing tools to apply validation without having to jump through hoops and apply out-of-bands knowledge to derive which "flavour" of the EE namespace a particular descriptor is.

The reason to have them in a single namespace was just to emphasize their
relationship to the parent spec that contains them all.

> Re URNs, yes, they solve the issue of tieing schema identity and physical hosting location together; I've experienced more than one case where tools fetched the schema from the namespace URL upon validation, causing performance issues. That's avoided by not creating that perception that the schema is neccessarily available at the URL resembling its id. Would be interesting to learn about the disadvantages you experienced, @bshannon.

The performance issue is real and should be considered.  The downside of URNs,
as I've explained, is that no one knows where to find the document that corresponds
to the URN.  Worst case, they start typing the document in themselves and make a
mistake.  There is no URN registry or URN directory service where you can look up
the URN and get back the document.

> That said, I brought this up now mainly to raise awareness, as it in particular means that we might do one change now (jcp.org -> jakarta.ee) and another one in 10 (URNs, moving to distinct namespaces, should we want to do that), creating migration friction twice. That's not a problem of course if we agree that the jcp.org -> jakarta.ee change is all we want to do.

I agree that we should plan to do all the changes now, not spread over multiple releases.

**Comment by arjantijms** [comment]
> The performance issue is real and should be considered. The downside of URNs,
as I've explained, is that no one knows where to find the document that corresponds
to the URN.

That's indeed a very real problem. I've been having this problem myself, and in my capacity as lead developer before have seen a number of devs struggling with exactly this.
