### ISSUE TITLE
Add the Primer on Committee Responsibilities for Jakarta EE Releases

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#593]
Add the Primer on Committee Responsibilities for Jakarta EE Releases to jakarta.ee/committees
[Primer on Committee Responsibilities for Jakarta EE Releases.pdf](https://github.com/jakartaee/jakarta.ee/files/4067274/Primer.on.Committee.Responsibilities.for.Jakarta.EE.Releases.pdf)

**Comment by autumnfound** [comment]
Did you just want the PDF posted under committees, or did you want an actual page?

**Comment by TanjaObradovic** [comment]
Pdf would be good, I think.

**Comment by chrisguindon** [comment]
Related https://github.com/jakartaee/jakarta.ee/issues/597

**Comment by chrisguindon** [comment]
I am addressing this issue via https://github.com/jakartaee/jakarta.ee/issues/597
