### ISSUE TITLE
Add Article to Announcement section 

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#595]
Please add the following article to jakarta.ee under the announcements section:

https://blogs.eclipse.org/post/mike-milinkovich/moving-forward-jakarta-ee-9

Title: Moving Forward With Jakarta EE 9
Description: On behalf of the Jakarta EE Working Group, we are excited to announce the unanimous approval of the plan for Jakarta EE 9, with an anticipated mid-2020 release.

**Comment by chrisguindon** [comment]
Done!
