### ISSUE TITLE
Please add link to Jakarta Tech Talks under Resources

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#606]
Can you please add https://www.meetup.com/jakartatechtalks_/ under Resources on jakarta.ee?

![image](https://user-images.githubusercontent.com/40073121/72990304-ec40bb80-3dbd-11ea-9feb-adb93bbbe664.png)

**Comment by autumnfound** [comment]
Could you check this URL to ensure that I got your requirements right? Thanks!
https://deploy-preview-608--jakartaee.netlify.com/

**Comment by TanjaObradovic** [comment]
That will do!
Thanks!

**Comment by autumnfound** [comment]
This is live! https://jakarta.ee/resources/#meetups

**Comment by aeiras** [comment]
This added feature is great! Thank you Team 👌🏼
