### ISSUE TITLE
Publishing Jakarta EE Marketing Committee Meeting - January 9, 2020

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#607]
This is not a problem; we need to add new entries for Marketing meeting minutes on
https://jakarta.ee/meeting_minutes/

under section
Jakarta EE Marketing Committee

in the same way as other files with just adding a date with the link.
e.g, June 25, 2018 (pdf)

I have attached the latest one:

[Jakarta EE Marketing Committee Meeting - January 9, 2020.pdf](https://github.com/jakartaee/jakarta.ee/files/4105141/Jakarta.EE.Marketing.Committee.Meeting.-.January.9.2020.pdf)

**Comment by autumnfound** [comment]
This is now live: https://jakarta.ee/meeting_minutes/#marketing_committee
