### ISSUE TITLE
Deleting links on the resources pagers

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#609]
at jakarta.ee/resources please under the Presentations section please move Introducing the EFSP

**Presentations**
- Jakarta EE presentations
- Introducing the EFSP

Then remove the **Specification Process** section from the menu (Resources drop-down) and on the page itself
Also please remove **Videos** from the Resources drop-down and on the page itself

**Comment by autumnfound** [comment]
These sections have now been removed
