### ISSUE TITLE
Add Announcement to Jakarta.EE

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#610]
Add an announcement to Jakarta.ee website, set live at 7:00AM tomorrow:
Announcement copy: 
[CN4J Day @ Kubecon EU - Press Release_vFNL.docx](https://github.com/jakartaee/jakarta.ee/files/4117629/CN4J.Day.%40.Kubecon.EU.-.Press.Release_vFNL.docx)

Title: The Eclipse Foundation Announces the CN4J Day 2020 Event for Building Enterprise Java on Kubernetes

Preview: Today the [Eclipse Foundation](https://www.eclipse.org) announced the launch of the [Cloud Native for Java (CN4J) Day event](https://eclipse-5413615.hs-sites.com/cn4j-day), a full-day of expert talks, demos, and thought-provoking sessions focused on enterprise applications implemented using open source vendor-neutral Jakarta EE (successor of Java EE) and Eclipse MicroProfile specifications on Kubernetes. 

Please include the hyperlinks inserted in the preview above.

**Comment by chrisguindon** [comment]
As discussed with @shabnammayel, this will go live around 8pm.

**Comment by ericpoirier** [comment]
Hi Graeham,

This news item is now on the production website.

Let me know if there's anything else.

Thanks.

**Comment by chrisguindon** [comment]
I am re-opening this issue.

The summary of this news is too long and it's affecting the layout of this page:
https://jakarta.ee/

**Comment by chrisguindon** [comment]
![Screen Shot 2020-01-28 at 12 09 04 PM](https://user-images.githubusercontent.com/893942/73287262-ff40fa80-41c6-11ea-8edb-b455dbe368b8.png)

**Comment by autumnfound** [comment]
This has been fixed:

![image](https://user-images.githubusercontent.com/23018241/75063243-7b6eeb00-54b2-11ea-9d9e-dc53d43f2a55.png)
