### ISSUE TITLE
Missing projects on jakarta.ee/projects page

### ISSUE THREAD

**Issue by kwsutter** [jakartaee/jakarta.ee#614]
**Describe the bug**
The https://jakarta.ee/projects/ page does not list Jakarta Servlet.  When I look at the [_index.md ](https://github.com/jakartaee/jakarta.ee/blob/src/content/projects/_index.md)file, it looks like it should be collecting all "jakarta-ee" projects.  But, there must be missing metadata associated with the Servlet project.

Jakarta Servlet does show up on this manual search:  https://projects.eclipse.org/list-of-projects?combine=jakarta&field_project_techology_types_tid=All&field_state_value_2=All&page=1

There must be other missing projects as well.  I only count about 21 on the jakarta.ee/projects page, but there are about 30 on the search I did above (only counting the Specification projects).

**To Reproduce**
1. Go to https://jakarta.ee/projects/
2. Jakarta Servlet is missing

**Expected behavior**
All Jakarta EE projects should be listed on this page, including Servlet.

**Screenshots**
Not necessary.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Firefox
 - Version: not sure

**Smartphone (please complete the following information):**
 - n/a

**Additional context**

**Comment by chrisguindon** [comment]
Wayne, I am assigning this bug since EMO is currently responsible for tagging a project under a specific working group.

Can you help us out here?
https://github.com/jakartaee/jakarta.ee/pull/371#issuecomment-572725472

**Comment by chrisguindon** [comment]
We must tag the project with **Jakarta EE** under the Working Group field for it to show on the project page of jakarta.ee

![Screen Shot 2020-01-28 at 11 09 31 AM](https://user-images.githubusercontent.com/893942/73281902-ae2d0880-41be-11ea-8c67-7b469e0c6b4c.png)

**Comment by chrisguindon** [comment]
We decided to leverage this tagging field to allow Working Group sites to avoid a 1 to 1 relationship between project and working group.

For example, OpenADx WG and IoT WG decided to include Eclipse Cyclone DDS (iot.cyclonedds) on their project page.

This functionality is a feature not a bug but we definitely need to update our metadata to make sure that all Eclipse EE4J projects are listed on jakarta.ee

**Comment by chrisguindon** [comment]
I did notice that summary for each project is missing.

@ericpoirier Is currently looking into this issue!

**Comment by waynebeaton** [comment]
I believe that I've updated the project metadata such that all specification projects now have the "Jakarta EE" working group association. I'm not seeing this reflected on the page; I assume that there's a cache involved.

**Comment by waynebeaton** [comment]
I've assumed that the working group wants to list only specification projects. Eclipse GlassFish is not listed, for example.

The way that this is set up is that the working group decides that it is "interested" in a particular project. This is represented separately from whether or not the project is a specification project. So... to list implementation projects (if this is what the working group wants), we can flip that switch in the implementation project metadata. This is the working group's call.

**Comment by kwsutter** [comment]
@waynebeaton Thanks!  My main goal was to get all of the Jakarta EE Specification projects properly listed on this page.  I think that was the original intent of this Projects page.  If somebody wants to pursue alternate content, I will let them do the leg work.

I'll wait until the "cache" is purged to verify that the pages look good and then I'll close out this Issue.  Thanks!

**Comment by chrisguindon** [comment]
> I believe that I've updated the project metadata such that all specification projects now have the "Jakarta EE" working group association. I'm not seeing this reflected on the page; I assume that there's a cache involved.

The website is automatically updated at midnight everyday, otherwise a change must occur in the repo to rebuild the site.

I manually started a travis-ci build for the website which will update the project page: https://travis-ci.org/jakartaee/jakarta.ee

**Comment by kwsutter** [comment]
Looks good now!  All 30 of the Spec Projects are now on https://jakarta.ee/projects/
