### ISSUE TITLE
Publish Steering Committee Minutes - January 7, 2020

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#617]
This is not a bug.

We need to add new entries for Steering meeting minutes on
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached pdf files
[Minutes of Jan 7 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/4141474/Minutes.of.Jan.7.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by chrisguindon** [comment]
Thanks @autumnfound
