### ISSUE TITLE
URGENT!!Add Tmax on the jakarta EE website

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#622]
Add Tmax on the Jakarta EE website
Participant Member

**Comment by autumnfound** [comment]
@ZahraFazli could you provide a URL + logo?

**Comment by ZahraFazli** [comment]
URL: https://jakarta.ee/membership/members/
Logo: 
![Tmax logo](https://user-images.githubusercontent.com/50374570/73873195-2169f680-481f-11ea-951a-dc8fab1a5618.png)

**Comment by autumnfound** [comment]
I mean a URL for the member itself, apologies

**Comment by ZahraFazli** [comment]
https://www.tmaxsoft.com/

**Comment by autumnfound** [comment]
This is now live
