### ISSUE TITLE
Publishing meeting minutes for Specification Committee

### ISSUE THREAD

**Issue by paulbuck** [jakartaee/jakarta.ee#624]
We need to add new entries for Jakarta EE Specification Committee meeting minutes on the "Specification Committee" tab on https://jakarta.ee/meeting_minutes/ 

I have attached pdf files...

[Spec Committee Agenda December 11, 2019.pdf](https://github.com/jakartaee/jakarta.ee/files/4167868/Spec.Committee.Agenda.December.11.2019.pdf)
[Spec Committee Agenda December 18, 2019.pdf](https://github.com/jakartaee/jakarta.ee/files/4167870/Spec.Committee.Agenda.December.18.2019.pdf)
[Spec Committee Agenda January 8, 2020.pdf](https://github.com/jakartaee/jakarta.ee/files/4167872/Spec.Committee.Agenda.January.8.2020.pdf)
[Spec Committee Agenda January 22, 2020.pdf](https://github.com/jakartaee/jakarta.ee/files/4167873/Spec.Committee.Agenda.January.22.2020.pdf)

Thanks ... Paul

**Comment by TanjaObradovic** [comment]
@autumnfound please hold off on this, I will create a PR to help out

**Comment by chrisguindon** [comment]
Thank you!
