### ISSUE TITLE
Publish Jakarta EE Steering Committee Minutes Jan 14, 21, 28

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakarta.ee#627]
This is not a bug.

We need to add new entries for Steering meeting minutes on
https://jakarta.ee/meeting_minutes/

...under the tab:
Jakarta EE Steering Committee

in the same way as other files with just adding a date with the link.
e.g, June 5, 2018 (pdf)

I have attached pdf files
[Minutes of January 14 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/4183212/Minutes.of.January.14.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of January 21 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/4183213/Minutes.of.January.21.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)
[Minutes of January 28 Jakarta EE Steering Committee Meeting - Google Docs.pdf](https://github.com/jakartaee/jakarta.ee/files/4183214/Minutes.of.January.28.Jakarta.EE.Steering.Committee.Meeting.-.Google.Docs.pdf)

**Comment by chrisguindon** [comment]
Thank you !
