### ISSUE TITLE
Add Kingdee Apusic Cloud Computing to the Jakarta EE website 

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#635]
Please add Kingdee to the Jakarta EE website https://jakarta.ee/membership/members/

![Kingdeedownload](https://user-images.githubusercontent.com/50374570/74471122-aaaba980-4e6d-11ea-8f0c-b35b657c6f9b.png)

**Comment by autumnfound** [comment]
Which of those two logos should I use? It seems to be munged into one image

**Comment by ZahraFazli** [comment]
Sorry, I am struggling to separate the two, that's they way they sent it to us but its the one on the right.

**Comment by autumnfound** [comment]
For the website, should I link to the Apusic website (which is all in Mandarin) or to the Kingdee (parent) website, which is available in English?

**Comment by ZahraFazli** [comment]
We should use their Apusic website. I am sure folks can translate that in English

**Comment by autumnfound** [comment]
This is live
