### ISSUE TITLE
Add Primeton Information Technologies logo on the Jakarta EE website

### ISSUE THREAD

**Issue by ZahraFazli** [jakartaee/jakarta.ee#636]
Please add Primeton Information Technologies' logo 
<img width="473" alt="Primetonlogo" src="https://user-images.githubusercontent.com/50374570/74842687-ccd37a80-52f8-11ea-99a3-144d27f5b3ab.png">

on the Jakarta EE website https://jakarta.ee/membership/members/

**Comment by autumnfound** [comment]
This is live

**Comment by ZahraFazli** [comment]
Hi, Primeton Information Technologies is an Enterprise Member. We need to create a different section for them, apologies on missing that part in the original bug.
The new section goes between Strategic and Participant. Thanks

**Comment by ZahraFazli** [comment]
Hi, Primeton Information Technologies is an Enterprise Member. We need to create a different section for them, apologies on missing that part in the original bug.
The new section goes between Strategic and Participant. Thanks

**Comment by ZahraFazli** [comment]
Is there a chance we can make the logo bigger

**Comment by autumnfound** [comment]
This is live
