### ISSUE TITLE
Update the post scheduled for announcement section

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#646]
I had previously created an issue for webdev to schedule posts for all upcoming JKT EE update calls under the Jakarta.ee announcement section. 

The upcoming Jakarta EE update call date is changed from 11 March to March 18th 10 AM EST. Please update the date in the post that is scheduled to go out soon.

**Comment by autumnfound** [comment]
When should the announcement go out? Should it still go live on the 3rd, or should I push it a week later to reflect the change in the call schedule?

**Comment by shabnammayel** [comment]
Please push it a week later. thanks

**Comment by autumnfound** [comment]
This is finished
