### ISSUE TITLE
Jakarta EE SVG logo with Registered Symbol

### ISSUE THREAD

**Issue by ChristieWittEclipse** [jakartaee/jakarta.ee#647]
Sharon MacDonald just confirmed that our Jakarta EE logo (with the boat only) has been fully registered. Please update the SVG logo on the website to reflect this. I've attached the updated image.
[jakarta_ee_logo_schooner_white_horizontal_R.svg.zip](https://github.com/jakartaee/jakarta.ee/files/4251614/jakarta_ee_logo_schooner_white_horizontal_R.svg.zip)

**Comment by ChristieWittEclipse** [comment]
Please hold on this while we confirm with Sharon.

**Comment by ChristieWittEclipse** [comment]
Hello, Sharon just confirmed that we can update the SVG logo on the website to reflect the full registration of the Jakarta EE logo. Please proceed with this update. Email is attached. 
![Screen Shot 2020-02-26 at 10 53 45 AM](https://user-images.githubusercontent.com/58480647/75362198-631e1800-5886-11ea-8bb2-720ee14b7397.png)

**Comment by autumnfound** [comment]
@ChristieWittEclipse just checking, but are we keeping the coloured version with just the TM and this one with the registered mark?

**Comment by autumnfound** [comment]
I can make use of the files on this comment from December if we want to switch this one over as well https://github.com/jakartaee/jakarta.ee/issues/548#issuecomment-562621184

**Comment by ChristieWittEclipse** [comment]
@autumnfound both the colored version and the black versions are registered now. We only need to add the registered symbol to the first logo instance on the page. Please note that the attached "Compatible" and "Member" logos are not yet registered.
![Screen Shot 2020-02-26 at 11 27 18 AM](https://user-images.githubusercontent.com/58480647/75365276-fb1e0080-588a-11ea-9506-4814b579c03b.png)

**Comment by autumnfound** [comment]
Image has been updated
