### ISSUE TITLE
The Jakarta EE 8 announcement under Jakarta.ee announcement section seems broken

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#650]
The announcement piece under the Jakarta.ee announcement section seems to be broken into smaller sections, please fix. Here's the screenshot of the issue: 
<img width="944" alt="Screen Shot 2020-02-28 at 3 38 02 PM" src="https://user-images.githubusercontent.com/51449073/75585531-5513f700-5a40-11ea-93c4-48daa858322f.png">

**Comment by autumnfound** [comment]
Could you expand on what you expect to be displayed in these sections? Right now its working as intended and showing the first sentence as a preview. If we make these sections any bigger, it bloats the rest of the boxes on the page.

**Comment by shabnammayel** [comment]
these smaller sections are a part of a press release, please view full document here: https://docs.google.com/document/d/1SxxICz2_LchfbEB2m9iETEG4wGOZjsSFeT5CAZEIE5Y/edit

yes We want the title to show only the first sentence. but now once you click on each section, its empty! so all these smaller sections should be removed, only the first one should remain, and once we click on it, it should provide the full content (I have provided the link above)

**Comment by autumnfound** [comment]
To clarify for future self, issue is on the announcements "view all" subpage rather than the homepage. Currently all announcements link to the news entry and never use the link parameter provided. When available, this link should be used instead.

**Comment by chrisguindon** [comment]
Thanks @autumnfound
