### ISSUE TITLE
Add events to event section on Jakarta.ee

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#652]
Please add the following events to jakarta.ee events section on the home page

**Dev.next**
March 24-27, 2020
Broomfield, Colorado
https://www.devdotnext.com

**Devoxx France**
April 15-17, 2020
Porte Maillot, Paris
https://www.devoxx.fr

**Devoxx UK**
13th - 15th May, 2020
London, United Kingdom
https://www.devoxx.co.uk

**Comment by autumnfound** [comment]
This is live both here and on events.eclipse.org
