### ISSUE TITLE
Publishing Jakarta EE Marketing Committee Meeting - February 6, 2020

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#654]
This is not a problem; we need to add new entries for Marketing meeting minutes on
https://jakarta.ee/meeting_minutes/

under section
Jakarta EE Marketing Committee

in the same way as other files with just adding a date with the link.
e.g, June 25, 2018 (pdf)
[Jakarta EE Marketing Committee Meeting - February 6, 2020.pdf](https://github.com/jakartaee/jakarta.ee/files/4277086/Jakarta.EE.Marketing.Committee.Meeting.-.February.6.2020.pdf)

I have attached the latest one:

**Comment by chrisguindon** [comment]
@shabnammayel let's use this issue as an example for our website training session next week!

**Comment by shabnammayel** [comment]
There will be another Marketing call tomorrow, we can use the next MKT minutes for the practice

**Comment by chrisguindon** [comment]
We can but you tell me it's urgent, it will be easier to add both pdf at the same time.

**Comment by chrisguindon** [comment]
@TanjaObradovic volunteered to make this change! thanks!

**Comment by chrisguindon** [comment]
Thank you @shabnammayel !
