### ISSUE TITLE
JEUS 8.5 as Compatible product of Jakarta EE Full Profile

### ISSUE THREAD

**Issue by TmaxEE** [jakartaee/jakarta.ee#657]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

[https://www.eclipse.org/membership/showMember.php?member_id=1391](https://www.eclipse.org/membership/showMember.php?member_id=1391)

**A product name and version**
JEUS 8.5

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[bi_jeus.zip](https://github.com/jakartaee/jakarta.ee/files/4285662/bi_jeus.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
TmaxSoft Co., Ltd

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
[https://github.com/eclipse-ee4j/jakartaee-platform/issues/156](https://github.com/eclipse-ee4j/jakartaee-platform/issues/156)

**The URL where Compatible Software Product is available for download**
[https://kr.tmaxsoft.com/jakee/jeus8-b266.zip]()

**Comment by TmaxEE** [comment]
signed agreement is being processed and is underway

**Comment by shabnammayel** [comment]
please pause featuring the logo in the website until the agreement process is complete, thanks

**Comment by shabnammayel** [comment]
Signed agreement received. please go ahead with featuring the logo in Compatible Products page, thanks.

**Comment by autumnfound** [comment]
This is live https://jakarta.ee/compatibility/
