### ISSUE TITLE
Please include Red Hat JBoss Enterprise Application Platform 7.3.0.GA as both Full Platform + Web Profile compatible

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#659]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=731

**A product name and version**
Red Hat JBoss Enterprise Application Platform 7.3.0.GA

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Both

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/RedHatOfficial/jbosseap-certifications/blob/EE8/images/Logo-Red_Hat-JBoss_Enterprise_Application_Platform-B-Standard-RGB.png

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Red Hat

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/146
https://github.com/eclipse-ee4j/jakartaee-platform/issues/147

**The URL where Compatible Software Product is available for download**
http://www.redhat.com/en/technologies/jboss-middleware/application-platform

**Comment by shabnammayel** [comment]
+1 please go ahead with featuring the logo in Compatible Products page, thanks

**Comment by autumnfound** [comment]
Please see https://deploy-preview-662--jakartaee.netlify.com/compatibility/ for review

**Comment by shabnammayel** [comment]
+1 LGTM

**Comment by chrisguindon** [comment]
Thanks all!

**Comment by scottmarlow** [comment]
Thank you!
