### ISSUE TITLE
Add list of mailing lists

### ISSUE THREAD

**Issue by jgallimore** [jakartaee/jakarta.ee#660]
**Is your feature request related to a problem? Please describe.**
We'd like to try and provide a page with all the Jakarta EE mailing lists in one place, with simple navigation. This may overlap with https://github.com/jakartaee/jakarta.ee/issues/110.

**Describe the solution you'd like**
Single page, with all the mailing lists listed as a table.

**Describe alternatives you've considered**
I appreciate the links are under the 'Download' button on the project page, but it isn't as intuitive as it perhaps could be - I wouldn't expect to click 'Download' for example, and I'd prefer 1 click to 2.

**Additional context**
I'm trying to create a PR for this myself, potentially with some other options, but I am well and truly stuck. I'm lost as to whether the layout for the projects page is in the theme, this project, or just some weird kind of magic. @chrisguindon @ericpoirier - any ideas?

**Comment by chrisguindon** [comment]
@jgallimore We have some documentation on how the project page is generated here:
https://eclipsefdn-hugo-solstice-theme.netlify.com/components/eclipsefdn_projects/

We basically have a script (https://github.com/EclipseFdn/hugo-solstice-theme/blob/master/bin/projects/index.js) that fetch projects data from the PMI:
https://projects.eclipse.org/api/projects?working_group=jakarta-ee

Documentation: 
https://api.eclipse.org/#operation/FetchProjects

The mailing list links are missing but I do agree that it might be useful to fetch that information. If you need that information, can you create a request on Eclipse Bugzilla asking us to include mailing-list links in our Project API:

https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community

Assume that information is available in the PMI, we should be able to include it in our API response!

**Comment by TanjaObradovic** [comment]
@jgallimore I think we completed this https://jakarta.ee/connect/mailing-lists/ and the issue can be closed now. Agree?

**Comment by jgallimore** [comment]
That's good with me. Thanks!
