### ISSUE TITLE
Replace CN4J Day Banner in Jakarta.ee

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#663]
Please remove the below CN4J Day banner from the banner carousel on Jakarta.ee.
<img width="1405" alt="Screen Shot 2020-03-05 at 3 37 43 PM" src="https://user-images.githubusercontent.com/59481959/76023508-512c1d00-5ef7-11ea-907f-590476625f35.png">

Additionally, if there are other CN4J Day banners, please remove those as well.

**Comment by shabnammayel** [comment]
Please replace the CN4J Day banner with what we have in the footer for now: 

<img width="1347" alt="Screen Shot 2020-03-05 at 3 53 20 PM" src="https://user-images.githubusercontent.com/51449073/76024632-73269f00-5ef9-11ea-8948-c153206b7d97.png">

**Comment by shabnammayel** [comment]
please ignore my comment if Jakarta EE 8 release is in rotation.

**Comment by autumnfound** [comment]
Banner has been removed
