### ISSUE TITLE
Make Updates on the Jakarta EE Trademark Guidelines page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#666]
We have made some updates on the Jakarta EE Jakarta EE Trademark Guidelines content here: 
https://docs.google.com/document/d/1k4QXOm1eiPeyKWs_-1DZhxF2PlmAkB4g893HJN5NIhM/edit?ts=5e664797#

The page needs to be updated:
https://jakarta.ee/legal/trademark_guidelines/

**Comment by chrisguindon** [comment]
Great job @shabnammayel
