### ISSUE TITLE
Update Events on Jakarta.ee

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#667]
Please remove the following events from Jakarta.ee:
- Javaland
- Dev.next
- KubeCon
- CN4J
- Devoxx France

Please also add the following events:
- IBM Think 2020
      - Date: May 5-7
      - Location: Virtual
      - URL: https://www.ibm.com/events/think/
- Red Hat Summit 2020
      - Date: April 28-29
      - Location: Virtual
      - URL: https://www.redhat.com/en/summit

**Comment by chrisguindon** [comment]
Thanks
