### ISSUE TITLE
Adding JUGs logos on the "Adopt a Spec" page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#669]
The process for now is that the JUGs who adopt a spec create a pull request and their logos are added on the specification page that they adopted.

At the same time, can we also add their logos on the "Adopt A Spec" for JUGs page?
https://jakarta.ee/community/adopt-a-spec/

After the Sign up section, create a sections called: 
Adopters
We should add their logos on an alphabetical order

**Comment by shabnammayel** [comment]
right now we have added Madras and SouJava JUGs

**Comment by TanjaObradovic** [comment]
Is there a chance to make the logos smaller? For example half the size from what is now at https://jakarta.ee/specifications/jsonp/ page?

**Comment by autumnfound** [comment]
The width of the adopter logos on the adopt a spec page has now been halved.
