### ISSUE TITLE
Meeting minutes aren't published regularly

### ISSUE THREAD

**Issue by erik-brangs** [jakartaee/jakarta.ee#672]
Meeting minutes are not published regularly. This makes it hard to keep track of what's going on for people not in the meetings because not everything is discussed on the mailing lists. This was already discussed on the jakarta-community mailing list in the thread "Meeting Minutes" in September 2019 and again in November 2019.

I would expect that somebody in the commitee is responsible for publishing the minutes. This does not seem to be the case because publishing isn't happening regularly.

The marketing committee seems to be the best at getting minutes published. Their minutes are currently out of date but the marketing commitee seems to be aware of the problem (see #654 ). The minutes for the specification commitee and the steering commitee need to be published, too.

**Comment by chrisguindon** [comment]
We are currently working with each committee in an effort to nominate a designated person that will be responsible for publishing and committing the meeting minutes on the website.

The expectation would be that these people will submit a pull request instead of creating an issue.

**Comment by TanjaObradovic** [comment]
Apologies for the delay, we are still working on the Steering Committee updates.

**Comment by TanjaObradovic** [comment]
Thanks for your help Erik! We occasionally do need a reminder to publish minuted regularly .

**Comment by aeiras** [comment]
Hola @erik-brangs, 

I follow this space with other 18 Jakartees. It is wonderful that you chose to report the issue directly via the Jakarta EE Repo. Your actions rock!
Next time, I recommend you link the issue and simple send it to the Community forum. Your actions are exemplary and worthy of emulation. Keep up the caring by sharing and doing so via open channels. #ossDOER whose actions rock!
