### ISSUE TITLE
[Swag Folder needed] under Jakarta EE Community drive

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#677]
Hola Team, 

Can you please add a Swag folder and make it so those choosing to create stuff & share with the Community, can also drop it directly in that space?

Also, that space needs to have the project's:

- stickers

- t-shirts

- cups

- any Swag that is in circulation as final vs prototype are needed folders of the space. 

Ideally, anyone who participates in the project is welcomed to print and distribute Jakarta EE Swag.  THIS brings ownership to understand that not only a **a few** are approved to print and distribute but anyone who finds it valuable and conducive to fun branding in smaller or larger communities. Here thinking of Global JUGs. :) 
[JakartaEE-Sticker-2x2-PRINT.pdf needs to be added to the "Prototype folder- thank you EF Team](https://github.com/jakartaee/jakarta.ee/files/4339953/JakartaEE-Sticker-2x2-PRINT.pdf)

**Comment by bshannon** [comment]
Can it include a link to cafepress to order the swag, when appropriate?

**Comment by ivargrimstad** [comment]
https://drive.google.com/drive/u/1/folders/1K5XXGViSr_38Pw_d5FmcIzTqGBlMTcXQ
