### ISSUE TITLE
Add following banner to banner rotations on Jakarta.ee

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#680]
Please add the following Jakarta EE 9 dev progress banner in the banner/footer rotations on Jakarta.ee in rotation with the Jakarta EE 8 banner. Please link to the following: https://jakarta.ee/specifications/platform/9/

Banner:
![2](https://user-images.githubusercontent.com/59481959/76978263-ddcdd680-690c-11ea-916b-6e8b5339c34c.png)

Footer: 
![1](https://user-images.githubusercontent.com/59481959/76975633-356a4300-6909-11ea-9a5f-a0a46850f367.png)

**Comment by autumnfound** [comment]
@GraehamHui could you post the background image for the banner? It doesn't look quite like the one we have on Jakarta currently. Thanks!

**Comment by autumnfound** [comment]
Also whats the expiration date on this banner?

**Comment by GraehamHui** [comment]
I'm not quite sure, I would ask Shabnam. She gets back from vacation
tomorrow.

**Comment by shabnammayel** [comment]
@autumnfound No expiration date, we will update you once the Jakarta EE 9 release date is confirmed to schedule for removing this and replace it with Jakarta EE 9 release page banner. thanks

**Comment by chrisguindon** [comment]
thank you @autumnfound
