### ISSUE TITLE
Add website link to specification page

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/jakarta.ee#684]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
- Please create a link to the external website for the project if it exists. 
- Link text should be "**Website**", Icon should be `fa fa-globe`. 
- The link should be fetched from the "Website" property on the PMI page for the specification project

Example:
Jakarta EE Platform should have a link to [https://eclipse-ee4j.github.io/jakartaee-platform/](https://eclipse-ee4j.github.io/jakartaee-platform/)

- If the specification does not have the `project_id` property defined its `_index.md` , no links should be displayed.
- If the specification has `project_id` defined, but no property for "Website", only the Project link to the PMI pages should be displayed
- If the specification has both `project_id` and property for "Website" defined both the **Project** and the **Website** links should be displayed

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by chrisguindon** [comment]
Thank you @autumnfound
