### ISSUE TITLE
Primeton AppServer V7 as Compatible product of Jakarta EE Full Platform

### ISSUE THREAD

**Issue by jxtaliu** [jakartaee/jakarta.ee#702]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://www.eclipse.org/membership/showMember.php?member_id=1401

**A product name and version**
Primeton AppServer V7

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
http://primeton.com/products/pas/tck_results/images/pas_logo.png

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Primeton Information Technologies, Inc

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
[eclipse-ee4j/jakartaee-platform#171](https://github.com/eclipse-ee4j/jakartaee-platform/issues/171)

**The URL where Compatible Software Product is available for download**
http://primeton.com/products/pas/

**Comment by shabnammayel** [comment]
@chrisguindon Signed agreement received. but please pause featuring the logo until the certification issue is approved: eclipse-ee4j/jakartaee-platform#171

**Comment by shabnammayel** [comment]
Certification issue is now approved. Please go ahead with featuring the logo in Compatible Products page, thanks.

**Comment by chrisguindon** [comment]
Thanks for the update @shabnammayel

**Comment by autumnfound** [comment]
I've looked at this but there doesn't appear to be a download link on the page. It looks to be more of a marketing page with an online chat button. This seems like it could be misleading as the button to click is a Download button. Are we good to proceed?

**Comment by shabnammayel** [comment]
@jxtaliu is there a link to the download page for this?

**Comment by jxtaliu** [comment]
> @jxtaliu is there a link to the download page for this?
Sorry, because of our mistake, the download link was not put in place.
But now, the download link works.

**Comment by autumnfound** [comment]
This is live!

**Comment by arjantijms** [comment]
@jxtaliu I tried the download page, but there's a challenge that's quite difficult to get passed:

<img width="635" alt="download page" src="https://user-images.githubusercontent.com/3037006/78839522-f2c3f400-79f8-11ea-8549-3666b846dde5.png">

How can I complete this challenge? I think it wants a code, but it always gives me back "提示 手机号码格式错误！"

**Comment by arjantijms** [comment]
@jxtaliu Today the challenge screen has changed, with an option for an email. When I enter my email, it now says: "提示 手机号码不能为空！"

**Comment by jxtaliu** [comment]
> @jxtaliu Today the challenge screen has changed, with an option for an email. When I enter my email, it now says: "提示 手机号码不能为空！"


As the third-party SMS service we use does not support your telecom operator, it cannot pass the authentication. But now we have added the mail authentication mode, you can pass the mail authentication. The problem you encountered is caused by the browser cache. It is recommended that you clear the browser cache and try again. If you still have any questions, please contact us by email. Thank you.

**Comment by arjantijms** [comment]
@jxtaliu Thanks so much for the help. After clearing the browser cache I could complete the first challenge. But now there's a second challenge displayed.

After I put something in every box on the screen, it keeps giving me: "提示 请检查姓名,公司字段"

I think I have to enter something in the input fields labeled "姓名 *" and "公司 *", but I don't know what exactly. I tried many things, but unfortunately nothing works.

Another hint would be highly appreciated.

**Comment by arjantijms** [comment]
@jxtaliu Never mind, I hard refreshed the second challenge as well, and then it suddenly worked! The strange thing is I never had the second challenge before, so wonder how refreshing it could have helped, but oh well.

Now there's a third challenge, which is downloading something from Baidu, which for some reason puts up challenges as well.

**Comment by jxtaliu** [comment]
> @jxtaliu Never mind, I hard refreshed the second challenge as well, and then it suddenly worked! The strange thing is I never had the second challenge before, so wonder how refreshing it could have helped, but oh well.
> 
> Now there's a third challenge, which is downloading something from Baidu, which for some reason puts up challenges as well.


Download may be a little complicated. I'll leave my email. You can send me an email (liuxiang@primeton.com). I'll write you a detailed download instruction with screenshots.
