### ISSUE TITLE
Add Banner and Footer for Developer Survey Promo to Jakarta.EE

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#704]
Please add the following banner and footer for the Jakarta EE Developer Survey to Jakarta.ee. We would prefer for it to be live Monday at 8AM but if you can't, just upload it whenever you guys can. Thank you!

Banner: 
![Copy of JakartaEE9 Banners-6](https://user-images.githubusercontent.com/59481959/78294566-980e3200-74f8-11ea-99a2-13d7ee6e0449.png)

Footer: 
![2](https://user-images.githubusercontent.com/59481959/78282391-35159e80-74ea-11ea-9243-8f46eae08eac.png)

CC: @shabnammayel

**Comment by autumnfound** [comment]
@GraehamHui @shabnammayel can we get the source images for those banners? I don't believe we have the desk background image or anything like it on our site currently

**Comment by GraehamHui** [comment]
Hey Martin,

Here's the source image:
Let me know if you need anything else.
[image: Copy of Search - Canva-5.png]

**Comment by autumnfound** [comment]
I don't think the image attached properly, could you attach it via Github directly?

**Comment by GraehamHui** [comment]
Oops sorry, here it is

![Copy of Search - Canva-5](https://user-images.githubusercontent.com/59481959/78386214-293de100-75ab-11ea-9a47-300997a74dcb.png)

**Comment by GraehamHui** [comment]
Forgot to add this last week, but the survey should link to this: [https://www.surveymonkey.com/r/YS75R27]

**Comment by shabnammayel** [comment]
@autumnfound can you please put a pause on "The Jakarta EE 8 is here" and "Jakarta EE 9 is  underway" banners while we are promoting the survey?Can we go live with the survey banner today? thanks

**Comment by autumnfound** [comment]
The image you attached doesn't have the blue hue, so the banner won't either. Is that alright?

**Comment by GraehamHui** [comment]
![JakartaEEDevSurvey2020](https://user-images.githubusercontent.com/59481959/78570709-51b81c00-77f3-11ea-8387-2b16b58caabe.png)

Hey Martin, my bad - here's the source image with the blue banner

**Comment by GraehamHui** [comment]
@autumnfound The survey ends after April 30th

**Comment by autumnfound** [comment]
@GraehamHui I've pushed a version of this up as a draft to review, as there are quite a few differences in the final product. My initial question regarding the mockups is what font were you using to create them? My output doesn't match even after updating my computers font libraries.

The orange horizontal rule that was included in both mocks isn't something that can be easily inserted into the featured content as its a template. The main aim of this component is to reduce the amount of custom code/CSS to create a consistent look and feel and make turnaround time shorter.

Similar to the previous point, there is an additional paragraph in the mockup for the main story banner that doesn't exist within the template. 

The current state can be seen on the following page. You may need to refresh a couple of times to get the right footer as we left the newsletter in rotation.
https://deploy-preview-712--jakartaee.netlify.com/

**Comment by autumnfound** [comment]
Also something to note. As the header story only has 50%  width, the title will never be oneline

**Comment by GraehamHui** [comment]
The font is Libre Franklin. If that font can't be found, don't worry about
it. I would modify the case of the letters to just the first letter of each
word as it doesn't really work with the current font.

Additionally, how can we get the additional paragraph, "April 6 to April
30" onto the banner?

**Comment by autumnfound** [comment]
I've put a breakline in and I was able to get it in but it doesn't look fantastic 
![image](https://user-images.githubusercontent.com/23018241/78592112-8daea980-7812-11ea-9abe-a93f37cb9c25.png)

**Comment by GraehamHui** [comment]
Could we see what it looks like with a second line break or slightly smaller font for the date?

**Comment by autumnfound** [comment]
More space
![image](https://user-images.githubusercontent.com/23018241/78598707-c30cc480-781d-11ea-9d7b-58535914170e.png)

14px font:
![image](https://user-images.githubusercontent.com/23018241/78598785-edf71880-781d-11ea-9836-ca21ebd9d73b.png)

**Comment by autumnfound** [comment]
https://deploy-preview-712--jakartaee.netlify.com/ I've updated the PR with what should pretty closely match the mock up tell me what you think

**Comment by shabnammayel** [comment]
Can we make the section a bit more narrow, that banner section has become too big I think!

**Comment by autumnfound** [comment]
Which banner are you referring to?

**Comment by shabnammayel** [comment]
please make the font size a bit smaller to shrink the title so that the banner section is less taller than usual

**Comment by autumnfound** [comment]
Please see the above link for updated visual

**Comment by shabnammayel** [comment]
+1 looks better thanks

**Comment by autumnfound** [comment]
This is live
