### ISSUE TITLE
The ® could be more decent on the Jakarta.ee frontpage

### ISSUE THREAD

**Issue by keilw** [jakartaee/jakarta.ee#706]
**Describe the bug**
The front page https://jakarta.ee/ contains the string "Jakarta® EE" where the "®" is overly dominant, it should be superscript like the image on the left hand side or even in the page title the font size looks smaller than in the body of the page. 

**To Reproduce**
1. Go to 'https://jakarta.ee/'
2. See error

**Expected behavior**
The "®" should be a smaller font size compared to the rest of the text and ideally superscript.

**Additional context**
The HTML code shows it to be `<span class=tm-Span>®</span>`, so it seems like a CSS problem where the CSS code for this class should be improved to have a smaller size and be superscript.

**Comment by autumnfound** [comment]
@keilw thanks for the issue! This was something I saw previously and had fixed on another site and is due to Hugo changing the class names when we print the jumbotron title. Looks like the bug came back, and I'll be putting in a fix today

**Comment by autumnfound** [comment]
This fix is live!
