### ISSUE TITLE
navigation to meeting minutes is different for each committee

### ISSUE THREAD

**Issue by bshannon** [jakartaee/jakarta.ee#708]
**Describe the bug**
There are so many inconsistencies to web page navigation that when I go back and try to
reproduce the bug, I can't.  In particular, there are several paths from the home page to the list
of committees, but the lists are different.

**To Reproduce**
Look under Connect and resources and find Committees.
Click on it.
See that the subsequent pages are different.

**Expected behavior**
The same list in every case.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 73.0.1

More data...

Connecting on Connect takes me to jkarta.ee/connect/.
Then clicking on Resources takes me jakarta.ee/connect/#.
Why?
Clicking on Meeting  minutes in the right nav bar takes me to  tabbed page with a tab for each
committee, but no description of each committee.
If I now click on Resources I get  sub-page with a menu that has a Meeting Minutes item.
If I click on that, it takes me to https://jakarta.ee/committees/, which is the page I was expecting to see at the beginning of this bug report!

PLEASE HIRE A WEB DESIGNER, NOW!

I know this is not a commercial product, but it will be seen as competing with commercial
products, and this sort of thing shows a lack of professionalism.

Thanks.

P.S. Someone reverted my previously reported fix to the title of the tab, it should be
"Specification Committee", NOT "Specification*s* Committee".

P.P.S. Because some of these problems are not easy to reproduce, they're easy to address
as just a fluke.  That's even worse!

**Comment by chrisguindon** [comment]
Hi @bshannon,

> Connecting on Connect takes me to jkarta.ee/connect/.
> Then clicking on Resources takes me jakarta.ee/connect/#.
> Why?

The Resources menu-item is a dropdown. We are using a drop-down here since people think these pages are important and that they should be a link to these resources in the main-menu.

> Clicking on Meeting minutes in the right nav bar takes me to tabbed page with a tab for each
> committee, but no description of each committee.

I think it's time to consider moving the meeting minute page to our new Committee page.

```
If I now click on Resources I get sub-page with a menu that has a Meeting Minutes item.
If I click on that, it takes me to https://jakarta.ee/committees/, which is the page I was expecting to see at the beginning of this bug report!
```

I am not sure I understand. If I click on Resources > Meeting Minutes, I go to https://jakarta.ee/meeting_minutes/ not https://jakarta.ee/committees/

> PLEASE HIRE A WEB DESIGNER, NOW!

I don't think this will solve the problem! My team does not decide the navigation or the content for the site. We are responsible for doing the work.

@shabnammayel Is the Marketing team/committee still working on improving the navigation of the work? My understanding is that Marketing was still working on https://github.com/jakartaee/jakarta.ee/issues/457 even if the issue was closed 11 days ago.

> P.S. Someone reverted my previously reported fix to the title of the tab, it should be
> "Specification Committee", NOT "Specifications Committee".

I took a look at the history of content/committees/specification/_index.md and you are the last author. I think you a referring to the Committee members section which your patch did not fix.

> P.P.S. Because some of these problems are not easy to reproduce, they're easy to address
> as just a fluke. That's even worse!

I am sorry, I don't understand what you are trying to say.

**Comment by chrisguindon** [comment]
@bshannon,

My main takeaway from your comment is that we need to find a better home for our meeting minutes. May I propose that we use this bug to discuss this. 

Let me get the ball rolling here:

How about we move the minutes for each committee. For example, we should list Marketing minutes on this page:
https://jakarta.ee/committees/marketing/

**Comment by shabnammayel** [comment]
@chrisguindon yes Chris, we have a plan for improving the navigation bar and revamping the website, not something that will be implemented in Q2 though. I

**Comment by chrisguindon** [comment]
Thanks @shabnammayel

**Comment by bshannon** [comment]
> > If I now click on Resources I get sub-page with a menu that has a Meeting Minutes item.
> > If I click on that, it takes me to https://jakarta.ee/committees/, which is the page I was expecting to see at the beginning of this bug report!
> 
> I am not sure I understand. If I click on Resources > Meeting Minutes, I go to https://jakarta.ee/meeting_minutes/ not https://jakarta.ee/committees/

I feel like I'm running into behavior that I can't reproduce.  The Resources submenu would
only come up some times, other times it would take me to a page.

> > PLEASE HIRE A WEB DESIGNER, NOW!
> 
> I don't think this will solve the problem! My team does not decide the navigation or the content for the site. We are responsible for doing the work.

When things aren't working right, I get the felling that no one thought about how the navigation
should work; which links or menus where should take you to which pages?  Should there be
multiple pages with the same or similar names but different content?  When I was clicking
through trying to find something I'd seen before, it all felt very inconsitent to me.

I can't tell how much of this is a design problem and how much is a problem with the underlying
technology.

> > P.S. Someone reverted my previously reported fix to the title of the tab, it should be
> > "Specification Committee", NOT "Specifications Committee".
> 
> I took a look at the history of content/committees/specification/_index.md and you are the last author. I think you a referring to the Committee members section which your patch did not fix.

Ah ha!  Another place with the same set of tabs but different content.

> > P.P.S. Because some of these problems are not easy to reproduce, they're easy to address
> > as just a fluke. That's even worse!
> 
> I am sorry, I don't understand what you are trying to say.

What I'm saying is that I get the feeling of inconsistent navigation as I traverse the site,
of not understanding how I get to where I am or how to get back there.

**Comment by chrisguindon** [comment]
I've decided to re-open issue  #457 as I agree with you, the navigation on jakarta.ee is really bad.

I will also submit a patch today to move the meeting minutes

**Comment by chrisguindon** [comment]
I created a PR to get us started:
https://deploy-preview-717--jakartaee.netlify.com/

Changelog:

- Removed Committee members from https://deploy-preview-717--jakartaee.netlify.com/committees. The members are now listed on each landing page for each committee. For example: https://deploy-preview-717--jakartaee.netlify.com/committees/specification/

- Meeting minutes are now listed on the landing page for each committee:
https://deploy-preview-717--jakartaee.netlify.com/committees/marketing/

Outstanding questions/Decision:

- If we chose to move forward with my proposal, what should we do we do with the previous meeting minute page https://deploy-preview-717--jakartaee.netlify.com/meeting_minutes/? 

Should we remove it and redirect to https://deploy-preview-717--jakartaee.netlify.com/committees/ or should we simply keep it around?

**Comment by TanjaObradovic** [comment]
@chrisguindon thanks for doing this!
This is slightly different then what I thought we should do, but never the less, I think makes sense, until navigation and overall website design is not addressed.
Here are a few suggestions, if we go that route!
Looking at the Steering Committee page, I would propose first to have section sin teh following order
Committee Members
Meeting Minutes
Documents

In addition to that can we tabular view of the meeting minutes per year? So we open with tab on 2020 / tab 2019 and then tab 2018.

**Comment by chrisguindon** [comment]
> Here are a few suggestions, if we go that route!
> Looking at the Steering Committee page, I would propose first to have section sin teh following order
> Committee Members
> Meeting Minutes
> Documents

I made the change! 

> In addition to that can we tabular view of the meeting minutes per year? So we open with tab on 2020 / tab 2019 and then tab 2018.

It's possible but would require us to rethink our meeting_minutes.yml date file which I don't want to change with this issue.

I would recommend that create a separate issue for that once we are done addressing @bshannon issue.

**Comment by chrisguindon** [comment]
Closing this issue! We are currently working on sorting the minutes by year via a different issue.
