### ISSUE TITLE
Add Mike's blog to announcements section on Jakarta.ee

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#709]
Please link to Mike's blog post in the Jakarta EE announcements page - full info/link will be provided tomorrow when it is published

@shabnammayel

**Comment by shabnammayel** [comment]
Mike's blog is live now: https://blogs.eclipse.org/post/mike-milinkovich/add-your-voice-2020-jakarta-ee-developer-survey
Please add it under announcement section, thanks

**Comment by autumnfound** [comment]
This is live
