### ISSUE TITLE
Please add JakartaOne Livestream CN4J under Jakarta.ee event section

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#720]
Please add the following on The Jakarta.ee event section:

JakartaOne Livestream CN4J 
Virtual
12 May, 2020

Event URL: https://jakartaone.org/cn4j2020/

**Comment by GraehamHui** [comment]
Please also add the following EclipseCon event to the website as well:

EclipseCon 2020
Virtual
October 20 - 22, 2020

Event URL: https://www.eclipsecon.org/2020

**Comment by autumnfound** [comment]
These are live
