### ISSUE TITLE
Add JakartaOne Livestream Cloud Native Banner Rotation

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#724]
Please add the following banner to the current rotation on Jakarta EE:

![Copy of JakartaEEDevSurvey2020_banner-4](https://user-images.githubusercontent.com/59481959/79157074-ee555d80-7da1-11ea-9c51-0ae3f5db1fb5.png)

Please link it to here: https://jakartaone.org/cn4j2020/

Let me know if there's any other info you need.

@shabnammayel

**Comment by autumnfound** [comment]
This is live
