### ISSUE TITLE
Ad blocker is blocking "Dukes Choice Award Winner" block

### ISSUE THREAD

**Issue by ChristieWittEclipse** [jakartaee/jakarta.ee#727]
When a browser has an ad blocker on, the "Dukes Choice Award Winner" block doesn't appear on the Jakarta.ee home page (see screenshot of the area I'm referring to).

As I just discussed with Chris, please try removing the word "ad" from the blocks class name to see if that resolves the issue.

![Jakarta® EE Software   Cloud Native   The Eclipse Foundation](https://user-images.githubusercontent.com/58480647/79375190-3b623c80-7f26-11ea-9153-a9fc58d62bc1.png)

**Comment by ericpoirier** [comment]
Hi Christie,

The Duke's choice award block is now showing up.

Let me know if there's anything else.

Thanks.
