### ISSUE TITLE
Project Page Design for Spec Implementations in EE4J

### ISSUE THREAD

**Issue by ChristieWittEclipse** [jakartaee/jakarta.ee#735]
We'd like Jakarta EE specification projects to use https://github.com/jakartaee/jekyll-theme-jakarta-ee and we need to create a new Jekyll theme with the Eclipse.org look and feel.

@ChristieWittEclipse will provide an updated header image if it's required.

**Comment by chrisguindon** [comment]
After reflecting on this, I do believe that there is value in providing a Jekyll theme for all Eclipse Projects as it is the easiest way to publish a site on Github.

I created a new jekyll-theme-eclipsefdn theme (https://github.com/EclipseFdn/jekyll-theme-eclipsefdn) that all our project can use based off the work done via: https://github.com/jakartaee/jekyll-theme-jakarta-ee

Website demo: https://eclipsefdn.github.io/jekyll-theme-eclipsefdn/

Would this work?

**Comment by ChristieWittEclipse** [comment]
@chrisguindon This looks great! I will let @TanjaObradovic and @ivargrimstad +1 this as well.

**Comment by chrisguindon** [comment]
I spoke to @ivargrimstad and all seems good for now! 

We already have a few project using this:

https://eclipse-ee4j.github.io/glassfish/
https://eclipse-ee4j.github.io/soteria/
https://eclipse-ee4j.github.io/mojarra/
https://eclipse-ee4j.github.io/tyrus/
https://eclipse-ee4j.github.io/openmq/

Bugs and issue must now be reported in the theme repo: https://github.com/EclipseFdn/jekyll-theme-eclipsefdn
