### ISSUE TITLE
Apusic AAS V10.1 as Compatible product of Jakarta EE Full Platform

### ISSUE THREAD

**Issue by PatrickHuang888** [jakartaee/jakarta.ee#744]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=1397

**A product name and version**
Apusic AAS 10.1

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://raw.githubusercontent.com/apusic/aas-tck/master/aas.jpg
https://github.com/apusic/aas-tck/blob/master/aas.jpg

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Kingdee Apusic cloud computing Co., Ltd.

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/175

**The URL where Compatible Software Product is available for download**
http://www.apusic.com/wp-content/uploads/AAS-V10.zip

**Comment by shabnammayel** [comment]
Please pause featuring the logo until the certification issue is approved: eclipse-ee4j/jakartaee-platform#175

**Comment by ivargrimstad** [comment]
The certification request has been approved.

**Comment by shabnammayel** [comment]
Perfect! Please go ahead with featuring their logo in the compatible products page, thanks

**Comment by PatrickHuang888** [comment]
Updated product logo url.

**Comment by autumnfound** [comment]
The product logo seems to be broken and cannot be loaded: `error on line 53 at column 69: Specification mandates value for attribute data-pjax-transient`

**Comment by PatrickHuang888** [comment]
> The product logo seems to be broken and cannot be loaded: `error on line 53 at column 69: Specification mandates value for attribute data-pjax-transient`

Hi autumnfound,
I have updated logo again, try you try this jpg file?

**Comment by autumnfound** [comment]
Looks good, I've updated the PR. Thanks!

**Comment by autumnfound** [comment]
This is live
