### ISSUE TITLE
[YouTube Content Contribution]  DevNexus 2020 Jakarta EE Interview by IBM & Tomitribe 

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#759]
video first published via twitter [here](https://twitter.com/mgrygles/status/1261044953431650304?s=20) 

Youtube [link]( https://www.youtube.com/embed/PGusThV86Rw)

Now that the official Jakarta EE youtube channel is a reality can it start its prompt welcoming via Mktg Repo issues to anyone whose sessions solely focus on:

- migrating to Jakarta EE

- session on Jakarta EE APIs

- lessons learn and much more 

Ideally, the vision & value of the Youtube channel**IS** for anyone who is an active Jakartee to know that she/he can submit, via the chosen OSS tooling,  video content and expect a public follow up by the WG assigned to such activity, directly via the tool,  stating via each iteration that EVERYONE in this ecosystem has a responsibility to shape **any Jakarta media**. 

That contributions or requests to change stuff and braid this ecosystem are not just the responsibility of the _paying partners_ via the hire individuals' actions who have been assigned 100% via the yearly Jakarta annual budget to marketing and branding activities.

**Comment by shabnammayel** [comment]
Hey Amelia, do you have the source video link so that we can upload it directly on the Jakarta EE. Right now it link to IBM's youtube channel. I have pinged Emily to help with this if she can, but let me know if you have it. thanks

**Comment by aeiras** [comment]
Happy Monday @shabnammayel, 

I don't have the original video but let me add @rstjames who is the expert of video processing. 
Ryan when time allows you, could you please provide training video support to @shabnammayel so that this opportunity is beneficial to future video content contributions? Thank you both!

**Comment by rstjames** [comment]
@shabnammayel @aeiras 
Not sure what the standards are for taking this video and adding to another youtube video. If you have permission from IBM to do this I don't see a problem. If Emily can not get you the source video file I can export the the video so you can add it to Jakarta EE youtube. 

let me know if I should do this.

**Comment by shabnammayel** [comment]
never mind @rstjames, we are going to add this video to a playlist directly. thanks.

**Comment by shabnammayel** [comment]
The video is already added to the Jakarta EE Youtube channel last week, please close this issue. thanks
