### ISSUE TITLE
Update Events on Jakarta.ee

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#770]
Please update the events page on Jakarta.ee with the following:

- Remove Devoxx UK as it has been cancelled

- Add JakartaOne Livestream Brazil:
     - Name: JakartaOne Livestream Brazil
     - Location: Virtual
     - Date: August 29, 2020
     - URL: https://jakartaone.org/brazil2020/

Please let me know if any other info is needed.

CC: @shabnammayel

**Comment by ivargrimstad** [comment]
I just removed Devoxx UK
