### ISSUE TITLE
Add banner to banner rotation on Jakarta.EE

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#775]
Please add the following banner to the banner rotation on Jakarta.ee

![Jakarta EE Youtube Channel Banner](https://user-images.githubusercontent.com/59481959/82928214-ee737c00-9f4f-11ea-9ef5-faf605539f38.png)
For the time being, please make this an ongoing banner as we want to maximize our subscriptions to the channel.

The banner should link here: https://www.youtube.com/channel/UC4M7h5b6elu9VlzjLfzuXyg

Please let me know if there's any other additional info needed.

CC: @shabnammayel

**Comment by autumnfound** [comment]
For future issues for things such as banners, can you include the copy as well as the expected output? It reduces the chance for user error and makes the process a little faster :)

**Comment by GraehamHui** [comment]
@autumnfound what do you mean by the expected output? Could you clarify that for me, please?

**Comment by autumnfound** [comment]
In this case, the expected output would be the reference image for the banner. Apologies, I could have been clearer.
