### ISSUE TITLE
[ADD Platform Tuesday Call recordings- past  & future] to the Youtube channel

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#787]
Lets please add the past recordings to the channel and start including the future calls to the medium.

**Comment by ivargrimstad** [comment]
The platform calls are not recorded. Minutes are made available [here](https://eclipse-ee4j.github.io/jakartaee-platform/minutes/minutes.html) shortly after the call.

**Comment by aeiras** [comment]
@ivargrimstad, 

Is there a reason the calls are not recorded? 

To me, the Platform calls are the most important calls that enable contributors & contributors alike to come together and learn how best/and most effective to use their time on the Jakarta tasks. 

While I appreciate your prompt response, I don't appreciate for the ticket to be closed without further conversation that welcomes others within this ecosystem to help adjust an item that is Public and welcoming by nature to skip such step.  Further, I ask you as the devRel for the project to step back & think twice before closing issues without confirming it with the creator of any ticket, specially anything not related to code review. This feedback is provided with a smile! 

With Jakarta EE 9 release aiming at June 23rd, NO other call within this ecosystem is as valuable as the Platform call.

**Comment by ivargrimstad** [comment]
@aeiras Recording the meetings have never been brought up in the calls. I guess nobody has seen it as necessary. It is up to the project team to decide how to conduct their meetings.

As for closing the ticket, the scope of the request is outside of this issue tracker.

- Publishing on YouTube: Contact the Marketing and Brand Committee
- Project-related matters: Contact the project. In this case, the Platform team.

With a smile as always :)
