### ISSUE TITLE
The Jakarta RESTful Web Services 3.0 (milestone) page is not rendered

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/jakarta.ee#792]
**Describe the bug**
The Jakarta RESTful Web Services 3.0 (milestone) page is not rendered.
**To Reproduce**
1. Go to https://jakarta.ee/specifications/restful-ws/3.0/

**Expected behavior**
The page should display as the Netlify preview for the PR ([155](https://github.com/jakartaee/specifications/pull/155)) showed: https://deploy-preview-155--jakartaee-specifications.netlify.app/specifications/restful-ws/3.0/

**Comment by kwsutter** [comment]
The date in the _index.md file was set to 2020-06-05.  So, until that day, only the title was being displayed.  Now, today (June 05), everything is displaying as expected.  It does look a little funny to only see the title on the page, but maybe that's okay???  Anyway, that's the explanation.

**Comment by ivargrimstad** [comment]
Great! I'll close the issue then :)

**Comment by chrisguindon** [comment]
@kwsutter Correct! I forgot to comment but I triggered a rebuild of the site 2 hours to generate this content!

https://travis-ci.org/github/jakartaee/jakarta.ee/builds/694675576

**Comment by chrisguindon** [comment]
Sorry wrong link: https://travis-ci.org/github/jakartaee/jakarta.ee/builds/695028293
