### ISSUE TITLE
Add announcement: 2020 Jakarta EE Developer Survey and Jakarta EE 9 Milestone Release

### ISSUE THREAD

**Issue by shanda-eclipse** [jakartaee/jakarta.ee#814]
Announcement
date = "2020-06-23"
title = "Amid Growth in Cloud Native Enterprise Java Adoption, Eclipse Foundation Announces Results of 2020 Jakarta EE Developer Survey and Jakarta EE 9 Milestone Release"
link = "https://newsroom.eclipse.org/news/announcements/amid-growth-cloud-native-enterprise-java-adoption-eclipse-foundation-announces"
description = "Use of Jakarta EE continues to grow at an unprecedented pace, setting the stage for true open source innovation for cloud native Java with Jakarta EE 9 and beyond"

NOTE: This press release will be published through the newsroom tomorrow (June 23) at 7 AM ET. Please add this to Jakarta.ee after 7 AM.

**Comment by shabnammayel** [comment]
Also Please add Mike's blog in the announcement section:
date = "2020-06-23"
title: Jakarta EE Is Taking Off
Description: With the results of the 2020 Jakarta EE survey and the initial milestone release of the Jakarta EE 9, it’s clear the community’s collective efforts are resonating with the global Java ecosystem.
Link: https://blogs.eclipse.org/post/mike-milinkovich/jakarta-ee-taking
