### ISSUE TITLE
Add the Landing Page URL for Developer survey under resources button

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#815]
Here is the landing page URL for Jakarta EE Developer Survey: http://outreach.jakartaee.org/2020-developer-survey-report 
(Note: This page will be live tomorrow morning at 7 a.m. ET.) 

Please add it under resources button in Jakarta.ee: "Surveys" section - 2020 Developer Survey

**Comment by ChristieWittEclipse** [comment]
@chrisguindon The pull request is here: https://github.com/jakartaee/jakarta.ee/pull/816

**Comment by chrisguindon** [comment]
> @chrisguindon The pull request is here: #816

Committed! Thanks!
