### ISSUE TITLE
Add Mike's blog to announcement section

### ISSUE THREAD

**Issue by GraehamHui** [jakartaee/jakarta.ee#820]
Please add Mike's blog, "Jakarta EE Is Taking Off" to the announcement section of Jakarta.ee

The announcement should redirect to the following link: https://blogs.eclipse.org/post/mike-milinkovich/jakarta-ee-taking

Summary: With the results of the 2020 Jakarta EE survey and the initial milestone release of the Jakarta EE 9, it’s clear the community’s collective efforts are resonating with the global Java ecosystem.

Please let me know if anything else is needed.

**Comment by autumnfound** [comment]
This is live
