### ISSUE TITLE
[ Jakarta EE Resources Tab] Add Friends of Jakarta link 

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#835]
I recommend using the public google document that contains the agenda minutes and includes in its header:

https://docs.google.com/document/d/1qojkqFrHfHlkBs6sFZdJujY2_ZQvxbkFvmDc6SQ-6bo/edit#

- zoom access link

- calendar access link

- jakarta ee branding 

- doodle poll that welcomes proactively feedback as the call gets know as the space where candid conversations with Ask ME Anything is the standard.

**Comment by shabnammayel** [comment]
+1 @chrisguindon

**Comment by shabnammayel** [comment]
Please add "Friends of Jakarta EE" under resource section and link to https://docs.google.com/document/d/1qojkqFrHfHlkBs6sFZdJujY2_ZQvxbkFvmDc6SQ-6bo/edit#

FYI for everyone, all Jakarta EE related calls, tech talks, etc. are featured in The Jakarta EE community calendar, and the link to the calendar is available under resource section-Jakarta EE Community calendar.

**Comment by autumnfound** [comment]
@shabnammayel please see the following link https://deploy-preview-852--jakartaee.netlify.app/resources/#friends for the update. Does this work for you?

**Comment by shabnammayel** [comment]
Can you add "Minutes" as a bulleted list similar to the other items in that page? thanks

**Comment by autumnfound** [comment]
Updated!

**Comment by aeiras** [comment]
https://github.com/jakartaee/jakarta.ee/pull/852

Dias team, I have left a msg to the ticket above. the minutes cannot be hidden, they are a standalone under the Resources page.

**Comment by autumnfound** [comment]
I responded in the PR, but I'll make the comment here as its likely to be lost/difficult to find there. There is currently a link for this 
page (https://jakarta.ee/resources/#friends), but it was missed in the meganav. I'll add a patch so that it appears in the list

**Comment by aeiras** [comment]
Thank YOU Martin!  As usual you rock :)
