### ISSUE TITLE
Add Tools Vendor Datasheet Jakarta EE 9 to website

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#843]
There _Tools Vendor Datasheet Jakarta EE 9_ is a pdf created by the Jakarta EE Working Group that contains the namespace migration challenge & opportunity tool vendors are tackling for the Jakarta EE 9 release.

The pdf needs to be available, ideally, on the Resources page from the https://jakarta.ee/ website.

**Comment by jgallimore** [comment]
We discussed this on the marketing list. I'll be doing a PR shortly.

**Comment by aeiras** [comment]
[JakartaEE-Datasheet-July172020_final.pdf](https://github.com/jakartaee/jakarta.ee/files/4955641/JakartaEE-Datasheet-July172020_final.pdf)

Finalized data sheet :)
