### ISSUE TITLE
[Correct naming] Under EE4J tutorial page

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#851]
Hola EF Team, 

Please **CUT** the Eclipse word that happens **two** times on this page https://eclipse-ee4j.github.io/jakartaee-tutorial/CONTRIBUTING:

- Contributing to Jakarta EE Platform

Eclipse must never be added before Jakarta EE. Jakarta EE is a stand alone project under the ee4j umbrella. 

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/10731224/88744206-8aaa3280-d0fb-11ea-907e-f12f7d16b375.png">

**Comment by kwsutter** [comment]
@aeiras, I don't have the permissions to reroute this Issue, but it should be directed at https://eclipse-ee4j.github.io/jakartaee-tutorial.  That team is responsible for the GitHub pages you are referencing.  Thanks.

(If you don't have authority to transfer it, then you might have to just close this issue and create a new one against the proper repo.  Thanks.)

**Comment by chrisguindon** [comment]
I have the ability to transfer issue but we can only transfer issue withing the same user or org:
https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

I am closing the issue!

**Comment by aeiras** [comment]
Thank YOU @kwsutter & awesome @chrisguindon! 

@jgallimore has already copied ticket here: https://github.com/eclipse-ee4j/jakartaee-tutorial/issues/197 and opened a PR for it: https://github.com/eclipse-ee4j/jakartaee-tutorial/pull/196 -- thank YOU Jon! :)

Closing the ticket is OK!
