### ISSUE TITLE
Open Liberty 20.0.0.3 as a Compatible Software Product for Jakarta EE 8

### ISSUE THREAD

**Issue by brideck** [jakartaee/jakarta.ee#855]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Brian Decker - IBM - Eclipse Profile](https://accounts.eclipse.org/users/bdeckerhdt)

**A product name and version**
[Open Liberty 20.0.0.3](https://openliberty.io/)

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Both

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[https://openliberty.io/certifications/assets/OL_logo_navy.zip](https://openliberty.io/certifications/assets/OL_logo_navy.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[IBM Corporation](https://www.ibm.com/)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Full Platform: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/227](https://github.com/eclipse-ee4j/jakartaee-platform/issues/227)
Web Profile: [https://github.com/eclipse-ee4j/jakartaee-platform/issues/228](https://github.com/eclipse-ee4j/jakartaee-platform/issues/228)

**The URL where Compatible Software Product is available for download**
[https://openliberty.io/downloads/](https://openliberty.io/downloads/)

**Comment by shabnammayel** [comment]
LGTM @chrisguindon, please update the Open Liberty compatible product on the compatible products page to this new version. Thanks

**Comment by chrisguindon** [comment]
I am re-opening since we were asked to revert the previous PR.

**Comment by chrisguindon** [comment]
@shabnammayel @TanjaObradovic @kwsutter 

Please let us know once the underlying issue is resolved.

**Comment by kwsutter** [comment]
@chrisguindon Looks like PR #872 was merged 20 days ago.  So, the page is now ready to accept multiple versions of a Compatible Implementation.  Can we finish up this Issue soon?  Thanks!

**Comment by TanjaObradovic** [comment]
@flora8984461 & @chrisguindon I believe this is all ready to go.
