### ISSUE TITLE
Update Proof of compatibility links on Compatible Products page

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/jakarta.ee#861]
The  Proof of compatibility links on https://jakarta.ee/compatibility/must be updated to point to the Public URL of TCK Results Summary link provided in the Certification Request for the products. The link will (in most cases) be an external link to the vendor providing the product.

This item was discussed in the Specification Committee call August 12, 2020.

**Comment by Thr-r** [comment]
I'd like to try updating the site for this issue. The URL in the issue returns a 404, I assume the correct URL is: https://jakarta.ee/compatibility/

**Comment by jgallimore** [comment]
Hi @ivargrimstad , could you assign this to @Thr-r ? Thanks.

**Comment by rstjames** [comment]
Here is a version of how the page could look. I set it up this way so that it gives each Product its "own" space without blending into each other, easier on the eyes & responsive friendly. 

![JakartaEE-compatible-page](https://user-images.githubusercontent.com/12132146/91444881-a7aa6080-e875-11ea-9328-006a92be3773.png)

**Comment by aeiras** [comment]
pretty crisp, effective & mobile --- fantastic design!

**Comment by ChristieWittEclipse** [comment]
I've attached the final preferred design of the 8 examples, as discussed in the Marketing Committee meeting today.

Note that: 
• The blue button titled "Compatibility Requests" on the top right side will link to the compatibility requests on GitHub: https://github.com/eclipse-ee4j/jakartaee-platform/issues?q=is%3Aissue+is%3Aclosed+label%3Acertification
• This version, which excluding the word "Versions" about the version #'s is preferred.
• We can list only versions that have proof of compatibility. We need to ensure Jakarta EE Compatibility logo is displayed on the vendor site next to the version that is certified and where it is downloadable.
• If/when there are more than 3 compatible versions, we will add a link that says "See all" and link to a page that includes all downloads.
• Each logo on this page should be clickable and lead to the product page and possibly download page (but this is up to the vendor).
• I will work collaboratively with everyone to create phase 2 of this page design by October 13th, which will accommodate the addition of the Jakarta EE 9 compatible products.

![Compatible-Page-Mockup-09-03-2020](https://user-images.githubusercontent.com/58480647/92146059-2445bd80-ede7-11ea-863f-c2a09e01bc3f.png)

**Comment by jgallimore** [comment]
Please see PR 872 https://github.com/jakartaee/jakarta.ee/pull/872 for the latest code to implement this.

**Comment by karenmcnaughton** [comment]
On this page: https://jakarta.ee/compatibility/

We need to do the following:

remove the orange Download button that is top right on the page
add a new button the to left of "Compatibility Requests" that says "Download Compatible Products"
when you click on that new button, it will take you to a new page
the design file for this new page can be found here:

**Comment by karenmcnaughton** [comment]
@flora8984461 https://drive.google.com/file/d/1IpRSyn_hOVcgxOk1AoQx8Ef7r7vVDOjT/view?ts=5fc8f5e1

**Comment by chrisguindon** [comment]
Thanks @Thharrison for the contributions!

I will assign this issue to @flora8984461 now to address the new changes that @karenmcnaughton is describing to us.

**Comment by chrisguindon** [comment]
Actually, I think we can close this one and create a new one for @karenmcnaughton request.
