### ISSUE TITLE
How to enable generation on specification pages

### ISSUE THREAD

**Issue by starksm64** [jakartaee/jakarta.ee#862]
I have started looking into how some content could be generated rather than hand coded in the specifications _index.md pages. The first thing I'm looking into is the tck download URLs since those can be generated from a pattern and the spec project information. Here is an example attempt I made in the specifications repo:

https://github.com/jakartaee/specifications/pull/254

The PR adds an inline shortcode that can be seen in the first file in the PR.

It is not working because the enablement of the inline shortcodes needs to be done at the project configuration level.

The question I have is whether we will be able to add the enableInlineShortcodes: true setting to the jakarta.ee site? If we can, this would be a request to do so. 

If not, then I'll look into creating a new single page template for the specifications that uses a common layout and derives all of the specification specific info from a json file.

**Comment by chrisguindon** [comment]
Adding addition information about inline Shortcodes to help us make a decision:
https://gohugo.io/templates/shortcode-templates/#inline-shortcodes

+1 for enabling `enableInlineShortcodes = true` since we have full control over our content files and we trust our committers.
