### ISSUE TITLE
Phase 2 - Compatible Products Page Design for Oct 13th

### ISSUE THREAD

**Issue by ChristieWittEclipse** [jakartaee/jakarta.ee#878]
As discussed on the Marketing Committee call today, we'd like to launch phase 2 of the Compatible product page design for the JakartaEE 9 release in November. 

Tab 1 mockup:
![Tab 1](https://user-images.githubusercontent.com/58480647/92154145-52c99580-edf3-11ea-8d7d-57babc504181.png)

Tab 2 mockup:
![Tab 2](https://user-images.githubusercontent.com/58480647/92154170-5e1cc100-edf3-11ea-8dc0-73d61d4853ca.png)

Please respond on this issue with any feedback, and I've added this task to my backlog for mid-October.

**Comment by kwsutter** [comment]
This looks good.  Where do the generic logos link to on the "Jakarta EE Compatible Products" tab?  What if the logo links for Jakarta EE 8 and Jakarta EE 9 are different (for example, what if Open Liberty changes their desired link)?  I'm just wondering if the "Jakarta EE Compatible Products" tab is necessary...

**Comment by dblevins** [comment]
Could we simply list the latest two versions in order of most recent and then have an "older versions" link at the bottom?

**Comment by TanjaObradovic** [comment]
I think this looks good @chrisguindon! @kwsutter and @dblevins this design was approved by MKT Cmte and the idea of the non version specific page is to list all products that were certified as once we have a new release the latest release tab will be empty and could be for a while. the logo will point to the product home page.

**Comment by TanjaObradovic** [comment]
I suggest we proceed with implementation. @chrisguindon if any questions please let me know.

**Comment by chrisguindon** [comment]
> I suggest we proceed with implementation. @chrisguindon if any questions please let me know.

I am not clear on the first tab where it's only the logo.

Do we need it? Is that the default tab on page load? Where should the logo link to?

**Comment by TanjaObradovic** [comment]
The default tab should list logos of all compatible products of current members (no need to make separation between Platform and Web Profile releases. I think we can only do logos, without any links to the product pages, as those are provided on the specific Jakarta EE Release page.

**Comment by chrisguindon** [comment]
Thanks @TanjaObradovic! We have everything we need to get us started on this!

**Comment by chrisguindon** [comment]
@flora8984461 posted the first revision for this issue:
https://deploy-preview-944--jakartaee.netlify.app/compatibility/

Please let us know what you all think!

**Comment by TanjaObradovic** [comment]
Looks great to me, I would suggest however we always have the latest release tab first after the main one, so Jakarta EE Compatible Product tab, then Jakarta EE 9, and then Jakarta EE 8.

**Comment by flora8984461** [comment]
> Looks great to me, I would suggest however we always have the latest release tab first after the main one, so Jakarta EE Compatible Product tab, then Jakarta EE 9, and then Jakarta EE 8.

Updated.

**Comment by karenmcnaughton** [comment]
@chrisguindon Elspeth will provide a .psd design file of the page that has the additional download button to the page with the version listings that meet the IP/legal terms. @TanjaObradovic and I met with her today and she will send asap.

**Comment by chrisguindon** [comment]
@karenmcnaughton Thanks for the update!

**Comment by edbratt** [comment]
Me personally, I would prefer product name text just below the images on the generic tab. If the bold text from the version specific tabs was included below the images, that would be better -- for me.

> @flora8984461 posted the first revision for this issue:
> https://deploy-preview-944--jakartaee.netlify.app/compatibility/
> 
> Please let us know what you all think!

**Comment by flora8984461** [comment]
> Me personally, I would prefer product name text just below the images on the generic tab. If the bold text from the version specific tabs was included below the images, that would be better -- for me.
> 
> > @flora8984461 posted the first revision for this issue:
> > https://deploy-preview-944--jakartaee.netlify.app/compatibility/
> > Please let us know what you all think!

Hello @edbratt , Sure I can add that, and please check the new preview after it's refreshed. 

But I will defer to you and other design&marketing members to decide shall we keep the same as the original design or add the names.

Thanks!

**Comment by edbratt** [comment]
I like the new version and I realize that some images have the name in 
them while some don't.

**Comment by chrisguindon** [comment]
Are we ok to push this live or do we need more people to comment before we do so?

 https://deploy-preview-944--jakartaee.netlify.app/compatibility/

**Comment by TanjaObradovic** [comment]
it looks great to me!

@karenmcnaughton please comment if we are still waiting on Elspeth, or we can go ahead with this and we'll adjust later.

**Comment by karenmcnaughton** [comment]
Let's go ahead with this version and we will circle back to @chrisguindon next week if need be.

**Comment by flora8984461** [comment]
> Let's go ahead with this version and we will circle back to @chrisguindon next week if need be.

@chrisguindon @TanjaObradovic Before merging, do we want to put anything in Jakarta EE 9 or just leave a "coming soon"? I'm gonna add it to Chinese as well if we decide to use some words like "coming soon"

**Comment by TanjaObradovic** [comment]
We should switch on all Jakarta EE 9 related pages on Dec 8th and late evening Dec 7th, as that was agreed as approach with MKT committee. Till then we should have it as "coming soon".

**Comment by flora8984461** [comment]
> We should switch on all Jakarta EE 9 related pages on Dec 8th and late evening Dec 7th, as that was agreed as approach with MKT committee. Till then we should have it as "coming soon".

Sounds good. I made a little adjustment on the alignment of "coming soon" and added a Chinese translation. (Not sure if this is needed though)
https://deploy-preview-944--jakartaee.netlify.app/compatibility/#tab-9
https://deploy-preview-944--jakartaee.netlify.app/zh/compatibility/#tab-9

Thanks!
