### ISSUE TITLE
 Open Please remove jts-dev@eclipse.org from https://jakarta.ee/connect/mailing-lists

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#885]
Please remove jts-dev@eclipse from https://jakarta.ee/connect/mailing-lists.  

https://jakarta.ee/connect/mailing-lists contains jts-dev which is not a Jakarta EE technology:

> The JTS Topology Suite is a Java library for creating and manipulating vector geometry. It also provides a comprehensive set of geometry test cases, and the TestBuilder GUI application for working with and visualizing geometry and JTS functions. 

Also see description on https://github.com/locationtech/jts for more details about the JTS project.

**Comment by chrisguindon** [comment]
@shabnammayel, I believe this page is owned by EF Marketing, can you confirm that we can go ahead with this change as described?

@flora8984461 Please make this change once we get a +1 from @shabnammayel!

**Comment by TanjaObradovic** [comment]
+ 1 to remove this. @shabnammayel please approve.

**Comment by shabnammayel** [comment]
+1 thanks
