### ISSUE TITLE
Change Apusic AAS V10.1 as Compatible product to Apusic AAS V10

### ISSUE THREAD

**Issue by PatrickHuang888** [jakartaee/jakarta.ee#895]
Due to some version error from beginning, It should be Apusic AAS V10 as a Compatible product. Plea help me change the listing change to V10.
Original issue: https://github.com/jakartaee/jakarta.ee/issues/744
and testing result url http://www.apusic.com/info_safety/server/aas_v10_tck

**Comment by PatrickHuang888** [comment]
Why change back to v10.1 again? do I need open a new issue?

**Comment by shabnammayel** [comment]
@PatrickHuang888 the compatible products page was recently updated and unfortunately the V10 update was missed. Can you please create a new issue? thanks

**Comment by autumnfound** [comment]
I've created a patch for this. This was accidentally reverted while rebasing the Chinese language patch, apologies! https://github.com/jakartaee/jakarta.ee/pull/919

**Comment by autumnfound** [comment]
@PatrickHuang888 I've merged a patch that fixed this issue, thanks for letting us know!
