### ISSUE TITLE
Page title metadata for JESP shows incorrect version

### ISSUE THREAD

**Issue by edbratt** [jakartaee/jakarta.ee#901]
[JESP Page](https://www.eclipse.org/projects/efsp/) title is incorrect. The title meta-data is <title>Eclipse Foundation Specification Process, v1.1 | The Eclipse Foundation</title> It should be changed to v1.2, to match the current page version.
(Sorry, I could not locate where this meta-data is captured, I did not see anything in the source repository that seemed appropriate)

**Comment by chrisguindon** [comment]
I created a patch (https://git.eclipse.org/r/c/www.eclipse.org/projects/+/169854) for that section is owned by @waynebeaton.

I will let him merge the PR.

@edbratt In the future, please submit an issue via Bugzilla for reporting problems with www.eclipse.org: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community
