### ISSUE TITLE
Fujitsu Enterprise Application Platform as a Compatible Software Product for Jakarta EE

### ISSUE THREAD

**Issue by kazumura** [jakartaee/jakarta.ee#904]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

[Kenji Kazumura - Fujitsu](https://accounts.eclipse.org/users/kkazumura)

**A product name and version**

FUJITSU Software Enterprise Application Platform V1.0

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**

Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

[EAP.zip](https://github.com/jakartaee/jakarta.ee/files/5289369/EAP.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

[Fujitsu Limited](https://www.fujitsu.com/jp/)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**

https://github.com/eclipse-ee4j/jakartaee-platform/issues/244

**The URL where Compatible Software Product is available for download**

https://www.fujitsu.com/jp/software/applatform/

**Comment by shabnammayel** [comment]
@chrisguindon LGTM, the agreement is executed and the certification issue is approved. the URL to DL the logo will go live on 1 Oct. The request is to list the product in the compatible product page after Sep. 30th evening (EST). 

Also based on the new changes approved for the URLs in the compatible products page, please link proof of compatibility button to this page (TCK results page): https://www.fujitsu.com/jp/products/software/middleware/business-middleware/middleware/applatform/jakartaee-report/eap100-ee8full-tck-results/ 

thanks,

**Comment by ggam** [comment]
Seems like the download url is broken, no?

**Comment by chrisguindon** [comment]
@ggam My understanding is that the download url will work after Sep. 30th evening (EST).

**Comment by shabnammayel** [comment]
@chrisguindon yes, the URL to DL the logo will go live on 1 Oct.
