### ISSUE TITLE
Please update Payara Server latest compatible version

### ISSUE THREAD

**Issue by MarkWareham** [jakartaee/jakarta.ee#906]
Note: this is an update to an existing product's version number

To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://projects.eclipse.org/user/11967

**A product name and version**
Payara Server 5.21.2

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
Please use existing logo

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Payara 

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/246

**The URL where Compatible Software Product is available for download**
https://www.payara.fish/downloads/

**Comment by shabnammayel** [comment]
@chrisguindon LGTM, please note that the "proof of compatibility" button should link to: https://docs.payara.fish/enterprise/docs/5.21.0/jakartaee-certification/5.21.2/tck-results-full-5.21.2.html
