### ISSUE TITLE
Host production website with Netlify

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#925]
As many of you might already know, we are currently leveraging Github pages in order to host the jakarta.ee website:
https://github.com/jakartaee/jakarta.ee/blob/src/.travis.yml

## Problem

I have been noticing delays/errors when deploying updates to the jakarta.ee website. Builds are timing out even worst, not starting which is delaying updates from making their way on to prod.

To address this. I am manually triggering rebuilds in order to publish changes to the website... As a result, It took me 12 hours to deploy the new Chinese translation yesterday.

I believe this issue is related to the Backlog of Linux builds for Open source projects on travis-ci.org which seems to be increasing:

<img width="900" alt="Screen Shot 2020-10-23 at 8 06 34 AM" src="https://user-images.githubusercontent.com/893942/97001701-d015aa80-1506-11eb-894f-833fb1ca1b63.png">

## Solution

I am proposing that we migrate hosting providers from Github pages to Netlify. 

We have been using Netlify for its PR preview feature for more than a year now and it's proven to more reliable than travis-ci. It also makes sense for us to use the same automation server for production and staging.

In order to make the switch, we will need to point the jakarta.ee domain to Netlify servers instead of Github. We will also need to make some tweaks to our configs:

- We would need to remove the "disallow_robots_txt" script: https://github.com/jakartaee/jakarta.ee/blob/src/package.json#L23
- Remove the deploy/env section from https://github.com/jakartaee/jakarta.ee/blob/src/.travis.yml

This change should also improve security for the site since this will allow us to remove the encrypted access token from our travis-ci file: https://github.com/jakartaee/jakarta.ee/blob/src/.travis.yml

Please let me know if you have any concerns about this proposal. I am currently scheduling this work to be done by the end of November in order to give us some time to communicate this change with our community.

If all goes well with the DNS update, this update will be seamless to the community!

**Comment by chrisguindon** [comment]
This is scheduled for November 24.

**Comment by aeiras** [comment]
Chris, 

I saw this when you delivered the issue. If it doesn't cut the way contributors can help update the website, then there is no issue. 
After all, it is you and your team who need to deal with the WG websites infra support. Finding ways to avoid SLA mean you get up at wee hours notified that something broke is not ok. 

:)

**Comment by chrisguindon** [comment]
> I saw this when you delivered the issue. If it doesn't cut the way contributors can help update the website, then there is no issue.

I believe this will improve the way contributors can help with the site. We will be using the same service that we are currently using for PR previews to deploy the website.

We will also see commits on production within minutes from merging them. Right now, a deployment can take up-to a few hours because of the throttling done by Travis-ci.

> After all, it is you and your team who need to deal with the WG websites infra support. Finding ways to avoid SLA mean you get up at wee hours notified that something broke is not ok.

I agree! I think this chance reduces the complexity of the site which is a good thing when it comes to this!

**Comment by aeiras** [comment]
That's wonderful, Chris! :) 

Thank you for caring enough to provide insight as to why something needs to be adjusted and making space to allow feedback to come in. 
I asked our team, who handles our websites' support early. Your actions made that possible.  I hate being **informed** about open source stuff. So disrespectful and unfair.

 That's why I always tell you how much I appreciate how you handle stuff-- it makes you accountably awesome. I tell you this b/c it needs to be said publicly!:) 

Cheers!

**Comment by chrisguindon** [comment]
Quick update:

We successfully migrated jakartaone.org but we did not move jakarta.ee. We started with jakartaone.org in order to make sure that our migration plan was good.

Unfortunately, we realized that the migration makes the website unavailable for 30 minutes. The delay is caused by Netlfily waiting for DNS propagation before generating an SSL cert from Let's Encrypt.

Since this was unexpected, we decided not to go through with the Jakarta.ee move in order to notify the community.

I would like to propose that we re-schedule this migration for next week but since the site will not be available for 30 minutes, we should notify our users of this maintenance windows on social media before we start.

**Comment by chrisguindon** [comment]
We also need to come up with a solution for implementing the start.jakarta.ee redirect to https://eclipse-ee4j.github.io/starter/ from Netlify.

I will investigate this and use one of our test sites to test a solution. I will report back once we have a solution.

Please note that I consider this redirect issue a blocker to the migration. We will not migrate to Netlify until we have a solution for the start.jakarta.ee redirect.

**Comment by ivargrimstad** [comment]
It would be nice if we could get start.jakarta.ee to be integrated into the website, but I guess that is a slightly bigger job...

**Comment by chrisguindon** [comment]
I am done with my testing and we can easily set up redirects. I just did this for the openmdm.org website:
https://github.com/EclipseFdn/openmdm.org/blob/master/static/_redirects

@ivargrimstad I've got some good news for you then :) We can use this solution to proxy to the  https://eclipse-ee4j.github.io/starter/ website.

For example:
https://start.chrisguindon.com/

Configs:
https://github.com/chrisguindon/chrisguindon.github.io/blob/master/static/_redirects

With this said, we don't any blocker other than making sure the community is ok with the ~30 minutes downtime that we need to generate the SSL certs!

**Comment by chrisguindon** [comment]
The plan would be to migrate this on December 2 at 1 pm EST.

**Comment by chrisguindon** [comment]
The migration is now complete!

Please note that it might take up to 48 hours for DNS propagation. It's possible that some users are still visiting the gh-pages server but the website is the same on both!

@ivargrimstad I also created a proxy rule for https://start.jakarta.ee/. We are no longer redirecting users!
