### ISSUE TITLE
Navigation sidebar contains broken links

### ISSUE THREAD

**Issue by lukasj** [jakartaee/jakarta.ee#927]
**Describe the bug**
Navigation sidebar for spec projects contains broken links

**To Reproduce**
1. Go to 'https://jakarta.ee/specifications/soap-attachments/2.0/'
2. verify links in the navigation sidebar

=> 9 from 11 are broken

**Comment by lukasj** [comment]
![Uploading image.png…]()

**Comment by chrisguindon** [comment]
This was a regression from last week where we added the Chinese translation on the site.

Thanks for reporting.
