### ISSUE TITLE
IBM WebSphere Liberty 20.0.0.3 as a Compatible Software Product for Jakarta EE 8

### ISSUE THREAD

**Issue by NottyCode** [jakartaee/jakarta.ee#933]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
[Alasdair Nottingham - IBM - Eclipse Profile](https://accounts.eclipse.org/users/anottingham)

**A product name and version**
[IBM WebSphere Liberty 20.0.0.3](https://www.ibm.com/cloud/websphere-liberty)

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Both

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
[websphereliberty.svg.zip](https://github.com/jakartaee/jakarta.ee/files/5467815/websphereliberty.svg.zip)

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
[IBM Corporation](https://www.ibm.com)

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
Web Profile: https://github.com/eclipse-ee4j/jakartaee-platform/issues/264
Full Platform: https://github.com/eclipse-ee4j/jakartaee-platform/issues/263

**The URL where Compatible Software Product is available for download**
https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EWebSphere&product=ibm/WebSphere/WebSphere+Liberty&release=20.0.0.3&platform=All&function=fixId&fixids=wlp-javaee8-20.0.0.3&includeSupersedes=0

**Comment by flora8984461** [comment]
Hello,
Please check the preview: https://deploy-preview-936--jakartaee.netlify.app/compatibility/

And please also check the links to compatibility are https://www.ibm.com/cloud/websphere-liberty/platform-tckresults and https://www.ibm.com/cloud/websphere-liberty/profile-tckresults.

Thanks!

**Comment by NottyCode** [comment]
@flora8984461 looks good to me, thanks.

**Comment by kwsutter** [comment]
@NottyCode The URLs for the TCK Results look fine for this initial request, but we'll have to figure out something better down the road to be able to differentiate between versions (WebSphere Liberty version and/or Jakarta EE versions).  Otherwise, this looks good!  Thanks!

**Comment by NottyCode** [comment]
@kwsutter yes I agree.
