### ISSUE TITLE
SEO Optimization: Meta Refresh

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#941]
Here are the new meta tags for the site  as a result of the SEO exercise: https://docs.google.com/spreadsheets/d/1ZQClxxCM1QWbjBKnqfrcrMIPUnYodhyEntDlZ0_vYW4/edit?usp=sharing

Any questions, please let me know! kristy@excentric.ca

**Comment by aeiras** [comment]
Hola Kristy, 

Are you providing visibility on the SEO work on behalf of the Vendor hired to help with the activity?

**Comment by excentrickristy** [comment]
Hi Amelia,
Yes, Excentric was the vendor and I was instructed to provide visibility here by Shabnam/Karen and @chrisguindon

**Comment by aeiras** [comment]
Kristy, 

This issue and the form to use the Jakarta EE work tools are excellent and deeply appreciated. Thank you! 

On behalf of Tomitribe, I thank you for submitting your very first issue. So fantastic!  

Some of us care about stats & communicating effectively.  As such, we look forward to collaborating with you via open-channels!
