### ISSUE TITLE
What happened to the Jakarta EE Specifications page?

### ISSUE THREAD

**Issue by kwsutter** [jakartaee/jakarta.ee#947]
In the last day or two, something changed with the Specifications page and there's no rhyme or reason as to the order of the Specifications:  https://jakarta.ee/specifications/

It's good that the Platform and Web Profile are first, but we were used to having the others in alphabetical order.  Much easier to find the ones you are looking for rather than searching everytime I come to the page.  Can we get this reverted?  Thanks!

**Comment by aeiras** [comment]
+ 1 Kevin!

It is hard to keep track of the issues & PRs related to the adjustment page for the Jakarta EE 9 release but I find it’s incorrect facts are disturbing as well. 

Currently, the page states that the release has:

1-   31 Spects & not the 40.
2- 60 repos which includes EE4J stuff. 
3- it seems that we are choosing to ignore that EE4J is not Jakarta EE. Jakartee is not the dump of EE4J, it is the project that lives under EE4J as standalone with its very own budget & community.  To scale, EE4J PMC needs to clean up what currently is. 

If we don’t care to educate ourselves & others with current project facts in the new page, how do we expect the community that has yet to learn about Jakarta EE to trust the rebranding & communications? 

On that note, I will send a note about this to the platform dev forum & likely add Wayne to that thread for feedback & clarification.

**Comment by autumnfound** [comment]
@aeiras did you mean to post your comment on this issue? This is just about the ordering of specs on the spec landing page, which is expected to be in alphabetic order.

**Comment by aeiras** [comment]
Yes, I did as a brainstorming- a bit unfair but Kevin’s ticket reminded me that I too need to send a note to the forums bc I don’t know where the relevant ticket is for my specific points is located. 

Ignore the comments as it is unrelated yet consistent with what we present & how we present the data to be consumed. Thanks!

**Comment by kwsutter** [comment]
> Ignore the comments as it is unrelated yet consistent with what we present & how we present the data to be consumed. Thanks!

You could just delete the comment...

**Comment by aeiras** [comment]
Kevin, I agree with your recommendation.:)

**Comment by chrisguindon** [comment]
@kwsutter We can definitely change the ordering but the current order is by design.

The layout file is looping specifications `.ByWeight`:
https://github.com/jakartaee/jakarta.ee/blob/src/layouts/specifications/list.html#L31

The weight is defined in the specification repo:
https://raw.githubusercontent.com/jakartaee/specifications/master/platform/_index.md

Should we replace .ByWeight with `.ByTitle`?

**Comment by ivargrimstad** [comment]
@chrisguindon The weight sorting is only there to make sure that the Platform and Web Profile are always first. None of the other specs have this parameter set.

**Comment by dblevins** [comment]
Sounds like we need to first sort by title, then sort by weight.  If only the Platform and Web Profile specs have a weight and the other specs have no (or the same) weight, it should work out.

**Comment by dblevins** [comment]
@Dexmaster Do you know if a primary and secondary sort like the above is possible in Hugo?

**Comment by flora8984461** [comment]
Hello All, 
Could you please help me check if this order is correct?
https://deploy-preview-995--jakartaee.netlify.app/specifications/

Thanks!

**Comment by dblevins** [comment]
Looks great to me!  Thank you @flora8984461

**Comment by chrisguindon** [comment]
@flora8984461 to the rescue! Thanks for the fix!

**Comment by Dexmaster** [comment]
> @Dexmaster Do you know if a primary and secondary sort like the above is possible in Hugo?

It just needed to use additional range function with ByParam, but I see @flora8984461 already done it. *(there is another way with GroupByParam but it will have the same result) Great job!

**Comment by flora8984461** [comment]
> > @Dexmaster Do you know if a primary and secondary sort like the above is possible in Hugo?
> 
> It just needed to use additional range function with ByParam, but I see @flora8984461 already done it. *(there is another way with GroupByParam but it will have the same result) Great job!

Thx for the info, I did not know there is "GroupByParam", a good syntax to learn

**Comment by Dexmaster** [comment]
https://github.com/hamoid/long-hugo-doc#functions.range.md - this doc has some good info on functions, might be useful when you need some esoteric one :)
