### ISSUE TITLE
[Jakarta EE Mailing List Inventory Adjustments] Jakarta Examples- (RETIRE)

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#971]
https://jakarta.ee/connect/mailing-lists/

11/16.2020 status:
jakartaee-examples developer discussions

email: jakartaee-examples-dev@eclipse.org (52 subscribers)

Change description to Discussions related to developer examples. 

**Recommendation:** archive. The forum has not been used since May 2020. Examples ought to be placed with the code within the repo and not via mailing lists.

**Comment by manorrock** [comment]
This is the mailing list for the JakartaEE examples repository as required by Eclipse, see https://github.com/eclipse-ee4j/jakartaee-examples

**Comment by aeiras** [comment]
jakartaee-examples-dev@eclipse.org	Jakarta EE Examples. Documentation, samples, tutorials of APIs & TCKs.
