### ISSUE TITLE
[Jakarta EE Mailing List Inventory Adjustments]Mailing list: javamail-dev (40 subscribers)

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#977]
https://jakarta.ee/connect/mailing-lists/

11/16.2020 status:
EE4J Eclipse Project for JavaMail developer discussions

email: javamail-dev  (40 subscribers)

**Retired but still listed.**  Can this forum be retired for good?

**Comment by lukasj** [comment]
where did you find this? https://projects.eclipse.org/projects/ee4j.mail/contact has correct and up-to date info...

**Comment by aeiras** [comment]
Hola Lukas, 

https://accounts.eclipse.org/mailing-list/javamail-dev

It says that the mailing list is not valid YET the API is active. 

Thank you for checking this out and helping fix current issue. What I found out last night is that there is not even a history of the mailing list. Lets fix this!

**Comment by lukasj** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=548921#c3 should explain that

**Comment by aeiras** [comment]
Love it, can 1 of you submit a PR helping fix issue using the List PR here?

The 41 issues I submitted yesterday, enable the review to be completed before using the 1 PR to adjust stuff :) 

https://github.com/jakartaee/jakarta.ee/blob/src/layouts/shortcodes/pages/mailing-lists.html

**Comment by aeiras** [comment]
It is likely that you two help close this ticket ASAP :) You two rock! thank YOU. 

Please close ticket once the PR has been sent, super happy here- cheers with tea!

**Comment by edbratt** [comment]
https://github.com/jakartaee/jakarta.ee/pull/994

I can't merge b/c I am not a committer to this project.

https://deploy-preview-994--jakartaee.netlify.app/connect/mailing-lists/

**Comment by aeiras** [comment]
Only Chris and his team can merge the PRs Ed.

The mailing list falls into the jurisdiction of the INFRA of Jakarta EE controlled by the EF. 

Chris is already aware of these issues and we will use the PR to submit all changes. On that note, you can comfortably closed this ticket. I recommend that you add extra context on the commit you pushed with a clearer description and formal project name as well. Recommendation!!

**Comment by edbratt** [comment]
I don't know how to edit the PR comments via the direct-edit web UI 
which I used. Sorry about the terseness. If you know how to do that, I'd 
appreciate the guidance.

**Comment by aeiras** [comment]
Gotcha Ed!

Will do this when I tackle the PR "details". Do not close this ticket to remind me of your request. 

Direct asks into how we collaborate are always preferred. It makes protecting each other's time precious and most appreciated by people like you, me, and others. Therefore, don't ever apologize for being direct with me nor waste your time trying to figure out how when you can state it and ask others to help.  

 Thanks for the review!

**Comment by edbratt** [comment]
https://github.com/jakartaee/jakarta.ee/pull/994 -- This can be closed.

**Comment by aeiras** [comment]
amazing Ed!

**Comment by aeiras** [comment]
mail-dev@eclipse.org	Jakarta Mail. A framework to build mail and messaging applications.
