### ISSUE TITLE
[Jakarta EE Mailing List Inventory Adjustments] jts-dev@eclipse.org (remove)

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#989]
https://jakarta.ee/connect/mailing-lists/

11/16.2020 status:
JTS project developer mailing list

**email:**  jts-dev@eclipse.org (29 subscribers)

**Recommendation:**  How is this mailing list related to Jakarta EE

-  used only 1 in March 2020. -- archived as well. (maybe)?

**Comment by aeiras** [comment]
Added to deprecate tab. https://docs.google.com/spreadsheets/d/1JB-dvwp2Dd9kkiEfF8kHJPlsHRbMe6NZfXo52G0eot8/edit#gid=0

**Comment by scottmarlow** [comment]
[JTS](https://projects.eclipse.org/projects/locationtech.jts) is not part of Jakarta EE and does not belong in https://jakarta.ee/connect/mailing-lists

**Comment by aeiras** [comment]
Thank you, Scott, for helping review the mailing list. :)
