### ISSUE TITLE
[Jakarta EE Mailing List- Google Sheet]  Inventory to help update the EF accounts - database via API

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakarta.ee#996]
Using [ Open
[Jakarta EE Mailing List Inventory Adjustments] Jakarta WebSocket
](https://github.com/jakartaee/jakarta.ee/issues/993#issuecomment-728951816) with Chris's [comment ](https://github.com/jakartaee/jakarta.ee/issues/993#issuecomment-730612016) the google sheet will contain the 3 items required to update across the EF infra the Jakarta EE Mailing list. 

https://docs.google.com/spreadsheets/d/1JB-dvwp2Dd9kkiEfF8kHJPlsHRbMe6NZfXo52G0eot8/edit#gid=0

**Comment by TanjaObradovic** [comment]
@aeiras is the idea to engage the community and update the spreadsheet with emailing lists and descriptions (long and short description should be in fact the same)? If so, I updated 3 mailing lists as an example and to get things going, I hope this helps.
Mailing lists are associated with projects, so I believe all we need to do is provide the project name that the list is intended for.

**Comment by aeiras** [comment]
Hola Tania, 

Yes, the idea is to work together on the clean up :)  I know it might be challenging but if you could find the issues for the mailings list you mention and track your help on those tickets, that would be perfect as it will help close the tickets as stuff gets reflected into the google sheet. 

Cheers,

**Comment by aeiras** [comment]
Hey all, 
This week I will start the work on this!

**Comment by aeiras** [comment]
Ok, I am picking up this task today :)

**Comment by aeiras** [comment]
David contributed to the Jakarta community forum on Nov. 17th, 2020 copy/paste:

_I've changed the subject to reflect the topic._

_A couple of quick notes that might help here:

 - Each spec has a `summary_sixty_char` description.  See for example: https://raw.githubusercontent.com/jakartaee/specifications/master/messaging/_index.md
 - These summaries intentionally do not contain the project name as it is already visible where this data is used: https://jakarta.ee/specifications/

If we want to use these descriptions on the mailing list page, that's great.  On that page however we need to make sure we're also using the project name.  For example:

BAD
 - mvc-dev : Standardizes the action-based model-view-controller pattern
 - faces-dev: MVC framework for building user interfaces for web apps

GOOD (or at least better)
 - mvc-dev : Jakarta MVC. Standardizes the action-based model-view-controller pattern
 - faces-dev: Jakarta Faces. MVC framework for building user interfaces for web apps

Also if we don't like some of the descriptions we should make sure to update the `summary_sixty_char` description of the appropriate spec.

If someone has some energy, we could probably put the mailing list links in the `_index.md` file as headers and generate the mailing-list page._

**Comment by aeiras** [comment]
@autumnfound & Chris, 

The google sheet contains the inventory of the working group emails. 

I would deeply appreciate your feedback on the format of the sheet.  If there is anything I need to adjust, do let me know.   I don't understand the use of List_short_description_varchar (255)	colunm. 
Please see the naming patern of the imput on List_Description. 

I have placed the APIs emails as they are listed in the [Specification page](https://jakarta.ee/specifications/) while  prioritizing the Jakarta EE main group emails at the beginning of the list. 

The sheet has 4 tabs forming the current inventory of 2021 emails:

- **Active:**  Jakarta EE
- **Needed** maybe Emails?  not sure.  2 months later, with Jakarta EE 9 release a few more projects are now active.  : ) For the community to decide if new mailing lists are required. 
- **deprecate** emails that are not used. 

- **EE4J emails:**  Is there a way to link the 3 emails to the current house of EE4J?
As the parent umbrella, EE4J ought to stand on its own.   https://projects.eclipse.org/projects/ee4j/

**Comment by aeiras** [comment]
https://docs.google.com/spreadsheets/d/1JB-dvwp2Dd9kkiEfF8kHJPlsHRbMe6NZfXo52G0eot8/edit#gid=0  

Google email inventory

**Comment by chrisguindon** [comment]
@ericpoirier Since you wrote the Drupal Mailing list module, can you explain to @aeiras where we use List_short_description and List_Description please?

**Comment by ericpoirier** [comment]
I created the following screenshot to illustrate where on the Mailing list page we are displaying the short and long description.

![Screen-Shot-2021-03-15-at-9 36 45-AM](https://user-images.githubusercontent.com/623165/111162191-509a7d80-8572-11eb-9fc3-a4e78d646d54.jpg)

This is a screenshot taken from the following page:
https://accounts.eclipse.org/mailing-list/jakarta.ee-wg

Let me know if you have any questions.

Thanks.

**Comment by aeiras** [comment]
Chris & Eric, 

Thank you both. I finally understand how to complete the sheet. Thank you! 
I will update this week, join the Jakarta EE platform next week and discuss it with EE developers before pushing it to completion. :) Your support is wonderful!

**Comment by aeiras** [comment]
@ericpoirier & @chrisguindon, 

Using your feedback, I completed the information on the 3rd colunm.

Can you let me know if anything else is a miss? 
Ideally, we update what currently is this month. There is no reason to wait for more feedback. More than 10 active Jakartees used the forums, the tickets and private to provide feedback. 

Once the update is completed, we need to move the sheet under "no public edit access" still located under the Community folder- Tanja can likely help create a new folder "Mailing Lists". 

Thank you, infra Team! 

[April 2021- Final](https://docs.google.com/spreadsheets/d/12TciEZNOyEZdLNHG619OFzpqyBTZxj2LTe8wiwajfM8/edit#gid=0)

**Comment by TanjaObradovic** [comment]
thanks for your work @aeiras! I would suggest a further refinement of the spreadsheet as I noticed that List_Description sometime describes the project and sometime describes the list as a place where topics about the projects are discussed. I will look into updating the spreadsheet with this in mind. Once completed you can review, before we change the setting and maybe create .pdf to lock it down for now.

**Comment by aeiras** [comment]
Sure @TanjaObradovic, extra eyes are always welcomed. 

Please note that we used what currently is listed under the Specs [page](https://jakarta.ee/specifications/) 
**Current issue**: A few descriptions there do not match what the project does. I have asked those involved in helping with the mailing list improvement to submit PRs against current information yet there is a barrier on fixing the data.  I thought every part of the website welcomes PRs improvements, can you please confirm this is still the case. 

Also, note that the write-up for the List-Description is the same across all the emails, do not change the format or naming, please. If you are able to bring more detail into each API that could be great as it will likely improve the API page as well. 

Thanks,

**Comment by TanjaObradovic** [comment]
Sounds good @aeiras. Let's fix one problem at the time. I have updated the spreadsheet and it now good to go. I tried to make minimal changes and introduce "The list is used for technical discussions related to [short description from spec page]."

Please see the spreadsheet. thanks!

**Comment by aeiras** [comment]
Tanja, I see you and Ivar did some review, it is wonderful. 

Can you help PDF and create a new subfolder under the Community drive with "view access" **only**?  That will help protect this and future inventory email versions (it is likely a new emails will be created sometime soon)  that will update the mailing list in the Jakarta Website and the Eclipse Website. 

Let's tackle the updating of the API's page to mirror the mailing list information without the formality of it- just actions :) I think Ivar could help us there.

**Comment by TanjaObradovic** [comment]
@aeiras as you are the owner of the file, you'll have to do it. I have created the folder for you. Please move the file here (we are trying to stay away from the archived community drive) 

https://drive.google.com/drive/u/0/folders/1SxWPw6_9iV7ckaM83WYfz3uYZCGYbR0N

and change the setting to read only please.

Thanks!

**Comment by aeiras** [comment]
Hey Tania, 

Can you provide the new Community folder link? 
I didn't know the original drive space was dropped.  I cannot move the document with the link you have provided alone. Also, I contribute in many other activities that use the original drive, so I will need to move all that content as well. :) Thanks in advance!  

This is what I see with the link you provided: 
<img width="792" alt="image" src="https://user-images.githubusercontent.com/10731224/113929574-143ef380-97a5-11eb-9596-3c3e68ae753b.png">
There is no "house" or source. Is the new space "private"?

**Recommendation:** 
Can you send to the WG forum an email update stating the changes to the active community that still uses the old drive?

**Comment by TanjaObradovic** [comment]
The folder link is the one I provided
https://drive.google.com/drive/u/0/folders/1SxWPw6_9iV7ckaM83WYfz3uYZCGYbR0N
The folder is empty as there is nothing in it.

The structure is as shown here. We now have the ability to create shared folders from the Google Drives (new feature which we did not have before)
![image](https://user-images.githubusercontent.com/40073121/113930432-478e7c00-97bf-11eb-9f77-51ddd595f7fc.png)

The other drive is still in use, but we will gradually move to the new one and cross-reference old and new  Community folders.

Communication will follow in due time.

Thanks!

**Comment by aeiras** [comment]
Thanks, Tanja. 
I need the link of the main folder Jakarta EE Community (External) to locate it and drop it in the email folder.

**Comment by TanjaObradovic** [comment]
I see. 
Try this one
https://drive.google.com/drive/u/0/folders/11nvqdVqFlCxm5AfPh2NdnanTBrCPW8Xv

**Comment by aeiras** [comment]
Now, I can see the folder, yeay!  However,  I don't have permission to drop stuff. I have added the PDF here, Tanja. 
While you and the Marketing team figure out the new Community drive's collaboration access, can you please drop the PDF in the folder? Gracias! 

@ericpoirier & @chrisguindon 
The document is ready to enable the update.  Thank you! 

[Jakarta EE Mailing Lists - April 2021.pdf](https://github.com/jakartaee/jakarta.ee/files/6274677/Jakarta.EE.Mailing.Lists.-.April.2021.pdf)

The excel version is shared above.  The current work should be enough to help update the Jakarta Website and the EF infra systems. 

Let me know what else I can do to assist you, and many thanks for your and Chris' support!

**Comment by aeiras** [comment]
@TanjaObradovic, 

Thank you for providing me edit access to drop the 3 documents into the Mailing list folder. 
I was not able to move the 3 documents there b/c the "archive" Jakarta Community folder exists within the new drive. FYI. It was not an issue, copy/paste worked great. 

Can you please remove the community/including my own edit access to the April PDF?

**Comment by chrisguindon** [comment]
@aeiras I took a look at this and the list_name is missing from your pdf. I need that information to know which list needs to be updated since it's the PK.

Is it possible to share a spreadsheet instead of a pdf? I think that will make it easier for me to copy and paste.

Thanks!

**Comment by aeiras** [comment]
Hola @chrisguindon, 

I have deleted the PDF from the drive. 
[Jakarta EE Mailing List Folder](https://drive.google.com/drive/u/0/folders/1SxWPw6_9iV7ckaM83WYfz3uYZCGYbR0N)

You are correct, the PDF conversion cut the format of the excel sheet. Amazing review from your part. 
https://docs.google.com/spreadsheets/d/1gaOd1Y1j0eMIPNZKAR03PVRiw7pbOqkhOWWwK2q6Bg0/edit#gid=0
here is the 1 tab that contains the updated version. 

The other document within the drive contains 4 tabs that will enable Jakartees to likely create new email forums based on active "new" APIs.   Not our concern.

Please pull me in if you need anything else, abrazos and thanks!

**Comment by chrisguindon** [comment]
@aeiras I made all the required changes to our database. Let me know if you notice any mistakes I could have made since this was a manual process for me!

**Comment by aeiras** [comment]
@chrisguindon, 

I have checked the [mailing list](https://jakarta.ee/connect/) and the EF infra regular project's pages of a few deprecated emails, I don't see any changes yet, which means it is taking extra time for the manual process to update the information.

**Comment by chrisguindon** [comment]
@aeiras I did not make the change on the jakarta.ee website. The spreadsheet was for updating our database which is reflected here: https://accounts.eclipse.org/mailing-list and on sub-pages for mailing-list: https://accounts.eclipse.org/mailing-list/faces-dev

The mailing list on the jakarta.ee website simply needs a PR for this file: https://github.com/jakartaee/jakarta.ee/blob/src/layouts/shortcodes/pages/mailing-lists.html

**Comment by aeiras** [comment]
Gotcha, Chris. 
I have reviewed the EF mailing list (many emails)  and it looks awesome.  I see no human-errors, the only improvement would have been to add the name of the mailing list to start the description when each email is separated from the Jakarta Mailing list, yet I think current work is an improvement.  Thank YOU for always being amazing Chris!

You can expect that PR next week, yeay!

Have a quiet/safe wknd,

**Comment by chrisguindon** [comment]
Thanks, @aeiras!!

I am looking forward to the PR! Take care!

**Comment by cesarhernandezgt** [comment]
@chrisguindon @aeiras PR with the changes is ready: 
https://github.com/jakartaee/jakarta.ee/pull/1123

Preview available here: https://deploy-preview-1123--jakartaee.netlify.app/connect/mailing-lists/

**Comment by chrisguindon** [comment]
Thanks @cesarhernandezgt 

I approved and merged your PR!

**Comment by aeiras** [comment]
Yeay! 

Chris, mil gracias for your awesomeness via actions! 
Cesar-- thanks for prioritizing the PR submission. 

So happy to close for us to close this +5 months issue and PRs related to it!
